### ISSUE TITLE
[Question] Integration tests with NSubstitute

### ISSUE THREAD

**Issue by vpopescu** [reactiveui/refit#1009]
I am looking for an example for using Refit client as part of integration testing with xUnit and NSubstitute. For example, I have a controller such as:

```
public interface IMyController { ... };

public class Dependency1 : IDependency1 {}
public class Dependency2 : IDependency2 {}
public class MyController : ControllerBase {    public MyController(IDependency1 A, IDependency2 B) {} }
```

I would like to replace some of the methods in IDependency1 and IDependency2 while I test MyController.  So...

```
var d1= Substitute.For<IDependency1>();
d1.SomeFunction(...).Returns(...);

var d2= Substitute.For<IDepedency2>();
d2.SomeFunction(...).Returns(...);

// how do I adjust the following (with or without RefitFixture) to use a properly created instance of MyController?
// what I've tried so far ends up using a MyController instance with the default, rather than the mocked dependencies.

var fixture = new RefitFixture<Startup, IMyController>(RestService.For<IMyController>)) 
var refitClient = fixture.GetRefitClient();
var result = await refitClient.SomeFunction();
 ```

This is my first foray into C# integration tests, so please excuse if this is something obvious, i just can't find it in the documentation, and my googling has turned up either outdated or confusing information.

**Comment by nicostouch** [comment]
I don't use `NSubstitute` but I have had great success with writing integration tests  using `Refit` and `XUnit` including swapping out some dependencies where needed like you are trying to do. 

How I do is leverage IClassFixture<WebApplicationFactory<Startup>> which tells XUnit to spin up an in memory TestServer for doing integration tests against and provides a factory method that allows you to both inject replacement dependencies and configuration into the DI container, as well as get services out of the DI container to interact with them at test setup or as part of doing your asserts. When the WebApplicationFactory sets up the `TestServer` it gives you back an `HttpClient` configured to talk to that in memory test server correctly. You can then take that `HttpClient` and pass it to Refit!

Something like this looks fairly close to what I would consider to be a fairly standard pattern for integration testing in .NET Core. Though I would like to see Refit become a default part of that stack as it's way easier to use than raw HttpClient

https://medium.com/@dev.satbir/integration-tests-using-webapplicationfactory-xunit-and-mongo2go-225068da834f

Hope that helps.

**Comment by vpopescu** [comment]
Thanks @james-s-tayler . I am still struggling a bit with some of this, but I'm going to close it here because I think the problem is more related to the IntegrationFixture package (ConnectingServices.X).
