### ISSUE TITLE
[BUG] No stub generated if derived interface does not contain Refit methods

### ISSUE THREAD

**Issue by daangruijters** [reactiveui/refit#1019]
**Describe the bug**
Refit does not recognize derived interfaces as a Refit-interface, if the derived interface does not contain methods decorated with a Refit attribute.

**Steps To Reproduce**
1. Create a generic Refit-interface, for example:
```
public interface ICrudOperations<TEntity> where TEntity : class    
{
    [Delete("/{id}")]
    Task<IActionResult> Delete(long id);

    [Get("")]
    Task<TEntity> Get(long id);

    [Get("")]
    Task<IEnumerable<TEntity>> GetAll();

    [Post("")]
    Task<TEntity> Create(TEntity dto);

    [Put("/{id}")]
    Task<IActionResult> Update(long id, TEntity dto);
}
```

2. Now create another interface that inherits from this interface:

```
public interface IOrdersAPI : ICrudOperations<Order>
{
}
```

3. Now create a client based on the second interface:

`RestService.For<IOrdersAPI>(url);`

Refit will throw an exception because it does not recognize 'IOrdersAPI' as a Refit-interface.

**Expected behavior**
Stub will be generated, even if the derived interface does not specify any Refit methods itself.

**Comment by clairernovotny** [comment]
Should be fixed by the latest code in main. The next 6.0 preview should have the fix, can you please verify with that?

**Comment by clairernovotny** [comment]
Actually realized it's won't work yet. The generator is looking for methods with and won't see derived types.
