### ISSUE TITLE
[Query] HeaderCollection attribute availability

### ISSUE THREAD

**Issue by tahiat** [reactiveui/refit#1024]
From which version HeaderCollection attribute will be available to use. I have tried with `6.0.0-preview.37` but it is still not available there. What could be a possible solution to use a dictionary as header if `HeaderCollection` is not available?

**Comment by clairernovotny** [comment]
Please try the latest refit, the changes are in main and should be there.

**Comment by clairernovotny** [comment]
Closing as this is in v6.
