### ISSUE TITLE
[Feature] Ability to specify resource name to reuse HttpClient for multiple derived interfaces

### ISSUE THREAD

**Issue by daangruijters** [reactiveui/refit#1036]
**Is your feature request related to a problem? Please describe.**
When trying to instantiate more than one Refit client, that both derive from a base interface, I am looking for a way to specify the resource name for each of these individual clients, when using the HttpClient constructor.

For example:

```
public interface IGetAPI<TEntity> 
{
    [Get("/{key}")]
    Task<TEntity> Get(long key);
}

public interface IUsersAPI : IGetAPI<User> 
{
}

public interface IOrdersAPI : IGetAPI<Order> 
{
}

public class SomeIntegrationTest 
{
    public void TestGet()
    {
        HttpClient httpClient = new WebApplicationFactory(connectionString).CreateClient();
        
        IUsersClient usersClient = RestService.For<IUsersAPI>(httpClient);
        IOrdersClient ordersClient = RestService.For<IOrdersAPI>(httpClient);

        ...
    }
}
```

Since both clients are based on the same HttpClient, and both are derived from the same interface, there is no way to specify the resource name in addition to the base address, i.e. localhost/**users**. 

**Describe the solution you'd like**
The possibility to specify a resource name when instantiating a client with HttpClient.

**Describe alternatives you've considered**
The alternatives are to either specify an url instead of HttpClient, or instantiate a seperate HttpClient for each resource. However, both are not possible in my specific situation.

**Describe suggestions on how to achieve the feature**
An overload on RestService.For<>(), or a property in RefitSettings, to specify the resource name.

**Comment by clairernovotny** [comment]
What would you propose the syntax looks like?

**Comment by clairernovotny** [comment]
I think for now, we're going to wait-and-see on this one. If there's a lot of demand we can consider it but we need to fully understand all of the different scenarios. Once we implement something, it'd be a bad breaking change if we need to alter the behavior.

**Comment by daangruijters** [comment]
Fair enough.

> What would you propose the syntax looks like?

Either decorate the interface with an attribute, or an overload like `RestService.For<IOrdersAPI>(httpClient, "orders")` .

**Comment by clairernovotny** [comment]
If we added the type of the interface to the HttpRequest properties, you could write an HttpHandler that reads that and does whatever you want to the request URL on the HttpMessageRequest. That's an easy thing to add.

**Comment by clairernovotny** [comment]
Closing as something that can be done like this now: https://github.com/reactiveui/refit#target-interface-type
