### ISSUE TITLE
[BUG] Unable to reference Refit.HttpClientFactory in ASP.NET Core 2.2 app

### ISSUE THREAD

**Issue by henkwedel** [reactiveui/refit#1039]
**Describe the bug**
Hi,

I use Refit.HttpClientFactory package in an ASP.NET Core 2.2 application. As of this [commit](https://github.com/reactiveui/refit/commit/7ff9cc92396b01d37b7ec92ac4a5403f382d9393#diff-1d32053a3f440e591c8ae9c6cae88bcc35902a608f20cb52bedf2cdcc86acf7c) I can no longer reference Refit.HttpClientFactory due to the dependency `Microsoft.Extensions.Http` requiring a conflicting version of the assembly.

I am happy to open a PR for conditionally specifying `Microsoft.Extensions.Http` to target 2.2.0 so as to allow the Refit.HttpClientFactory to be referenced by my ASP.NET Core 2.2 application however I wanted to initially understand if the Refit project is open to supporting a target framework of `netcoreapp2.2`?

**Steps To Reproduce**

Provide the steps to reproduce the behavior:
1. Go to 'Manage NuGet Packages...'
2. Update Refit.HttpClientFactory from 4.7.9 to 5.2.4
3. Observe the following error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.Extensions.DependencyInjection from 3.1.7 to 2.2.0. Reference the package directly from the project to select a different version. 
 Acme.Application -> Refit.HttpClientFactory 5.2.4 -> Microsoft.Extensions.Http 3.1.7 -> Microsoft.Extensions.Logging 3.1.7 -> Microsoft.Extensions.DependencyInjection (>= 3.1.7) 
 Acme.Application -> Microsoft.Extensions.DependencyInjection (>= 2.2.0)	Acme.Application		
```

**Expected behavior**
Ideally I would like the project file to conditionally reference `Microsoft.Extensions.Http` to 2.2.0 when the target framework is `netcoreapp2.2`.
I do understand that this target is not LTS however updating the ASP.NET Core application will take some time and if there is no strict requirement on Microsoft.Extensions.Http being greater than 2.2.0 that would be great.

**Screenshots**

**Environment**

- OS:       Windows 10
- Device:   PC
- Version:   5.2.4
- Working Version: 4.7.9

**Additional context**

**Comment by clairernovotny** [comment]
ASP.Net Core 2.2 is no longer supported. We won't be taking a PR for this.

The v6 preview supports 3.1 and 5.0.
