### ISSUE TITLE
[BUG] Refit + Fusillade fails with System.ObjectDisposedException

### ISSUE THREAD

**Issue by JeremyBP** [reactiveui/refit#1048]
**Describe the bug**
Actually the same as #460 witch is closed but not fixed. 
Using Refit with Fusillade fails with System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Http.HttpConnectionResponseContent'.
The exception is thrown at Refit.RequestBuilderImplementation.<DeserializeContentAsync>d__15`1.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 324
It seems that when Fusillade deduplicates requests returning [val.Response.ToTask(cancellationToken)](https://github.com/reactiveui/Fusillade/blob/b64e7e2594083bc35e2e152f3cf75c811267bd66/src/Fusillade/RateLimitedHttpMessageHandler.cs#L145), Refit fails [deserializing HttpContent](https://github.com/reactiveui/refit/blob/ead7e8b64e47cd6d46718f566e9b2ce582684dd6/Refit/RequestBuilderImplementation.cs#L324) because it's disposed.

**Steps To Reproduce**
Create a Refit RestService with any Fusillade's NetCache HttpMessageHandler into the HttpClient, and send the same request at least twice at the same time.
Something dummy like:

```csharp
try
{
	var reqResService = RestService.For<IReqResService>(new HttpClient(NetCache.UserInitiated)
	{
		BaseAddress = new Uri("https://reqres.in/api")
	});

	var task1 = reqResService.GetUsersAsync();
	var task2 = reqResService.GetUsersAsync();

	var result = await Task.WhenAll(task1, task2);
	var userList = result.FirstOrDefault();
}
catch (Exception e)
{
	throw;
}
```

with IReqResService:
```csharp
public interface IReqResService
{
	[Get("/users")]
	Task<UserList> GetUsersAsync();
}
```
and Models:
```csharp
public class UserList
{
	[JsonProperty("page")]
	public int Page { get; set; }

	[JsonProperty("per_page")]
	public int PerPage { get; set; }

	[JsonProperty("total")]
	public int Total { get; set; }

	[JsonProperty("total_pages")]
	public int TotalPages { get; set; }

	[JsonProperty("data")]
	public List<User> Data { get; set; }
}

public class User
{
	[JsonProperty("id")]
	public int Id { get; set; }

	[JsonProperty("first_name")]
	public string FirstName { get; set; }

	[JsonProperty("last_name")]
	public string LastName { get; set; }

	[JsonProperty("avatar")]
	public string Avatar { get; set; }

	[JsonProperty("email")]
	public string Email { get; set; }
}
```
Well interface and models are not the point, it's just to illustrate the bug.
Note that everything succeed when using Fusillade without Refit, I mean using HttpClient directly like:
```csharp
try
{
	var client = new HttpClient(NetCache.UserInitiated)
	{
		BaseAddress = new Uri("https://reqres.in/api/users")
	};

	var task1 = client.GetAsync("");
	var task2 = client.GetAsync("");

	var responses = await Task.WhenAll(task1, task2);
	var jsonString = await responses.First().Content.ReadAsStringAsync().ConfigureAwait(false);
	var userList = JsonConvert.DeserializeObject<UserList>(jsonString);
}
catch (Exception e)
{
	throw;
}
```

Note that everything succeed to, when using Refit without Fusillade like:
```csharp
try
{
	var reqResService = RestService.For<IReqResService>("https://reqres.in/api");

	var task1 = reqResService.GetUsersAsync();
	var task2 = reqResService.GetUsersAsync();

	var result = await Task.WhenAll(task1, task2);
	var userList = result.FirstOrDefault();
}
catch (Exception e)
{
	throw;
}
```

So it's only when using both of it.

**Expected behavior**
Should return result

**Environment**

- OS:      All
- Device:   All
- Version:   All

**Comment by clairernovotny** [comment]
This looks like a bug in Fusillade. I added a test for parallel requests and it's passing with the mock handler:

https://github.com/reactiveui/refit/blob/main/Refit.Tests/RestService.cs#L1003-L1033

If Fusillade is improperly disposing things, that could be interfering.

**Comment by clairernovotny** [comment]
Looking a little closer, Refit always disposes it's underlying HttpRequestMessage when a concrete type is returned.

**Comment by JeremyBP** [comment]
I agree that parallel requests with Refit and without Fusillade works as expected.
I have to admit that parallel requests with Fusillade and without Refit works as expected to.
I opened the same issue on the Fusillade side so that we could cross investigate things.
Seems to me like the middle of a bridge :)

**Comment by clairernovotny** [comment]
Closing as external.
