### ISSUE TITLE
[BUG] Refit 6.0 does not correctly annotate generated code as such

### ISSUE THREAD

**Issue by martincostello** [reactiveui/refit#1066]
**Describe the bug**

Refit 6.0 does not correctly annotate the generated code as generated by a tool.

Consequently, if used in a project using a tool such as StyleCop.Analyzers with TreatWarningsAsErrors enabled, the project will fail to compile.

For example, here is the CI for a dependabot PR to update from 5.2.4 to 6.0.1 that fails due to this: https://github.com/martincostello/antiforgery-testing-application-part/runs/1860614618

**Steps To Reproduce**

Use Refit 6.0 in a project that uses StyleCop.Analyzers where the code conventions do not match the generated code's.

**Expected behavior**

Code continues to compile as tools ignore generated code for style analysis etc. as it is appropriately annotated as generated code as it did in Refit 5.

**Screenshots**

N/A

**Environment**

GitHub Actions runners for Linux, macOS and Windows with .NET 5.0.102 SDK.

**Additional context**

As noted above, this was not an issue with Refit 5.

**Comment by clairernovotny** [comment]
This is really an external issue with StyleCop: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3299

They need to solve this for Source Generators in general.

**Comment by martincostello** [comment]
Before that, can that be worked around in the short term here with emitting `// <auto-generated />` as before?

StyleCop.Analyzers hasn't had a new _stable_ version ship for a considerable period of time now, but that wasn't really a problem because it "just worked".

As this isn't something I can really work around without just turning off entire classes of rules because of the generated Refit code, otherwise the only option I have is to stay stranded indefinitely on Refit 5.2.4 or switch to prerelease versions of StyleCop.Analzyers (if they fix something on their side).

**Comment by martincostello** [comment]
Thanks for the fix Claire - I've just validated this against the referenced repo of my own with the 6.0.3 package from Azure Artifacts and things work as expected.
