### ISSUE TITLE
MS AppCenter fails to build Xamarin.Forms app using Refit 6.0.1

### ISSUE THREAD

**Issue by Alex-Dobrynin** [reactiveui/refit#1074]
After update Refit version from 5.2.4 to 6.0.1 in our Xamarin.Forms app MS AppCenter fails to build with this error message:

/Users/runner/.nuget/packages/refit/6.0.1/buildTransitive/netstandard2.0/refit.targets(19,5): error : Projects using Refit cannot build using MSBuild '16.6.0'. MSBuild '16.8.0' or later is required.

We are using Refit in our PCL project. What is strange that in our PCL project TargetFramework set to netstandard2.1 but in this message we can see mention about netstandard2.0

And I don`t know whose error is this, Refit's or MS AppCenter's

**Comment by clairernovotny** [comment]
That would be AppCenter, it looks like they're using an old version of Visual Studio (VS 2019 16.6). They need to have Visual Studio 2019 16.8 or later on their agents.

**Comment by Alex-Dobrynin** [comment]
What about netstandard2.0 and 2.1? why in the error I see netstandard2.0 but TargetFramework of the PCL set to netstandard2.1?

**Comment by clairernovotny** [comment]
This is about the tools using to build the project, not the targets. Source Generators require the .NET 5.0.100 SDK or MSBuild 16.8 or later. Those toolsets can target any .NET version.

**Comment by clairernovotny** [comment]
Closing this issue as there's nothing Refit can do.

**Comment by shumkis** [comment]
More details here: https://github.com/microsoft/appcenter/issues/2120
