### ISSUE TITLE
feature: Do not emit generated code if no Refit interfaces

### ISSUE THREAD

**Issue by martincostello** [reactiveui/refit#1075]
**Is your feature request related to a problem? Please describe.**

As part of investigating https://github.com/coverlet-coverage/coverlet/issues/1084 and the impact it is having on various projects I maintain trying to use Refit 6.0, I noticed that Refit is emitting a `Generated` class into each project that references Refit, even transitively, rather than only projects which explicitly define a Refit interface.

As a consequence this spreads the coverlet issue to the entire solution through the transitive reference(s) and breaks coverlet code coverage for all projects under test that reference Refit.

Unless there's a specific reason why this emitted code must always be present, it seems to me that it would be better not to emit the `Generated` class (or `PreserveAttribute`). As well as helping mitigate the problem in coverlet, it would also reduce the on-disk size of assemblies referencing Refit by not emitting unused types.

Would you accept a PR to adjust the generator in this way?

**Describe the solution you'd like**

Refit does not emit any generated code into an assembly referencing Refit if no Refit interfaces are present to generate code for.

**Describe alternatives you've considered**

None.

**Describe suggestions on how to achieve the feature**

Have the [`GenerateInterfaceStubs()`](https://github.com/reactiveui/refit/blob/f6621d99872b33521460863b51da18d6e2e98039/InterfaceStubGenerator.Core/InterfaceStubGenerator.cs#L45) method exit early if there are no Refit interfaces found.

https://github.com/reactiveui/refit/blob/f6621d99872b33521460863b51da18d6e2e98039/InterfaceStubGenerator.Core/InterfaceStubGenerator.cs#L45

**Additional context**

Screenshot of ILSpy showing a `Generated` class in three assemblies, where two are empty, despite only one containing a Refit interface.

The assemblies were generated from this repro project: https://github.com/martincostello/coverlet-refit-repro

![image](https://user-images.githubusercontent.com/1439341/107674687-1eee7800-6c8f-11eb-9141-3ce93f9b004f.png)

**Comment by clairernovotny** [comment]
Totally valid -- we shouldn't be emitting code into projects where there aren't any interfaces.
