### ISSUE TITLE
[BUG] Still doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project

### ISSUE THREAD

**Issue by sevencat** [reactiveui/refit#1080]
version:Refit.6.0.15.nupkg
netframework:4.8 

```csharp
using System.Threading.Tasks;
using Refit;

namespace SnapOffline
{
	public interface IWtApi
	{
		[Post("/xx/showreport.asp")]
		Task<ResponseShowReport> ShowReport([Body(BodySerializationMethod.UrlEncoded)]
			RequestShowReport req);
	}
}
```
```
System.InvalidOperationException: IWtApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
   在 Refit.RestService.GetGeneratedType(Type refitInterfaceType) 位置 /_/Refit/RestService.cs:行号 100
   在 Refit.RestService.For(Type refitInterfaceType, HttpClient client, IRequestBuilder builder) 位置 /_/Refit/RestService.cs:行号 36
   在 Refit.RestService.For[T](HttpClient client, IRequestBuilder`1 builder) 位置 /_/Refit/RestService.cs:行号 13
   在 Refit.RestService.For[T](HttpClient client, RefitSettings settings) 位置 /_/Refit/RestService.cs:行号 20
   在 Refit.RestService.For[T](HttpClient client) 位置 /_/Refit/RestService.cs:行号 23
   在 SnapOffline.Program.Main(String[] args) 位置 E:\work\med\MedSnap\weitong\Snap\SnapOffline\Program.cs:行号 23
```

**Comment by clairernovotny** [comment]
How are you building this project? What version of Visual Studio/MSBuild? Do you have a minimal repro solution?

**Comment by t1g0rs** [comment]
I've same problem. After upgrading from version 5.2.4 I've noticed build targets for old version were removed from csproj, but no new were added. 
VS 2019. Target framework 4.8.

**Comment by automachina** [comment]
I have the same issue.
Just happened after updating Refit to version 6.0.15 from 5.2.1
I've attached a Xamarin Workbook file that reproduces the issue and mimics the method that's throwing the method. 
<img width="1350" alt="RefitServiceException" src="https://user-images.githubusercontent.com/26698328/108238945-45346d80-70fe-11eb-94c5-5d50e792e97c.png">


Xamarin Workbook Details
#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.5.0 |
| Git Branch | 1.5-release |
| Git Hash | 11f83dc |
| VSTS Definition | Workbooks & Inspector (Mac) |

#### System Info
| Component | Value |
| :- | :- |
| macOS | Version 10.15.7 (Build 19H524) (64-bit) |
| CPU Cores | 4 / 4 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Mono | 6.12.0.122 |
| Xamarin Mac | 7.4.0.4 |
| Xamarin iOS | 14.10.0.4 |
| Xamarin Android | 11.1.0-26 |
| Visual Studio | 8.8.9.10 (808090010) |


[RefitServiceException.workbook.txt](https://github.com/reactiveui/refit/files/5997264/RefitServiceException.workbook.txt)

**Comment by clairernovotny** [comment]
It appears that Xamarin Workbooks doesn't support Source Generators yet. That's likely a different issue than the first one.

**Comment by automachina** [comment]
Oh okay, sorry about that.
I had to walk the version back to 5.2.4 to get it to run in my Xamarin project.

=== Visual Studio Community 2019 for Mac ===

Version 8.8.9 (build 10)
Installation UUID: 35fb9683-7640-4056-9f83-040b50bd7056
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	2.1.701
	2.1.503
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.7
	2.0.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/gaelan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/gaelan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.4.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:22-0500

=== Xamarin.iOS ===

Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

=== Build Information ===

Release ID: 808090010
Git revision: 0061f975f58a5dba53e339f116371f4853edeb75
Build date: 2021-02-11 11:16:18-05
Build branch: release-8.8
Xamarin extensions: 0061f975f58a5dba53e339f116371f4853edeb75

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jan 12 22:13:05 PST 2021
    root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

.NET Core support for Mono.Debugging 8.0.5
Android Signature Tool 2.2.0

**Comment by namilkimfree** [comment]
I've same problem. 6.0.1 and 6.0.15 
VS 2019, Target framework 4.6.1


`  

            [Headers("Content-Type: application/json")]
            public interface ILabTicketAPI
            {
                 [Post("/regist/{parkId}/{ymd}")]
                 Task<string> Test(string parkId, [AliasAs("ymd")] string today);
             }


             var clinet = new HttpClient();
            clinet.BaseAddress = new Uri(setting.BaseUrl);

            var refitSettings = new RefitSettings()
            {
                ContentSerializer = new NewtonsoftJsonContentSerializer(
                    new JsonSerializerSettings()
                    {
                        ContractResolver = new CamelCasePropertyNamesContractResolver(),
                        DefaultValueHandling = DefaultValueHandling.Ignore,
                        NullValueHandling = NullValueHandling.Ignore,
                    })
            };

            labTicketApi = RestService.For<ILabTicketAPI>(clinet, refitSettings);  ---> Throw Exception

`

@clairernovotny

**Comment by mekangarayev** [comment]
I have the same problem 
i updated to 6.0.15 from 5.2.4
framework : 4.7.2
private async Task<Unit> ExecuteApiImpl()
        {
            try
            {
                var s = SqlGenerator.GetInvoiceDetails(DateTime.Today, DateTime.Today, "8");
                var data = DataAccess.getExecuteSqlAsList<InvoiceDetails>(s);
                var onlineapi = RestService.For<IInvoiceApi>(akh_api_base_address);//====>throws exception
                await onlineapi.Upload_InvLines(data, akh_api_token, akh_api_aliaspath).ConfigureAwait(true);
            }
            catch (Exception ex)
            {
                var exmes = ex.Message;
            }
            return Unit.Default;
        }

**Comment by clairernovotny** [comment]
@mekangarayev @namilkimfree As this is related to Source Generators, I need more information about how the project is built, not just the interface itself.

What version of VS are you using and how are you building the project when you see this error?

**Comment by namilkimfree** [comment]
@clairernovotny 
VS version = Version 16.8.4
msbuild / version 15.0
refit version 6.0.1 and 6.0.15
refit.Newtonsoftjson 6.0.1
VS 2019, Target framework 4.6.1

**Comment by clairernovotny** [comment]
How is msbuild 15.0 is being used? How is that being located? That's the VS 2017 version of MSBuild.

**Comment by namilkimfree** [comment]
It is Programfiles(x86)₩msbuild₩15.0

**Comment by clairernovotny** [comment]
Understood, but how are you getting that? Are you calling a "Developer Command Prompt"? What is putting that in the path? 

MSBuild shouldn't generally be in the path like that as it's pulling in that older version and will cause you other issues too.

**Comment by namilkimfree** [comment]
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

and "Developer Command Prompt" path is C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools

**Comment by clairernovotny** [comment]
Thanks. I'll look into the issue with the Roslyn team but my first guess is that there's an issue with Source Generators using older packages.config nuget format. There's no reason to use that anymore -- can you right click the `packages.config` file in VS and select the "convert to PackageReference" option? I believe that should be there.

**Comment by namilkimfree** [comment]
@clairernovotny  thank you

.Net Framework  4.6.1 isn't throw exception when migration to PackageReference .

it's done!

**Comment by mekangarayev** [comment]
Yes, perfect, it works!
