### ISSUE TITLE
Remove JsonStringEnumConverter from default SystemTextJsonContentSerializer

### ISSUE THREAD

**Issue by RemcoBlok** [reactiveui/refit#1091]
SystemTextJsonContentSerializer by default adds a JsonStringEnumConverter . This may be fine for deserializing a response but with updating to Refit 6 has broken my code when serializing the body of a POST request to an asp.net core web api that does not have the same JsonStringEnumConverter added. Asp.net core does not add JsonStringEnumConverter by default.

I would like for Refit not to add JsonStringEnumConverter by default either.

As a workaround I have to provide custom RefitSettings with custom JsonSerializerOptions and manually add the other default JsonSerializerOptions that are set in SystemTextJsonContentSerializer like the ObjectToInferredTypesConverter except the JsonStringEnumConverter of course.

**Comment by clairernovotny** [comment]
This is by design as it mimics what most users expect to happen by default. As you note, you can provide your own serializer options if you require different behavior.

**Comment by RemcoBlok** [comment]
I did not expect this to happen as it is different from what happened with Newtonsoft.Json. But as indicated in the release notes version 6 has a breaking change.

**Comment by clairernovotny** [comment]
Most users don't want the underlying enum value to be serialized as Json -- that's hard to reason about and interop between systems. Serializing enums as strings is generally preferred.
