### ISSUE TITLE
[BUG] Can't Build .NetStandar 2.1 Project with Refit v6

### ISSUE THREAD

**Issue by bbenetskyy** [reactiveui/refit#1096]
**Describe the bug**
I faced a couple of problems with `System.IO.IOException: Unable to read data from the transport` and found comments that it was fixed at Refit v6.

But when I upgrade from `5.2.4` to any v6 I've got this:

![image](https://user-images.githubusercontent.com/8330262/109552727-72a3f280-7ad2-11eb-98f2-bb2a4c3fb009.png)

**Environment**
- IDE:       Rider 2020.3.3 (latest) and VS for Mac also latest from Stable
- Version:   Refit v6.* for example latest `6.0.24`
- Working Version: Refit `5.2.4`

What should I do to resolve this issue? Help me pls...

**Comment by clairernovotny** [comment]
You need to contact JetBrains, sorry. It looks like the MSBuild they're using is too old and doesn't contain support for Source Generators.

**Comment by khalidabuhakmeh** [comment]
So I was able to recreate the same issue. The issue arises when you are using the `.NET 3.1 SDK` and targeting .NET Standard 2.1.

The fix is to install the .NET 5 SDK and add a global JSON.

```json
{
  "sdk": {
    "version": "5.0.100",
    "rollForward": "Minor"
  }
}
```

This will make sure that Rider (and other IDEs) pick up the right build tools.
