### ISSUE TITLE
Refit 6.0.x: Content-Length not set for PATCH requests

### ISSUE THREAD

**Issue by softmatters** [reactiveui/refit#1099]
Hi

It seems like the following issue is related to a slightly old issue i.e. #885 and probably #372 

**Description**

I am consuming a third-party REST API using .NET 5/C# 9.0 and Refit version 6.0.24. The third-party system doesn't support chunked encoding. When making a PATCH call the `Transfer-Encoding: chunked` header is getting added, and the API returns with 400 status code.

The interface method looks like below:
```
[Patch("/states/{Id}"), Headers("Content-Type: application/json")]
Task<ApiResponse<State>> ChangeState([Body] StateControl stateControl, string id);
```
I have tried changing the `[Body]` attribute to all possible documented values without any success

```
- [Body]
- [Body(true)]
- [Body(BodySerializationMethod.Default, true)]
- [Body(BodySerializationMethod.Serialized)]
- [Body(BodySerializationMethod.Serialized, true)]
```
Following is the request and response captured by Fiddler

Request
---
```
PATCH http://thidparty.api.com:5000/states/0 HTTP/1.1
Host: thidparty.api.com:5000
X-Correlation-ID: 3edcc52b-aec1-4a8c-b725-c646fc269e95
traceparent: 00-4f869cf85a015f4fae43466700c2a395-5effe2f12308e444-00
Transfer-Encoding: chunked
Content-Type: application/json

1C
{"state":"new","force":true}
0
```
Response
---
```
HTTP/1.1 400 BAD REQUEST
server: gunicorn/19.4.5
date: Mon, 01 Mar 2021 23:29:51 GMT
content-type: application/json
content-length: 92
x-sentry-id: 3b2b0bad862a4eed9d62e8e76c96a7f0

{"message": "The browser (or proxy) sent a request that this server could not understand."}
```

**Expected behavior**
The expected behavior should be how it was in the version prior to 6.0.x. i.e. Content-Length header should be set. It works fine in version 5.2.4, without changing the [Body] attribute. Following is the request and response captured by Fiddler when using Refit version 5.2.4

Request
---
```
PATCH http://thidparty.api.com:5000/states/0 HTTP/1.1
Host: thidparty.api.com:5000
X-Correlation-ID: 3edcc52b-aec1-4a8c-b725-c646fc269e95
traceparent: 00-1b3b2ddae1c35c4f9ae2b6c6e7c72093-ce1d3605b1a6b241-00
Content-Length: 28
Content-Type: application/json

{"state":"new","force":true}
```
Response
---
Please note that 408 is the expected status code for this request :) 
```
HTTP/1.1 408 REQUEST TIMEOUT
server: gunicorn/19.4.5
date: Mon, 01 Mar 2021 18:01:03 GMT
content-type: application/json
content-length: 35
x-sentry-id: 1b4b324faff9412e831aeff453efbeb2

{"message": "State didn't change"}
```

**Environment**
- OS:       Windows 10 Professional
- Version:   Refit 6.0.x
- Working Version: Refit 5.2.4

**Additional context**
I am using a workaround mentioned at #372 in a delegating handler before the request is sent like below and it works fine. However, it would be great if this issue can be fixed. I am happy to contribute if I can get some direction. It would probably be my first contribution ever :)

```C#
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    if (request.Method == HttpMethod.Patch && request.Content != null)
    {
        var content = await request.Content.ReadAsStringAsync(cancellationToken);
        request.Content = new StringContent(content, Encoding.UTF8, "application/json");
    }

    return await base.SendAsync(request, cancellationToken);
}
```

**Comment by clairernovotny** [comment]
I haven't looked any closer yet, but it sounds like the content-length header isn't being set when the body is set to buffered?

Details here:
https://github.com/reactiveui/refit#buffering-and-the-content-length-header

By default, body content is unbuffered, meaning it streams and thus no content-length header can be set. If it's buffered, we have the length and the value can be sent.

**Comment by softmatters** [comment]
@clairernovotny Yes, as per the documentation it should set the Content-Length header when using [Body(true)]. However, as I explained above, I tried all possible combinations of [Body], but the `Transfer-Encoding: chunked` is always getting added to the request header.

It may be the issue with PATCH requests only, however, I haven't tried with POST request as the third party API doesn't expose any

**Comment by vbornand** [comment]
Same issue with a POST.

**Comment by vbornand** [comment]
It is not a bug in Refit. The `HttpRequestMessage.Content` is a `JsonContent` when buffered is set to true, and a `PushStreamContent` when buffered is disabled. But the `HttpClient `sends it with `Transfer-Encoding: chunked` even with a `JsonContent`.

If you do the request without refit you have the same issue:

```
            var req = new WooCommerce.Client.RestAPIV3.Model.CreateWebhookRequest()
            {
                DeliveryUrl = "https://test",
                Name = "test",
                Secret = "toto",
                Topic = "order.created"
            };

            var content = JsonContent.Create(req);
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://end4k0sp8oyzi.x.pipedream.net");

            var ret = new HttpRequestMessage
            {
                Method = HttpMethod.Post,
                Content = content
            };

            await client.SendAsync(ret);
```

I discovered also a little incosistency, if you set the `Body` attribute without the `buffered` property defined, by default it is buffered, because it uses the value of `RefitSettings.Buffered` with `true` as default value. If you don't set a Body attribute, if is never buffered even with `RefitSettings.Buffered = true`.

I continue to investigate to find a way to send a `JsonContent` with a `Content-Length`.

**Comment by vbornand** [comment]
I created a PR to fix this bug.

Meanwhile, a more elegant workaround:
```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    if (request.Content != null)
    {
        await request.Content.LoadIntoBufferAsync();
    }

    return await base.SendAsync(request, cancellationToken);
}
```

**Comment by softmatters** [comment]
@vbornand Thanks a lot. I haven't had a chance to try the fix yet. However, the workaround seems nice.  I'll get back to you as soon as I can.

**Comment by danspark** [comment]
I'm currently using the [latest release (6.0.38)](https://github.com/reactiveui/refit/releases/tag/v6.0.38), but seems that the issue is still there. I'm not getting the `Content-Length` header and the body is being chunked, causing my azure functions to not work :(

Can anyone tell me if I'm doing something wrong? I've looked into what's being sent with Wireshark and this is the request:
![image](https://user-images.githubusercontent.com/23037278/126081574-c6c33a21-672d-4dda-9c33-fd81d99487cd.png)

This is how my client is configured:
``` csharp
public interface IApplicationApi
{
	[Post("/api/process-failed-contracts")]
	Task ProcessFailedContractFiles([Body(true)] ProcessFailedContractFilesRequest request,
		[Header("x-functions-key")] string functionKey = "test", CancellationToken cancellationToken = default);
}
```

I even tried to set `Buffered` to true when creating a RestService:
```csharp
var api = RestService.For<IApplicationApi>("http://localhost:5001", new RefitSettings
{
	Buffered = true,
	ContentSerializer = new SystemTextJsonContentSerializer(new JsonSerializerOptions(JsonSerializerDefaults.Web))
});

await api.ProcessFailedContractFiles(new ProcessFailedContractFilesRequest{
	Prefetch = 10,
	ConsumerCount = 1
});
```

**Comment by syahman** [comment]
> Same issue with a POST.

i can submit simple json poco object. but failed with multiple object (DTO) with list. my requirement is to send json in single call. here is sample request data captured from httploghandler : 

`{
  "invMainInd": [
    {
      "bil": 1,
      "imItem": "KATIL",
      "imCode": "001",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 2,
      "imItem": "SOFT BOARD",
      "imCode": "006",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 3,
      "imItem": "INTERNET CABLE",
      "imCode": "009",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 4,
      "imItem": "TILAM",
      "imCode": "002",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 5,
      "imItem": "SET KUNCI",
      "imCode": "008",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 6,
      "imItem": "KERUSI PELAJAR",
      "imCode": "005",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 7,
      "imItem": "MEJA PELAJAR",
      "imCode": "004",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 8,
      "imItem": "ALMARI",
      "imCode": "003",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    },
    {
      "bil": 9,
      "imItem": "RAK BUKU",
      "imCode": "007",
      "quantity": "-",
      "category": "INDIVIDUAL",
      "condition": "-"
    }
  ],
  "invMainComm": [
    {
      "bil": 1,
      "imItem": "RAK KASUT",
      "imCode": "110",
      "quantity": "2",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 2,
      "imItem": "CERMIN MUKA",
      "imCode": "112",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 3,
      "imItem": "KIPAS SYILING",
      "imCode": "114",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 4,
      "imItem": "RAIL LANGSIR",
      "imCode": "116",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 5,
      "imItem": "CEREK",
      "imCode": "118",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 6,
      "imItem": "FLUSH",
      "imCode": "021",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 7,
      "imItem": "MANGKUK TANDAS",
      "imCode": "023",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 8,
      "imItem": "PILI PAIP",
      "imCode": "025",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 9,
      "imItem": "SETERIKA",
      "imCode": "027",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 10,
      "imItem": "LAN PORT",
      "imCode": "030",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 11,
      "imItem": "WATER HEATER",
      "imCode": "032",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 12,
      "imItem": "LAMPU",
      "imCode": "029",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 13,
      "imItem": "AMPAIAN",
      "imCode": "020",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 14,
      "imItem": "SINKI",
      "imCode": "022",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 15,
      "imItem": "GETAH PAIP",
      "imCode": "024",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 16,
      "imItem": "SHOWER",
      "imCode": "026",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 17,
      "imItem": "DOOR CLOSER",
      "imCode": "028",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 18,
      "imItem": "PENGHAWA DINGIN",
      "imCode": "031",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 19,
      "imItem": "MEJA KOPI",
      "imCode": "033",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 20,
      "imItem": "TOMBOL PINTU",
      "imCode": "111",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 21,
      "imItem": "KIPAS DINDING",
      "imCode": "113",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 22,
      "imItem": "LANGSIR",
      "imCode": "115",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 23,
      "imItem": "PAPAN GOSOK",
      "imCode": "117",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    },
    {
      "bil": 24,
      "imItem": "TONG SAMPAH",
      "imCode": "119",
      "quantity": "-",
      "category": "COMMON USER",
      "condition": "-"
    }
  ],
  "hostelInfo": {
    "dxxxr": "XXXXXXXX",
    "smxxxd": "XXXXX",
    "smxxxxe": "XXXXXXXXXXXXXXXX",
    "smxxxo": "XXXXXXXXX",
    "smxxxxxe": "XXX",
    "cmxxx": "XXXX",
    "daxxxx": "XXXX",
    "daxxx": "XXXX",
    "daxxxx": "XXXXX",
    "dxxx": "XXXXX",
    "dxxx": "XXXXX",
    "cxxx": "XXXXX",
    "smxxx": "XXXXXX"
  }
}`

**Comment by mycroes** [comment]
> @softmatters please open a new issue

What do you want us to put in the new issue; see #1099? This issue has all the relevant details...

**Comment by lotz** [comment]
@softmatters @mycroes We noticed this as well with void return methods, which may be what you are seeing too. PR #1293 will fix that code path.

**Comment by softmatters** [comment]
> We noticed this as well with void return methods, which may be what you are seeing too. PR #1293 will fix that code path.

@lotz Thanks for the fix. I presume that it would work with the methods that return Task<T> as I mentioned in this bug. I'll give it a go and will let you know.

**Comment by Marcin198** [comment]
Wszystko  ok

**Comment by bernardofm** [comment]
Hi,

It seems that the content-length stills not working.

I am using the 6.3.2 version.

**Comment by 9511052** [comment]
Hey, I'm still seeing this issue, with my API set up with the following:

        [Patch("/api/.../{id}")]
        Task<string> UpdateCustomer(Guid id, [Body(true)]string updates);

When this request is received by its endpoint, it has an invalid content-length, and the consumer of the request is responding with "A non-empty request body is required.". Am I missing something? (The '...' obviously corresponds to a real route.)
