### ISSUE TITLE
[BUG] URL path must start with '/' and be of the form '/foo/bar/baz'

### ISSUE THREAD

**Issue by mjfara** [reactiveui/refit#1105]
Is this enforced for any reason?
I have a particular case where I do not want to start the url with a '/'

For instance, take this generic Get:
```
        [Get("({key})")]
        Task<T> Get(TKey key);
```
My base address is something like:
mysite.com/contacts

And I would like the attribute to simply append an id in brackets (123-456-789), resulting in:
mysite.com/contacts(123-456-789)

Any way to hack around this?

**Comment by arty1901** [comment]
Are you sure that your way of building url is correct? It doesn't make sense
That`s would be better:
Base address: mysite.com
`[Get("contacts/{key}")]`

**Comment by mjfara** [comment]
Yup I'm positive. The Microsoft Dynamics Web Api is using OData.

**Comment by clairernovotny** [comment]
@arty1901's answer looks correct.... can you please explain why that won't work?

**Comment by mjfara** [comment]
I am trying to make a generic class for this, so I would not want to include "contacts" in the route.
Aside from that, his answer would fail as well because there is no leading slash "/".

I submitted a very simple PR to rectify this:
https://github.com/reactiveui/refit/pull/1113

**Comment by clairernovotny** [comment]
What is the value in having this completely generic?

Like why not have 

```
        [Get("/contacts({key})")]
        Task<T> GetContacts(Key key);

        [Get("/sales({key})")]
        Task<T> GetSales(Key key);
```

Or use two different interfaces, `IContacts`, and `ISales`. As you're setting the base address differently for each, you already have different client instances.

The design here looks strange.

**Comment by mjfara** [comment]
I got this design straight from the refit docs:
https://github.com/reactiveui/refit#using-generic-interfaces

The only difference is, I do not want to be forced to include a leading slash "/".

There are ~100 different entities in Dynamics, so rather than writing hundreds of different methods to perform simple CRUD operations, having a generic service for this seems like the better approach.

I am currently using the multiple service approach but feel it's a lot of wasted time and effort when a single generic class can do it all.

**Comment by clairernovotny** [comment]
@mjfara I would recommend using a custom delegating HttpHandler that can rewrite the URLs that you need. We're not going to be changing this behavior at this time.

**Comment by mjfara** [comment]
Hmm, a custom delegating HttpHandler that removes the forced leading slash is pretty hacky when compared to including an option to override the arbitrary enforcement to begin with. 

It wouldn't be a change of behavior, but rather an option in the RefitSettings, the default does not change. Not sure why this isn't being considered seeing as it cleanly resolves this issue.

I do appreciate the workaround, but feels hacky to be doing some string substitution on the url. I guess I'll stick with my forked repo for now.

**Comment by Xavier1708** [comment]
Interessante
