### ISSUE TITLE
[TYPO] Minor README.md correction

### ISSUE THREAD

**Issue by fsilvateles** [reactiveui/refit#1109]
In README.md > SDK Requirements > Breaking changes in 6.x > Second paragraph, there's a typo. See below:

![image](https://user-images.githubusercontent.com/1843801/110548488-65f54f00-810f-11eb-868a-f82d048e328a.png)

I think the right text here is `FromHttpContentAsync<T>`.

**Steps To Reproduce**
Open README.md page to see the typo:
https://github.com/reactiveui/refit/blob/main/README.md

**Expected behavior**
The text `FromHttpContentAsync<T>` instead `FromHttpContnentAsync<T>`.

**Comment by ChrisPulman** [comment]
Issue notified as resolved.
