### ISSUE TITLE
[BUG] Build failed with sdk:3.1-buster docker image for Refit >= 6.0.1

### ISSUE THREAD

**Issue by lorsabyan** [reactiveui/refit#1123]
I'm using `mcr.microsoft.com/dotnet/core/sdk:3.1-buster` docker image as a build image. The build failed with the following error message when I'm using Refit >= 6.0.1 for my `netcoreapp3.1` application.

`/root/.nuget/packages/refit/6.0.24/buildTransitive/netstandard2.0/refit.targets(19,5): error : Projects using Refit cannot build using MSBuild '16.7.2'. MSBuild '16.8.0' or later is required.`

Should I use Refit < 6.0.1 for .net core 3.1 applications or it's a bug of Refit?

**Comment by marwahaks** [comment]
Trying updating your visual studio to the latest and try again

**Comment by lorsabyan** [comment]
@marwahaks Thanks for the reply. 
I have no issue with the Visual Studio. The build process happens inside the docker container created from mcr.microsoft.com/dotnet/core/sdk:3.1-buster image.

**Comment by clairernovotny** [comment]
You can target any .NET version, but you do need to use a 5.x SDK to build it.

**Comment by lorsabyan** [comment]
@clairernovotny Thanks for clarification!
I'm closing this issue.
