### ISSUE TITLE
[BUG] Projects using Refit cannot build using MSBuild '16.6.0'. MSBuild '16.8.0' or later is required

### ISSUE THREAD

**Issue by dansiegel** [reactiveui/refit#1137]
**Describe the bug**

This has been reported a few times from the looks of it (variation of #1074)... however it seems that there has been some information missing which is why I'm opening this as a new issue. Previously this issue was reported purely as some issue with App Center. However this really appears to affect anyone building on Mac. As you'll notice from the screenshots I've provided below, I have the latest stable release of Visual Studio for Mac. I am using the latest stable .NET Core SDK and still if I try this locally from the CLI the build will fail with the error 'Projects using Refit cannot build using MSBuild '16.6.0'. MSBuild '16.8.0' or later is required. Since all CI Build's are going to be building outside of Visual Studio from the CLI they are all subject to this issue (also how I first discovered it). 

Note that this works just fine on Mac... inside of Visual Studio for Mac... but completely fails outside of the full IDE. 

**Steps To Reproduce**

- Use Refit
- Build on a Mac from the CLI or in CI (which is from the CLI 😆 )

**Expected behavior**

It should build from the CLI / or in CI

**Screenshots**

![image](https://user-images.githubusercontent.com/3860573/112530041-36775100-8d63-11eb-8cfe-e8475226c5e7.png)

![image](https://user-images.githubusercontent.com/3860573/112530179-61fa3b80-8d63-11eb-9273-a53f678a5998.png)

**Environment**

- OS:       macOS 11.2.3
- Device:   n/a
- Version:   6.0.38
- Working Version: unknown

**Additional context**

none

**Comment by clairernovotny** [comment]
There should be a solution here: https://github.com/microsoft/appcenter/issues/2120#issuecomment-798798890

**Comment by dansiegel** [comment]
Thanks for the reference @clairernovotny... hopefully you can use some of your internal position there to get the VS4Mac team to resolve this issue.... this seems like a pretty significant issue that will affect anyone using Source Generators or libraries like Refit that are using Source Generators.

**Comment by chuckgiddens** [comment]
I am having this issue on DevOps build Pipeline with my YAML.  Why is this closed?  This is still an issue.

**Comment by chuckgiddens** [comment]
I guess I will roll back to 5.x
