### ISSUE TITLE
feature: Ignore the status code?

### ISSUE THREAD

**Issue by doghappy** [reactiveui/refit#1138]
Refit supports get data when StatusCode is not 200, it looks like this:

```cs
interface ICoreApi
{
    Task<ApiResponse<CodeDataResponse<User>>> GetUserAsync(string name);
}

// ...

var response = await coreApi.GetUserAsync("refit");
if (response.IsSuccessStatusCode)
{
    Console.WriteLine(response.Data.Name);
}
else
{
    var data = await response.Error.GetContentAsAsync<CodeDataResponse<User>>();
    Console.WriteLine(data.Message);
}
```

Note that no matter what the status code is, the expected model is the same, My app uses HttpStatusCode as business logic code, In order to simplify the above coding, I should encapsulate a new method to handle it.

But can Refit provide a way to ignore the status code?

## Describe suggestions on how to achieve the feature

Provide two ways to ignore the status code:
1. Provide a property `IgnoreStatusCode` in RefitSetting, which controls the global
2. Provide an `[IgnoreStatusCode]` attribute for users to use on the interfaces or methods

I have already forked and implemented it. I know this does not meet the specification with the HTTP specification, but I still want to ask the Refit team, are you willing to accept this Feature request? Thanks :)

**Comment by Dreamescaper** [comment]
If you want to prevent Refit from throwing the exception, you can provide custom exception factory. See here:
https://github.com/reactiveui/refit#handling-exceptions
