### ISSUE TITLE
[BUG] Response status code does not indicate success: 412 (Precondition Failed).

### ISSUE THREAD

**Issue by ChinaBruce** [reactiveui/refit#1155]
**Response status code does not indicate success: 412 (Precondition Failed).**

**Steps To Reproduce**
I defined a web api method
[Post("/wxa/media_check_async")]
Task<MediaCheckResult> MediaCheckAsync([Query] string access_token, [Body] MediaCheckBody mediaCheck);

and then I call it, it throw Response status code does not indicate success:412 (Precondition Failed).

**Environment**
Version：6.0.38

**Additional context**
 at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 279

**Comment by james-s-tayler** [comment]
There's not enough information here. 412 is the response you're getting back from the server that you made an http request to. It's telling you it's unhappy with the request. I'm assuming you need to tell make the request correctly. I'm not seeing a bug in Refit based on the information provided.

**Comment by clairernovotny** [comment]
Closing due to age. Please re-open if there's still an issue and more information can be provided.

**Comment by falsebo** [comment]
I repeated the problem
Downgrade to 6.0.1 , it works ok

**Comment by clairernovotny** [comment]
Can you please provide some more details? Things like the shape of the body class. If you can use Fiddler to record each request, on the version that works and the version that doesn't, that would be helpful. You can redact any sensitive values/tokens, but that would help us figure out what the differences are in the requests.

**Comment by falsebo** [comment]
when I use Fiddler , it works fine.

**Comment by falsebo** [comment]
my settings
` private static RefitSettings refitSettings = new RefitSettings
        {
            ContentSerializer = new NewtonsoftJsonContentSerializer(new JsonSerializerSettings
            {
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new SnakeCaseNamingStrategy()
                },
                NullValueHandling = NullValueHandling.Ignore
            }),
            HttpMessageHandlerFactory = () =>
            {
                return new HttpClientHandler()
                {
                    Proxy = new WebProxy("http://127.0.0.1:8888"),
                    UseProxy = true
                };
            }
        };`

**Comment by clairernovotny** [comment]
If it works correctly with fiddler in 6.0.38 or 6.0.94, but not without it, then it seems like there's something else going on that's outside of Refit's control?

**Comment by falsebo** [comment]
BodyAttribute.Buffered set true it works fine
6.0.1 RefitSettings.Buffered default is true 6.0.38 is false
[https://github.com/reactiveui/refit#buffering-and-the-content-length-header](url)

**Comment by clairernovotny** [comment]
It looks like while Buffered was true, there was a bug where it wasn't actually working.

There was a bug fixed in this PR: https://github.com/reactiveui/refit/pull/1115

In this case, the change in default value was necessary to ensure proper behavior. Setting it in the attribute is the correct fix.
