### ISSUE TITLE
[BUG] Refit 6 should be able to work with client libraries, generated by Refit 5

### ISSUE THREAD

**Issue by nZeus** [reactiveui/refit#1172]
Hi, 

We have a library `L1` which describes our REST API and is generated with Refit 5.x; and a project `P1` that references `L1`.
We're trying to upgrade `P1` from .netcore 3 to .net 5.
Because of this we had to upgrade Refit in `P1` from 5.x to 6.x.

But now we get the `{L1_ApiClientInterface} doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.`

The issue happened because the assembly qualified name [was changed](https://github.com/reactiveui/refit/blob/15bbe4bdc73aaa4511a94df7385e4f9c9ccc1ffb/Refit/UniqueName.cs#L47) in Refit 6. (Compare [to v5](https://github.com/reactiveui/refit/blob/48ad63976c72f8a0b000ec5d096ebe947c0c6b5b/Refit/UniqueName.cs#L23)).

The Refit library should be able to work with client libraries, generated by Refit 5.

![image](https://user-images.githubusercontent.com/2727326/117996284-4f9f8580-b342-11eb-843b-ac0e5cf955fe.png)
![image](https://user-images.githubusercontent.com/2727326/117996386-680fa000-b342-11eb-9761-881e0396266e.png)

**Comment by clairernovotny** [comment]
v6 is a major version update and is expected to have breaking changes. Changing the format of the assembly qualified name was required in this case. That's not expected to change again any time soon.

**Comment by nZeus** [comment]
Very sad. How do you suggest people to upgrade the projects? all at once? 👎

**Comment by mronnblom-cint** [comment]
We use a similar approach, with libraries containing the Refit interfaces, and other applications consuming those as NuGet packages. My guess is that this is not an uncommon scenario.
This breaking change causes "NuGet hell" and forces us to upgrade all Refit libraries and all consuming applications simultaneously. At the very least, I think that this should be added to the documentation, as it's not mentioned at all [there](https://github.com/reactiveui/refit#breaking-changes-in-6x).
