### ISSUE TITLE
[BUG] JsonSerializationException: Error converting value   (json inside json)

### ISSUE THREAD

**Issue by namilkimfree** [reactiveui/refit#1194]
**Describe the bug**

An exception occurs when deserializing json in json.

example json data 
 ```
{
            "test": "en",
            "name": "namil",
            "extraInfo": "{\"class\":\"2\",\"value\":\"nadada\"}",
 }
```

example parsing class
```
 public class Response
 {
	public stringe Test { get; set; }

	public string Name { get; set;}

	public ExtraInfo ExtraInfo { get; set; }
}
 public class ExtraInfo 
 {
	public stringe Class{ get; set; }

	public string Value{ get; set;}
}
```

**Steps To Reproduce**
1.  make the api
        [Post("/profile/v4/get")]
        Task<ApiResponse<Response>> GetProfile();
        
2. call the api   refit.GetProfile();
   

**Expected behavior**
Parsing json into json should succeed.

After receiving the value as a string, the manual deserialization succeeds.

**Environment**

- OS:       Windows 10
- Device:   Desktop
- Version:   6.0.38 
- Working Version: 6.0.38 
- dotnet core  3.1

**Comment by lostincomputer** [comment]
Change your return type to `Task<ApiResponse<Response>>`

**Comment by namilkimfree** [comment]
@lostincomputer 

[Post("/profile/v4/get")]
Task<ApiResponse<Response>> GetProfile();

Class propery don't parsing thorw exception.

but  if I deserialize it myself, it works fine.

**Comment by lostincomputer** [comment]
JSON Serializers doesn't have native support for JSON within a JSON. Which JSON Serializer are you using? Is it JSON.net or System.Text.Json?

**Comment by namilkimfree** [comment]
ArgumentException: Could not cast or convert from System.String to ExtraInfo.

   ContentSerializer =  new NewtonsoftJsonContentSerializer( new JsonSerializerSettings()
                    {
                        ContractResolver =  new CamelCasePropertyNamesContractResolver(),
                        NullValueHandling = NullValueHandling.Include,
                        MissingMemberHandling = MissingMemberHandling.Ignore,
                        MaxDepth = Int32.MaxValue,
                        DefaultValueHandling =  DefaultValueHandling.Include,
                    }),

**Comment by lostincomputer** [comment]
I highly highly discourage you to have a JSON within a JSON because JSON wasn't designed for that. However, if you really need to have a JSON within another JSON, here is how you could do it in JSON.net


```
   public class Response
   {
      public string Test { get; set; }
      public string Name { get; set; }

      [JsonConverter(typeof(EmbeddedJsonConverter))] // For handling JSON within a JSON
      public ExtraInfo ExtraInfo { get; set; }
   }

   // This class is very rudimentary because it doesn't handle edge cases such as a nulls. If you want to enhance this, take a look at https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs
   public class EmbeddedJsonConverter : JsonConverter
   {
      public override bool CanConvert(Type objectType) => true;

      public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
      {
         using var stringReader = new StringReader(reader.Value.ToString());
         return serializer.Deserialize(stringReader, objectType);
      }

      public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
      {
         using var stringWriter = new StringWriter();
         serializer.Serialize(stringWriter, value);
         writer.WriteValue(stringWriter.ToString());
      }
   }
```

What you raised is not a bug.

**Comment by namilkimfree** [comment]
@lostincomputer   hi, thank you best regards.

close with this issue.
