### ISSUE TITLE
[BUG] Query does not work properly if parameter is a part of the url

### ISSUE THREAD

**Issue by ilya-git** [reactiveui/refit#1195]
**Describe the bug**

`[Query(CollectionFormat.Csv)]` attribute does not work properly if parameter injected in the URL

    [Get("/odataQuery?$filter=id in ({ids})")]
    Task<string> RunQuery([Query(CollectionFormat.Csv)]IEnumerable<long> ids);

**Steps To Reproduce**

Run a query similar to the one in the example. Url will be this:

`odataQuery?$filter=id in %28System.Collections.Generic.List1%5BSystem.Int64%5D%29`

**Expected behavior**

A query like this:

`odataQuery?$filter=id in %281,2,3,4%29`

**Environment**

- OS:       Windows
- Device:   PC
- Version:  Refit.HttpClientFactory 6.0.38

I am actually not sure it's a bug, perhaps I just don't understand the docs fully, maybe query is only supposed to work with parameters it adds itself. Should probably then throw an exception that query attribute parameter is allowed to be a part of the URL.

Would be nice to have a way of doing this, so far I have only a workaround to generate a string parameter myself

**Comment by lostincomputer** [comment]
Yes, you misunderstand the docs. Refit attributes can only contain the URL path.

**Incorrect**
```
[Get("/users/list?ages={ages}")]
Task Search([Query(CollectionFormat.Csv)]int[] ages);
```

**Correct**
```
[Get("/users/list")]
Task Search([Query(CollectionFormat.Csv)]int[] ages);
```

One way to cater to your use case is to do this:
```
   interface IRestClient
   {
      [Get("/odataQuery")]
      Task<HttpResponseMessage> RunQuery(RunQueryParams params);
   }

   class RunQueryParams
   {
      [AliasAs("$filter")]
      public string Filter { get; private set; }

      public RunQueryParameter(params long[] ids)
      {
         Filter = $"id in ({string.Join(",", ids)})";
      }
   }
```

**Comment by ilya-git** [comment]
Hi! Thanks a lot for help, interestingly enough I have used this solution almost exactly as you described, it works well.
