### ISSUE TITLE
[BUG] ApiResponse<T> Content is null for non-successful status codes

### ISSUE THREAD

**Issue by haacked** [reactiveui/refit#1221]
**Describe the bug**

I have an API endpoint that can result in a 409 Forbidden response with a response body. When I call it with a Refit client method, the body is null. If I change the endpoint to return a 200 status code, the body is not null.

**Steps To Reproduce**

If you're familiar with ASP.NET MVC, here's an example of the endpoint (more or less):

```csharp
[HttpPut]
public async IActionResult Put() {
    var conflictResult = Json(new MyResponse {Success = false, Message = "conflict!"});
    conflictResult.StatusCode = StatusCodes.Status409Conflict;
    return conflictResult;
}
```

Here's the class that represents the body of the response.

```csharp
public class MyResponse {
    public bool Success {get;set;}
    public string Message {get;set;} = string.Empty;
}
```

Here's my Api Client:

```csharp
public interface MyApi {
    [Get("/api")]
   Task<ApiResponse<MyResponse>> PutAsync();
}
```

And my code to call the API:

```csharp
var client = RestService.For<IAbbotApi>("https://localhost:1234/api");
var response = await client.PutAsync();
Console.WriteLine(response.Content.Message); // response.Content is null
```

**Expected behavior**
I expected that even though the response status code is 409, that the `response.Content` is not null but is populated by the body of the request. Note that if I make the same call with Postman or Curl I can see that the body is in the response even though the status code is 409.

**Actual Behavior**

The `response.Content` is null.

**Additional Context**

If I change the controller so it returns a 200 status code (aka remove the line `conflictResult.StatusCode = StatusCodes.Status409Conflict;`) then `response.Content` is not null and populated properly.

Thanks!

**Comment by haacked** [comment]
I forgot to mention, I am using Refit `6.0.94`

**Comment by haacked** [comment]
Some more context, I do have a workaround.

```csharp
public interface MyApi {
    Task<HttpResponseMessage> PutAsync();
}
```

Then I can use the following code in the client.

```csharp
var client = RestService.For<IAbbotApi>("https://localhost:1234/api");
var response = await client.PutAsync();
var body = await response.Content.ReadFromJsonAsync<SkillUpdateResponse>();
Console.WriteLine(body?.Message);
```

So I'm not blocked by this, but it would be nice if I could use `ApiResponse` here.

**Comment by clairernovotny** [comment]
Any chance of a PR? ;)

**Comment by haacked** [comment]
Maybe. Can you point me in the general direction of the code that handles this stuff?

**Comment by clairernovotny** [comment]
Should be in ApiResponse.Create 

https://github.com/reactiveui/refit/blob/main/Refit/ApiResponse.cs

**Comment by haacked** [comment]
@clairernovotny it looks like the [current behavior is intentional](https://github.com/reactiveui/refit/blob/main/Refit/RequestBuilderImplementation.cs#L272).

The comment there says: "Only attempt to deserialize content if no error present for backward-compatibility"

This was introduced in: 0abca6411372ab54b2dac76df1cb5165081407a7 by @Dreamescaper.

It looks like `ApiException.Content` is populated with the body of the request (as a string) when a non-success error status code is returned. I think that may be the right behavior because there may be cases where the response body is different in error cases than in success cases.

**Comment by nathanpovo** [comment]
For anyone else that stumbles onto this, you can access the `string` content of an unsuccessful response through the `Error` property.

```diff
var client = RestService.For<IAbbotApi>("https://localhost:1234/api");
var response = await client.PutAsync();
-Console.WriteLine(response.Content.Message); // response.Content is null
+Console.WriteLine(response.Error.Content); // response.Error.Content is a string that can be deserialised to MyResponse
```

This works for refit 6.3.2. I am not sure when this functionality was added.
