### ISSUE TITLE
[BUG] IMyInterface doesn't look like a Refit interface. 

### ISSUE THREAD

**Issue by wfswanepoel** [reactiveui/refit#1233]
Upgraded the projects from version 5.2.4 to version 6.0.94 and when I started to run the project, I was getting the following error:

IMyInterface doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

**Steps To Reproduce**
Just upgrade an existing project that used an older version.

More Information.
TargetFramework: net5.0
LangVersion: 8

I doubled checked that I reference the correct version and no other library that we use are using the older version.
I updated the interface to use the Refit attributes, so they are all clean from the .net http attributes.
I removed Refit library from my project and added it back again.

I am still getting the same exception and it is driving me crazy!

**Comment by tanshanli** [comment]
how to fix it?

**Comment by wfswanepoel** [comment]
> how to fix it?

You have to make sure that EVERY library that uses Refit HAS to be the same version.

We used a lot of libraries that we have built inhouse and the one library that logs data used it and I had to update that library too.

It is a lot of searching that you have to do but yeah. If one library use the older version, Nothing will work.

I assume it is because of the major breaking changes in version 6

**Comment by tanshanli** [comment]
> > how to fix it?
> 
> You have to make sure that EVERY library that uses Refit HAS to be the same version.
> 
> We used a lot of libraries that we have built inhouse and the one library that logs data used it and I had to update that library too.
> 
> It is a lot of searching that you have to do but yeah. If one library use the older version, Nothing will work.
> 
> I assume it is because of the major breaking changes in version 6.
> 
> You will not get a warning and nothing will tell you which library is breaking it. So you will have to do a lot of searching.
> 
> Good luck

I know the reason for my problem, Post("Variables cannot be used") 
error:  Post(MyClass.Path)
validity: Post("/api/test")
