### ISSUE TITLE
[BUG] JsonPropertyAttribute ignored in Refit v6.0.94,but work well with v5.2.4

### ISSUE THREAD

**Issue by Mrchensama** [reactiveui/refit#1236]
**Describe the bug**

Runtime Environment: DotNet 5
  I was going to use the class named `HeaderCollection` which is not defined in version 5.2.4. So, i upgrade `Refit` to version 6.0.94(latest) and i got the class `HeaderCollection`.
  But when i debug some interfaces ,i got some trouble. It ignores the `JsonPropertyAttribute` on property of the parameters and returns.
  For example, if the entity to receive result looks like :
``` CSharp
public class DemoReturns{
  [JsonProperty("errcode")]
  public string? ErrorCode {set;get;}
  [JsonProperty("errmsg")]
  public string? ErrorMsg {set;get;}
  [JsonProperty("expire_in")]
  public int? ExpireIn {set;get;}
  public int? Test {set;get;}
  public int? TestNum{set;get;}
}
```
  And the return json looks like :
``` Json
{
    "errcode":"xxx",
    "errmsg":"xxx",
    "expire_in": 120,
    "test": 1,
    "testnum":1
}
```
  And then i will get an object of type `DemoReturns` whose json looks like :
``` json
{
    "errcode":null,
    "errmsg":null,
    "expire_in": null,
    "test": 1,
    "testnum":1
}
``` 
  And i actually configured this in `Startup.cs` file.
``` CSharp
 AddControllers().AddNewtonsoftJson()
```
  After a few times of test ,i'm sure that it was that the lastest version of Refit ignored the `JsonPropertyAttribute`,**but it works well with `JsonPropertyNameAttribute` which is defined in `System.Text.Json.Serialization`**.

  Finally,i did not solve this problem ,so i degrade Refit to version 5.2.4 which works well.

  I'm still not clear about whether it is a bug or not. 
  Appreciation to any idea about this problem.

**Environment**

- OS:     win10  
- Device:  desktop  
- Version:  6.0.94  
- Working Version:  5.2.4

**Comment by IOL0ol1** [comment]
Newtonsoft.Json.JsonProperty❌ 
System.Text.Json.Serialization.JsonPropertyName ✔

**Comment by clairernovotny** [comment]
Hi,

It looks like you're not setting the Newtonsoft Json content serializer as described here: https://github.com/reactiveui/refit#breaking-changes-in-6x.

That method you mentioned is for ASP.NET Core; other libraries don't know what that is.

**Comment by Mrchensama** [comment]
> Hi,
> 
> It looks like you're not setting the Newtonsoft Json content serializer as described here: https://github.com/reactiveui/refit#breaking-changes-in-6x.
> 
> That method you mentioned is for ASP.NET Core; other libraries don't know what that is.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b7654185c3bbae4306b74cd31476cc4ac2e8f1eeea3a1865ae77b16416baff2c/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f663939666238323564613035663532373530613433343036326463646662643239343563623635323936633934623865353538613737313965623138363230642f726561637469766575692f7265666974"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - reactiveui/refit: The automatic type-safe REST library for .NET Core, Xamarin and .NET. Heavily inspired by Square's Retrofit library, Refit turns your REST API into a live interface.](https://github.com/reactiveui/refit)**The automatic type-safe REST library for .NET Core, Xamarin and .NET. Heavily inspired by Square's Retrofit library, Refit turns your REST API into a live interface. - GitHub - reactiveui/refit...

Thanks for your reply, clairenovotny. Following the given link , i find the reason. As you said, it's not a bug but my fault. I ignored that paragraph of breaking change in the document .Thanks a lot.
