### ISSUE TITLE
feature: Add Xml documentation for public methods

### ISSUE THREAD

**Issue by laurentksh** [reactiveui/refit#1274]
**Is your feature request related to a problem? Please describe.**

I recently started using this library and I found the lack of Xml documentation to be disorienting (compared to other OSS libraries and most of the .NET libraries).
For example, I had to check the source code to know exactly what exception ApiResponse<T>.EnsureSuccessStatusCodeAsync() is throwing.

**Describe the solution you'd like**

I would like to add Xml docs. to various public methods and classes in the library.

**Describe alternatives you've considered**

I guess the alternative would be to leave the code as-is.

**Describe suggestions on how to achieve the feature**

Add Xml documentation to public methods and classes.

**Additional context**

I already started working on a Pull request to add Xml documentation on my fork of the repo.
I really like this library and I think these comments would be a good addition.

Best regards,

**Comment by clairernovotny** [comment]
Documentation is always very welcome!

**Comment by laurentksh** [comment]
@clairernovotny glad to hear that ! :)
