### ISSUE TITLE
feature: Built-in support for the .NET 6 JSON source generator

### ISSUE THREAD

**Issue by martincostello** [reactiveui/refit#1277]
**Is your feature request related to a problem? Please describe.**

The new [JSON source generator](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/) in .NET 6 allows applications to use a source generator to produce more performant (de)serialization code for JSON that the default reflection-based approach.

The default Refit `IHttpContentSerializer` implementation for System.Text.Json does not use/support this feature as it is today.

**Describe the solution you'd like**

A built-in implementation of `IHttpContentSerializer` that uses the `JsonSerializerContext` class and the relevant new `JsonSerializer` methods added in .NET 6 so applications can quickly plug the JSON source generator into Refit with minimal ceremony/effort.

**Describe alternatives you've considered**

Applications write their own implementation of `IHttpContentSerializer` to achieve this as needed.

**Describe suggestions on how to achieve the feature**

[This gist](https://gist.github.com/martincostello/53b10574fbee2d8bc7b0f75bf0855a84) shows a potential way to achieve this in code as a standalone type for illustrative purposes. It could potentially be built into the existing `SystemTextJsonContentSerializer` class instead via a new constructor overload, rather than creating a new type.

**Comment by martincostello** [comment]
I'm going to close this, as it turns out I'd missed a new feature as part of the JSON source generator work, that lets you bind a context to an options so it is used for type metadata when (de)serializing if there's a registration associated with it: [`JsonSerializer.AddContext<TContext>()`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.addcontext?view=net-6.0)

Thus, the existing `SystemTextJsonContentSerializer` class should be able to work with it as-is.

**Comment by clairernovotny** [comment]
@martincostello It might be worth a note in the readme about this -- can you please submit a PR with that?

**Comment by martincostello** [comment]
Sure @clairernovotny - I'll open something later on today 👍
