### ISSUE TITLE
[BUG] Error deserializing response while debugging connected Xamarin.Forms Android

### ISSUE THREAD

**Issue by najeeb-np** [reactiveui/refit#1280]
I have been using refit for the Xmarin Android project and it was working well. Recently Android project while debugging from visual studio 2022 refit failed to retrieve data from server, while investigating the issue I found that data does not retrieve while the android application is in debugging mode and works when I stop debugging( I meant when I open the app in the android emulator or phone device application works as expected if debugging is disconnected)

**Steps To Reproduce**

//Interfeace
public interface IAPI
 {
        [Get("/api/alislahmainapi")]
        Task<List<AlIslah>> GetAlIslahsAsync([AliasAs("filter")] string filter = null);
 }

//Xamarin app class in shared library project(Here  i am initializing rest client)
 public partial class App : Application
    {
        public static IAPI RestClient { get; private set; }

        public App()
        {
            var uname = "xxxxxxxx@outlook.com";
            var uauth = "xxxxxxx";
            var authHeader = Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(uname + ":" + uauth));

            var client = new HttpClient
            {
                BaseAddress = new Uri(Constants.RestUrl),
                DefaultRequestHeaders =
                    {
                        {"Authorization", $"Basic {authHeader}"}
                    }
            };
           RestClient = RestService.For<IAPI>(client);
}

//retrieving data web API
 var items = await App.RestClient.GetAlIslahsAsync("home");

**Error**
[0:] An error occurred deserializing the response.

**Expected behavior**
All objects must be retrieved

**Environment**
- OS:       Android 11
- Device:  Emulator or actual device

**Comment by clairernovotny** [comment]
This seems like an external issue that should be opened up with Microsoft or in the Xamarin/Android repos. I'm going to close this here as not being anything specific to Refit.
