### ISSUE TITLE
feature: Improve support for nullable

### ISSUE THREAD

**Issue by dannyBies** [reactiveui/refit#1302]
**Is your feature request related to a problem? Please describe.**

In my project I have nullable reference types enabled `<Nullable>enable</Nullable>`.

I retrieve data like this:
```
var response = await RestApi.Users.Query.GetUrl("1234");
if (!response.IsSuccessStatusCode)
{
    Logger.LogError(response.Error.Message);
    return;
}
var url = response.Content.Url;
```
The issue I'm seeing is that I get CS8602 warnings(Dereference of a possible null reference) for `response.Content` and `response.Error`  due to these being nullable. However I am checking `response.IsSuccessStatusCode` which I believe make sure that either `Content` or `Error` is populated.

**Describe the solution you'd like**

To not get these warnings.

**Describe suggestions on how to achieve the feature**

I believe we can add the following attributes to `IsSuccessStatusCode` to fix this issue.
`[MemberNotNullWhen(true, nameof(Content))]`
`[MemberNotNullWhen(false, nameof(Error))]`

**Comment by clairernovotny** [comment]
Can you please share a sample interface definition that matches what you're doing? It's not clear what the type of `response` is here.

**Comment by dannyBies** [comment]
This happens for every call that uses `ApiResponse` https://github.com/reactiveui/refit/blob/569108a65079d364647f06437f977df8145fc578/Refit/ApiResponse.cs#L45

An example could be:
```
[Get("/api/xyz")]
Task<ApiResponse<UrlResponse> GetUrl(CancellationToken cancellationToken = default);

public record UrlResponse(string Url);
```

**Comment by clairernovotny** [comment]
Can you please submit a PR to add the correct attributes?

**Comment by dannyBies** [comment]
I've submitted a PR, thanks!

**Comment by clairernovotny** [comment]
Are there other places in the public API that we need to decorate with the nullable attributes to be more accurate?

**Comment by dannyBies** [comment]
I've looked through `ApiResponse` and `ApiException` and have added one more property to the list. I haven't looked through the rest of the API as I'm not too familiar (yet!) with the project and I unfortunately don't have the time right now to look through everything.

If you can point me to the exact properties that could also use this change I'd be happy to make another commit.

**Comment by clairernovotny** [comment]
Thanks!
