### ISSUE TITLE
[BUG] Dynamic API endpoint creation with dynamic url is slow

### ISSUE THREAD

**Issue by LuukVerhagen** [reactiveui/refit#1308]
**Describe the bug**
I use Refit with different host URLs, which come dynamically from the database. To accomplish this, I have created a factory service, which creates the Refit Endpoints dynamically based on the URL of the database. The problem which I encountered, is that the first API call with this newly created endpoint object is really slow (more than 40 seconds). If I debug the same code with a literal string URL instead of an URL from the database, I don't encounter this slowness.

```csharp
//Slow
Project project = await projectService.GetSelectedProject();
var endpointWithDynamicUrl = Refit.RestService.For<TApiEndpoint>(project.Url, new Refit.RefitSettings()
{
    AuthorizationHeaderValueGetter = this.apiAuthService.GetToken
});

//Fast
var endpointWithLiteralUrl = Refit.RestService.For<TApiEndpoint>("https://example.com/", new Refit.RefitSettings()
{
    AuthorizationHeaderValueGetter = this.apiAuthService.GetToken
});
```

**Steps To Reproduce**

**Expected behavior**

That dynamically created API endpoint objects with a dynamic URL source doesn't cause a slow endpoint call.

**Screenshots**

**Environment**

- OS: Windows
- Device:   Lenovo thinkpad p1
- Version:   
- Working Version: 

**Additional context**

If the URL in the database is a local URL, the first call is much faster.

**Comment by codeex** [comment]
Any suggestions for improvement?  It doesn't look like a bug!

**Comment by LuukVerhagen** [comment]
I finally found the problem. The underlying HttpClient wasn't able to resolve my IPv6 address (which was wrongly configured in my DNS). It takes more than half a second for the HttpClient to figure out IPv6 won't work and to switch to IPv4. To conclude the problem wasn't in Refit.
