### ISSUE TITLE
feature: Do not throw exception when status code is not 200

### ISSUE THREAD

**Issue by andrew-vdb** [reactiveui/refit#1315]
**Is your feature request related to a problem? Please describe.**

We would like refit to not throw exception when response status code is not 200
Api may response with status code 400 and return the error message etc
According the best practices https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0
![image](https://user-images.githubusercontent.com/12871379/153589316-abbec4e2-dc71-4eba-a974-2200cddb37f0.png)

**Describe the solution you'd like**

RefitSetting boolean, do not throw when status code is not 200

**Describe alternatives you've considered**

SonarQube complaining about this and I'm not quite sure with the risk of this code
![image](https://user-images.githubusercontent.com/12871379/153588801-878d65fb-6ade-4832-a5f4-d44c3a52bf57.png)

**Describe suggestions on how to achieve the feature**

RefitSetting boolean, do not throw when status code is not 200

**Additional context**

I'm not the first one who request this issue, the work around still throw exception but we just don't provide the handling? 
Don't see why its difficult to implement this feature

**Comment by DouglasKSmith** [comment]
Have you considering making your Refit interface methods [return `Task<IApiResponse>`, `Task<IApiResponse<T>>`, or `Task<ApiResponse<T>>`](https://github.com/reactiveui/refit#when-returning-taskiapiresponse-taskiapiresponset-or-taskapiresponset)? This would cause non-successful responses to be populated as an `ApiException` into the `ApiResponse.Error` property without being thrown.

**Comment by andrew-vdb** [comment]
Yes, changing signature feels like a bit overkill

The main point is there is no exception
400 is also valid successful response as the server successfully responding the client
Exception should be used when there is real exception like the server is not responding (with timeout)
but that's my opinion so....

We could simply make a change here
https://github.com/reactiveui/refit/blob/92ee8887fce181f211cb7ca1e7f8d8c7afa0a821/Refit/ApiResponse.cs
![image](https://user-images.githubusercontent.com/12871379/154710823-06ec2322-6099-4581-bdfd-eb21f543b80e.png)

**Comment by andrew-vdb** [comment]
Another argument is that calling this method is fully optional to the caller
```
EnsureSuccessStatusCode
```

**Comment by HelloKitty** [comment]
Did anything like this end up getting implemented? I'd love to be able to have refit try to deserialize the body by default on all response codes and only throw if it cannot.

**Comment by anaisbetts** [comment]
I think the current behavior is as intended, if users want custom error handling there is a mechanism to do so.
