### ISSUE TITLE
Add certificates request

### ISSUE THREAD

**Issue by ggaj** [reactiveui/refit#1318]
Hello guys,

How can I add certificate (.pfx) at request by refit?

I've been looking for this topic but haven't found anything.

Thanks!

**Comment by Moreno-Borsalino** [comment]
I have the same problem. I would like to see a solution too.

**Comment by anaisbetts** [comment]
Refit is a wrapper around HttpClient, it doesn't directly implement HTTP or TLS - if you want to examine the certificate you probably need to go a level below Refit and work with HttpClient directly (you can always provide Refit with your own HttpClient so it's not an either/or)
