### ISSUE TITLE
feature: Post List<Guid> through Refit

### ISSUE THREAD

**Issue by velvetflair** [reactiveui/refit#1326]
**Is your feature request related to a problem? Please describe.**

I'm unable to post List<Guid> through refit. Here's the interface declaration:

[Post("")]
        [Headers("Content-Type:application/json")]
        Task MyMethod([Body(BodySerializationMethod.UrlEncoded)] CommandType command)
        
        Here's the CommandType class

public class CommandType
    {
        public IEnumerable<Guid> Prop { get; set; }
    }

Even though Refit is able to make the call but the argument for Prop is null at the receiving end.

I tried with [Body(BodySerializationMethod.UrlEncoded)] [Query(CollectionFormat.Multi)] too but no luck!

[FOUND SOLUTION] I've solved it using just the following by removing both Body attribute and CommandType. Instead, put the Property inside the class into the parameter directly. Just FYI.

[Query(CollectionFormat.Multi)] List<Guid> Prop

**Comment by ChrisPulman** [comment]
Issue notified as resolved.
