### ISSUE TITLE
Support CamelCase Query

### ISSUE THREAD

**Issue by lauglam** [reactiveui/refit#1333]
**Is your feature request related to a problem? Please describe.**

I have a class like this

```c#
public class Query
{
    public int? Limit { get; set; }
    
    public int? Offset { get; set; }
}
```

It needs to be converted like this

```text
?limit=10&offset=0
```
But it is actually converted to

```text
?Limit=10&Offset=0
```

Is there any way to support CamelCase without using AliasAs?

**Describe the solution you'd like**

I am now like this but very redundant

```c#
public class Query
{
    [AliasAs("limit")]
    public int? Limit { get; set; }

    [AliasAs("offset")]
    public int? Offset { get; set; }
}
```

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

**Additional context**

**Comment by carlosharrycrf** [comment]
Any updates on this? It's a little confusing that `RefitSettings.ContentSerializer` ignores queries as objects.

**Comment by anaisbetts** [comment]
Though I agree that this should probably have been done differently, this probably will have to be opt-in because it would be an incredible trolly breaking change otherwise

**Comment by tcortega** [comment]
@ChrisPulman this should be closed
