### ISSUE TITLE
[BUG] 请求WEBAPI的时候,会导致一下问题吗？高并发的情况下An error occurred while sending the request.

### ISSUE THREAD

**Issue by huangyedie** [reactiveui/refit#1341]
**Describe the bug**

请求API的时候，并发高会导致这个问题吗？An error occurred while sending the request.
Unable to read data from the transport connection: Connection reset by peer.Connection reset by peer

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:       
- Device:   
- Version:   5.2.4
- Working Version: 

**Additional context**

**Comment by YongZhouPolestar** [comment]
Same issue ,after update to .net 6 with latest refit

**Comment by anaisbetts** [comment]
This is an issue with the underlying HttpClient, Refit does not do anything special in this regard. You should try writing an example request with HttpClient directly and see what is going across the wire with e.g. Wireshark
