### ISSUE TITLE
Adding Refit Version 6.3.2 to MVC Application causes Error and Renders Application Unusable

### ISSUE THREAD

**Issue by QueenBee61** [reactiveui/refit#1342]
When I try to add Refit Version 6.3.2 I receive the following error on build:

Packages.config does not support Analyzers, including Source Generators. Migrate to PackageReference: 'https://devblogs.microsoft.com/nuget/migrate-packages-config-to-package-reference/'

It is not usable in MVC Applications?  Is there a particular version I must use?  I am able to install version 4.0, in the MVC application but then I can't use the SDK created with 6.3.2.  I tried to create the SDK using 4.0 and receive the error "ApiResponse" does not exist.

**Comment by anaisbetts** [comment]
Isn't this telling you what to do?

**Comment by QueenBee61** [comment]
It doesn't work.  It tells me either the project is not using packages.config or is not eligible, or something on that order.

**Comment by jakeshoemaker** [comment]
@QueenBee61  there are ways to force VisualStudio to think its eligible. You need to edit the .csproj file and change it to a class library then you can migrate it. I just did it. It was lots of work with a big repo, but doable. This StackOverflow article helped me https://stackoverflow.com/questions/57581514/vs-2015-to-2017-migrate-to-package-reference-failed

**Comment by QueenBee61** [comment]
@jakeshoemaker - thanks!

**Comment by jonathh21** [comment]
> What version of Refit do I need to downgrade to that will support `packages.config`? I can't afford to migrate a huge MVC project on full framework today.

I'm here.. same reason thinking the same thing.. looking for the same solution.

Did you find a version?

Thanks

**Comment by jrummell** [comment]
> I'm here.. same reason thinking the same thing.. looking for the same solution.
> 
> Did you find a version?
> 
> Thanks

@jonathh21 I believe it was `4.7.51`

**Comment by jonathh21** [comment]
Wow thanks.

Just crept up on 6.0.15 a change to 6.0.21 and the error returns.

However I haven't actually used it yet! So might back to go lower..

**Comment by jonathh21** [comment]
Spoke to soon.

Anything 6.* and I get the error 

"doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project."

Changing to 5.2.4 and that error (at least) goes away.

**Comment by ChrisPulman** [comment]
Closing as a user-based resolution, please update to the latest version, thank you.
