### ISSUE TITLE
Refit needs a logo/icon for the NuGet feed/package

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/refit#135]
It's a shame that NuGet doesn't support GIFs as this how working on a project that uses Refit makes me feel:

![Popping](http://www.reactiongifs.com/r/poppin1.gif)

/cc: @paulcbetts (What should the logo be?)

**Comment by paulcbetts** [comment]
Not sure - the Retrofit library doesn't have a logo, so we can't copy it :(

**Comment by bennor** [comment]
I reckon this would be a better representation of what it does...

![Refit](http://www.reactiongifs.com/r/mgc.gif)

**Comment by ghuntley** [comment]
We could lift a logo from http://thenounproject.com/search/?q=lazy as long as the README.md is attributed similar to how the Fody guys do it @ https://github.com/Fody/Fody/blob/master/README.md
* ![](https://d30y9cdsu7xlg0.cloudfront.net/png/97948-84.png)
* ![](https://d30y9cdsu7xlg0.cloudfront.net/png/97936-84.png)

**Comment by paulcbetts** [comment]
That's got a lot goin' on. Lemme see what I can do.

**Comment by bennor** [comment]
Those are kind of wacky and complicated for a logo, aren't they?

It's maybe not that original, but what about something like this:

![image](https://cloud.githubusercontent.com/assets/1063280/6569213/16d82040-c73a-11e4-86bb-0841af42e056.png) 
([source](http://thenounproject.com/term/branch/60039/)

If the license allowed modification, we could change the left hand part to be a lighter colour (implying the automatic nature of Refit). Wouldn't be too hard to whip up something similar if licensing is a problem.

**Comment by hougasian** [comment]
<img width="291" alt="screen shot 2018-04-17 at 9 07 25 am" src="https://user-images.githubusercontent.com/6231956/38871592-4e994064-421f-11e8-9a08-3ae20f561799.png">
<img width="572" alt="screen shot 2018-04-17 at 9 11 00 am" src="https://user-images.githubusercontent.com/6231956/38871610-5a6e83ea-421f-11e8-8664-c1618078856b.png">

**Comment by hougasian** [comment]
<img width="865" alt="screen shot 2018-04-17 at 9 24 51 am" src="https://user-images.githubusercontent.com/6231956/38872438-3fcc9a34-4221-11e8-8ccc-fceda67943b0.png">

**Comment by paulcbetts** [comment]
Let's go with the Green, to match Retrofitr

**Comment by ghuntley** [comment]
oh snap I was literally just about to tweet about this. Nice @hougasian. Send in the PR to https://github.com/paulcbetts/refit/blob/master/Directory.build.props

<img width="638" alt="screen shot 2018-04-23 at 11 15 05 am" src="https://user-images.githubusercontent.com/127353/39102487-aea89a3c-46e7-11e8-9314-2b27e01165f2.png">

**Comment by onovotny** [comment]
The SVG was merged in, now just need to generate assets for the package

**Comment by bennor** [comment]
Better late than never, eh? 😹
