### ISSUE TITLE
Question - how to handle BSON data with Refit

### ISSUE THREAD

**Issue by roarjoss** [reactiveui/refit#1378]
Hello,
If I have a controller method returning BSON like shown below, how should I handle this using Refit?
Currently Content is null because can't deserialize.
I have tried to search but can not find this information anywhere.

```
[Produces("application/bson", Type=typeof(MyDto))]
[HttpGet("/api/pdfs/bson/{id}")]
public async Task<IActionResult> GetDocumentDataAsBson(Guid id) 
```

**Comment by anaisbetts** [comment]
I would try replacing `ContentSerializer` with one that understands BSON (there's one in Newtonsoft as I recall!)
