### ISSUE TITLE
[BUG] Refit.ApiException: Response status code does not indicate success: 400 (Bad Request).    at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288 --- End of stack trace from previous location ---

### ISSUE THREAD

**Issue by wj8400684** [reactiveui/refit#1388]
The machine works normally, but an error is reported when it is placed on the server! Server version Windows Server 2022 datacenter 21h2！

**Comment by wj8400684** [comment]
Reinstall solution！

**Comment by auvansang** [comment]
I have this problem to, I can get response body, but after that polly retry the request due to status code 400

**Comment by noontz** [comment]
Same here when deployed to Azure Functions (in process) running on windows
Works locally in simulated functions environment
Have tried [Body(buffered:true)] and custom implementation of IHttpContentSerializer as seen in https://github.com/reactiveui/refit/issues/1122#issuecomment-1113400824 with no luck
Back to vanilla HttpClient 🥱

**Comment by anaisbetts** [comment]
This doesn't seem related to Refit. If someone can provide more information that shows that it _is_ related to Refit, please comment and we can reopen.

**Comment by noontz** [comment]
@anaisbetts In my case you are absolutely correct, that this is not related to Refit. It was a configuration issue on the server side.
