### ISSUE TITLE
using Refit can't compile success in VS 17.3.0

### ISSUE THREAD

**Issue by zwcm2007** [reactiveui/refit#1402]
I have  a WPF  Desktop application  that  framework targets net6.0-windows .   When my  IDE  VS2022  upgrading from 17. 2.1 to 17.3.0 and  using  Refit 6.3.2 ,  vs compiles errors as belows:

![56E997DD-89C5-4363-BF0B-3B7B2F45A408](https://user-images.githubusercontent.com/20622446/183847655-37b799b7-31c6-4fec-b6d9-ce369d4e69ab.png)

There is nothing except a interface file named "IAccountApi",    so  how to resolve this problem?

**Comment by AliveDevil** [comment]
Works for me in WPF, please bear in mind that current .NET SDK (6.0.7/6.0.302 and newer) has a regression that invokes source generators multiple times[^1].
Add this[^2] fix to your .csproj file and it will resolve it self, or install .NET SDK 6.0.301 and restrict SDK to 6.0.301 through global.json.

[^1]: https://github.com/dotnet/wpf/issues/6792
[^2]: https://github.com/dotnet/wpf/pull/6800/files

**Comment by zwcm2007** [comment]
thank you for answer, this problem is resolved in dotnet-sdk-6.0.401 environment!
