### ISSUE TITLE
[BUG] The 'InnerHandler' property must be null.

### ISSUE THREAD

**Issue by jchannon** [reactiveui/refit#1403]
Using the code defined in the README https://github.com/reactiveui/refit#reducing-header-boilerplate-with-delegatinghandlers-authorization-headers-worked-example, running the app results in an exception:

```
Unexpected application termination! "The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.\nHandler: 'Easee.Connector.AuthHeaderHandler'"
System.InvalidOperationException: The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'Easee.Connector.AuthHeaderHandler'
   at HttpMessageHandler Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline(HttpMessageHandler primaryHandler, IEnumerable<DelegatingHandler> additionalHandlers)
   at HttpMessageHandler Microsoft.Extensions.Http.DefaultHttpMessageHandlerBuilder.Build()
   at ActiveHandlerTrackingEntry Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(string name)
   at ActiveHandlerTrackingEntry Microsoft.Extensions.Http.DefaultHttpClientFactory+<>c__DisplayClass14_0.<.ctor>b__1(?)+() => { }
   at void System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
   at void System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
   at T System.Lazy<T>.CreateValue()
   at T System.Lazy<T>.get_Value()
   at HttpMessageHandler Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(string name)
   at HttpClient Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(string name)

```

**Steps To Reproduce**

**Expected behavior**
My app to run.

I believe you shouldn't set the InnerHandler

**Environment**

- OS:       macOS 12.5
- .NET Core: 6

**Comment by MarkEnverus** [comment]
Is there a workaround?  It seems we cannot use the delegation handler w/ Dependency Injection?

**Comment by Ninja2** [comment]
As @jchannon said, the inner handler should not be set when using from DI or it will fail when building the handlers pipeline

**Comment by MarkEnverus** [comment]
@Ninja2  should we update the docs to reflect this? It's confusing and then you need separate setups for either RestService.For and DI?

**Comment by salghazaly** [comment]
I m facing the same issue in a MAUI Blazor App in .Net 7.0
in my app there are two messages handler on for SSL Pinning as follow
`
public class HttpsValidation : HttpClientHandler
{
public HttpsValidation()
{
    AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate | DecompressionMethods.Brotli;
    UseProxy = true;
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
   
    ServerCertificateCustomValidationCallback = OnValidateCertificate;
}
}
`
and a DelegatingHandler message handler for httpclient request as follow

`
public class CustomHttpRequestHandler : DelegatingHandler
{

}
`
I m injecting httpsclient as follow 
`

builder.Services.AddHttpClient<HttpClient>(
    "MyhttpClient",
    client => client.BaseAddress = new Uri(BaseUrl)
    ).ConfigureHttpMessageHandlerBuilder(builder => builder.PrimaryHandler = new HttpClientHandler()
    {
        UseDefaultCredentials = true
    }
    ).ConfigurePrimaryHttpMessageHandler(() => new HttpsValidation())
    .AddHttpMessageHandler<CustomHttpRequestHandler>();

`


Really the app is working fine but sometimes this issue apares suddenly evn sometimes when the app is idle for a while I get this error as follow

_blazor.webview.js:1  The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'CustomHttpRequestHandler '_

**Comment by rsr-maersk** [comment]
any status update here?
