### ISSUE TITLE
[BUG] Projects with dashes in the name break the code analyzer

### ISSUE THREAD

**Issue by mattsmithdev** [reactiveui/refit#1404]
**Describe the bug**
If your dotnet project has a `-` in the name, you will receive a build error...
` Generator 'InterfaceStubGeneratorV2' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'`
If you rename the project to something without the dash it will work fine.

**Steps To Reproduce**
Create a project (or rename an existing project) to include a `-` in the name and Build.

**Expected behavior**
Builds without error.

**Environment**
- OS:           Mac M1 Arm
- Version:   12.5
- Dotnet:    6
- Refit:       6.3.2

**Comment by Clockwork-Muse** [comment]
WAT.

That explains my issue.

**Comment by JanterSchure** [comment]
Well that explains it.
Thank you, had some issues last weekend and finally found this one.

**Comment by TimothyMakkison** [comment]
Fixed by #1921

**Comment by ChrisPulman** [comment]
Issue notified as resolved.
