### ISSUE TITLE
Using Refit with F#

### ISSUE THREAD

**Issue by paulyoung** [reactiveui/refit#145]
I've set up an API interface in an F# PCL that looks like the following:

``` fsharp
[<Headers("User-Agent: MyApiClient", "Authorization: Bearer")>]
type IMyApi =

    [<Get("/users/{user}")>]
    abstract member GetUser: user:string -> Task<User>
```

I have a test project that references the PCL. I was initially getting the `You've somehow included the PCL version of Refit in your app.` error so I also added Refit to the test project via NuGet.

I'm now getting the following message when running the tests:

> System.InvalidOperationException : IMyApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

Am I doing something wrong here or does Refit not work with F#?

**Comment by bennor** [comment]
Refit doesn't support F#... yet. It builds proxy classes at compile time by evaluating the abstract syntax trees of your interfaces. You might have some luck with v1.3 (or [this polyfill](https://gist.github.com/bennor/c73870e810f8245b2b1d)). However, neither of those approaches will work on iOS.

**Comment by paulyoung** [comment]
Thanks @bennor.

It should be possible to do the same for F# using `FSharp.Compiler.Service`.

**Comment by paulcbetts** [comment]
The other thing you could do for F# is revert back to using Castle.Core, which generates the classes at runtime - we removed this in Refit 2.0 because both iOS and WinRT cannot generate classes at runtime

**Comment by bennor** [comment]
@paulcbetts That's exactly what that polyfill does - puts back Castle.Core support so you can keep using the other good stuff added since 2.0.

You reckon it's worth addressing some of these situations with a second NuGet package?

**Comment by paulyoung** [comment]
I'd prefer a solution that works for iOS (and probably WinRT too) so will look into a compile-time solution.

**Comment by paulyoung** [comment]
I just wanted to give this a little bump and share that I've made some progress in porting Refit.Tests to FSharp.

**Comment by onovotny** [comment]
Happy to revisit this if there's any updates here?

**Comment by dboris** [comment]
Trying 4.0.1 in an F# project, I get this error:

> The file extension of 'obj/Debug/netstandard2.0/RefitStubs.g.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli. (FS0226)

Any updates on F# support?

**Comment by onovotny** [comment]
F# is not supported currently since this library needs compile-time code generation. Happy to accept a PR for this. It would need an F# moustache template file and MSBuild logic to determine which language to use based on the target project.

We also use Roslyn for the syntax parsing, so this all hinges on support there too.

**Comment by kamcma** [comment]
Would it be possible to configure a Refit client in a C# class library, and then consume that from an F# project? Without doing anything special, I get the same error as @dboris above, but perhaps there is some csproj compiler property to, I don't know exactly, vend only compiled artifacts?

**Comment by ElijahReva** [comment]
I'm using Nuke.Build project that using Refit as dependency and could not use it from FSharp project even when using csproj as proxy for dependency

**Comment by clairernovotny** [comment]
Closing due to age. Workaround is to put Refit interface into a C# project and reference that from F#.

**Comment by baronfel** [comment]
Ideally there would be some config flag to disable stub generation entirely, so that attempting cases like trying to use Nuke.Build from F# would be approachable. As it stands we can't even explore that direction because we can't stop the stub generation.

**Comment by clairernovotny** [comment]
There shouldn't be any output classes generated if there aren't any refit interfaces in the project. I'm not sure I understand the scenario that's causing an issue here? You should be able to put the Refit interfaces into a C# class lib and then reference that from an F# library.

**Comment by baronfel** [comment]
@clairernovotny I've made a quick repro project over at https://github.com/baronfel/nuke-build-fsharp-test that I think has cut the problem down to the simplest repro. I think there's some component in Nuke that's triggering refit? But I'm also not up to speed on nuke/refit overall and am just starting my explorations with it and F# together.

**Comment by clairernovotny** [comment]
@baronfel That's using an older version of Refit. Can you please try with the latest 6.x?

**Comment by baronfel** [comment]
I can certainly try! Get back to you in a bit.

**Comment by baronfel** [comment]
Yep! Using the latest version of Refit (6.0.38) allowed me to build on that repo. Thank you for the pointer!
