### ISSUE TITLE
[Bug]: InvalidOperationException on `RestService.For` when Refit interface assembly is loaded using `Assembly.LoadFile`

### ISSUE THREAD

**Issue by eduardocampano** [reactiveui/refit#1476]
### Describe the bug 🐞

We're working on a system with a ViewModel Composition Gateway architecture. In short, it means there is a composition gateway which loads composition handlers using `Assembly.LoadFile()`

When we try to get the Refit client instance inside of the loaded assembly, we get the `doesn't look like a Refit interface` error.

I created a repository to reproduce the issue [here](https://github.com/eduardocampano/RefitIssue). The `SimpleConsole` app runs as expected without issues, but the `CompositionConsole` app fails with this error:

```
INameGeneratorClient doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
```

A bit of more context, In the actual project where we found the problem we use dependency injection to allow composition handlers to register their dependencies at startup time and therefore the scenario is a bit different from this one, but we imagined the issue is related to using `Assembly.LoadFile`. In that project we're seeing a different error `InvalidCastException  ` throw at this line from `RestService` class `return (T)For(typeof(T), client, builder);` which means that the refit client instance is able to be created but for some reason it cannot be casted to the refit interface. I'm still not able to reproduce that same issue in an isolated environment.

### Step to reproduce

1. Clone https://github.com/eduardocampano/RefitIssue
2. Build the solution
3. Run SimpleConsole app, it works ok
4. Run CompositionConsole app, see error

### Reproduction repository

https://github.com/eduardocampano/RefitIssue

### Expected behavior

`RestService.For()` should return proper Refit client instance.

**Comment by 3t9xboss** [comment]
Hi @eduardocampano, I'm not a contributor but I think I can help.
In CompositionConsole program.cs, try to change Assembly.LoadFile to Assembly.LoadFrom, because of Assembly.LoadFile doesn't add your assembly to AssemblyLoadcontext.Default, so in the runtime, Refit can not use reflection to get the generated type. Assembly.LoadFrom does, so it can work.

**Comment by eduardocampano** [comment]
Wow, thank you @tuanle2193, I just tested my sample code using `Assembly.LoadFrom` and it works. I will close the bug then.
