### ISSUE TITLE
[Bug]: Refit query does not complete in WASM RELEASE mode, works fine in debug mode

### ISSUE THREAD

**Issue by assassin316** [reactiveui/refit#1484]
### Describe the bug 🐞

I have an Uno app that is built for UWP and WASM, the Refit queries all work in both Release and Debug EXCEPT for Wasm Release mode.

### Step to reproduce

1. Change your build options to compile WASM in RELEASE
2. Place a breakpoint in App.cs on line 23 (optional)
3. Launch the app in release
4. Once line 23 executes, the rest does not execute (line 26), this ONLY happens in RELEASE mode, debug mode works fine.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

The queries should successfully complete like they do in debug.

### IDE

Visual Studio 2022

### Additional information ℹ️

You can find the sample project here:

https://drive.google.com/file/d/1tq1ifdNPUM8HVbhAU2d0yDLQ_BnCrG6Z/view?usp=share_link

**Comment by assassin316** [comment]
Fixed.

Refit was necessary to be specified in the LinkerConfig.xml

![image](https://user-images.githubusercontent.com/17514380/227783460-4f06a8e9-4efa-46d9-bd25-5f548056b2d6.png)

**Comment by protonJMG** [comment]
assassin316, ty for this Issue, I have been whit this problem 10h !!! i love you
