### ISSUE TITLE
[Bug]: Refit.Newtonsoft.Json version 6.5.1 can't be used because it's depending on Refit 6.5.1 which is not published

### ISSUE THREAD

**Issue by JelleDamen** [reactiveui/refit#1497]
### Describe the bug 🐞

Refit.Newtonsoft.Json version 6.5.1 can't be used because it's depending on Refit 6.5.1 which is not published

### Step to reproduce

1. Go to nuget
2. try to add Refit.Newtonsoft.Json version 6.5.1
3. installing will not succeed since it's dependent on Refit 6.5.1, but the highest version available is 6.3.2

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

make Refit 6.5.1 available or change the dependency

### IDE

Visual Studio for Mac

### Operating system

Mac OS

**Comment by clairernovotny** [comment]
Fixed by unlisting 6.5.1 and 6.4.1 as they were inadvertently published.
