### ISSUE TITLE
[Bug]: Refit fails to generate if more than two types have the same name

### ISSUE THREAD

**Issue by yoelhalb-hitech** [reactiveui/refit#1519]
### Describe the bug 🐞

When having more than _two_ Refit interfaces with the same name in the same project (but different namespaces or different enclosing type) the generator will fail to generate the classes.

The warning at compile time is:

`CSC : warning CS8785: Generator 'InterfaceStubGeneratorV2' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'ITest1.g.cs' of the added source file must be unique within a generator.
`

While at runtime it fails with:

` System.InvalidOperationException : ITest doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.`

### Step to reproduce

```
namespace A
{
	public interface ITest
	{
		[Post("/")]
		public Task<object> Test1(object test);
	}
}

namespace B
{
	public interface ITest
	{
		[Post("/")]
		Task<object> Test2(object test);
	}
}

namespace C
{
	public interface ITest
	{
		[Post("/")]
		Task<object> Test3(object test);
	}
}
```

### Expected behavior

- Should work perfectly
- Otherwise it should at the minimum:

  - Give a descriptive _error_ (not just a warning) _at compile time_ (and in case a user doesn't want it as an error there might be an option in the csproj to remove it, and this can be mentioned in the error message, but by default a novice user expects Refit to work...)
  - Also the error message _at runtime_ should mention the possibility that the source generation failed (otherwise users are left in the dark scratching their head).

### IDE

Visual Studio 2022

### Operating system

Windows 10

### Refit Version

6.3.2

**Comment by anaisbetts** [comment]
Can you contribute a PR that adds this as a test case?
