### ISSUE TITLE
[Bug]: NuGet packages 6.4.1 and 6.5.1 are unlisted on nuget.org

### ISSUE THREAD

**Issue by 304NotModified** [reactiveui/refit#1529]
### Describe the bug 🐞

I guess this is a bug?

Because these versions are still in https://github.com/reactiveui/refit/releases

See https://www.nuget.org/packages/Refit/6.4.1 and  https://www.nuget.org/packages/Refit/6.5.1

related: https://github.com/reactiveui/refit/discussions/1493

### Step to reproduce

1. Go to https://www.nuget.org/packages/Refit/6.5.1
1. See unlisted  warning

### Reproduction repository

https://www.nuget.org/packages/Refit/6.5.1

### Expected behavior

All versions on https://github.com/reactiveui/refit/releases are listed on nuget.org

### Screenshots 🖼️

![image](https://github.com/reactiveui/refit/assets/5808377/42b42769-9a51-4d2e-b1a8-85b366c4df62)

#### GitHub releases
![image](https://github.com/reactiveui/refit/assets/5808377/bca7ef14-2002-4be1-b3e0-09895e348dc6)

### Refit Version

6.4.1, 6.5.1

### Additional information ℹ️

related: https://github.com/reactiveui/refit/issues/1490, https://github.com/reactiveui/refit/issues/1497

**Comment by anaisbetts** [comment]
Correct, use 7.0.0-beta.1 instead!

**Comment by 304NotModified** [comment]
and why are those are still listed on https://github.com/reactiveui/refit/releases? And no explanation? This isn't really clear

**Comment by 304NotModified** [comment]
Please add also a message on those packages on nuget.org.
