### ISSUE TITLE
[Bug]: JsonPropertyName attribute is ignored (does not rename properties as expected)

### ISSUE THREAD

**Issue by 7amou3** [reactiveui/refit#1541]
### Describe the bug 🐞

Hello
`the [JsonPropertyName("mycustomePropName")]` doesn't seems to work, the serializer always output the property name, 
for example: in the DummyRequest class below, the url is: 

`http://localhost/myendpoint/json?All=True&Limit=10`
instead of
`http://localhost/myendpoint/json?all=True&otherText=10`

the [AliasAs("othertext")] works fine, but I don't want to use it
Any Idea?
Thanks

### Step to reproduce

create a new .Net 7 project and paste the following code in program.cs
```
using System.ComponentModel;
using System.Text.Json.Serialization;
using Refit;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

// Configure Refit
builder.Services
               .AddRefitClient<IGithubApi>()
               .ConfigureHttpClient(c =>
               {
                   c.BaseAddress = new Uri("http://localhost/");
               });

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

// Test client
var api = app.Services.GetService<IGithubApi>();
var res = api.GetContainers(new DummyRequest() { All = true, Limit = 10 });

app.Run();


public class DummyRequest
{
    [JsonPropertyName("all")]
    public bool All { get; set; } = true;

    
    [JsonPropertyName("otherText")]
    public int Limit { get; set; }
}

interface IGithubApi
{
    [Get("/myendpoint/json")]
    Task<Container> GetContainers(DummyRequest request);
}
```

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

Serialized properties that have the [JsonPropertyName("myPropName")] should be renamed accordingly

### Screenshots 🖼️

bellow the sent request 
![https://i.imgur.com/hJkiH3a.png](https://i.imgur.com/hJkiH3a.png)

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

11

### Refit Version

7.0.0

**Comment by 7amou3** [comment]
Hello, any help?

**Comment by sergeivalko** [comment]
@7amou3 it's not a bug, it's by design, i've prepared pr, but i think it's odd to use `JsonPropertyName` for query params, do you have any reasons why you do not want to use `AliasAs`

**Comment by 7amou3** [comment]
I don't want to use `AliasAs` Because I share a Nuget package that host the models, and I don't want the nuget to have a dependancy on refit

**Comment by damidhagor** [comment]
I'm running into the same issue where I want to remove Refit from my core package and reuse the models between my library which I want to support trimming and AOT and a child library which adds a Refit client separately.
Supporting the JsonPropertyNameAttribute (or an alternative BCL included attribute) as a replacement for the AliasAsAttribute for query parameters would be helpful to not have my shared models depend on Refit references.

**Comment by sergeivalko** [comment]
@7amou3 @damidhagor oh i get it, i forgot about that case, PR still on review so we have to wait 😄

**Comment by 7amou3** [comment]
@clairernovotny can you check and merge this fix please?

**Comment by tcortega** [comment]
The issue arises because query strings aren't JSON and thus aren't processed in the same way as JSON serialization. While JSON serialization has its own conventions and rules, query strings follow a different set of standards and encoding mechanisms. The two are distinct and require different handling approaches.

**Comment by Thepriestdude** [comment]
Any updates on this?

**Comment by tcortega** [comment]
> Any updates on this?

You have to use the `AliasAs` attribute. Sadly the refit them has not reviewed my PR.
https://github.com/reactiveui/refit?tab=readme-ov-file#api-attributes

**Comment by Thepriestdude** [comment]
Question: Would it be possible to also add in support for using the formatters for bodies since they also ignore the [JsonPropertyName] attribute? Having one interface for both would cut down on the clutter.

**Comment by tcortega** [comment]
@ChrisPulman this should be closed
