### ISSUE TITLE
Graceful Handling of Simple Response Bodies

### ISSUE THREAD

**Issue by chrstophr-wltrs** [reactiveui/refit#1547]
## Problem

Refit by default (as far as I know) attempts to deserialize response bodies into JSON, even if the return type in the method signature isn't a complex data type.

For example, if I have a method like this:

```csharp
[Post("/user/create")]
Task<IApiResponse<Guid>> CreateUser([Body] CreateUserRequest request);
```

and the response body consists only of 

```
4ab1f3d4-6cc7-48d7-b74f-01950e9bd9ff
```

when I do some code like 

```csharp
var response = await api.CreateUser(new());
```

then `response.Error` technically contains:

```
Refit Error: System.Text.Json.JsonException
	'-' is an invalid end of a number. Expected a delimiter. Path: $ | LineNumber: 0 | BytePositionInLine: 8.
```

even though the API has responded exactly as intended and as expected.

This same behavior happens if the response is a string, or a byte array, or anything that doesn't have an easy JSON equivalent.

## Solution

It'd be great if Refit could handle responses like the one outlined above, without the response containing an Error, so that the Error field could be used as an effective indicator of problems. This could either happen natively, or it could be annotated in some way, like adding `[NoJsonResponse]` to the example method described above (though you'd probably want to use a more sensible name).

## Alternatives

To my knowledge, the only way to avoid something like this would be to sidestep Refit entirely, by changing the method to read something like this:

```csharp
[Post("/user/create")]
Task<HttpResponseMessage> CreateUser([Body] CreateUserRequest request);

/* ... */

var response = await api.CreateUser(new());
var content = (Guid)response.Content;
```

But just disabling the error handling doesn't seem like the ideal way to go.

## Suggestions

I'll be honest, I'm a relatively new developer. 😅 I'm enormously appreciative of the utility and productivity that Refit has provided for me, but the scope of a project like Refit is very beyond my grasp. I just had a thought for a behavior that I think would be helpful.

**Comment by anaisbetts** [comment]
Refit is for APIs that return JSON, and returning a GUID as plaintext is unfortunately not valid JSON. I think the workaround you've got is Okay though I can see why it would be Annoying. If it's only that particular API, I would put an extension method on your Interface that calls the inner CreateUser but returns the string instead
