### ISSUE TITLE
[Bug]: JSON string response not being deserialized

### ISSUE THREAD

**Issue by munichmule** [reactiveui/refit#1582]
### Describe the bug 🐞

Hi Guys,

My API responds with a valid JSON. It could be any valid JSON really - an object, a number or a string. Strings are obviously wrapped with double-quotes, according to JSON spec. Ofc I make sure to add `Content-Type: application/json` to the response, so client knows what to expect. The HTTP-response message looks like this:
```
HTTP/1.1 200 OK
Cache-Control: public, must-revalidate, max-age=0
Content-Type: application/json; charset=utf-8
"some valid json-serialized string response here"
```

Now, when I tell my refit client that the method returns a string, it goes wild and returns a raw string instead of deserialized one, wrapped in double-quotes. I checked old bugs, and I've found [this one](https://github.com/reactiveui/refit/issues/356), but I honestly don't get it. Why is this considered a correct behavior? The server explicitly tells client that it sends JSON, so body content must be treated as JSON and deserialized. Why does refit return the raw string?

I know I can go for some stupid workaround, but why?

Thanks

### Step to reproduce

1. make an api return json-serialized string (eg response body contains string wrapped in double-quotes)
2. add `Content-Type: application/json;` to let client know it's json, not plain text
3. create a refit client that returns `Task<string>`
4. the response is not json-deserialized, so the string is wrapped in double-quotes

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

Refit client should respect content-type of response and deserialize accordingly. Strings should not be an exclusion.

**Comment by softeip** [comment]
In my scenario I get base64 string which I need to convert to byte array, so I specified Task<byte[]> as return type and it works well.

**Comment by anaisbetts** [comment]
`string` is a Magic Type in Refit, `Task<string>` effectively asks for just the result as plain text. Unfortunately, changing this would be an extremely Breaking Change so you might have to live with this one, sorry
