### ISSUE TITLE
[Bug]: Refit 6.5.1 is no longer available on nuget.org

### ISSUE THREAD

**Issue by colinblaise** [reactiveui/refit#1592]
Refit 6.5.1 is no longer available on nuget.org

**Comment by ChrisPulman** [comment]
![image](https://github.com/reactiveui/refit/assets/4910015/497e4d64-6a2e-4871-8c1d-929e6a5cb228)
This is still there if used in a project, however,  it's been unlisted due to some issues with the release, we would recommend upgrading to a later release for full compatibility.

**Comment by colinblaise** [comment]
Thanks for the info. Not sure how I missed that
