### ISSUE TITLE
Target .NET 8 in Refit

### ISSUE THREAD

**Issue by DanRogers99** [reactiveui/refit#1603]
**Is your feature request related to a problem? Please describe.**
The current version of Refit is targeting several older versions of .NET, including netstandard2.0, netstandard2.1, net462, net6.0, and net7.0. This setup may limit its compatibility with the latest features and optimizations in the framework, particularly .NET 8.

**Describe the solution you'd like**
I would like to request an update to Refit to target .NET 8. This update will enable users to fully leverage the enhancements and optimizations introduced in .NET 8.

**Comment by anaisbetts** [comment]
Fam it just came out like 2 days ago, jeez louise

**Comment by ChrisPulman** [comment]
We are working on updating all the ReactiveUI projects to .Net 8.0 but this takes time and much consideration, in some cases we need to wait for dependent packages to support net8.0 to be able to fully obtain the benefits.
I would thank you for your patience while we evolve into a net8.0 compatible set packages.
As always community PR's will always be considered when appropriate.

**Comment by DanRogers99** [comment]
Many thanks, Chris.

**Comment by clairernovotny** [comment]
Refit may target the older frameworks, but that's really just API surface area and does not affect what future runtimes it's supported on. Neither Refit, nor any other library, *has* to explicitly target `net8.0` for it to work on .NET 8.
