### ISSUE TITLE
Support [ValueConvertion] attribute

### ISSUE THREAD

**Issue by CodingOctocat** [reactiveui/refit#1681]
**Is your feature request related to a problem? Please describe.**

I'm using WPF and I'm developing a web query program with a number of textboxes (as request query conditions, `FooRequest`), the inputs to the textboxes are all of type `string`, but `FooRequest.SomeProperty` may be of other types, and I know that I can use WPF's ` IValueConverter`, but I also need to preserve the original input of the textbox.

**Describe the solution you'd like**
```csharp
class FooRequest
{
    // Use the attribute to invoke the value converter at the time of the web request.
    [ValueConvertion<StringToOtherTypeConverter>]
    public string SomeProerty { get; set; }

    // or
    [ValueConvertion(typeof(StringToOtherTypeConverter))]
    public string SomeProerty { get; set; }
}
```

**Describe alternatives you've considered**
```csharp
class FooRequest
{
    public OtherType SomeProerty => CallStringToOtherTypeMethod();

    public string SomeProertyForBinding { get; set; }
}
```

**Additional context**
There is a problem with the alternative, If my `FooRequest` uses Json, then I can use `[JsonIgnore]`, but I'm using `BodySerializationMethod.UrlEncoded`, and I didn't find a way to ignore some properties，see https://github.com/reactiveui/refit/discussions/1680

**Comment by anaisbetts** [comment]
This feature is already supported, check out https://www.reactiveui.net/docs/handbook/data-binding/value-converters.html

**Comment by CodingOctocat** [comment]
@anaisbetts The link is not what I want, and, that means I need to use it with ReactiveUI?

**Comment by anaisbetts** [comment]
@CodingOctocat No, I'm just a huge dummy and misread this entire thing, my apologies!
