### ISSUE TITLE
[Bug]: "doesn't look like a Refit interface" when inheriting empty interface from interface with refit function

### ISSUE THREAD

**Issue by pagdot** [reactiveui/refit#1687]
### Describe the bug 🐞

Inheriting an empty interface from a base interface with refit methods causing it to not be detected. Seems like this issue occurs during roselyn code generation because no classes are generated for the derived interface(s)

### Step to reproduce

```c#
using System;
using System.Threading;
using System.Threading.Tasks;
using Refit;
		
public interface IBaseService
{
    [Get("/resources")]
    Task<string> GetResource(string id);
}

public interface IDerivedServiceA : IBaseService
{
}

public class Program
{
	public static void Main()
	{
		var api = RestService.For<IDerivedServiceA>("https://example.com");
		Console.WriteLine(api.GetResource("abc"));
	}
}
```

(Tested at <https://dotnetfiddle.net/> with refit package installed)

### Expected behavior

No error about `doesn't look like a Refit interface`. Provided example should only stumble when trying to do the actual API call because the api doesn't exist

### IDE

Visual Studio 2022

### Refit Version

7.0.0

### Additional information ℹ️

Probably happens on other (older) versions too. Reproduced it with 7.0.0 in my minimal sample

**Comment by TimothyMakkison** [comment]
Are there many use cases for this? I wonder if this is intentional to prevent Refit from generating several identical classes.

**Comment by pagdot** [comment]
My use case was multiple apis where only the healthcheck was interesting combined with dependency injection, where I needed different interfaces for different apis

**Comment by TimothyMakkison** [comment]
Hey, not sure when it was fixed but this seems to work in Refit 8.0.0

**Comment by ChrisPulman** [comment]
@pagdot Are you able to confirm that this is now resolved.

**Comment by pagdot** [comment]
Minimal sample now compiles and runs as expected :) Thanks for checking it :)
