### ISSUE TITLE
[Bug]: Parameter named ex causes compile error

### ISSUE THREAD

**Issue by pro1dream** [reactiveui/refit#1724]
### Describe the bug 🐞

When using a parameter named `ex` in a method of an interface used by refit, there's a name clash in the generated code that prevents compilation.

### Step to reproduce

- Create an interface with a method like so:
``` csharp
interface IMyClient 
{
    [Get("/")]
    Task MyMethodAsync(string ex);
}
```
- Try to compile
- You will get the following error:
```
error CS0136: A local or parameter named 'ex' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
```

### Expected behavior

It should compile

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

10

### Refit Version

7.1.0

**Comment by ChrisPulman** [comment]
Thank you for raising this, we will see if there's a way to avoid clashing with the Source Generated code.
I assume that you are only experiencing this issue with an exact matched parameter in your Source named "ex"

**Comment by ChrisPulman** [comment]
I you happen to have a repo that demonstrates the issue, this would be very useful too, thank you.
