### ISSUE TITLE
[Bug]: Sealed types in 7.1.0 break existing apps using 7.0.0

### ISSUE THREAD

**Issue by mvromer** [reactiveui/refit#1733]
### Describe the bug 🐞

Prior to Refit 7.1.0, attribute types like `PropertyAttribute` were not marked as sealed. In one of my projects, I derived from that class in particular so that I didn't have to constantly set the key in the attribute's argument list. The code roughly looked like this:

```csharp
using Refit;

// Custom request options class. Exact details don't matter.
// It's just a way for requests to be modified at call site.
// A delegating handler attached to the generated client
// can then look for the presence of the request options
// and perform the updates on a per-request basis.
public record class RequestOptions(
    string SomeState,
    string SomeOtherState
);

// Custom attribute
[AttributeUsage(AttributeTargets.Parameter)]
public class RequestOptionsAttribute : PropertyAttribute
{
    public RequestOptionsAttribute()
        : base(key: "request-options") { }
}

// Client interface
public partial interface IMyServiceClient
{
    // Bunch of methods here, each which could specify
    // the RequestOptions parameter type.
    [Get("/resource-one")]
    Task<ResourceOne> GetResourceOne(
        [RequestOptions] RequestOptions? options = default,
        CancellationToken cancellationToken = default
    );
}
```

This compiled just fine in Refit 7.0.0. However, in Refit 7.1.0, the following compile error occurs:

```
Unhandled exception. System.TypeLoadException: Could not load type 'My.Namespace.RequestOptionsAttribute' from assembly 'My.Assembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because the parent type is sealed.
```

It appears the public types got marked as sealed as part of commit aa78fc08b. I did not expect a minor release to include a breaking change on the public types declared in Refit. It would be nice to have the previous declaration in place so that things like the above can still be supported.

### Step to reproduce

Create a new project that uses Refit 7.1.0, define some types like above, and try to build the project to get the compiler error.

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

At least in the 7.x line of releases, it would be ideal for at least some of the attribute types to not be marked as sealed so that code already using that major version won't break on minor version upgrades. It would be nice if in subsequent major versions the types continue to not be marked as sealed as to allow for patterns like the above which help to reduce code verbosity/boiler plate.

### Refit Version

7.1.0

**Comment by ChrisPulman** [comment]
Thank you for raising this issue, sealing the Attributes was done accidentally, I will add some API checks into the tests to ensure the right level of change is made and also that the API is not changed accidentally.
There should now be a 7.1.1 release that I hope will resolve the issue.
If all is satisfactory with the new release, please close this issue, again my apologies.

**Comment by mvromer** [comment]
I just pulled the latest package, and my builds are succeeding with 7.1.1. Thanks for the fast patch! Much appreciated!
