### ISSUE TITLE
Enhance default URL parameter formatting for custom formats

### ISSUE THREAD

**Issue by MikeAmputer** [reactiveui/refit#1775]
**Problem Statement:**

I have a `WebService` and two packages: `Models` (containing request and response models) and `Integration` (containing client abstractions and referencing `Refit`). `WebService` does not reference `Refit`. Both `WebService` and `Integration` package are reference `Models`.

`Integration` package contains the following client (simplified example):
```c#
public interface IMyClient
{
	[Get("/XXX/Y1")]
	Task<Models.MyResponse> GetValue([Query] Models.MyRequest request);

	[Get("/XXX/Y2")]
	Task<Models.MyResponse> GetSecondValue([Query(Format = "yyyy-MM-dd")] DateTime dt);
}
```
`Models.MyRequest` contains a `DateTime` property that also needs to be formatted, but I can not use the `QueryAttribute` because it would introduce a `Refit` reference in the `WebService`, which I would prefer to avoid.

As a workaround, I pass a custom `IUrlParameterFormatter`. However, I cannot inherit from `DefaultUrlParameterFormatter` while needing both `QueryAttribute` and type-based formatting. This forces me to implement my own version of the interface, duplicating code fragments from `DefaultUrlParameterFormatter`.

**Proposed Solution:**

To address this, I suggest enhancing `DefaultUrlParameterFormatter` to allow adding custom formats for specific types ([preview PR here](https://github.com/MikeAmputer/refit/pull/1)). This way, a custom formatter can look like this:
```c#
public class MyUrlParameterFormatter : DefaultUrlParameterFormatter
{
	public MyUrlParameterFormatter()
	{
		AddFormat<Models.MyRequest, DateTime>("yyyy-MM-ddTHH:mm:ss.fffZ");
	}
}
```

**Comment by MikeAmputer** [comment]
Any thoughts? I am ready to contribute of you are ok with the solution.

**Comment by ChrisPulman** [comment]
You Pre-PR looks good, I would like to see some test's around the updated functionality too both to show that it works and to give a demonstration of how each new section is intended to operate.
I am sorry for taking so long to reply, I am preparing for a project to be installed in Australia and Singapore in the next couple of weeks.

**Comment by MikeAmputer** [comment]
@ChrisPulman should we do the same for `DefaultFormUrlEncodedParameterFormatter` for consistency?
