### ISSUE TITLE
Improve incremental generator caching

### ISSUE THREAD

**Issue by TimothyMakkison** [reactiveui/refit#1791]
While working on a more source generated approach, I noticed that Refit does not correctly use incremental generator caching. While  a previous PR uses some of the more modern techniques such as `CreateSyntaxProvider`, the lines [829-846](https://github.com/reactiveui/refit/blob/7cfdeded6363adf5c7eb0d3902db528e92a17f17/InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs#L829) are functionally useless and will never successfully cache anything. This is due to how both `ImmutableArray` handles equality and the passing of the reference type `Compilation` (this will always change between re-runs).

- Methods should be represented by a structurally comparable object
- A benchmark could be created to confirm the benefits. Its possible that generating the code in a single pass is faster than caching.
- Tests should be added to verify that the caching works as intended
- Why is `PreserveAttribute.cs` added and then its [namespace queried](https://github.com/reactiveui/refit/blob/7cfdeded6363adf5c7eb0d3902db528e92a17f17/InterfaceStubGenerator.Shared/InterfaceStubGenerator.cs#L231)? Would the compiler change this? I assume it would always be `global::RefitInternalGenerated.PreserveAttribute`
- `CancellationToken` [should be respected](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#handling-cancellation) to reduce IDE lag

I'll start work on a PR for this but I don't promise anything.

Related https://github.com/reactiveui/refit/issues/1389

**Comment by ChrisPulman** [comment]
Thanks Tim, much appreciated, I was going to head down the same rabbit hole and try to make things better, I see that AoT is important to many people too :)

**Comment by TimothyMakkison** [comment]
Hey, added some preliminary benchmarks in #1798.

I was planning on adding some tests to verify steps in the incremental generator like I've done for [Mediator](https://github.com/martinothamar/Mediator/blob/main/test/Mediator.SourceGenerator.Tests/Incremental/IncrementalGeneratorTest.cs). I used `WithTrackingName` to check specific steps. Unfortunately this is only available in Roslyn 4.1+. I believe I could either:
- Update `InterfaceStubGenerator.Roslyn40` to `InterfaceStubGenerator.Roslyn41` (probably a breaking change)
- Add `InterfaceStubGenerator.Roslyn41` and use it for the tests.
