### ISSUE TITLE
[Bug]: Form post for Dictionary<string, string> formData, does not work

### ISSUE THREAD

**Issue by infofromca** [reactiveui/refit#1796]
### Describe the bug 🐞

I used:
[Post("/api/checkout/confirm/{providerName}/{paymentIntentId}/{shoppingCartId}?middleUrl={middleUrl}")]
Task<PaymentOperationStatusViewModelVM> ConfirmPaymentAsync(
string providerName,
string paymentIntentId,
string shoppingCartId,
string middleUrl,
Dictionary<string, string> formData,
CancellationToken cancellationToken = default);

### Step to reproduce

4. See error result:
POST /api/checkout/confirm/Stripe/pi_3PtFFARpyWVeDn6H1ILOQ5FA_secret_WWaffORTB0NIqzQjZpCZx6bXk/4fwn1mf881vbh2n35zgcn2hqxz?middleUrl=guangmauiauth HTTP/1.1
Host: localhost:62354
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

{"BillingAddress.Address.Name":"andy","BillingAddress.Address.Department":"","BillingAddress.Address.Company":"","BillingAddress.Address.StreetAddress1":"42","BillingAddress.Address.StreetAddress2":"","BillingAddress.Address.City":"t","BillingAddress.Address.Province":"r","BillingAddress.Address.PostalCode":"12345","BillingAddress.Address.Region":"c","BillingAddress.UserAddressToSave":"BillingAddress","ShippingAddress.Address.Name":"qq","ShippingAddress.Address.Department":"","ShippingAddress.Address.Company":"3","ShippingAddress.Address.StreetAddress1":"22","ShippingAddress.Address.StreetAddress2":"","ShippingAddress.Address.City":"rr","ShippingAddress.Address.Province":"gg","ShippingAddress.Address.PostalCode":"23456","ShippingAddress.Address.Region":"vv","ShippingAddress.UserAddressToSave":"ShippingAddress"}

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

when I used .net way , it worked:
using GuangCore.Blazor.BaseLibrary;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace GuangBlazingOrchard.Refit.Services;
public class ApiService
{
    private readonly HttpClient _httpClient;
    public ApiService()
    {
        _httpClient = new HttpClient();
        _httpClient.BaseAddress = new System.Uri(Constants.ServerBaseUrl);
    }
    //public ApiService(HttpClient httpClient)
    //{
    //    _httpClient = httpClient;
    //}

    public async Task<string> PostFormUrlEncodedAsync(string url, Dictionary<string, string> formData)
    {
        var content = new FormUrlEncodedContent(formData);
        content.Headers.ContentType = new MediaTypeHeaderValue("application/x-www-form-urlencoded");

        var response = await _httpClient.PostAsync(url, content);
        response.EnsureSuccessStatusCode();

        return await response.Content.ReadAsStringAsync();
    }
}
which produce the correct data as the following:
POST /api/checkout/confirm/Stripe/pi_3PtGvdRpyWVeDn6H0fOrwH7y_secret_3cpfrEu6kq4VnCcj5RTsvXXQs/4b1s7d9e0bth8x3q5mcack65wq?middleUrl=guangmauiauth HTTP/1.1
Host: localhost:62354
Content-Type: application/x-www-form-urlencoded
Content-Length: 955

Total=0&OrderPart.BillingAddress.Address.Name=aaa&OrderPart.BillingAddress.Address.Department=&OrderPart.BillingAddress.Address.Company=&OrderPart.BillingAddress.Address.StreetAddress1=aa&OrderPart.BillingAddress.Address.StreetAddress2=&OrderPart.BillingAddress.Address.City=tt&OrderPart.BillingAddress.Address.Province=oo&OrderPart.BillingAddress.Address.PostalCode=23456&OrderPart.BillingAddress.Address.Region=vvv&OrderPart.BillingAddress.UserAddressToSave=BillingAddress&OrderPart.ShippingAddress.Address.Name=ggg&OrderPart.ShippingAddress.Address.Department=&OrderPart.ShippingAddress.Address.Company=gg&OrderPart.ShippingAddress.Address.StreetAddress1=566&OrderPart.ShippingAddress.Address.StreetAddress2=&OrderPart.ShippingAddress.Address.City=dd&OrderPart.ShippingAddress.Address.Province=vc&OrderPart.ShippingAddress.Address.PostalCode=33333&OrderPart.ShippingAddress.Address.Region=ccc&OrderPart.ShippingAddress.UserAddressToSave=ShippingAddressHTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
X-Powered-By: OrchardCore
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer
X-Powered-By: ASP.NET
Date: Thu, 29 Aug 2024 22:36:29 GMT

**Comment by TimothyMakkison** [comment]
Did you use the [`Body` attribute](https://github.com/reactiveui/refit?tab=readme-ov-file#form-posts)?

```C#
[Post("/api/checkout/confirm/{providerName}/{paymentIntentId}/{shoppingCartId}?middleUrl={middleUrl}")]
Task ConfirmPaymentAsync(
string providerName,
string paymentIntentId,
string shoppingCartId,
string middleUrl,
[Body(BodySerializationMethod.UrlEncoded)]
Dictionary<string, string> formData,
CancellationToken cancellationToken = default);
```

**Comment by infofromca** [comment]
Yes, I missed [Body(BodySerializationMethod.UrlEncoded)], thanks. close it.
