### ISSUE TITLE
[Bug]: Refit interfaces do not implement base interface non refit methods

### ISSUE THREAD

**Issue by TimothyMakkison** [reactiveui/refit#1801]
### Describe the bug 🐞

Generated refit interfaces are invalid if the base interface has a non refit method.

### Step to reproduce

```C#
// 'Generated.IGeneratedInterface' does not implement interface member 'IBaseInterface.NonRefitMethod()'
var gitHubApi = RestService.For<IGeneratedInterface>("https://api.github.com");

public interface IGeneratedInterface : IBaseInterface
{
    [Get("/users")]
    Task<string> Get();
}

public interface IBaseInterface
{
    void NonRefitMethod();
}
```

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

Refit should generate stub implementations which throw an error when called to satisfy the interface. Similar to how non refit methods are handled in non derived refit interfaces.

### IDE

Rider Windows

**Comment by TimothyMakkison** [comment]
This is a pretty easy fix as all the required code is present, just an intentional???/bug prevents it from functioning, [see here.](https://github.com/reactiveui/refit/commit/347297365439f70257c2e700f8d5b204c3c92ba7#diff-5e1ed3fa001a01712615b16d24e37cc36f11550ab918d6f90921c7e3632007adR358) `derivedMethods.Except(derivedMethods` will always return an empty set.

The problem arises when we consider interface inheritance and manual casting. For instance `Refit.Tests\RestService.InheritedInterfaceWithoutRefitInBaseMethodsTest` relies upon Refit only generating the method for a "more derived" refit method and not generating an explicit implementation for the base.

```C#
interface IBase {
   Task Do(); // Not a refit method, refit will not generate a method for this.
}

interface IDerived {
    [get("/")]
    Task Do(); // This refit method will hide IBase.Do()
}

IDerived derived = RestService.For<IDerived>();
derived.Do() // calls the IDerived implementation for Do()
var base = (IBase)derived;
base.Do(); // still calls the IDerived implementation for Do()
// with my fix this would call `IBase.Do()` and throw an exception. A breaking change
```

Because of this, my fix would be a breaking change unless I take measures to circumvent this. I can either keep this behaviour or fix it. I'm not sure what would be expected by the user and what is considered "correct".

**Comment by ChrisPulman** [comment]
@TimothyMakkison 
From a technical perspective, I would expect IBase.Do() to be executed when cast to IBase, if it's currently looking for the first Refit layer to execute then this is breaking inheritance and in my opinion should be corrected. At this point in time the next Release will be a breaking Release anyway so should be expected to have changes to the operation.
