### ISSUE TITLE
Use dependabot for version upgrades.

### ISSUE THREAD

**Issue by sukreshmanda** [reactiveui/refit#1807]
## Use dependabot

We are currently seems to be upgrading package versions manually. This requires contributors to raise PRs and get them reviewed. This can cause delays in upgrades and patches.

**Describe the solution you'd like**
Enable dependabot for this repository and use it to create version upgrades on time and effectively.

**Comment by sukreshmanda** [comment]
I was mistaken to think we are not using any tools for dependencies upgrading. Sorry for creating this. I am closing this now.

**Comment by ChrisPulman** [comment]
No problem, we moved away from dependabot as it was missing some packages and not dealing with conflicts well.
