### ISSUE TITLE
Support dynamic multiple headers (vs single header) using single parameter

### ISSUE THREAD

**Issue by Korayem** [reactiveui/refit#197]
We have more than 5 headers that we set with each call and it's cumbersome to do it with current implementation because it means adding 5 arguments to EACH API call
### What I suggest is the following:

```
[Get("/users/{user}")]
Task<User> GetUser(string user, [Headers] string[] headers);

// Will add list of headers to the request:
var user = await GetUser("octocat", new []{"header1: value1","header2: value2"}); 
```

**Comment by bennor** [comment]
This could (should?) also be achieved by allowing the headers value to be a dictionary.

**Comment by CreepyGnome** [comment]
I know this is old, and would like to add two cents to this. I have a set of headers that have to be provided to all methods as params, and I was thining it would be really nice if I had a POCO that I can use that used the existing HeaderAttribute on properties of this POCO and you just pass the POCO as a single param. Then the Headers would be pulled from this just like as if they where parameters with the HeaderAttribute.

Also it could be useful if I could pass a single POCO that had multiple properties that could be AliasAsAttribute or HeaderAttribute. This would allow for a single "request" POCO that can be passed in and it can set headers, path replacement values, and query string values.

Just a thought, as this came up today and would have made the method definition a lot cleaner if I had a single POCO or even two, one for headers and one for everything else.

**Comment by Massimo37** [comment]
I'm running into the same problem, had to add all the dynamic headers to EACH call, but would be nice if this would be achieved through a collection or through a model (POCO type).
