### ISSUE TITLE
Set the accept header by default or from settings

### ISSUE THREAD

**Issue by mtman** [reactiveui/refit#204]
Many providers support json but serve xml by default. It's strange to decorate every interface with `[Headers("Accept: application/json")]` to achieve default behavior.

**Comment by Cheesebaron** [comment]
Default behavior of what? I don't think refit should add any headers on it's own.

**Comment by mtman** [comment]
@Cheesebaron Refit doesn't support xml. You should be able to opt-out from it in those rare cases where a provider requires a custom accept header for json, otherwise I cannot see space for any ambiguity.

**Comment by bennor** [comment]
Most APIs these days are JSON only or JSON by default. If you have to use an accept header, it's not that hard to decorate the interface with it.

What you're asking for is a potentially breaking change for some people to save you one line of code.

**Comment by mtman** [comment]
This isn't that true for enterprise, especially Java world, they typically do support json but are xml-first. Also it isn't one line of code if you have several aspect-specific interfaces for a larger api. The main problem however is that it's counter-intuitive. It's standard that a library makes it clear what underlying format it recognizes (e.g. RestSharp). Also it would be extremely rare if it would break anything.

**Comment by MKuckert** [comment]
Can't you just set some [DefaultRequestHeaders on a custom HttpClient instance](https://msdn.microsoft.com/de-de/library/system.net.http.httpclient.defaultrequestheaders(v=vs.118).aspx)? I don't think that Refit has to support such a "feature"...

**Comment by ahmedalejo** [comment]
Like @MKuckert stated any default header should go into the:

```
var configuredHttpClient = new HttpClient();
configuredHttpClient.DefaultRequestHeaders.Add("Accept", "application/json")
///or
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue( "application/json"))
//then
var acceptanceService = RestService.For<IAcceptanceService>(configuredHttpClient);

await acceptanceService.AcceptMe();
```

**Comment by aliabdoli** [comment]
It seems this ticket has been around for a while. So, wondering if anyone is working on it? otherwise, can I work on it and contribute?

**Comment by bennor** [comment]
@aliabdoli If you really want to do it, it might be okay under the following condition:

**Before automatically adding an accept header to the request, you need to be sure that we're going to be deserializing the response as JSON.**

That means it can't happen in any of the following situations:

- there is a custom `ContentSerializer` set in `RefitSettings`
- the method return type is `Task`, `Task<string>`, `Task<Stream>`, `Task<HttpContent>` or any other variation that won't result in JSON deserialization.

This info may be available already as a single property on the `RestMethodInfo`. I can't remember. If not, it might warrant adding one.

Before you go ahead, let @onovotny weigh in and confirm he's okay with it too.

**Comment by aliabdoli** [comment]
@bennor I m on it. I ll send the pr. thanks for help

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
