### ISSUE TITLE
Multipart progress

### ISSUE THREAD

**Issue by Mittchel** [reactiveui/refit#206]
Hi there,

For a project we're in need of uploading photos to a Web API. Since this api requires multipart we're planning on using refit for this :-)

Is there any way we can track progress for the file upload?
Is it also possible to send along a JSON object with the File? I've seen some feature requests about this, but not sure if it is implemented yet.

Thanks in advance

**Comment by Speedrockracer** [comment]
I have the exact same question.

In retrofit I would do something like this http://stackoverflow.com/questions/33338181/is-it-possible-to-show-progress-bar-when-upload-image-via-retrofit-2
Can't seem to find anything similar for Refit.

**Comment by cfl777** [comment]
Any progress on this?

**Comment by Cheesebaron** [comment]
Pull requests are welcome

**Comment by nikeee** [comment]
You can check whether RestEase supports that. It's basically the same as refit, but with some differences in the details.
https://github.com/canton7/RestEase

**Comment by cfl777** [comment]
@nikeee RestEase doesn't work with our project, we use PCLs, we had an issue. Thanks though.

**Comment by clairernovotny** [comment]
Closing due to age.
