### ISSUE TITLE
Oauth Authorization Extension

### ISSUE THREAD

**Issue by ghost** [reactiveui/refit#229]
Firstly thanks for making Refit, I have been using on a couple of projects and I think its fantastic.

I notice that you have a sample for [Authorization (Dynamic Headers redux)](https://github.com/paulcbetts/refit#authorization-dynamic-headers-redux) in the readme. Just wondering if there would be any appetite for an extension for Oauth that would bake in the authorization access token and refresh token calls when making the API calls. Or perhaps its already there an I’m missing something?

**Comment by opcodewriter** [comment]
I have same question.
Does Refit have support for oAuth2 ?

**Comment by Korayem** [comment]
I got my app to successfully auto refresh expired tokens by closely studying this part in the documentation: https://github.com/paulcbetts/refit#authorization-dynamic-headers-redux

**Comment by dixosj** [comment]
Hi Korayem,

Thanks for the reply. Essentially I have done that. I have implemented an AuthenticatedHttpClientHandler which implements from HttpClientHandler.

It will get a refresh token if needed before making the API call. I was just wondering if there would be an appetite to include this in Refit (or as a separate module that would have it baked in).

**Comment by Korayem** [comment]
Ditto! considering how frequent this use case happens, it might be a good idea to bake it in or at least update the sample with easier to understand example because honestly it took me around an hour to get my head around it and implement it properly.

**Comment by ravensorb** [comment]
+1

**Comment by onovotny** [comment]
The challenge is that there's no single OAuth implementation. That's why there's a `GetToken` method instead that allows you to use your own flavor. Facebook, Google, Microsoft and others all do it differently. Likewise, some libraries, like Microsoft's ADAL, handle token caching, while others don't. 

Open to suggestions though.

**Comment by onovotny** [comment]
Reopening to track doc updates to explain better.

**Comment by bennor** [comment]
@onovotny, has this been clarified in the docs yet?

**Comment by onovotny** [comment]
We talk about auth here https://github.com/reactiveui/refit#authorization-dynamic-headers-redux, but I'm sure it could be better

**Comment by bennor** [comment]
I've felt for a long time that the docs could do with a serious overhaul. I should have some time soon to look at actually doing it. 🤣🎉

Do you want to keep this open as a reminder or should I start up a separate issue for docs overhaul and add this as a bullet point?

**Comment by onovotny** [comment]
A new issue for the docs is probably better

**Comment by ousspero** [comment]
> Ditto! considering how frequent this use case happens, it might be a good idea to bake it in or at least update the sample with easier to understand example because honestly it took me around an hour to get my head around it and implement it properly.

an hour you are good, it took a day for me

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
