### ISSUE TITLE
HttpResponseMessage & multiple requests with empty response body 

### ISSUE THREAD

**Issue by mohammedshareef-edm** [reactiveui/refit#244]
Hi Guys,

  I have a request which returns an empty body & I am using HttpResponseMessage to get a StatusCode. Ideally I would like to use a custom type but the response is null for it even when it inherits  from HttpResponseMessage. 

Also when I try multiple calls with the HttpResponseMessage  return type only the first two succeed and I get a TaskCanceled Exception for anything thereafter. Mutiple calls work with a custom type but as the response is null I am unable to know the status code.

What am I doing wrong here. Is it possible to use a custom response for an empty body content. 

Thanks

**Comment by ahmedalejo** [comment]
Some code snippets would be great.

**Comment by mohammedshareef-edm** [comment]
`
public class UserApi
 {
       // Some more requests

       [Put("/users/{Id}/admin")]
       Task<HttpResponseMessage> UpdateUser([AliasAs("Id")] int userId, [Body] UserInfo info);
 }
`

![dhc - empty body response](https://cloud.githubusercontent.com/assets/20183645/16412250/2ef929ca-3d23-11e6-99f1-3672db9b8f7b.jpg)

**Comment by syboulayte** [comment]
Hi
I have exactly the same problem.
I try the following api
`        [Post("/api/clients/")]
        IObservable<HttpResponseMessage> Test1([Body] JsonStruct foo);
        [Post("/api/clients/")]
        IObservable<string> Test2([Body] JsonStruct foo);
`
If I do a multiple call to Test1, only the 2 or 3 first works.
` var l_names = new[] { "_1", "_2", "_3", "_4", "_5", "_6" };         
var l_list1 = l_names.Select(n => api.Test1(new JsonStruct {Name = n});
l_list1.Serialize().Wait();
`
If I do the same with Test2, everything works well
`           var l_names = new[] { "_1", "_2", "_3", "_4", "_5", "_6" };
            var l_list1 = l_names.Select(n => api.Test2(new JsonStruct {Name = n});
            l_list1.Serialize().Wait();
`
So I try to return a custom class as result but doesn't works.
How can I do ?

**Comment by refactorsaurusrex** [comment]
For anyone else experiencing the issue where multiple invocations of a Refit API method with a `Task<HttpResponseMessage>` return type, here is a workaround:

```
static void Main(string[] args)
{
    var things = RestService.For<IGetThings>("https://jsonplaceholder.typicode.com");

    var tasks = new List<Task<ApiResponse<string>>>();
    foreach (var counter in Enumerable.Range(0, 10))
    {
        //var task = things.GetHttpResponse();  // TaskCanceledException after 2 - 3 calls
        //var task = things.GetString(); // Works as expected
        var task = things.GetApiResponse();  // Works as expected
        tasks.Add(task);
    }

    Task.WhenAll(tasks).Wait();

    foreach (var t in tasks)
        Console.WriteLine($"Status Code: {t.Result.StatusCode} | Response: {t.Result.Content}");

    Console.ReadKey();
}

interface IGetThings
{
    [Get("/todos/1")]
    Task<ApiResponse<string>> GetApiResponse();

    [Get("/todos/1")]
    Task<HttpResponseMessage> GetHttpResponse();

    [Get("/todos/1")]
    Task<string> GetString();
}
```

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
