### ISSUE TITLE
Feature request: Add support for something like QueryMap in RestEase

### ISSUE THREAD

**Issue by ravensorb** [reactiveui/refit#252]
It would be great to see support for something like the [Querymap in RestEase](https://github.com/canton7/RestEase#query-parameters-map).  I am looking for some why to leverage an entire object as possible query string parameters (or at least all non null values).  This would make it easier to support search for more complex APIs

```
public class ProductItem {
    string name { get; set; }
    string brand { get; set; }
    string sku { get; set; }
    decimal? defaultCost { get; set; }
    bool? archived { get; set; }
}

[Get("/Account/{AccountID}/Item")]
Task<ProductItem> GetItemAsync([QueryMap(QuerySerializationMethod.QueryString)] ProductItem item);
```

This would generate different query strings based on which propertied are non-null/non-empty values.

**Comment by RaminMT** [comment]
Hi,
Any solutions or answers on this?

**Comment by ravensorb** [comment]
Yes, there is a pretty elegant solution that I found with @paulcbetts help.  Basically you can create an IRequestQueryParmSerializer and implement the SerializeQueryParam method,  In that method, I take "value" and using a little bit of reflection I convert it to a Dictionary<string, string> object.  So far this is working extremely well.

**Comment by RaminMT** [comment]
Thank you, So could you please help me on [this](https://github.com/paulcbetts/refit/issues/315)?

**Comment by RaminMT** [comment]
Hi again,
I didn't find any IRequestQueryParmSerializer (or sth near to this), So I guess I should create that, but after creating the interface & implementing the method, Where & How I should use that?!

Thanks

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
