### ISSUE TITLE
Response custom deserialization

### ISSUE THREAD

**Issue by opcodewriter** [reactiveui/refit#269]
Any example of how to implement my own deserialization?

**Comment by cfl777** [comment]
@opcodewriter Any progress with this?

**Comment by opcodewriter** [comment]
@cfl777 Umm, not really. I wish I got an answer too. 
The only solution I found is to have the method return string. I call the method and parse the string response. No idea if it's the best way.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
