### ISSUE TITLE
Cache-Control / max-age response header

### ISSUE THREAD

**Issue by haamaanaa** [reactiveui/refit#286]
Does refit floow response cache-control headers on requests? Or should this be done separate from Refit request / response calls?

I'm using ASP.NET cache control attribute [Strathweb.CacheOutput NuGet] to define REST API response headers:

        [CacheOutput(ClientTimeSpan = 600, ServerTimeSpan = 60, MustRevalidate = true, ExcludeQueryStringFromCacheKey = true)]

But every call via Refit goes to server, without using client side caching.

Attribute works when trying URL paths with DHC Chrome plugin.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
