### ISSUE TITLE
Multiple query parameters of same name

### ISSUE THREAD

**Issue by danielkarlsson** [reactiveui/refit#290]
How do I set multiple query paramters with the same name? 
Like ?id=1&id=2.

**Comment by JonDouglas** [comment]
You should be able to use a comma.

i.e.

id=1,2

Please note that some APIs may not adhere to this.

**Comment by JonDouglas** [comment]
Use a `;` instead. It should fix that issue!

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
