### ISSUE TITLE
Arrays as url parameters. ASP.NET Web API friendly implementation

### ISSUE THREAD

**Issue by s-tarasov** [reactiveui/refit#294]
I tried to use custom `IUrlParameterFormatter` for array arguments https://github.com/paulcbetts/refit/issues/93#issuecomment-137393067, but ASP.NET Web API doesn't understand comma separated arrays out of the box.. 

Tricky solution: return query string (`?value=1&value=2&value=3`) in `CustomUrlParameterFormatter`  

But this solution required small fix in `RequestBuilder`:
https://github.com/s-tarasov/refit/commit/a6f7758490439a3c3bf6d2738f8b22e4ac26b274

Can i create PR?

**Comment by onovotny** [comment]
There is now support for arrays as url parameters in #454

**Comment by s-tarasov** [comment]
:+1:
