### ISSUE TITLE
Refit namespace issue in VS for Mac (works fine in XS)

### ISSUE THREAD

**Issue by leonpotgieter** [reactiveui/refit#299]
Hi, hope someone more clever than me can assist with this...

- Xamarin Forms PCL (Profile 111) Project (currently only targetting iOS)
- Using Akavache as well so settled on Profile 111
- Installed Refit fine (had to install Netstandard.Library first)
- Configured Basic Interface and some Test code

Works perfectly using Xamarin Studio/Mac... compiles, runs, Refit works.

However on Visual Studio for Mac (Preview 5) I get "The type or namespace Refit could not be found, are you missing an assembly reference" with the the "using Refit" statement highlighted... (which is odd seeing as through VS added the statement for me using the Quick Fix?)

If I close Visual Studio for Mac and open/compile the project in Xamarin Studio then all works fine...

Any idea as to what could happening here and how I could get it working in VS/Mac?

Thanks

**Comment by onovotny** [comment]
Closing as stale. Please try with the latest VSfM and Refit and open a new issue if it still exists.
