### ISSUE TITLE
Please Add Exception Documentation

### ISSUE THREAD

**Issue by MrThreepwood** [reactiveui/refit#308]
Looking through various documentation and even looking for tutorials, I've been unable to find a way to properly make a network call with this library. In normal use cases I would obviously need to catch some exceptions when attempting to call any of Refit's methods. Looking through the issues I've managed to find that I should catch ApiException (an exception added by this library) and WebException (a standard C# exception I likely could have guessed on my own).

It would be nice to have an example of a production ready call (at least one) somewhere in the documentation.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
