### ISSUE TITLE
Dynamic querystring!

### ISSUE THREAD

**Issue by RaminMT** [reactiveui/refit#315]
Hi,
I've got an endpoint which has about 15 query string parameters for filtering purposes. As they are optional parameters, there will be a lot of parameter combination so overloads are useless and Also I should avoid setting null-value parameters as it does affect on the result.
I searched a little seems implementing `IUrlParameterFormatter` is the answer, but I don't have any idea of how to.
Would somebody guide me on this?!

Thanks
Ramin

**Comment by Cheesebaron** [comment]
Isn't this: https://github.com/paulcbetts/refit#form-posts what you want?

**Comment by RaminMT** [comment]
No, mine is a GET request & the parameters are query string parameters

**Comment by Cheesebaron** [comment]
It shouldn't matter that yours is a GET. If you look at the example it is converted into query string parameters.

**Comment by Cheesebaron** [comment]
So:

```
public interface IDerpApi
{
    [Get("/durr")]
    Task Herp([Body(BodySerializationMethod.UrlEncoded)] Dictionary<string, object> stuff);
}

var stuff = new Dictionary<string, object> {
    {"herpy", 1}, 
    {"derpy", "bar"}, 
    {"doo", new Guid("d1e9ea6b-2e8b-4699-93e0-0bcbd26c206c")}
};
```

This will give:

`/durr?herpy=1&derpy=bar&doo=d1e9ea6b-2e8b-4699-93e0-0bcbd26c206c`

**Comment by RaminMT** [comment]
Thank you, I tried that but no success.

**Comment by Cheesebaron** [comment]
What does "no success" mean?

**Comment by RaminMT** [comment]
No success means I didn't get the desired result!!
I expected that to narrow the results but it didn't go that way. I also sniffed the request using fiddler & saw that It has body just like it's a post request not the way you said according to documentations.

**Comment by RaminMT** [comment]
@bennor Well, thank you.
Extending to work with dictionary as #252? Would you please teach me by code or explain it more?

Thanks

**Comment by RaminMT** [comment]
Friends, No comment on this? I really don't have any idea.
@bennor @Cheesebaron @ravensorb

**Comment by RaminMT** [comment]
Friends, No comment on this? I really don't have any idea.
@bennor @Cheesebaron @ravensorb

**Comment by bennor** [comment]
Sorry. I'll try to have a look this weekend.

**Comment by RaminMT** [comment]
Thanks man that would be appreciated, Hope you get back with good news.

**Comment by bennor** [comment]
Hey, I've had a quick look into it and I can't see how it's possible without changes. I'll see if I can get a PR together to add support over the next week.

I had a look at #252, but I have no idea what it's about. There's no interface in Refit called `IRequestQueryParamSerializer`, but a Google search for it brought up RestEase.

**Comment by RaminMT** [comment]
Thank you dear,
I also checked what he said but I didn't find the interface, Also emailed to Paul for help on that but no response.
For now I'm not referencing Refit using Nuget, So if you share your changes with me, I can test it well & use it until your PR will available soon.

**Comment by ravensorb** [comment]
That was my bad.  I forgot i switched over to reastease as i needed this same functionality.

**Comment by RaminMT** [comment]
Hi,
@bennor What's the new bro?! Is there any chance?

**Comment by bennor** [comment]
Completely dropped.off the radar, sorry. Will take a look at it this weekend.

**Comment by RaminMT** [comment]
Tnx, I hope you come up with great news 😄 ;)

**Comment by RaminMT** [comment]
Hey @bennor 
Did you find any solution on this?!

**Comment by bennor** [comment]
Not yet. Too much going on in the rest of my life. I should be able commit to having it completed by mid September. Sorry to string you along.

**Comment by RaminMT** [comment]
Tnx buddy
Is there any temporary solution for me? Now I made an static method to make the request but I need it to be fixed soon so I can release my app.

**Comment by bennor** [comment]
If you change control over the API you could change it to accept a form post and use the form body serialization method. Otherwise you'll need to provide static versions of the parameters. Can you make some optional?

**Comment by RaminMT** [comment]
I don't have control over the api unfortunately. Also static parameters can't help me, because I have some sort of array in parameters like below:
```123=456&123From=4&567To=8```
These three parameters are completely dynamic. They can be repetitive & has permutations

**Comment by napalm684** [comment]
Any update when we might see this?  I have a similar problem where I cannot control the api.  Things get further complicated when its a multipart request with additional form data.  I found the api will accept the items as query string parameters but one of the two I need to pass is a dynamic value.  A workaround till the Query attribute is available would be helpful if anyone has figured that out?

**Comment by housecode** [comment]
Hi, any update of this?
