### ISSUE TITLE
Cookie header, how to remove it from all requests which are sent?

### ISSUE THREAD

**Issue by opcodewriter** [reactiveui/refit#322]
I am seeing the cookie header set but I'm not setting it.
Where does it come from?

"Cookie: _session_id=eVo4Vld5QVJVYXoyL2dXaWhKblc0cVdMaEJsdm5D"

**Comment by opcodewriter** [comment]
Oh, it make sense. 
How can I tell Refit NOT to include this header in ANY of the requests?

**Comment by opcodewriter** [comment]
I also tried 
`httpClient.DefaultRequestHeaders.Add("Cookie", "");` with no luck

**Comment by mostafa-boden** [comment]
I have similar issue.

**Comment by bennor** [comment]
This is standard behavior for .NET's `HttpClient`. You can turn cookies off on the `HttpClientHandler` instance:

```csharp
var handler = new HttpClientHandler
{
    UseCookies = false // This is what disables cookies
};
var httpClient = new HttpClient(handler)
{
    BaseAddress = new Uri("https://api.yoursite.com/") // Use your actual API base address here
};
var api = RestService.For<IYourApi>(httpClient);
```
