### ISSUE TITLE
 "doesn't look like a Refit interface" with visual studio on Mac Os

### ISSUE THREAD

**Issue by dinozero** [reactiveui/refit#325]
I built project success with Visual Studio on Windows. But with visual studio on Mac Os, It is failed.
I saw "doesn't look like a Refit interface" at  `var gitHubApi = RestService.For<IAPIService>(Constant.URL);`
My interface:

 ```
public interface IAPIService
    {
        /*[Get("/items/getItemsByRandom")]
        Task<JsonMesseage.Store> GetListStore();*/

        [Get("/location.php")]
        Task<JsonMesseage.Location> GetLocation();

        [Get("/packages/getPackage?id={id}")]
        Task<JsonMesseage.GetPackage> GetPackage([AliasAs("id")] int id);
}
```

Thank you for reading.

**Comment by AlexandruGH** [comment]
Greetings sir, I'm having the same issue. After I updated VS 2017 even if I use the "using Refit"import.

**Comment by onovotny** [comment]
Do you have a repro project? What environment (VS / VSfM) & version?

**Comment by bennor** [comment]
Closing due to no response in over a year. Reopen if it's still an issue.
