### ISSUE TITLE
Gzip uploads

### ISSUE THREAD

**Issue by Cheesebaron** [reactiveui/refit#327]
Would be really great to gzip uploads if the header is set. Should be fairly straight forward to just use `GZipStream` to gzip it before sending it.

**Comment by onovotny** [comment]
PR? :)

**Comment by Cheesebaron** [comment]
Looking at it :)

**Comment by Fjsmoreira** [comment]
Hey! Any news on this one?
Thanks

**Comment by Cheesebaron** [comment]
Got distracted by other work. Might look at it again soon. Otherwise feel free to give it a go @Fjsmoreira

**Comment by wcoder** [comment]
`JsonContent` for writing gzipped JSON in web requests:
https://gist.github.com/jonathanpeppers/c957f3f67d1a0f2994bd5501923c348d

I wrote this test without check, but maybe this code to work correctly:
```cs
public async Task MultipartUploadShouldWorkWithGZipStream()
{
	using (var stream = GetTestFileStream("Test Files/Test.pdf"))
	using (var gzip = new GZipStream(stream, CompressionMode.Compress, true))
	{		
		var fixture = RestService.For<IRunscopeApi>(runscopeUri);
		var result = await fixture.UploadStream(gzip);
		
		Assert.True(result.IsSuccessStatusCode);
	}
}
```
```cs
public interface IRunscopeApi
{
        [Multipart]
        [Post("/")]
        Task<HttpResponseMessage> UploadStream(Stream stream);
}
```

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
