### ISSUE TITLE
No stub generated if "using Refit" not found in file

### ISSUE THREAD

**Issue by MaxDeg** [reactiveui/refit#337]
I found a kind of inconsistency in the stubs generation. We cannot used fully qualified Attribute on methods because even if the HasRefitHttpMethodAttribute method get the last part of a fully qualified name there is a check before to ensure that the statement "using Refit;" is present on the file.

```csharp
            // Make sure this file imports Refit. If not, we're not going to 
            // find any Refit interfaces
            // NB: This falls down in the tests unless we add an explicit "using Refit;",
            // but we can rely on this being there in any other file
            if (nodes.OfType<UsingDirectiveSyntax>().All(u => u.Name.ToFullString() != "Refit"))
                return new List<InterfaceDeclarationSyntax>();
```
This make impossible the usage of fully qualified names only in a interface (which is my case, due to interface generation).

By the way I think issue #325 is related to the check on the argument of the attribute. I assume that a interpolated string is not a "SyntaxKind.StringLiteralExpression"

```csharp
        public bool HasRefitHttpMethodAttribute(MethodDeclarationSyntax method)
        {
            // We could also verify that the single argument is a string, 
            // but what if somebody is dumb and uses a constant?
            // Could be turtles all the way down.
            return method.AttributeLists.SelectMany(a => a.Attributes)
                .Any(a => httpMethodAttributeNames.Contains(a.Name.ToString().Split('.').Last()) &&
                    a.ArgumentList.Arguments.Count == 1 &&
                    a.ArgumentList.Arguments[0].Expression.Kind() == SyntaxKind.StringLiteralExpression);
        }
```

Maybe there are good reason about those checks, if not I could make a PR to fix that.

Max.

**Comment by bennor** [comment]
There was definitely a reason for requiring the `using`, but I can't think of it right now. Will have a look at the code tomorrow and see if I can remember.

As for the fact we don't allow constants, that's because I requires another level of static analysis. At the moment we get by on just the syntax tree, but reading constant values from (most likely) another file would require semantic analysis. It's also a layer of indirection that makes it harder to see what your API is doing at a glance.

**Comment by TGrannen** [comment]
Just a heads up, this is still occurring. 
```
<PackageReference Include="Refit" Version="5.2.4" />
<PackageReference Include="Refit.HttpClientFactory" Version="5.2.4" />
```
I very recently found this package and have been looking to incorporate it into my daily set of tools. However, it's been quite frustrating to receive the generic 'IMyInterface doesn't look like a Refit interface' error when there is just no Using statement in the interface file. 

I understand that this issue might be quite difficult to address, but maybe adding some more helpful tips to the generic error message would be a good start to help get some people down the right track if this is their problem.

**Comment by clairernovotny** [comment]
Please try v6.0-preview.84 and file bugs as you come across them.
