### ISSUE TITLE
Confusing API: RestService.For with HttpClient doesn't use RefitSetting.HttpMessageHandlerFactory

### ISSUE THREAD

**Issue by sergiorykov** [reactiveui/refit#353]
RestService.For(**HttpClient**, *) is self-descriptive. You can configure as you wish. In that case, the only thing to do is to provide docs with samples (custom authorization header, retry policies, and so on)
RestService.For(**url**, *) may be provided with default most useful configurations:
```
RestService.For(url, settingsWithJsonAndFormattingOnly, http => {
     http.AddAuthorizationHeader(tokenProviderAsyncFunc);
})
```

**Comment by bennor** [comment]
Is this a question? I'm not sure what you're trying to say.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
