### ISSUE TITLE
Always TaskCanceledException on Refit call

### ISSUE THREAD

**Issue by sergio11** [reactiveui/refit#357]
I have this service interface with Refit to authenticate users:

```
[Headers("Accept: application/json")]
    public interface IAuthenticationRestService
    {

        [Post("/")]
        Task<APIResponse<JwtAuthenticationResponseDTO>> getAuthorizationToken([Body] JwtAuthenticationRequestDTO authorizationRequest);

    }
```

This method is executed from a service as follows:

```
async public Task<string> LogIn(string email, string password)
        {
            Debug.WriteLine(String.Format("Login with {0}/{1}", email, password));

            return await _authenticationRestService.getAuthorizationToken(new JwtAuthenticationRequestDTO()
            {
                Email = email,
                Password = password
            }).ContinueWith(t => t.Result.Data.Token, TaskContinuationOptions.OnlyOnRanToCompletion);
        }
```

The problem is that the task is always canceled, the TaskCanceledException exception is always thrown. 

![captura de pantalla 2017-09-05 a las 13 02 55](https://user-images.githubusercontent.com/6996211/30061480-d213526e-9247-11e7-9cf7-5e0dee86b49d.png)

With a DelegatingHandler implementation I have verified that the query is done correctly and the response is a 403 (bad credentials). How can I correctly handle error responses? **An ApiException exception is not thrown.**.

Thanks in advance!!!

**Comment by onovotny** [comment]
Not sure about the Refit part, but that code looks really insecure. I would strongly advise against using a username/password to authenticate directly against a REST API and look towards using an OAuth2 based solution. Azure AD B2C is a good option, as is several other popular libraries if you want to DIY (which I highly discourage).

**Comment by scwang90** [comment]
ServicePointManager.Expect100Continue = false;

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
