### ISSUE TITLE
Multipart/mixed with nested HTTP requests

### ISSUE THREAD

**Issue by opcodewriter** [reactiveui/refit#361]
I've been thinking if it would be possible to implement with Refit a multipart request where each part is a HTTP request. Like in this example from Google Storage batch API https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch#example

To make this work, I'd like to be able to (somehow) pass an array with the methods (albeit ideally LINQ expressions would be much nicer): 

     await api.PostIt(new HttpRequestPart[] {
         new HttpRequestPart(nameof(api.DoA)),
         new HttpRequestPart(nameof(api.DoB)) });

    public interface IMyApi
    {
        [Post("/doA")]
        Task DoA();

        [Post("/doB")]
        Task DoB();
    
        [Multipart]
        [Post("/bulk")]
        Task PostIt([AliasAs("MyThing")] HttpRequestPart[] parts);
    }

    public class HttpRequestPart : MultipartItem
    {
        public HttpRequestPart(string methodName) : base("MySeparator", "application/http")
        {
        }
        protected override HttpContent CreateContent()
        {
              // meh... this is the hard part
        }
     }

I've been thinking and looking at the Refit implementation, and it doesn't seem I will be able to just extend it without actually changing Refit.
Any thoughts?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
