### ISSUE TITLE
I'm getting "dotnet quit unexpectedly." dialog on Mac when calling an API

### ISSUE THREAD

**Issue by mahdi** [reactiveui/refit#377]

**Comment by Cheesebaron** [comment]
You probably need to provide a bit more context :)

**Comment by mahdi** [comment]
Here's the Debug Console output:

```
Loaded '/Users/mahdi/.nuget/packages/refit/4.0.1/lib/netstandard1.4/Refit.dll'. 
Loaded '/Users/mahdi/.nuget/packages/microsoft.aspnetcore.webutilities/1.1.2/lib/netstandard1.3/Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Security.Cryptography.X509Certificates.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[22688] Fidilio.Core.Api.dll' has exited with code 0 (0x0).
```

**Comment by bennor** [comment]
Have you tried wrapping the offending line in a try/catch? I can't see how an API call would cause it to terminate _without throwing an exception_.

**Comment by mahdi** [comment]
@bennor Yes, I added a try/catch block but no exception throws at all.

**Comment by onovotny** [comment]
This looks like a bug in .NET Core. I would suggest one of two things:

1. Does it work if you return a string/type instead of using `dynamic`? If so, then there may be an issue with `dynamic`.
2. Filing an issue on the https://github.com/dotnet/corefx repo (and link back to here) so someone there can investigate.

**Comment by tjmoses** [comment]
@onovotny did you ever resolve this? I am having the same issue.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
