### ISSUE TITLE
DeclaringMethod, GenericParameterAttributes and GenericParameterPosition threw InvalidOperationException

### ISSUE THREAD

**Issue by strandloper** [reactiveui/refit#379]
I have run into a problem that I am struggling to find the cause for.

My client project that uses Refit targets .NET Standard 2.0 but a common library it depended on was still targeting .NET Framework 4.61. After porting the common library to .NET Standard 2.0 I have started getting many failing tests reporting 500 (Internal Server Error) but Stackify Prefix gives no indication that the REST calls are made at all.

So I started to dig a bit and have found the following. In RequestBuilderImplementation.cs in the BuildCancellableTaskFuncForMethod<T> method are the following two lines of code.

```
resp = await client.SendAsync(rq, HttpCompletionOption.ResponseHeadersRead, ct).ConfigureAwait(false);
if (restMethod.SerializedReturnType == typeof(HttpResponseMessage))

```
The SendAsync executes, then the if condition is true and the 500 result is returned. With a breakpoint set on the SendAsync line I examined the restMethod.SerializedReturnType data and noticed that the DeclaringMethod, GenericParameterAttributes and GenericParameterPosition properties all report having thrown System.InvalidOperationException. This is so even before the SendAsync call and I presume is what is causing it to set the resp variable to the 500 HTTP response without actually making a REST call.

As my tests passed before I ported the common code I presume that this is something outside Refit that is causing the error inside Refit but I'm at a loss as to what to look at to find the cause. Can anyone provide suggestions of where I should be looking or what I should be looking for?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
