### ISSUE TITLE
UWP HttpClient / IAsyncOperationWithProgress

### ISSUE THREAD

**Issue by zlstringham** [reactiveui/refit#382]
For UWP, it would be nice to have an alternative option to the `System.Net.Http.HttpClient` option; namely `Windows.Web.Http.HttpClient`. Instead of returning `Task<T>`, I would like to return an `IAsyncOperationWithProgress<T>` so I could i.e. use a `ProgressBar` rather than a `ProgressRing`.

**Comment by bennor** [comment]
I'm not sure how we could support that while supporting netstandard. 

I suspect supporting it would require rewriting a pretty big chunk of the library too.

**Comment by totht91** [comment]
Maybe this isn't the refit library's responsibility because you can convert to WinRT with some work: https://blogs.msdn.microsoft.com/windowsappdev/2012/06/14/exposing-net-tasks-as-winrt-asynchronous-operations/

**Comment by zlstringham** [comment]
@bennor I haven't done this myself previously, but I suspected this could be accomplished via conditional compilation (`#ifdef WINAPI_FAMILY_UNIVERSAL`?) and multi-targeted nuget packages? Maybe there is a caveat I'm missing there.

@totht91 That doesn't accomplish what is requested here. As mentioned in the original issue comment:
>  I would like to return an `IAsyncOperationWithProgress<T>` so I could i.e. use a `ProgressBar` rather than a `ProgressRing`

If you notice in the examples from the article you referenced, this is not supported. They hacked together some implementation for `IAsyncOperationWithProgress` that reports 0 (starting), 50 (started), and 100 (completed). This is fundamentally different than actual progress notifications.

**Comment by onovotny** [comment]
We may be able to adapt this:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/67532f1b9145a5f93d1ddd581c4347b4dc417e51/PackageExplorer/MefServices/PackageDownloader.cs#L197

It's an HttpMessageHandler that wraps a stream that reports progress.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
