### ISSUE TITLE
Support for SSE's

### ISSUE THREAD

**Issue by SKLn-Rad** [reactiveui/refit#389]
As many server side implementations are making use of the new HTML standard for Server Side Events. It would be cool to have this available in Refit as well so we can consume these new data styles.
That way .NET apps could consume and react to event streams in the same way as say an Angular or React application.

Standard: https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events
Spring WebFlux (Server side implementation guide): https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html

I know this standard isn't 100% confirmed yet, however it doesn't seem like it would be hard to do and would be a great use of the async streams feature when it is finally available in C#!

I don't mind having a look into a demo PR if this is okay?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
