### ISSUE TITLE
OAuth2 flow

### ISSUE THREAD

**Issue by alexandru-calinoiu** [reactiveui/refit#39]
Hi,

Do you have a suggestion for a best practice on implementing the OAuth2 authorization flow, especially the refresh token usage.

It will need to do something like:

```
original request -> repond: 401 -> request refresh_token -> respond: 200 -> original request -> respond: 200
```

Thank you,

**Comment by Necronux** [comment]
@alexandru-calinoiu shouldn't that be called spaghetti auth?
