### ISSUE TITLE
Refit in Unity3D 2017.2 with .NET 4.6.

### ISSUE THREAD

**Issue by SetoKaiba** [reactiveui/refit#391]
I try to use refit in Unity3D. Recently Unity3D 2017 added the support with .NET 4.6.
But I encounter the following problem.
I just test with the example.

> InvalidOperationException: IGitHubApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
> Refit.RestService.For[T] (System.Net.Http.HttpClient client, Refit.RefitSettings settings) (at <ceffed5d220e453184dcaa5bc0e6be90>:0)
> Refit.RestService.For[T] (System.String hostUrl, Refit.RefitSettings settings) (at <ceffed5d220e453184dcaa5bc0e6be90>:0)
> Refit.RestService.For[T] (System.String hostUrl) (at <ceffed5d220e453184dcaa5bc0e6be90>:0)
> BlueeyesTestLogin+<InitRefitService>c__async1.MoveNext () (at Assets/BlueeyesTestLogin.cs:57)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:92)
> UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:53)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:74)

**Comment by SetoKaiba** [comment]
I know why it doesn't work. Refit need do something when building.
But Unity3D doesn't support it.
I'm guided to Refit by https://github.com/jordan-thoms/Retrofit.Net.
It's working in Unity3D. But it's less maintained.
Is it possible to not relying with the building part?

**Comment by onovotny** [comment]
Can you share a repro? Refit relies on build-time MSBuild task that generates the code implementing the interfaces.

**Comment by SetoKaiba** [comment]
There's no MSBuild task for Unity3D. Does it mean that it can't be used for Unity3D?

**Comment by HelloKitty** [comment]
@SetoKaiba I created something similar to Refit/Retrofit that works in Unity3D. In fact I use it in Unity3D myself. It's [Typesafe.Http.Net](https://github.com/hellokitty/typesafe.http.net). It uses Castle.Core instead of code generation to build the Types at runtime. It supports RestSharp too, which some in Unity3D prefer to use. Or at least they used to.

It doesn't have full feature parity with with Refit and will be less performant but it's pretty similar API-wise. Just whipped it up real quick one week due to missing features I needed that Refit didn't have. One day I'll get around to finishing it that and other things.

**Comment by HelloKitty** [comment]
Just as a heads up, while Typesafe.Http.Net does work on net4x for Unity3D it will fail for Netstandard2.0 builds. The reasoning I received from Unity Technologies I don't agree with. Netcore/Netstandard support Castle.Core DynamicProxy yet Unity Technologies has elected not to support it even on the Windows platform with their custom .NET runtime so I'd recommend against Typesafe.Http.Net if you fall into that niche.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by surajkumarr12** [comment]
With Refit 6 and Unity 2020.3. Still not able make it work. 
For example when I build unity project for Andorid I'm getting below error.

Message: MissingMethodException: Constructor on type 'Refit.Implementation.Generated+<_InterfaceName_>' not found.
Stack Trace:
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <00000000000000000000000000000000>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <00000000000000000000000000000000>:0)
Refit.RestService.For[T] (System.Net.Http.HttpClient client, Refit.IRequestBuilder`1[T] builder) (at <00000000000000000000000000000000>:0)
System.Action`1[T].Invoke (T obj) (at <00000000000000000000000000000000>:0)
System.Action`1[T].Invoke (T obj) (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityAction.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1].Invoke (T1 handler, UnityEngine.EventSystems.BaseEventData eventData) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule:Process()

Any help on this will be appreciated.

**Comment by clairernovotny** [comment]
@surajkumarr12 According to the Unity docs, they do support source generators (which Refit requires), though there are special steps to use them. Also might need a newer version of Unity, but I'm not sure.

https://docs.unity3d.com/2022.1/Documentation/Manual/roslyn-analyzers.html

**Comment by surajkumarr12** [comment]
Thank you @clairernovotny. I'm using Unity 2020.3 where I don't see option for source generators. One more question, is it possible to generate refit interface implementation in a given path and package it with source code ?

**Comment by clairernovotny** [comment]
The source generator is required for Refit to work.

**Comment by surajkumarr12** [comment]
@clairernovotny yeah I understand. My question is I see refit interface implementations are mostly in temp folders in .net projects. So is it possible to pass parameter during build to generate interface in same folder so that I can export whole project including generated code to unity ?

**Comment by clairernovotny** [comment]
No, there isn't. Roslyn generates in memory.

**Comment by surajkumarr12** [comment]
ok thank you @clairernovotny
