### ISSUE TITLE
Response Interceptor

### ISSUE THREAD

**Issue by abhilashdonepudi** [reactiveui/refit#392]
Is there a way to intercept a response ? I am using OData rest api. I have to remove OData context from the json string and deserialize the value.

Below is the response from OData api.

{"@odata.context":"","value":[]}

**Comment by onovotny** [comment]
Not today, but I would suggest using a wrapper type for now. That can be generic too, like `ODataResponse<T>` and there's a single `Value` property of type `T`.

**Comment by conwid** [comment]
Alternatively a custom JsonConverter can be created and this can be specified when creating a RefitSettings. Inside the custom converter, parts of the json can be extracted and used for serialization.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
