### ISSUE TITLE
MultipartItem Extensions

### ISSUE THREAD

**Issue by martinstanek** [reactiveui/refit#395]
Hi All,

first of all thanks for this amazing library. We use it and we like it so much.

However we have spotted some issues with handling of the `MultipartItem`. The initial problem is: We would like to pass some more info while uploading a file, in the very same request. We can't use the route, since some parameters are optional, we have tried query strings, but this didn't work. So our idea was to inherit the `MultiPartItem` class and combine `StreamContent ` and couple `StringContent`s inside within one `HttpContent`.  Refit can process it somehow, but it struggles with proper boundaries inside. (`----MyGreatBoundary` is combined with GUID boundaries for the `StringContent`s which is coming from the internal `HttpClient`). 

So my question is: Is there any option to use query strings while having request like this? :

```
[Multipart]
[Post("/api/v1.0/documents/user/{userId}/key/{key}")]
Task<DocumentMetaData> SaveDocumentAsync(string userId, string key, [AliasAs("form")] StreamPart stream);
```

Or is there any plan to support `MultipartFormDataContent ` in such a way that we can pass whatever we want?

Or we would be happy to sketch the solution and issue a PR, if there is no plan to do similar feature in near future?

Thanks a lot!
Martin, EF

**Comment by sfalik** [comment]
I have a similar requirement -- optional parameters combined with multi-part content, interested to see where this goes...

**Comment by mjohnson0580** [comment]
:+1: +1

**Comment by xljiulang** [comment]
i would like this in [WebApiClient](https://github.com/xljiulang/WebApiClient)
```c#
// POST webapi/user  
[HttpPost("/webapi/user")]
ITask<UserInfo> UpdateUserWithMulitpartAsync(
    [MulitpartContent] UserInfo user, 
    [MulitpartText] string nickName,
    [MulitpartText] int? age,
    param MulitpartFile[] files);
```

**Comment by onovotny** [comment]
You should be able to use query strings with multipart uploads... I'm doing that with my SignClient here:
https://github.com/onovotny/SignService/blob/master/src/SignClient/ISignService.cs#L14-L16

If that's not sufficient, that I'm certainly open to ideas on how to imrove it.

**Comment by alec-lieberman-ef** [comment]
Has there been any traction on this issue? This seems like something that would be great to have.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
