### ISSUE TITLE
Documentation/terminology REST vs HTTP 

### ISSUE THREAD

**Issue by dave-hillier** [reactiveui/refit#398]
I am searching for REST libraries and came across this library which you've described as just that, but I couldn't find anything particularly related to REST, such as hypermedia, resources and so on. 

I had a click on the Refit link you've provided and I see that they call it a HTTP Client.  I would suggest that you adopt the same terminology to avoid this confusion. 

There is nothing wrong with plain old HTTP APIs but they are different from REST APIs.

**Comment by Cheesebaron** [comment]
I guess the readme is inspired by Retrofit, which back when Paul made Reft, also said REST: https://github.com/square/retrofit/commit/53a28ba663650a6004548b0de4f3a7bdafc2b713#diff-04c6e90faac2675aa89e2176d2eec7d8

It is however, not untrue that refit can help consume an REST API. However, you are right, nothing is done about HATEOAS, it is up to the user of this library to do something about that.

**Comment by dave-hillier** [comment]
Sure, it can consume REST APIs but it can also consume other HTTP APIs

**Comment by Cheesebaron** [comment]
@dave-hillier I personally am not opposed getting this clarified. What I suggest is that you open a Pull Request making this clarification and have @onovotny and @bennor take a look 😄

**Comment by dave-hillier** [comment]
@Cheesebaron I looked at the Documentation and realized that this terminology is baked into the API itself... so it might be one of those things that just has to be left.

**Comment by bennor** [comment]
I'm not sure it's important enough to justify a breaking change that will affect all users. I think we should close this, or maybe just remove it from the docs?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
