### ISSUE TITLE
Support RFC 6570

### ISSUE THREAD

**Issue by nikmd23** [reactiveui/refit#4]
It'd be awesome if `[HttpMethod]` attribute's `Path` property supported full blown, level 4 [uri templates as defined in RFC 6570](http://tools.ietf.org/html/rfc6570).

@darrelmiller already has [an implementation of the spec](https://www.nuget.org/packages/Tavis.UriTemplates/) that you'd probably be able to leverage pretty easily.

Parameter semantics like collections/arrays, and optional/nullables map pretty nicely to the spec too - so it's basically free (ok, so cheap) power.

The good news is, this wouldn't even be a breaking change!

**Comment by martijn00** [comment]
There seems to be some library's available that can be used to support this:
- https://github.com/rackerlabs/dotnet-uritemplate
- https://github.com/tavis-software/Tavis.UriTemplates

I would like to have a possibility this use those kind of templates. How are the thoughts on this currently?

**Comment by SimonSimCity** [comment]
@darrelmiller Is there some way I can help here? I really need level 4 templates as well when using Refit ...

**Comment by darrelmiller** [comment]
URI Templates now supports PCL and will run on "all the platforms".  I don't know Refit well enough to know how URITemplates might be incorporated.  I'll take a look though.

**Comment by darrelmiller** [comment]
From what I can glean, the first step would be to replace the use of a regex in buildParameterMap with uriTemplate.GetParameterNames.  The other piece would be replacing parameter values when recreating the URI in BuildRequestFactoryForMethod.  Am I missing other things?

**Comment by darrelmiller** [comment]
Ok, so it mostly just works.  58 out of 63 tests are passing.  The only part that doesn't work is with UriTemplates you are expected to explicitly identify query parameters that may appear in the query string.  This is causing a number of tests to fail.  

I'm assuming that the best option would be to add a property to RefitSettings to indicate if you wish to use regular Refit templates or UriTemplates.  Does this make sense?

**Comment by SimonSimCity** [comment]
@darrelmiller Thanks for the research so far. As those two template-formats aren't compatible to each other, I'd also do it the same way instead of tweaking the template implementation to somehow be compatible to that format here.

I'd also disable it by default for the next version, if it's not a major release, and then, in the next major release, make this the default, as it is a standard that is used for many applications - not only Refit :wink:

**Comment by martijn00** [comment]
Would it be an option to add that to the new RefitSettings that was introduced in 2.2.0: https://github.com/paulcbetts/refit/releases/tag/2.2.0

Something like this:
`var gitHubApi = RestService.For<IGitHubApi>("https://api.github.com",
    new RefitSettings {
        JsonSerializerSettings = new JsonSerializerSettings {
            ContractResolver = new SnakeCasePropertyNamesContractResolver(),
            UriTemplateHandler = new Tavis.UriTemplates()
        }
 });`

**Comment by martijn00** [comment]
@darrelmiller Did you come any further on this yet?

**Comment by darrelmiller** [comment]
@martijn00 I have not.  I'll try and get back to it

**Comment by darrelmiller** [comment]
I was able to do 95% of the refactoring to move UriTemplateHandler into a pluggable component but now I'm stuck in bait and switch hell.  Unfortunately, I'm not familiar enough with the technique to find my way out at the moment.

**Comment by SimonSimCity** [comment]
@darrelmiller Do you have a branch, I could continue on? Please do also outline the things where you see yourself stuck in the dirt :wink:

**Comment by darrelmiller** [comment]
@SimonSimCity Ok, so here is a branch that makes UrlTemplateHandler pluggable https://github.com/darrelmiller/refit/tree/URITemplate   I got it working, all the tests pass and the behaviour is the same as before.  I needed to create some stub classes to include in the portable library to prevent all kinds of dependencies leaking in.

Now, if you create a new handler that looks like this, https://gist.github.com/darrelmiller/deff3525791be6470520

Then you should get the new behaviour using RFC6570 templates.

If this approach makes sense to people, then I'll issue a PR for the pluggable changes and create a new Nuget package that has the new Handler with the dependency on Tavis.UriTemplates.

**Comment by darrelmiller** [comment]
PR is here https://github.com/paulcbetts/refit/pull/141 if anyone has any opinions.

**Comment by boodoolak** [comment]
Hi,
Refit already works with Tavis.UriTemplates?

**Comment by onovotny** [comment]
@bennor @paulcbetts where did we land with this? Still something to keep open or close it out as out-of-scope & design goals?

**Comment by bennor** [comment]
Not sure TBH. I don't know enough about the RFC6570 standard to know what the advantages would be. It's a shame @darrelmiller's PR wasn't merged when it was still in sync with the codebase, because it looked like a decent approach.

We definitely don't want to be taking an external dependency for support, but making it pluggable is fine.

**Comment by onovotny** [comment]
Closing for now as stale
