### ISSUE TITLE
ArgumentException: Get Method not found for 'Handle'

### ISSUE THREAD

**Issue by KennethKr** [reactiveui/refit#413]
Hi. 

Using latest Refit 4.1.0 I get this exception and crash when using the "Link sdk frameworks only" build option. This was not a problem before 4.1.0. 

When turning off linking, it works fine. Please see the attached screenshot. The interface where the exception is triggered is pasted below. Its the [Get("/order")] method.

```
    public interface IOrderApi
    {
        [Get("/order")]
        Task<TOrderListResponse> List(string route, string createdAfter, CancellationToken? cancellationToken);
        
        [Post("/order/accept")]
        Task Accept(string orderId);
        
        [Post("/order/reject")]
        Task Reject(string orderId);
    }


    [Preserve]
    public partial class AutoGeneratedIOrderApi : IOrderApi
    {
        /// <inheritdoc />
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIOrderApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        /// <inheritdoc />
        public virtual Task<TOrderListResponse> List(string route,string createdAfter,CancellationToken? cancellationToken)
        {
            var arguments = new object[] { route,createdAfter,cancellationToken };
            return (Task<TOrderListResponse>) methodImpls["List"](Client, arguments);
        }

        /// <inheritdoc />
        public virtual Task Accept(string orderId)
        {
            var arguments = new object[] { orderId };
            return (Task) methodImpls["Accept"](Client, arguments);
        }

        /// <inheritdoc />
        public virtual Task Reject(string orderId)
        {
            var arguments = new object[] { orderId };
            return (Task) methodImpls["Reject"](Client, arguments);
        }

    }
```

![screen shot 2018-01-26 at 14 07 35](https://user-images.githubusercontent.com/1160628/35442044-0c000de0-02a6-11e8-93e0-e16951a12c78.png)

**Comment by onovotny** [comment]
Hi,

This looks like a Xamarin bug as we have the `PreserveSig` attributes on the Refit generated code:
https://github.com/paulcbetts/refit/blob/master/InterfaceStubGenerator.Core/GeneratedInterfaceStubTemplate.mustache#L19-L29

Can you please follow-up with a link to the issue for Xamarin?
Thanks

**Comment by KennethKr** [comment]
Ok. I can do that. One thing tho, it does not happen with Refit 4.0.1? Same Xam SDKs.

**Comment by onovotny** [comment]
@KennethKr Not at all sure, there's not much we can control in the linking aside from adding that attribute.

**Comment by KennethKr** [comment]
Referenced Xam ios issue. I've attached more information like crash log and build log as well over there.

**Comment by KennethKr** [comment]
Hey @onovotny.

I did some more research into this.

I changed the signature of my method from

```
[Get("/order")]
        Task<TOrderListResponse> List(string route, string createdAfter, CancellationToken? cancellationToken);
```

to 

```
        [Get("/order")]
        Task<TOrderListResponse> List(string route, string createdAfter, CancellationToken token = default(CancellationToken));
```

Now it works. Any idea why?

**Comment by onovotny** [comment]
Not sure why the linker error is happening, but as a matter of correctness, I don't think `CancellationToken?` would work anyway since that's really a `Nullable<CancellationToken>` and the logic that looks for that parameter type isn't looking for a Nullable, IIRC.

**Comment by KennethKr** [comment]
It works when no linking is enabled :)

**Comment by bennor** [comment]
I think Oren's saying the code in Refit that uses the cancellation token may not do anything if you pass it as nullable. It may even be trying to pass it along as a querystring parameter. 😉

**Comment by KennethKr** [comment]
Hehe. You are right. It passes it as a query param :)

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
