### ISSUE TITLE
An error occurred during the installation of the Refit in the PLC project.

### ISSUE THREAD

**Issue by idimkk** [reactiveui/refit#418]
Hello!
An error occurred during the installation of the Refit in the PCL project:
> The "Refit 4.1.0" package could not be installed. You are trying to install this package in a project whose required version of the platform is ".NETPortable, Version = v4.5, Profile = Profile259", but the package does not have links to assemblies or content files compatible with this platform. For more information, contact the author of the package.

**Environment:**
Visual Studio 2017 version 15.5.5
Xamarin 4.8.0.760
Nuget 4.5.0

In the PCL project:

>     <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
>     <TargetFrameworkProfile>Profile259</TargetFrameworkProfile>

**Comment by Cheesebaron** [comment]
Refit is .NET Standard 1.4, so you won't be able to install it in a PCL.

**Comment by idimkk** [comment]
That is, I can not use it in a general project? Will it be necessary to implement specific platforms?

**Comment by idimkk** [comment]
I changed the project type. And it helped to solve my problem.
I'm sure you need to take it to FAQ.
[Help Link](https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/)
