### ISSUE TITLE
Why not use ModernHttpClient?

### ISSUE THREAD

**Issue by stefandevo** [reactiveui/refit#42]
Is there an option to use your great ModernHttpClient inside refit?

**Comment by montecillodavidacn** [comment]
Hey how do I use okhttp? I cannot use modernhttpclient since i used picasso.

**Comment by Cheesebaron** [comment]
I recommend not to use ModernHttpClient as it is not maintained by anyone and is awfully behind.

Use the handlers Xamarin provides, if you are on Android 5.0 or newer they will automatically use OkHttp.

**Comment by montecillodavidacn** [comment]
But I get untrusted certificate path error stuff. How do I accommodate this please?

**Comment by montecillodavidacn** [comment]
I was trying to do:

c#```var client  = new OkHttpClient(){ BaseAddress =  new Uri("server url")};```

but this doesnt work.

**Comment by dupovalo** [comment]
@Cheesebaron, what would you say about [this fork of ModernHttpClient](https://github.com/alexrainman/ModernHttpClient)? Is it good option to use with Refit? It appears to be the only client that picks up system proxy settings [properly](https://github.com/reactiveui/refit/issues/123).
