### ISSUE TITLE
Documentation : using Windows Authentication

### ISSUE THREAD

**Issue by Styxxy** [reactiveui/refit#427]
From conversation in PR #368 

Documentation should be updated how to use Windows Authentication to make API calls.

There are two options to solve this, create a HttpClient yourself, or set the clienthandlerfactory in the RefitSettings;

```csharp
// Option 1 : create HttpClient yourself
var client1 = RestService.For<IMyService>(
    new HttpClient(new HttpClientHandler() { AllowAutoRedirect = true, UseDefaultCredentials = true })
    {
        BaseAddress = new Uri("http://example.com/")
    });

// Option 2 : set the ClientHandler factory
var client2 = RestService.For<IMyService>(
    "http://example.com/",
    new RefitSettings()
    {
        HttpMessageHandlerFactory = () => new HttpClientHandler() { AllowAutoRedirect = true, UseDefaultCredentials = true }
    });
```

**Comment by Styxxy** [comment]
Note that using Refit in a Web API project to call another (Web) API that requires Windows Authentication, does **not** work with above code.

(Still figuring out a solution.)

**Comment by onovotny** [comment]
In general, wep api's using windows auth to call other web api's is a bad idea and I can't imagine is widely supported.

**Comment by Styxxy** [comment]
In our case (this case) it was a pure internal API that should only be accessible by certain Service Accounts (with certain roles). This is easily achieved through Windows Authentication.

But finally I found the culprit. Actually the solution (code in OT) is correct. The problem we encountered was a wrongly configured service (hosted in IIS): NTLM was used (instead of Kerberos) **and** on the test environment both services were deployed on the same machine **and** the requests were made using the hostname (instead of IP address). More details can be found on https://support.microsoft.com/en-us/help/896861/you-receive-error-401-1-when-you-browse-a-web-site-that-uses-integrate .

**Comment by onovotny** [comment]
Yup, one of many reasons why it's hard to use windows auth between service accounts. I've hit similar things in the past. OAuth2 is so much easier to diagnose by comparison :)

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by BritoMatheus** [comment]
With Dependency Injection:

```
services.AddRefitClient<IAccountApi>().ConfigureHttpClient((options) =>
            {
                options.BaseAddress = new Uri(Environment.GetEnvironmentVariable("AccountApiUrl"));
            }).ConfigurePrimaryHttpMessageHandler(() =>
            {
                return new HttpClientHandler()
                {
                    AllowAutoRedirect = true,
                    UseDefaultCredentials = true
                };
            });
```
