### ISSUE TITLE
Is there any support for temporary connection failures etc?

### ISSUE THREAD

**Issue by ChristianSauer** [reactiveui/refit#435]
I am wondering if there is any support to handle temporary connection / server errors?
E.g. a retry + circuit breaker mechanism?

**Comment by Cheesebaron** [comment]
You can use Polly or whatever other library to provide this

**Comment by khalidabuhakmeh** [comment]
This can be done at the `HttpClient` level using a `DelegatingHandler` to make the calls. It's not necessarily a Refit concern. Like @Cheesebaron mentioned, [Polly](https://github.com/App-vNext/Polly) is a good library to use in conjunction with modifying your HttpClient instance.

**Comment by bennor** [comment]
When we overhaul the docs, it would be great to document an example of using Polly with Refit.

**Comment by khalidabuhakmeh** [comment]
https://github.com/ziyasal/mstodoapi/blob/d059da7ece871463d2ec24cbf0a2bb7c20e295a8/MSTodoApi/Infrastructure/Http/HttpRetryMessageHandler.cs

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
