### ISSUE TITLE
How to dynamically add a query string KVP to the URL for auth?

### ISSUE THREAD

**Issue by CreepyGnome** [reactiveui/refit#438]
I don't see anyway via the readme to be able to add a query string key value pair to a URL for auth purposes. I have to call an API I do not control that requires an API Key to be in the query string. I do not want to hard code this in the attributes and would like to be able to read it via a config that would have its test values overridden in production.

If this isn't available I would like to request this ability as a new feature, if it is possible I would love to know how to do it.

**Comment by windischb** [comment]
If i unserstand your question correctly...

Have you tried

```csharp
[Get("/get/securevalue")]
Task<HttpResponseMessage> GetSecuredValue(string apiKey);

[Get("/get/securevalue")]
Task<HttpResponseMessage> GetSecuredValue([AliasAs("apiKey")]string key);

[Get("/get/securevalue")]
Task<HttpResponseMessage> GetSecuredValue([Query("apiKey")]string key);

```

All of them should be built an Url like http://example.api.com/get/securevalue?apiKey={...}

**Comment by onovotny** [comment]
@windischb's answer is the current way to do this, does that cover the need here?

**Comment by CreepyGnome** [comment]
It doesn't solve the problem it is just telling me what the doc already does which isn't sufficient to solve the issue. This requires the KEY to be passed into a method call EVERY time. When auth is handled via a header it can be set up one time via the HttpClient and then you don't for the lifetime of that client which most likely will be a while.

I have a REST Endpoint I don't control and requires the API KEY is only in the query string. I want to set up one time what the key is at the initialization of the API via Refit like I would an auth header. It feels dirty to have to make all the callers of the API be aware of the secure API KEY.  I also know I can use a client handler for HttpClient to inject it on every request I need it on, again however that isn't as clean as I would like However it is better than exposing the key to any calling of the API itself for every method endpoint method call.

So the best solution seems to be to use a custom handler for an HttpClient to inject the query string for the API KEY on requests that need it. While requesting a feature from the provider of said REST API to add optional auth header to use instead of query string. :)

I don't think it is any way for  Refit to do this cleanly without doing the above on the user's behalf which may not be something it should be doing.

It may be something to add to the readme/docs as an example of how to dynamically inject a auth API KEY into all required requests without exposing it in the Refit interface definition for each method call.

**Comment by bennor** [comment]
I wonder if adding support for writeable properties on the interface would be helpful. This could work for both attributes and query parameters. e.g. 

```csharp
public interface ISomeApi
{
    [Header("X-ApiKey")]
    public string ApiKey { get; set; }
}
```
or
```csharp
public interface ISomeApi
{
    [Query("apiKey")]
    public string ApiKey { get; set; }
}
```

**Comment by bennor** [comment]
An alternative would be some addition to `RefitSettings` to support the required behaviour.

**Comment by conwid** [comment]
This is a feature that I sorely need :)
If someone can help me with the basic how-to of contributing and we spec this feature appropriately, I can do the legwork on this feature and implement it.

**Comment by CreepyGnome** [comment]
@bennor those attributes would be great and they seem to fit with the Refit attribute design paradigm.

**Comment by Vertigo093i** [comment]
I've managed to hack on this by injecting a separate `HttpMessageHandler` into the HttpClent's message handlers pipeline. Something like this:

```csharp
services.AddRefitClient<ISomeApi>()
	.AddHttpMessageHandler(() => new InsertApiKeyHandler(apiKey));
```

Inside that handler's `SendAsync` override there is a read/write access to the origin request URI. Just modify it according your needs.

For those using direct `RestService.For<T>` approach the equivalent would be to direct inherit from the `HttpClientHandler` and pass it via `RefitSettings.HttpMessageHandlerFactory`.

Not an elegant solution but works.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
