### ISSUE TITLE
name Parameter for MultipartItems

### ISSUE THREAD

**Issue by windischb** [reactiveui/refit#440]
Hi!

I have the need to pass multiple FileInfoPart's.
If i use an IEnumerable<MultiPartItem> resources, all items have name=resources as Property..

The Api expected different names for each item.
How can i set such Property? 
Is there a Way to set the "name" on the FileInfoPart?

**Comment by ahmedalejo** [comment]
Code sample please :)

**Comment by windischb** [comment]
```csharp
[Post("/deployment/create"), Multipart]
Task<DeploymentObject> Create([AliasAs("deployment-name")]string deploymentName,
                              [AliasAs("enable-duplicate-filtering")]bool enableDuplicateFiltering,
                              [AliasAs("deploy-changed-only")]bool deployChangedOnly,
                              [AliasAs("deployment-source")]string deploymentSource,
                              [AliasAs("tenant-id")]string tenantId,
                              IEnumerable<MultipartItem> resources);



public async Task<DeploymentObject> TestCreate() {
    var resources = new List<FileInfoPart> {
        new FileInfoPart(new FileInfo("TextFile1.txt"), "TextFile1.txt"),
        new FileInfoPart(new FileInfo("TextFile2.txt"), "TextFile2.txt")
    };
    return await _restService.Create("testDeployment", false, false, null, null, resources);
}

```

which ends up as:

![image](https://user-images.githubusercontent.com/6182311/36299441-45d94ba0-12fd-11e8-9924-be49887bdf26.png)

**Comment by windischb** [comment]
Is this by design???
Or a Bug???
Nobody ever want's to send multiple Resources?

**Comment by zlstringham** [comment]
I'd like to bump this. An API I'm trying to interface with creates resources that contain multiple attachments.  On some endpoints, it expects the attachments to have distinct names like:
```
... name=attachments[0]; ...
...
... name=attachments[1]; ...
...
```

On others:
```
... name=attachments[]; ...
...
... name=attachments[]; ...
...
```

For the former case, it would be helpful if I could associate the `name` somewhere in a `StreamPart`. (Perhaps in a derived `NamedStreamPart`?)

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
