### ISSUE TITLE
Using generic interfaces

### ISSUE THREAD

**Issue by KratiChauhan** [reactiveui/refit#446]
Hello

I am evaluating refit to be used in my Xamarin native project. 
As far as i understood, we have to create interface files for each API Endpoints. Interface file will contain methods which will have HTTP attribute that provides the request method and relative URL. 
In could see in the documentation we can add placeholder for querystring. We however do not want to add the relative URL hardcoded in the interface, but want it to be coming from a config file. 

Can you please let me know if this is possible and if yes, a sample to do the same ?

**Comment by totht91** [comment]
Could you show us some examples?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
