### ISSUE TITLE
forking refit

### ISSUE THREAD

**Issue by windischb** [reactiveui/refit#448]
I'm not familiary with forking and licensing.
I would like to forking refit and integrate some improvements, which helps me in my daily work...
Before i start to do things, i would like to ask is it's allowed to use the current code from refit and start from there with my own version?
rename it, change the package properties, and so on...
Is it ok if i mention the "original" Refit Projekt in the README?

**Comment by onovotny** [comment]
You are well within your rights to fork refit. However, I would ask yourself the following:

1. Is there some way to contribute here?
2. Libraries and public packages require continual care-and-feeding. Is that a commitment you want to make?

If you really want to fork, you can based on the terms in the MIT license. However, you need to change your package name and cannot use Refit in the name to prevent confusion.

**Comment by windischb** [comment]
There are some things which would make my life easier for my daily work and are already discussed here, but they don't have enough benefit for others to include.
So i think the only way to make my workday less painfull, is to fork and integrate those things there.
You make really great work here and i understand that not all wishes can be included here, but i also don't want to use workarounds in every project i use for work.
Thanks for clarification!

**Comment by windischb** [comment]
Of course!
Many thanks!
