### ISSUE TITLE
Can't install 4.3 refit on PCL 

### ISSUE THREAD

**Issue by PSyron** [reactiveui/refit#452]
Hi,
As android dev refit sounds promising but I have a trouble to make it work on my PCL - MvvmCross project. I've installed it on platform project but still nothing works. Newest VS and libraries. 

Message:
Could not install package 'Refit 4.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by PSyron** [comment]
Fixed my problem by using version 3.1. Hope there no majors in this diff

**Comment by Cheesebaron** [comment]
Newer versions of Refit use .NET Standard.
