### ISSUE TITLE
Xamarin.Forms + .NET Standard + Refit

### ISSUE THREAD

**Issue by josuesamano** [reactiveui/refit#455]
I have the same problem, I have created a Xamarin.Forms project with .NET Standard, everything is fine, but it fails to deploy with Xamarin Live

I have the following versions .NET Standard 2.0 Refit 4.3.0 Xamarin.Forms 2.5.0.280555

It throws error when I put the code to call the endpoints of my service

```
async void BtnClicked(object sender, EventArgs e)
{
      var apiResponse = RestService.For<IAcountApi>("http://x.x.x.x:x");
      var makeUps = await apiResponse.LoginAsync(model);
}
```

Any ideas?

**Comment by onovotny** [comment]
I would file an issue on the Live Player repo. @jamesmontemagno?

**Comment by josuesamano** [comment]
What happens is that I throw these errors when I run the app for Xamarin.Live, but if I comment the code block of the button that I put up, all right

**Comment by josuesamano** [comment]
![image](https://user-images.githubusercontent.com/5949714/37720413-d60a4978-2cec-11e8-9f9c-9494f2673070.png)

**Comment by josuesamano** [comment]
![image](https://user-images.githubusercontent.com/5949714/37720454-e52b826e-2cec-11e8-942a-4a71483d2b8c.png)

**Comment by josuesamano** [comment]
![image](https://user-images.githubusercontent.com/5949714/37720477-f30bd05a-2cec-11e8-94b3-eacfec165b92.png)

**Comment by josuesamano** [comment]
![image](https://user-images.githubusercontent.com/5949714/37720639-507386c0-2ced-11e8-8a44-99b7b5fb2a9c.png)

**Comment by Phlash1989** [comment]
As far as I know, Xamarin Live Player doesn't support `System.Reflection` to this point, but Refit uses it for generating the API stubs. So it cannot work in Live Player at the moment.
There are many other APIs out there which are currently not supported for the Live Player because of similar issues.

**Comment by jamesmontemagno** [comment]
Ensure you are using the test flight version for iOS when using .NET Standard.

The Xamarin Live Player is meant as a getting started tool for mobile development and not intended to handle complex scenarios such as libraries that can not be interpreted.
