### ISSUE TITLE
ApiResponse behavior

### ISSUE THREAD

**Issue by Sbou** [reactiveui/refit#456]
Hi,

I try to use ApiResponse but I have an exception when my API doesn't return successfull response.

`Task<ApiResponse<Item>> GetItemById(string itemId);`

GetItemById API behavior:
If OK, the status code is 200 and I receive an item object.
If the item doesn't exist, the status code is 404 and the body is "Item not found".

With Refit I have an exception in 404 case because, I think, Refit try to deserialize the body to Item object even if the status code is not sucessfull.

Is it possible to have the ApiResponse with **Content** NULL and the body in **ReasonPhrase** ?

Thanks,

**Comment by totht91** [comment]
That's interesting. Does Refit support different reponse types for different status codes? eg. it's a common pattern that 400 errors give validation errors in the body to the user.

**Comment by bennor** [comment]
If the response from the server is an error status code, Refit will throw an `ApiException`. You can deserialize the content of the error with `ApiException.GetContentAs<T>()`.

**Comment by onovotny** [comment]
Closing as fixed
