### ISSUE TITLE
Xml / DataSet as return type?

### ISSUE THREAD

**Issue by SWarnberg** [reactiveui/refit#458]
Hi,

I have a specific Action in my ASP.NET Core MVC project that need to return a DataSet. Since Json doesn't seem to be a good format for serializing/deserializing DataSets, we changed the Action to serialize the DataSet as Xml.
From client side I could use the following code to get the resulting DataSet (yes, it's currently a hack, but you get the point). Is it a correct assumption that it's not doable in Refit?

```
HttpClient proxy = new HttpClient();
...
var sqlresp = proxy.PostAsJsonAsync<string>("program/GetSqlQuery", "select * mytable").GetAwaiter().GetResult();
if (sqlresp.IsSuccessStatusCode)
  var ds = sqlresp.Content.ReadAsAsync<DataSet>().GetAwaiter().GetResult();
```

**Comment by bennor** [comment]
It's now possible to deserialize XML. See: https://github.com/reactiveui/refit#xml-content
