### ISSUE TITLE
Adding Refit to a project from source

### ISSUE THREAD

**Issue by conwid** [reactiveui/refit#461]
Hi everyone,

I would like to add Refit to a project, but not as a NuGet package, but as a source module. 
So I have a a local git repo, in it I have a solution with two projects: a netstandard2.0 class library and a console application, .net 4.7.1. I would like to use refit from the class library, and then the class library from the console application.

I added refit as a submodule to this repository in the root folder (next to the solution file), then opened my solution in VS, added the Refit project to the solution as an existing project and finally added a reference from my projects to the Refit project.

The problem is that when I start the console app, I get the exception "'ITestAPI doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project". Everything works fine if Refit is added a NuGet package.

What am I missing? I see that there are other projects in the Refit solution and build tasks specified that maybe use those dll-s... How should I set up my repo and projects for this to work?

**Comment by onovotny** [comment]
Why are you looking for a source module? That won't work for refit since it also uses an msbuild task to  generate the code required to implement the interface.

**Comment by conwid** [comment]
I need a feature that's basically described in an issue: 
https://github.com/paulcbetts/refit/issues/438

I'm thinking about possibly adding this feature myself and maybe submitting a PR later, but for now, I would like to just fiddle around and find the best way to implement it.

**Comment by onovotny** [comment]
Closing since using Refit as source won't work with the current design

**Comment by drmcclelland** [comment]
@onovotny's suggestion worked for me to step into Refit:  https://github.com/reactiveui/refit/issues/476#issuecomment-389185290
