### ISSUE TITLE
HttpClientHandler.SendAsync is internal in .NET Core 

### ISSUE THREAD

**Issue by lanierhall** [reactiveui/refit#466]
Your documentation on implementing a custom HttpClientHandler to encapsulate dynamic headers won't work for .NET Core since they made SendAsync internal, unless I'm missing something. Is there another known solution for the same encapsulation in .NET Core, and if there is, can it be added to the documentation. If not, could it be pointed out in the documentation? Thanks!

**Comment by thomaslevesque** [comment]
It's not `protected`, [it's `protected internal`](https://source.dot.net/#System.Net.Http/System/Net/Http/HttpClientHandler.Windows.cs,445), as it has always been (not just in .NET Core). So you can override `SendAsync` in a derived class.

Anyway, it would be cleaner to use composition rather than inheritance:

```csharp
class AuthenticatedHandler : DelegatingHandler
{
    private readonly Func<Task<string>> getToken;

    public AuthenticatedHandler (Func<Task<string>> getToken)
    {
        if (getToken == null) throw new ArgumentNullException(nameof(getToken));
        this.getToken = getToken;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // See if the request has an authorize header
        var auth = request.Headers.Authorization;
        if (auth != null)
        {
            var token = await getToken().ConfigureAwait(false);
            request.Headers.Authorization = new AuthenticationHeaderValue(auth.Scheme, token);
        }

        return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
    }
}

var innerHandler = new HttpClientHandler() { BaseAddress = new Uri("https://the.end.point/") };
var handler = new AuthenticatedHandler(GetToken) { InnerHandler = innerHandler };
var client = new HttpClient(handler);
var api = RestService.For<IMyRestService>(client);

```

**Comment by benjaminhowarth1** [comment]
Recommend closing as documented behaviour.
