### ISSUE TITLE
Error trying to add Refit 

### ISSUE THREAD

**Issue by 4gDad** [reactiveui/refit#472]
I'm running VisualStudio 2017 Mac 
When I try and add the Refit nuget I am getting the following error.
Could not find file "/Users/development/Google Drive/Work/myApp.xApp/nugetpackages/runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl/4.3.2/runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.nuspec"

**Comment by onovotny** [comment]
Please raise an issue with VSfM. Doesn't appear to be related to Refit.
