### ISSUE TITLE
Update to latest Roslyn bits

### ISSUE THREAD

**Issue by onovotny** [reactiveui/refit#473]
Needed to ensure we don't break while parsing.

**Comment by wind-rider** [comment]
I'm getting exceptions like
```
Newtonsoft.Json.JsonReaderException: Input string '7.0' is not a valid integer.
```

(my API gives a correct response "7" which I try to parse as an int but somehow this gets replaced by 7.0 which makes Json.Net crash)

Is this what this issue is about?
