### ISSUE TITLE
Refit HTTP method attribute Error

### ISSUE THREAD

**Issue by 4gDad** [reactiveui/refit#474]
"IDveClient doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project."

**Comment by 4gDad** [comment]
I only get this with the 4.3.0 version 4.2.0 works just fine.

**Comment by Styxxy** [comment]
Code sample?

**Comment by clairernovotny** [comment]
Please try v6.0-preview.84 and file bugs as you come across them.
