### ISSUE TITLE
Strange issue with integer vs decimal

### ISSUE THREAD

**Issue by wind-rider** [reactiveui/refit#476]
I'm using Refit 4.3.0 in a Xamarin Forms on iOS project.

My API returns the following response (using Safari inspector):
```
{
    "FreeSpots": 8,
    "TotalSpots": 244,
    "PercentageFreeSpots": 3.278688524590164
}
```
(free spots and total spots are both `integer` types, which is correct)

However in Refit I get the following response when declaring the response as a string:
```
{
    "FreeSpots": 8.0,
    "TotalSpots": 244,
    "PercentageFreeSpots": 3.278688524590164
}
```
(free spots incorrectly show up as a decimal value, but total spots is an `integer`, which is weird - why does something modify free spots and not total spots?)

When I try to parse this to an object, I get an exception from Json.Net:

```
Newtonsoft.Json.JsonReaderException: Input string '8.0' is not a valid integer. Path 'FreeSpots', line 1, position 16.
```

Unfortunately I can't debug into the source of Refit (in https://github.com/reactiveui/refit/issues/461 it is said that you can't add Refit as a source). Does this sound familiar to any of you?

**Comment by bennor** [comment]
When you declare a response as a string, we pass the response body back unmodified. Is it possible your API is sending results back differently based on the presence or absence of a particular header? If you make a request to your API using curl, Postman or even an `HttpClient` in a console app, what do you get?

This seems like a server problem.

This seems like a server problem.

**Comment by wind-rider** [comment]
@bennor yes I thought the same, really weird case. I'll look into it further.

@onovotny thank you for pointing that feature out! I didn't know it existed! 😮
