### ISSUE TITLE
Support for vb.net/f#/c++/cli project

### ISSUE THREAD

**Issue by xljiulang** [reactiveui/refit#478]
Replacing Mono.cecli  with Microsoft.CodeAnalysis.CSharp, and injecting IL code after compilation

**Comment by onovotny** [comment]
We cannot inject IL code since that does not work on AOT systems like iOS. We need compile-time code generation.

This could still work but we need someone to add appropriate templates for this and update the build task to use the right one.

**Comment by bennor** [comment]
Could be a bit more complicated than that for anything other than VB.NET though. I'm no Roslyn expert but I thought it only analysed C# and VB.NET.

**Comment by clairernovotny** [comment]
Closing due to age. Workaround is to put Refit interface into a C# project and reference it from other places you want to use it.
