### ISSUE TITLE
Update github page description (url)

### ISSUE THREAD

**Issue by Styxxy** [reactiveui/refit#483]
Hi,
Maybe update the description : the specified url http://paulcbetts.github.io/refit/ doesn't exist anymore; I believe it should be http://reactiveui.github.io/refit/ now.

**Comment by bennor** [comment]
@onovotny I think it means the project description:
![image](https://user-images.githubusercontent.com/1063280/40454732-43480a9e-5f2d-11e8-8f29-0e33edb86767.png)

Even as a contributor, I can't update it. Might need to be done by the "owner" of the repo. I assume that means Paul or another ReactiveUI admin.

**Comment by onovotny** [comment]
Got it, thanks!
