### ISSUE TITLE
Add support for HttpClient MultipartItem

### ISSUE THREAD

**Issue by mjalil** [reactiveui/refit#489]
Hi Refit members,
I need to be able add `HttpContent` MultipartItem as used in [this library](https://github.com/jlucansky/Camunda.Api.Client/blob/master/Camunda.Api.Client/UserTask/IUserTaskRestService.cs#L114) :

```csharp
        [Post("/task/{id}/localVariables/{varName}/data"), Multipart]
        Task SetBinaryLocalVariable(string id, string varName, BinaryDataContent data, ValueTypeContent valueType);
```
In the example above `data` and `valueType` are inherited instances of `HttpContent`
[that library](https://github.com/jlucansky/Camunda.Api.Client) without support for `HttpContent` as MultipartItem falls back to Json serialization and causes exception. see issue [Camunda.Api.Client/#10](https://github.com/jlucansky/Camunda.Api.Client/issues/10)

**Comment by onovotny** [comment]
Merged in, thanks.
