### ISSUE TITLE
Using Refit with ASP.Net Core 2.1's HttpClientFactory

### ISSUE THREAD

**Issue by thecontrarycat** [reactiveui/refit#491]
The ASP.Net Core team have created a new way of working with HttpClient: the HttpClientFactory https://github.com/aspnet/HttpClientFactory

The idea behind `HttpClientFactory` is that you no longer need to worry about keeping singleton `HttpClient` instances around.  Instead, you can get as many instances of `HttpClient` as you like from the factory, and the underlying `HttpClientHandler` will have their lifecycles managed internally.  This ensures that the issues with `HttpClient` that added the singleton requirement such as socket exhaustion are solved, while the issues with using a singleton (such as failing to respond to DNS changes due to long-lived connections) are also handled.

Currently, to use `HttpClientFactory` with Refit you can simply new up an instance of your service with `RestService.For<T>(HttpClient)`.  However, this can lead to a performance reduction due to the way methods are cached (in a dictionary on the generated service class).

To make this work more smoothly, I propose moving the method caching out of the generated service class and adding it as a decorator around the `RequestBuilderImplementation`.  This then makes the `IRequestBuilder` separate from the generated class, enabling us to provide a new overload to `RestService.For<T>(HttpClient, IRequestBuilder)`, where the `IRequestBuilder` can be created by the caller (using `RequestBuilder.For<T>()` and kept around as a singleton.

I have the PR ready to go if you would like this feature.

**Comment by thecontrarycat** [comment]
Working commit: https://github.com/thecontrarycat/refit/commit/bf8b0f97c7fb9b9bfd6b2a118283cc8ff5432c7d

**Comment by bennor** [comment]
I think this is a good idea in theory, but do you have any measurements for the performance improvement?

**Comment by thecontrarycat** [comment]
All I've done is moved the existing caching to a different place so that people who aren't using a singleton HttpClient can benefit from it in the same way that those with a singleton HttpClient currently do.

I presume the existing caching was put there for a reason :)

**Comment by bennor** [comment]
I'm not sure when the caching was added or why. My only real concern is that we have an outstanding bug relating to concurrency (#449), and I'm not sure if that has anything to do with the existing caching. (I haven't had time to look at it yet - it may not even exist in the latest version.)

**Comment by bennor** [comment]
Other than a few minor nitpicks, the working commit looks good. I'd be happy to take the PR. Thoughts, @onovotny?

**Comment by onovotny** [comment]
Certainly happy to take a PR to utilize `IHttpClientFactory`

**Comment by thecontrarycat** [comment]
#494

**Comment by onovotny** [comment]
Implemented, thanks!
