### ISSUE TITLE
RefitStubs.g.cs showing up in unit test code coverage

### ISSUE THREAD

**Issue by gdodd1977** [reactiveui/refit#492]
How can I exclude this file if I can't manually alter it? Is there a way to add it to the runsettings file as an exclusion?

**Comment by onovotny** [comment]
Do you really want to exclude this? That does mean that you're not fully testing your app and the methods it uses....

**Comment by bennor** [comment]
Isn't it up to us to test the implementations? Code generated by a dependency should be a black box, shouldn't it?

**Comment by onovotny** [comment]
We do test the generated code. In this case though, it means that they have not written any tests that call that interface method as otherwise it'd show coverage. 

Question is where the coverage hit/miss belongs?

It's also likely possible to exclude coverage based on the source file name, depending on the tool you're using.

**Comment by bennor** [comment]
I guess we also can't add attributes that would hide from coverage because that would interfere with our coverage metrics.

Maybe we can close this then?

**Comment by onovotny** [comment]
We could figure something out if we needed. Question is what should we do?

**Comment by gdodd1977** [comment]
Why would I test generated code from a external library that should already be unit tested? All I'm using refit for is for an interface. All the actual logic is under the hood in the package that should have it's own unit tests. 

Also, to clarify, it's not calling the stubs as I do mock the interface. But code coverage gets dinged because that stub class is generated and not tested. That's the point of my question; how can we exclude that stubs class so that code coverage isn't incorrectly dinged for it.

I think the easiest answer is to change your code generation template to add the ExcludeFromCodeCoverage attribute where necessary.

**Comment by gdodd1977** [comment]
So anything on this?
