### ISSUE TITLE
Cannot open client on localhost with a port

### ISSUE THREAD

**Issue by njannink** [reactiveui/refit#506]
Hello when I try to generate a refit client for the following uri "http://localhost:5000" I get the following error: URL path must be of the form '/foo/bar/baz'

How can I get a refit client for a local running service which is very common during development/debugging?

**Comment by Cheesebaron** [comment]
Internally it just uses `BaseAddress = new Uri(hostUrl)`.

Can you describe your environment in more detail? Are you using a custom HttpClientHandler did you try provide your own `HttpClient` with `BaseAddress` set to your URL?

**Comment by njannink** [comment]
Nevermind this issue. 

The problem was in my api client I had there something like [Get("api/v2/something")] instead of [Get("/api/v2/something")]. Maybe the exception test can be improved to include the declaration with an issue so it's easier to pinpoint the problem.
