### ISSUE TITLE
Refit fails Build after upgrade to 4.6.16

### ISSUE THREAD

**Issue by amaters-easy** [reactiveui/refit#511]
Upgrading from 4.3.0 I get the following error in TeamCity:

[build] ...\.nuget\packages\refit\4.6.16\build\netstandard1.4\refit.targets(29,5): error MSB4062: The "Refit.Generator.Tasks.GenerateStubsTask" task could not be loaded from the assembly ...\.nuget\packages\refit\4.6.16\build\netstandard1.4\..\MSBuildCore20\InterfaceStubGenerator.BuildTasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

using this command: Starting: "C:\Program Files\dotnet\dotnet.exe" build SolutionFileName.sln --configuration Debug

Local machine the build works fine in Visual Studio.

**Comment by onovotny** [comment]
This is likely VS caching things. Try closing and restarting VS.

**Comment by amaters-easy** [comment]
The issue is not Visual studio. We only get the error on teamCity where we us the CLI "dotnet build" which will automatically restore all nuget packages

**Comment by SergeyKharchenko** [comment]
Had absolutely the same issue

**Comment by klowdo** [comment]
Same issue for me on VSTS

**Comment by onovotny** [comment]
Do you have a repro that can be shared? Could you have mixed versions of Refit in the solution?

**Comment by SergeyKharchenko** [comment]
@klowdo,
1. Create ConsolApp with .NetFramework 4.6.1 
2. Add Refit package via Nuget
3. Open console and run `dotnet build` command

**Comment by onovotny** [comment]
What template are you using for the console app? Is it an SDK style project or a legacy project?

**Comment by SergeyKharchenko** [comment]
The one that Visual Studio 17 provide

**Comment by onovotny** [comment]
They have both depending on what node you use to create it. Bottom line is that you cannot use `dotnet build` on non-SDK projects. You have to use `msbuild`.

You can tell by looking at the csproj file. If the top element is `Project` with an `Sdk` attribute, that's ok. Otherwise, there's tons of junk in it, it's legacy.

**Comment by SergeyKharchenko** [comment]
I don't think that Microsoft thinks that .NetFramework is legacy. Of course it is another platform (Windows only). Other dependencies works fine with `dotnet build` command on this project.

**Comment by onovotny** [comment]
It's not about .net framework being legacy. There are two project systems. Refit adds build targets and they work differently.

What kind of csproj is it?

**Comment by SergeyKharchenko** [comment]
Old one

**Comment by onovotny** [comment]
ok, so you have to use `msbuild /restore myproject.cspoj` on it. Otherwise, it's undefined and you just got lucky with `dotnet build`

**Comment by SergeyKharchenko** [comment]
I can confirm that with new format of `.csproj` file everything works. Thank you

**Comment by onovotny** [comment]
The new format is much cleaner/easier to deal with too...lots of good benefits.

**Comment by onovotny** [comment]
We've identified the cause and have a solution to this. Will be fixed in the next release later tonight.
