### ISSUE TITLE
GenerateStubsTask throws NullReferenceException if service interface is outside namespace

### ISSUE THREAD

**Issue by Rassi** [reactiveui/refit#512]
I accidentally created a RestService interface outside of a namespace and it results in the following message ```.nuget\packages\refit\4.6.16\build\netstandard1.4\refit.targets(29,5): error : Object reference not set to an instance of an object. [C:\temp\refitbug\refitbug.csproj]```

Here is a gist with a .NET Core 2.1 console app: https://gist.github.com/Rassi/39e1e0e50e291ceae8742d15a3b025a1

**Comment by Styxxy** [comment]
I submitted PR #524 to fix this.

One small note: the generated class will be placed into a namespace "AutoGenerated" + interfacename.
