### ISSUE TITLE
Missing XML comments in RefitStubs generate 1591 when XML documentation is required by the project

### ISSUE THREAD

**Issue by kyschouv** [reactiveui/refit#516]
We have some projects with the following:

```
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
```

We're trying to use Refit, but the generated public classes (in `RefitStubs.g.cs`) are missing xml comments (on at least the constructor). This is causing a compile-time error unless we disable 1591 (which we prefer not to do).

Could you either disable 1591 errors in the generated stubs file, or make sure all public methods are documented?

**Comment by bennor** [comment]
The error you mention relating to the constructor was fixed recently by #513. It will take effect when the next version is released.
