### ISSUE TITLE
Refit fails Build after upgrade to 4.6.16

### ISSUE THREAD

**Issue by ssc19940105** [reactiveui/refit#518]
ExcludeFromCodeCoverageAttribute is not found in the namespace(System.Diagnostics.CodeAnalysis)

**Comment by onovotny** [comment]
What is the target framework of the project you're using?

**Comment by ssc19940105** [comment]
The framwork is 4.6.1.

**Comment by ssc19940105** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ExcludeFromCodeCoverage' could not be found (are you missing a using directive or an assembly reference?)	BWHAPI	C:\Users\ssc19\source\repos\BWHTools\BWHAPI\obj\Debug\RefitStubs.g.cs	21	Active

**Comment by onovotny** [comment]
That has been in System.dll since .NET 4.0:
https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx

Is there anything special about your project?

**Comment by ssc19940105** [comment]
I've added syatem.dll to the project

**Comment by ssc19940105** [comment]
This is my code.You can clone from this(https://gitee.com/ssc19940105/BWHTools.git)

**Comment by ssc19940105** [comment]
You can update refit to lastest and rest it.

**Comment by ssc19940105** [comment]
I solved it by installing System.Diagnostics.Tools.

**Comment by ssc19940105** [comment]
May be caused by GAC cache errors.
