### ISSUE TITLE
Support for getting response body (JSON)

### ISSUE THREAD

**Issue by KhaledMostafaME** [reactiveui/refit#519]
Hello,

I'm using refit to post a JSON to this API and retrive a JSON too.
API: http://www.saudievents.sa/api/EventCalendar/SearchEvents

Here is the project
https://github.com/KhaledMostafaME/Tests/tree/master/DotNetCoreTest

Thanks.

**Comment by bennor** [comment]
I'm not sure there's a question here. The `ApiResponse` class you have in your example should have a type parameter that defines the class(es) you want the response deserialised into. I can't tell you what that is.

If you just want the raw response, you can have your interface return `Task<string>` to get the body content as a string, or  `Task<HttpResponseMessage>` to get the raw response message.

**Comment by KhaledMostafaME** [comment]
Thank you for checking, @bennor.

It was silly error in the `ApiResponse` the object here `public IList<Record> Record { get; set; }`
should be like this 'public IList<Record> Record**s** { get; set; }'
