### ISSUE TITLE
AliasAs and Format

### ISSUE THREAD

**Issue by aliveli186** [reactiveui/refit#520]
It would be nice to have a Fromat property for AliasAs or seperate FormatAs attribute like this:
```
[AliasAs(Name = "birthday", Format = "yyyy-MM-dd")]
public DateTime Birthday { get; set; }

```

**Comment by bennor** [comment]
There's actually already _undocumented_ support for this in a few ways.

Do you really need to format dates a special way for just that one property, because Refit already has a mechanism for controlling parameter formatting. (See: https://github.com/reactiveui/refit/blob/master/Refit/RefitSettings.cs#L29.)

You could do something like this:

```csharp
public class CustomUrlParameterFormatter : Refit.DefaultUrlParameterFormatter
{
    public override string Format(object parameterValue, ParameterInfo parameterInfo)
    {
        if(typeof(DateTime?).IsAssignableFrom(parameterInfo.ParameterType) && parameterValue != null)
        {
            return ((DateTime)parameterValue).ToString("yyyy-MM-dd"); 
        }
    }
}

// Usage
var refitSettings = new RefitSettings
{
    UrlParameterFormatter = new CustomUrlParameterFormatter()
};
var api = RestService.For<ISomeApi>("https://api.whatever.com", refitSettings);
```

Alternatively, if it's a query parameter, you can add the `[Query(Format = "yyyy-MM-dd")]` attribute.

**Comment by aliveli186** [comment]
@bennor Thank you but I need to format per property, a global formatter is nice but its too global :)

**Comment by bnserig** [comment]
I need this too.
Because sometimes its `yyyy-MM-dd` and sometimes its `yyyy-MM-dd HH:mm:ss`

**Comment by onovotny** [comment]
I’m confused about where the formatted value is being used? If it’s not in the query string or path segment, then json serialization is done with json.net and you can use whatever attributes and mechanisms it supports.

**Comment by bnserig** [comment]
In my case I use this as a parameter like this :
```
[Get("/user")]
Task<User> Get([AliasAs("last_conn")] DateTime lastconnection);
```

I just discovered Format in Query Attribute. So I use this :
```
[Get("/user")]
Task<User> Get([AliasAs("last_conn")] [Query(Format = "yyyy-MM-dd")] DateTime lastconnection);
```

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
