### ISSUE TITLE
System.MissingMethodException: Constructor on type ... error when .NET 4.6.1 project references .NET Standard 2 package

### ISSUE THREAD

**Issue by andrewchaa** [reactiveui/refit#521]
Refit on my .NET 461 project has been working well, until I've added a .NET Standard 2 nuget package, 
 [FunctionalWay](https://www.nuget.org/packages/FunctionalWay/0.6.0) to the project. Then the same code starts breaking, saying "System.MissingMethodException: Constructor on type '...AutoGeneratedIRestaurantEventApi' not found."

If I remove the .NET Standard 2 nuget package, it works well again. What should I do?

**Comment by onovotny** [comment]
Do you have a repro we can look at?

**Comment by onovotny** [comment]
Closing due to age. Please reopen with a repro.
