### ISSUE TITLE
Request object collection not serialized correctly

### ISSUE THREAD

**Issue by wozzo** [reactiveui/refit#522]
I have a search request class which has a collection which needs to be serialized as a comma delimited list, but it is currently being sent as System.String%5B%5D
```
public class Request {
    [Query(CollectionFormat.Csv)]
    public string[] Wibble { get; set; } = new string[] { "a", "b" }
}
```

the client is
```
    public interface ISearchApiClient
    {
        [Get("search")]
        Task<Response> Search(Request request);
    }
```

But the uri it ends up as is` /search?Wibble=System.String%5B%5D`. Any ideas what I'm doing wrong?

**Comment by bennor** [comment]
I'm not sure the `Query` attribute is designed to work inside request objects. It definitely works for a parameter.

**Comment by wozzo** [comment]
I still have the same issue without the `Query` attribute

**Comment by bennor** [comment]
I think you misunderstood. What I meant was that AFAIK the query attribute only works for method parameters -- not on properties of a request class.

**Comment by bennor** [comment]
If you look at `RequestBuilderImplementation.cs`, it converts request objects to querystring parameters in the `BuildQueryMap` method.

However, the only reference to `QueryAttribute` is here -- before the call to `BuildQueryMap`: https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L504

**Comment by wozzo** [comment]
The QueryAttribute is a bit of a red herring. If you have a collection on a request object it is serialized using the .ToString() implementation instead of being put onto the query string using either the CSV or Multi type options. I can reproduce with a unit test, but have yet to figure out what needs to change to fix it.

The unit test is 

```
        [Fact]
        public async Task B()
        {
            var mockHttp = new MockHttpMessageHandler();
            var settings = new RefitSettings
            {
                HttpMessageHandlerFactory = () => mockHttp
            };
            HttpRequestMessage request = null;
            mockHttp.Expect(HttpMethod.Get, "http://wibble.com/get").Respond(x =>
            {
                request = x;
                return new HttpResponseMessage(HttpStatusCode.Accepted);
            });

            var client = RestService.For<TestApi>("http://wibble.com", settings);

            var testRequest = new TestRequest
            {
                TestCollection = new List<string>()
                {
                    "A",
                    "B"
                }
            };

            // When
            await client.Get(testRequest).ConfigureAwait(false);

            // Then
            var query = request.RequestUri.Query;
            Assert.Equal("TestCollection=A,B", query);
        }
```

With the following interface and class set up as well

```
    internal interface TestApi
    {
        [Get("/get")]
        Task Get(TestRequest request);
    }

    internal class TestRequest
    {
        public ICollection<string> TestCollection { get; set; } = new List<string>();
    }
```

**Comment by bennor** [comment]
You would need to look for `QueryAttribute` when enumerating an object's properties in `BuildQueryMap`.

**Comment by wozzo** [comment]
If I change the collection type to be object[] then it will serialise using the Multi style (e.g. A=1&A=2&A=3...), so it looks like there is a bug for serialising collections where the type is known and a possible enhancement to allow using the `QueryAttribute` for properties on classes used as request objects. Does that sound right?

**Comment by davidnmbond** [comment]
I believe an object array: {"value": [ {"a": 1, "b": 2}, {"a": 3, "b": 4} ] } should be serialised into the query string as:

`?value[0].a=1&value[0].b=2&value[1].a=3&value[1].b=4`

**Comment by benjaminhowarth1** [comment]
This should be fixed in the latest (4.9.20) release on Myget. Recommend closing.

**Comment by teresaritorto** [comment]
@benjaminhowarth1 any idea when this is available via nuget?

**Comment by benjaminhowarth1** [comment]
@teresaritorto if you're comfortable with it, you can use the MyGet feed to install the "bleeding edge" release of Refit. Add this to your package repository in Visual Studio: https://www.myget.org/F/refit/api/v3/index.json

**Comment by moliver-bb** [comment]
@benjaminhowarth1 i'm only seeing 4.7.40 as the latest version in myget, is the correct version to use this fix? thanks so much!

**Comment by benjaminhowarth1** [comment]
@moliver-bb any version after 4.7.20 should have this fixed, so yes, 4.7.40 should have it. My pleasure! 🙂

**Comment by DanBiscotti** [comment]
How was this fixed? Do I add the Query attribute to the property declaration (in the request object) now? I'm still getting the .ToString() encoding as Wozzo mentioned

**Comment by kriscoleman** [comment]
same here, doesn't appear to be working on 5.0.23
