### ISSUE TITLE
'ExcludeFromCodeCoverageAttribute' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by hansmbakker** [reactiveui/refit#528]
When targeting netstandard 1.4 in a SDK style project using VS 2017 15.8 Preview 4, I get the error 
`'ExcludeFromCodeCoverageAttribute' is inaccessible due to its protection level in the generated code.` (twice).

I found https://github.com/reactiveui/refit/issues/518, but that is targeting netframework 4.6.1 instead of netstandard 1.4.

I deleted the `obj` and `bin` folders, rebuilt the project, restarted Visual Studio, but it doesn't help.

When searching on https://docs.microsoft.com/nl-nl/dotnet/api/?view=netstandard-1.4&term=ExcludeFromCodeCoverageAttribute, it doesn't list it as an available attribute.

Refit says to support netstandard 1.4, though.

The build output is:

```
1>C:\Program Files\dotnet\sdk\2.1.400-preview-009063\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
1>obj\Debug\netstandard1.4\RefitStubs.g.cs(20,6,20,29): error CS0122: 'ExcludeFromCodeCoverageAttribute' is inaccessible due to its protection level
1>obj\Debug\netstandard1.4\RefitStubs.g.cs(40,6,40,29): error CS0122: 'ExcludeFromCodeCoverageAttribute' is inaccessible due to its protection level
```

**Comment by onovotny** [comment]
We may have to revert adding `ExcludeFromCodeCoverageAttribute` entirely. We can't change the visibility to external since it can conflict with others.

The alternative is to try to pass the TFM in to the code-gen task, but that can get nasty when parsing all the variants.

**Comment by wind-rider** [comment]
You're quick!

The reason I'm trying to target 1.4 is that it is supported by build 14393 which is the lowest build supported by the freshly released [WinUI](https://docs.microsoft.com/nl-nl/uwp/toolkits/winui/) library. If I could up the minimum version to 16299 that would give me netstandard 2.0 support, but most of my colleagues are still running 15063 on their laptops..

> in October once Fall Creators Update is the lowest supported version of Windows 10
Does that also apply to [Enterprise editions of Windows 10](https://en.wikipedia.org/wiki/Windows_10_version_history#Rings)? It looks like 15063 is supported until April 9, 2019, according to that table.

**Comment by wind-rider** [comment]
My workaround is to downgrade Refit to 4.5.6.

**Comment by onovotny** [comment]
That applies to all editions of Windows 10. You can see the dates here:

https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

15063 is 1703, and it's end of support date is October 9, 2018. After then, everyone has to be on 16299 or higher, meaning everyone can use netstandard 2.0.

**Comment by wind-rider** [comment]
Yes, and there is a small writing below the table indicating that `Enterprise and Education editions for versions 1511, 1607, 1703 and 1709 will receive an additional 6 months of servicing after the end of service date.`.

**Comment by onovotny** [comment]
Fair enough, not sure I care :) Gotta pick a time sometime.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
