### ISSUE TITLE
Mentioning the PATCH HTTP verb

### ISSUE THREAD

**Issue by PaddoSwam** [reactiveui/refit#530]
I noticed that the PATCH verb is not mentioned in the documentation, however it _is_ built in.

And I also have a fix for this already: https://github.com/reactiveui/refit/pull/529

**Comment by Styxxy** [comment]
@PaddoSwam the PR is merged, you can close this issue.

If you mention fix #issue in the PR, it would have been automatically done :) .

**Comment by PaddoSwam** [comment]
I'll remember that! 👍
