### ISSUE TITLE
Need to support proxy

### ISSUE THREAD

**Issue by ssc19940105** [reactiveui/refit#533]
Need to support proxy

**Comment by bennor** [comment]
There is support for proxies by specifying your own `HttpClient` when creating an API client.

**Comment by BackDoorManUC** [comment]
Tried to use this: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/proxy-element-network-settings

But doesn't work surprisingly.

**Comment by bennor** [comment]
I'm not sure whether or not those config settings are supposed to influence the behavior of `HttpClient`, but something like this should work for you: https://stackoverflow.com/a/30605900/14451

**Comment by BackDoorManUC** [comment]
@bennor this config setting works when using `HttpClient` directly but surprisingly it doesn't work with Refit. I was looking for an easy way without changing my code to see requests in Fiddler.
