### ISSUE TITLE
BodySerializationMethod Raw mode.

### ISSUE THREAD

**Issue by agat366** [reactiveui/refit#541]
Hi!

In regards to https://github.com/reactiveui/refit/issues/329, what do you think of adding "Raw" mode for the passed data.

The issue is that in case if I need the value to be parsed as follows on the Web Api side: `[FromBody]string code`, I should define refit parameter this way `[Body(BodySerializationMethod.UrlEncoded)] Dictionary<string, object> data` and then call the endpoint like this `api.CallMyEndpoint(userId, new Dictionary<string, object>(){{"", activationCode}})`, which is neither handy nor looking nice.

If I pass something like `=theCodeValue` (this is how the only parameter body should look like) into the parameter (if it's defined like this `[Body(BodySerializationMethod.UrlEncoded)] string code`) I have (obviously) `=` encoded into the url, so .NET Web Api then can't parse it and the value is just empty on the server.

If I use `[Body] string code` it just doesn't work as well. Not sure if this is the case I should use (and it should work some way), but I still receive nothing on the server.

So, if we have BodySerializationMethod.Raw, and passing some string, it could be passed to the output fully "as is". It looks like a step aside from the goal Refit tries to achieve (the automation and abstraction of data), but the approach with `Dictionary<string, object> data` doesn't look appealing as well.

**Comment by Styxxy** [comment]
Just body should work. it will use BodySerializationMethod.Default, which is same as Json. If your parameter is string, json serialization should be skipped.

Did you check already with for example Fiddler what it actually being sent to the server?

**Comment by onovotny** [comment]
Also could be done with a custom serializer that was done in #571.
