### ISSUE TITLE
Add Custom TypedClient with Refit

### ISSUE THREAD

**Issue by kamran-pervaiz** [reactiveui/refit#542]
I am having issue when I am trying to add a custom client with Refit as I dont want httpClient. The reason to do is that I dont want my consumers to change httpclient configuration when they are consuming my refit implemented Client. Separation of concerns I guess.

I have a class CustomHttpClient which is inherited from httpClient.

```
var client = new CustomHttpClient();
            serviceCollection.AddRefitClient<IMyAPi>().AddTypedClient(sp => client).ConfigureHttpClient((serviceProvider, httpClient) =>
            {
                var options = serviceProvider.GetRequiredService<IOptions<RightslineClientOptions>>().Value;
                httpClient.BaseAddress =
                    new Uri(
                        $"{options.ApiProtocol}://{options.ApiHost}/{options.ApiVersion}");
            }).AddHttpMessageHandler<CustomHttpClientHandler>();
```

I am getting exception:

> System.InvalidOperationException: 'ValueFactory attempted to access the Value property of this instance.'

AddTypedClient adds the client as Transient which I want as Singleton. I am not sure how to tell Refit to use my CustomHttClient which should be singleton?

**Comment by lneninger** [comment]
The same here

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
