### ISSUE TITLE
Cannot deserialize when Status code is not 200

### ISSUE THREAD

**Issue by kamran-pervaiz** [reactiveui/refit#543]
I have a CustomHttpClientHandler and try/catch block but its not hitting catch for ApiException.

```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            try
            {
                request = await CreateRequest(request);
                return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
            }
            catch (Refit.ApiException ex)
            {
                throw new CustomApiHttpException("error occured while sending request.", ex);
            }
            catch (Exception ex)
            {
                throw new CustomApiHttpException("error occured while sending request.", ex);
            }
            
        }
```

I am not sure why it is not hitting catch block at all. it just fails my test and shows below description on reshaper

> Refit.ApiException : Response status code does not indicate success: 404 (Not Found).
>    at Refit.RequestBuilderImplementation`1.<>c__DisplayClass13_0`1.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in D:\a\1\s\Refit\RequestBuilderImplementation.cs:line 250
> --- End of stack trace from previous location where exception was thrown ---
>    at 

```
[Test]
public async Task GetCatalogueById_ReturnsCatalogueItemResource()
{
       var result = await client.GetCatalogueItemAsync<Brand>("doesnt exist");
       //Assertion on result
}
```
any suggestion?

**Comment by kamran-pervaiz** [comment]
update: it seems it was not the exception which was causing the issue. I am not sure what to do when Refit cannot deserialize to stated object. for example:

```
[Get("/contact/{id}")]
Task<Resource<TCharacteristics>> GetContactAsync<TCharacteristics>(string id)
    where TCharacteristics : Contact, new();
```
When status code is 404 e.g. it Tries to deserialize in Resource and fails. Could you please suggest if there is a way to handle or send null response back to consumer?

**Comment by Veikedo** [comment]
@kamran-pervaiz use ApiResponse<T>

**Comment by kamran-pervaiz** [comment]
@Veikedo could you please elaborate a bit more what do you mean by ApiResponse<T> ?

**Comment by Veikedo** [comment]
@kamran-pervaiz ah, you can actually just override JsonSerializerSettings. ie

     return RestService.For<T>(httpClient, new RefitSettings
      {
        JsonSerializerSettings = new JsonSerializerSettings
        {
          Error = (sender, args) => args.ErrorContext.Handled = true,
          ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
          NullValueHandling = NullValueHandling.Ignore,
          TypeNameHandling = TypeNameHandling.None
        }
      });

**Comment by Veikedo** [comment]
also there is related issue #537

**Comment by Abdulsametileri** [comment]
is there any update? I met this problem. I havent been find a way to deal with it..

**Comment by kamran-pervaiz** [comment]
@Abdulsametileri as @Veikedo suggested you will have to use ApiResponse class for example:

`Task<ApiResponse<YourClass>> Get(string input);`

you can also use ApiResponse in parameter

`private static void Method(ApiResponse<YourClass> creds) {}`

you can also write a Handler to check the response...I hope it helps
