### ISSUE TITLE
A base above ApiResponse<T> so we can extend collections of responses

### ISSUE THREAD

**Issue by lukepuplett** [reactiveui/refit#545]
Hello all,

I'd like to extend a collection of API response objects but given that they're generic `ApiResponse<T>` I can't. I can write the extension method but if each response has a different `T` then I can't use it.

If all the properties except `Content` were moved to a base `IResponseInformation` or something, then I think I could extend a collection of them, like so:

```
public static string CombineETags(this IEnumerable<IResponseInformation> responses) { ... }
```

```
var combinedETag = (new [] { r1, r2, r3 }).CombineETags();
```

Thoughts?

**Comment by lukepuplett** [comment]
Just adding for clarity. All properties except `T Content` could be extracted into an interface which would allow extensions.

Or those properties could go on a base class leaving `T Content`.

    public class ApiResponse<T> : ResponseInformation

Though an interface would suffice.

**Comment by clairernovotny** [comment]
Closing due to age.
