### ISSUE TITLE
How to Verify Refit API is supporting TLS 1.2 

### ISSUE THREAD

**Issue by venkatkancheti** [reactiveui/refit#551]
Hi Team,

I have changed the Settings of my mobile app to support TLS 1.2 as per the documentation mentioned below.

https://blog.xamarin.com/securing-web-requests-with-tls-1-2/

Please let me know whether Refit supports TLS 1.2 migration?
if yes can i know can we verify the same.

Thanks
Venkat K

**Comment by bennor** [comment]
That should work. You can provide a custom `HttpClientHandler` to an `HttpClient` and pass that to `RestService.For()`.

**Comment by venkatkancheti** [comment]
Hi @bennor, 

Thanks for the quick reply.

If we call the below without creating new custom HttpClient handler will it support the same.
In Android added Dependency service:

**In Android Project:**
  HttpClient httpClient = new HttpClient(new AndroidClientHandler()) { BaseAddress =  new Uri(url) } ;

**In PCL Call:**
  HttpClient client = await DependencyService.Get<IHttpClientHandler>().GetHttpClient(ApiUrl);

Thanks
Venkat K

**Comment by Cheesebaron** [comment]
Newer versions of Refit require you to upgrade your library to NET Standard.

Refit doesn't manage anything in regards to TLS 1.2, it is merely calling HttpClient. Hence, this is up to the HttpClientHandler used.

If you are using AndroidClientHandler, it should work.
