### ISSUE TITLE
How I can get the Current Request URL of the RestService/Response

### ISSUE THREAD

**Issue by KhaledMostafaME** [reactiveui/refit#555]
Hello,

I need to get the request/response URL after making the request.
var apiResponse = RestService.For<ILibyaAPI>(ip);
var result = await apiResponse.GetMainParents();

**Comment by bennor** [comment]
If you use `ApiResponse`, I think it's available on the request message.

**Comment by KhaledMostafaME** [comment]
Thanks, that worked. 
Another thing, is there any way to get if before making the request? 
Because I need to cache the request is cached or not before doing it.

**Comment by bennor** [comment]
Probably your best bet there is to write a custom [`DelegatingHandler`](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers) and use that when you create an `HttpClient`:

```csharp
public class CachingHandler : DelegatingHandler
{
    public CachingHandler(HttpMessageHandler innerHandler) : base(innerHandler) { }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // Your caching logic goes here
        return base.SendAsync(request, cancellationToken);
    }
}

// Usage
var cachingHandler = new CachingHandler(new HttpClientHandler());
var client = new HttpClient(cachingHandler)
{
    BaseAddress = new Uri("http://somewhere.com")
};
var api = RestService.For<IYourApi>(client);
```
