### ISSUE TITLE
Add hook for exception handling and transforming?

### ISSUE THREAD

**Issue by ChristianSauer** [reactiveui/refit#562]
Hi,
I am using Refit a lot, and noticed a pattern in my libraries which I dislike:

1. Use Refit
2. Notice that exceptions need to be handled somewhat differently than Refits generic mechanism (e.g. instead of throwing a generic ApiException throw an UnauthorizedAccessException if the StatusCode is a 401 or 403).
3. Write a wrapper interface around refit to statisfy #2

While this is not a large amount of code, it is annoying to write. 
Would it be possible to add some attributes to Refit which can be used to instpect a Response and transform it, if necessary?

e.g.

` [Post("/api/v1")]
 [OnException(ExceptionHandlingMethod)]

   Task<Model> CreateAsync([Header("Authorization")] string authorization, [Body] CreateModel);
`

**Comment by czeslav87** [comment]
+1
Similar to the issue i've just commented https://github.com/reactiveui/refit/pull/375#issuecomment-444378703
It'd be great to apply custom NonHttpSuccess handler. From my point of view, it'd be superb if Refit implementation of the client interface would allow us to use it as any other interface without having to worry about "hey - it's a refit implementation so if i want to handle non 2** responses i need to catch ApiException"

**Comment by alrz** [comment]
Unfortunately, this can't capture deserialization failures because technically that's not part of the request.
