### ISSUE TITLE
HttpClient should be reused in .Net framework

### ISSUE THREAD

**Issue by jvtroyen** [reactiveui/refit#567]
I'm experiencing performance issues when using a 3rd party library, based on Refit, in .Net 461

The problem I experience has to do with the following line of code in the RestService class.

var client = new HttpClient(innerHandler ?? new HttpClientHandler()) { BaseAddress = new Uri(hostUrl) };

.Net framework doesn't like this. HttpClient should be reused, can even be static.
If I replace the code with a static HttpClient, the problem goes away entirely (more extensive testing will follow). Has this issue been raised before?

**Comment by onovotny** [comment]
This issue isn't specific to Refit. It's one of the reasons `IHttpClientFactory` exists. It's also the reason Refit gives you the option to supply your own client instance. There can be some subtle downsides to reusing a static instance and so the default does not.

I'd say this is working as-designed for now.

**Comment by jvtroyen** [comment]
You are correct. Refit allows providing your own httpClient.
Unfortunately, the 3rd party dll (Umbraco.Headless.Client) is not open source and I cannot modify it's use of Refit.
I will let them know my findings on the matter.

Thank you
