### ISSUE TITLE
StreamPart disposed on retry

### ISSUE THREAD

**Issue by iamsap** [reactiveui/refit#569]
I'm trying to use Refit with Polly.  It works great except when I want to retry a multipart message with ```StreamPart```.  If I'm not mistaken it seems that my request streams are being disposed on ```finally``` (see attachment).  I can get around these by saving a copy of the data for retry and creating a new ```StreamPart``` each time.  

Do you have a better suggestion?  Could we instruct the client not to dispose of the StreamPart?  Thoughts?

![2018-10-15_14-44-17](https://user-images.githubusercontent.com/3976090/46974897-dc9ad900-d08a-11e8-8635-17416581e66d.png)

**Comment by e-tobi** [comment]
You can create a wrapper for your stream, which does not dispose the wrapped stream.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
