### ISSUE TITLE
How do you debug against refit?

### ISSUE THREAD

**Issue by DerekSMorin** [reactiveui/refit#572]
Let's say I want to build refit locally and debug with it.

How should I set up the references?

I'm getting:

System.InvalidOperationException
  HResult=0x80131509
  Message=IOptramRS doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
  Source=Refit

I tried to just add a reference to:

C:\Users\Derek.Morin\Source\Repos\refit\Refit\bin\Debug\net461\Refit.dll

If I use the nuget package things work.

**Comment by drmcclelland** [comment]
@onovotny's suggestion worked for me:  https://github.com/reactiveui/refit/issues/476#issuecomment-389185290

**Comment by benjaminhowarth1** [comment]
@onovotny recommend close
