### ISSUE TITLE
AddRefitClient ignores JsonSerializer?

### ISSUE THREAD

**Issue by ChristianSauer** [reactiveui/refit#574]
Just stumbled on this:

Given this API response:

```
{
"message": "something funny",
"unknown_image_names": ["a", "b", "c"]
}
```

I tried to use refit to deserialize this json using this POCO

```
    [DataContract]
    public class AppNotFound
    {
        [DataMember]
        [Required]
        public string Message { get; set; }

       // [DataMember(Name = "unknown_image_names")]
        [Required]
        public List<string> UnknownImageNames { get; set; }

        public AppNotFound()
        {
            
        }

        public AppNotFound(AppsNotFoundException e)
        {
            Message = e.Message;
            UnknownImageNames = e.UnknownImageNames;
        }

        public override string ToString()
        {
            return $"{Message} - {string.Join(", ", UnknownImageNames)}";
        }
    }
```

The client was configured like this:

```
            var snakeCaseDeserializer = new RefitSettings
            {
                JsonSerializerSettings = new JsonSerializerSettings
                {
                    ContractResolver = new DefaultContractResolver()
                    {
                        NamingStrategy = new SnakeCaseNamingStrategy()
                    }
                }
                
            };

            services.AddRefitClient<IMyApi>(snakeCaseDeserializer)
                .ConfigureHttpClient(c => c.BaseAddress = new Uri(apiUrl));

```

I would have expected that the SnakeCaseDeserializer is used, but the Field was null, so I think the serializer is ignored?

**Comment by benjaminhowarth1** [comment]
Hey @ChristianSauer:
1) can you provide a sample project (code & dependencies) that demonstrates the flaw?
2) have you upgraded to the latest Refit library?
3) pending #2, is this still an issue?

**Comment by bennor** [comment]
Could be due to this:

> Note that some of the properties of `RefitSettings` will be ignored because the `HttpClient` and `HttpClientHandlers` will be managed by the `HttpClientFactory` instead of Refit.

From https://github.com/reactiveui/refit#using-httpclientfactory

**Comment by clairernovotny** [comment]
Is this still an issue? The serializer should be configurable via the AddRefitClient.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
