### ISSUE TITLE
Header Parameter - we can not add a query parameter as header #bug

### ISSUE THREAD

**Issue by drioemgaoin** [reactiveui/refit#575]
**Context**

I want to add the id in a specific header which will be consumed by a middleware (.net core) to add it automatically in my log. Here the interface I built

[Get("/{id}")]
Task<string> Get([Header("X-Id")] Guid id);

**Resultat**
The X-Id header is not added. After some testing, I realised I can't add a parameter in the header that is a part of the endpoint path (here id is a part of the endpoint path)

**Workaround**
[Get("/{id}")]
Task<string> Get([Header("X-Id")] Guid xId, Guid id);

Even If I have a workaround, can you fix this issue?

Thank you

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
