### ISSUE TITLE
Upload image with object

### ISSUE THREAD

**Issue by angelru** [reactiveui/refit#576]
Hello,

I have my web api: 

`public async Task<IActionResult> UploadBlobFeed([FromForm] BlobFeed blob)`

The class BlobFeed have IFormFile and other properties.

In xamarin forms with Refit I do:

`Task UploadPhoto(BlobFeed Blob);`

I have the some class BlobFeed, Stream and other properties.

How I use Refit for upload photo with other properties the object for example: age, name, etc...

Thanks.

**Comment by Styxxy** [comment]
Did you try following? https://github.com/reactiveui/refit#multipart-uploads

**Comment by angelru** [comment]
Finally, Upload the photo in base64 format.
