### ISSUE TITLE
ApiResponse<T> don't expose response content headers (HttpContentHeaders)

### ISSUE THREAD

**Issue by gcelet** [reactiveui/refit#577]
Hi,

ApiResponse<T> exposes response headers (HttpResponseHeaders HttpResponseMessage.Headers) but don't expose response content headers (HttpContentHeaders HttpResponseMessage.Content.Headers).

I'm using Refit to call an api which use the header "Content-Range" for paginated result.

The header "Content-Range" is expose via HttpResponseMessage.Content.Headers.

I can use response content header when using HttpResponseMessage as return type from my refit interface.
But i can't access response content header when using ApiResponse<T> as return type from my refit interface.

The change can be something like that:

```csharp
// ...
namespace Refit
{
    // ...
    public sealed class ApiResponse<T> : IDisposable
    {
    // ...
        public HttpResponseHeaders Headers => response.Headers;

        public HttpContentHeaders ContentHeaders => response.Content?.Headers;
    // ...
    }
}
```

Any thoughts on this change ?

**Comment by Styxxy** [comment]
I opened PR #580 to add this feature.
