### ISSUE TITLE
ValidationException namespace not found

### ISSUE THREAD

**Issue by oooolivierrrr** [reactiveui/refit#582]
Using the current version, ValidationApiException is not found.

            try
            {
                var games = await gameController.GetAllAsync();
            }
            catch (ValidationApiException validationException)
            {
                // handle validation here by using validationException.Content, 
                // which is type of ProblemDetails according to RFC 7807
            }
            catch (ApiException exception)
            {
                // other exception handling
            }

**Comment by Styxxy** [comment]
ValidationApiException is not yet available in the package on Nuget. If you would like to use this, use the latest (>= 4.6.56) from the MyGet feed.

@onovotny Possibility to push latest version to nuget.org?

**Comment by Styxxy** [comment]
Also see #583

**Comment by Styxxy** [comment]
New version 4.6.58 has been published to Nuget. You can update to tgat version ;-).

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
