### ISSUE TITLE
Ability to update BaseAddress in controller

### ISSUE THREAD

**Issue by SujitGokhale** [reactiveui/refit#588]
Hi,

We are following "multi-single-tenancy" architecture wherein multiple back-end ASP.NET Core Web API service instances are stood up for each tenant having same code base. We have a multiplexer front-end ASP.NET Core application invoking  back-end services based on tenant specific request. The way we are calling back-end services from front-end app using HttpClientFactory like below - 

//Startup.cs
services.AddHttpClient<ITenantApiClient, TenantApiClient>(o => o.BaseAddress = new Uri(Configuration["TenantApiUri"]))
                .SetHandlerLifetime(TimeSpan.FromMinutes(5))
                .AddPolicyHandler(GetRetryPolicy());

//ITenantApiClient.cs
public interface ITenantApiClient
    {
        Task<long> GetCount(string tenant, string view);
    }

//TenantApiClient.cs
    public class TenantApiClient
    {
        private readonly HttpClient client;

        public TenantApiClient(HttpClient httpClient)
        {
            client = httpClient;
        }

        public async Task<long> GetCount(string tenant, string view)
        {
            long count = 0;

           HttpResponseMessage response = await client.GetAsync($"{GetTenantBaseUri(tenant)}/api/count/{view}");
            if (response.Content != null)
            {
                count = await response.Content.ReadAsAsync<long>();
            }

            return count;
        }
        private string GetTenantBaseUri(string tenant)
        {
            return string.Format(client.BaseAddress.ToString(), tenant);
        }
    }

As you could see switching to Refit is going to be great, but with Refit, we are not able to figure out a way to update BaseAddress in controller run (like we are changing it above) once it is set in Startup.cs. Would you please help?

services.AddRefitClient<ITenantApiClient>()
                .ConfigureHttpClient(c => c.BaseAddress = new Uri(Configuration["TenantApiUri"]))
                .SetHandlerLifetime(TimeSpan.FromMinutes(5))
                .AddPolicyHandler(GetRetryPolicy());

**Comment by Bartmax** [comment]
you can create 2 clients:
```c#
var tenant1Client = services
    .AddRefitClient<IApiClient>()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("tenant1.myapi.com"));
var tenant2Client = services
    .AddRefitClient<IApiClient>()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("tenant2.myapi.com"));
```

**Comment by benjaminhowarth1** [comment]
@onovotny please close
