### ISSUE TITLE
Usage of AuthorizeAttribute

### ISSUE THREAD

**Issue by marshal-nash** [reactiveui/refit#593]
Hello, it seems there is a problem using the AuthorizeAttribute which inherits from HeaderAttribute.

Whenever I try to use it, the authorization header is not set.

From what I understand, it looks like it is because of the ": {scheme}" in the name part of the header that it is not added to the request.

**Comment by natelaff** [comment]
Confused on this too. Did you ever get it to work?

**Comment by marshal-nash** [comment]
It's been some time, but I think I used a workaround by adding a custom attribute and a custom HttpMessageHandler to add the authorization header.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
