### ISSUE TITLE
"doesn't look like a Refit interface" when inheriting from another interface

### ISSUE THREAD

**Issue by davidnmbond** [reactiveui/refit#595]
The following interface "doesn't look like a Refit interface", I expect because it inherits from another interface:

`
    using Company.Product.Data;
    using Refit;

    namespace Company.Product.Api.Common.Interfaces
    {
       [Headers("Authorization: Bearer")]
       public interface IConnectionApi : ICrudApi<Connection>
       {
       }

        [Headers("Authorization: Bearer")]
        public interface ICrudApi<T> where T : IdentifiedItem
        {
            [Post("")]
            Task<int> Create([Body] T item);
    
            [Get("")]
            Task<IQueryResponse<T>> GetPage([Query(".", "search")] IQueryRequest pageQuery);

            [Get("/{id}")]
            Task<T> Get(int id);

            [Put("")]
            Task Update(T item);

            [Delete("/{id}")]
            Task Delete(int id);
        }
    }
`

**Comment by wocar** [comment]
+1

**Comment by ahmedalejo** [comment]
@davidnmbond Interface inheritance isn´t currently supported

but a pull request exist waiting for merge https://github.com/reactiveui/refit/pull/523

including other issue #176

**Comment by Sergio0694** [comment]
This was just implemented in #633 - so this can be closed 😄

**Comment by wocar** [comment]
Aré generics supported in this implementation?

**Comment by Sergio0694** [comment]
@wocar I'll be completely honest, so far I've just made sure this worked fine with non-generic interfaces, but you can clone `master` and give it a try.
If there are any problems you can open another issue and we can take it from there 👍
