### ISSUE TITLE
Large multipart uploads time out

### ISSUE THREAD

**Issue by Flohack74** [reactiveui/refit#596]
Hi,
we currently try to uploadf files up to 900MB. If the virtual machine behind the server side is slow, this takes longer than the default 100 seconds of what HttpClient is using.

I also think the misconception in .NET is that this timeout is not reset as long as the server is accepting data. You cannot fix HttpClient, but since you are wrapping it so nicely, maybe you can take a look into this reading: https://www.thomaslevesque.com/2014/01/14/tackling-timeout-issues-when-uploading-large-files-with-httpwebrequest/ - since you are fully asynchronous, can you elaborate on this part of the article:
```
In the case of asynchronous requests, the client application implements its own time-out mechanism. Refer to the example in the BeginGetResponse method.

So, a solution could be to to use these methods directly (or the new Task-based versions: GetRequestStreamAsync and GetResponseAsync)
```
Will it be possible to have a sliding ttl/timeout so larger uploads can run for minutes or even hours if necessary?

BR Florian

**Comment by ahmedalejo** [comment]
You can accomplish your need by using a `HttpClient` and setting it´s `Timeout` property.

```csharp
var httpClient = new HttpClient 
{ 
    BaseAddress = new Uri("https://the.end.point/"), 
    Timeout = TimeSpan.FromDays(24) //how long do you need?
};
RestService.For<IMyLargeUploadRestService>(httpClient);
```

But if you intend on handling connection loss and re-connection then you´d to dig deeper, using server side logic with a [`HttpClientHandler`](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers), `DelegatingHandler` to be more specific.

**Comment by Flohack74** [comment]
Thanks for the reply. I am not sure if this timeout will help me, since it still cannot distinguish between a) the endpoint could not be reached b) the data is uploading fine but it just takes longer. I think its not so much about reconnecting a lost connection, but rather do not timeout as long as data is flowing properly.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
