### ISSUE TITLE
Can I use complex types for GET actions?

### ISSUE THREAD

**Issue by nicholasyin** [reactiveui/refit#597]
For example, I could have a base SearchModel and quite a few [DomainObject]SearchModel that I want to be used in search operations that are all GET method. I'd like to have the service to automatic convert any object to a query-string representation so that in the interface method I only need to pass in the model object, instead of all primitive parameters, which is not quite extensible.

So, is this supported or not?

**Comment by ahmedalejo** [comment]
**First of all**: Yes it is supported out of box.

Reading the documentation will help you further:
[Dynamic Querystring Parameters](https://github.com/reactiveui/refit#dynamic-querystring-parameters)

>```csharp
>public class MyQueryParams
>{
>    [AliasAs("order")]
>    public string SortOrder { get; set; }
>
>    public int Limit { get; set; }
>}
>...
>[Get("/group/{id}/users")]
>Task<List<User>> GroupList([AliasAs("id")] int groupId, MyQueryParams params);
>
>[Get("/group/{id}/users")]
>Task<List<User>> GroupListWithAttribute([AliasAs("id")] int groupId, [Query(".","search")] MyQueryParams params);
>
>
>params.SortOrder = "desc";
>params.Limit = 10;
>
>GroupList(4, params)
>>>> "/group/4/users?order=desc&Limit=10"
>
>GroupListWithAttribute(4, params)
>>>> "/group/4/users?search.order=desc&search.Limit=10"
>```
**Secondly**, issues aren't meant for asking questions, but instead are for filing-in problems i.e "issues" or propose a new feature based on an "issue" that you are confronting.

**Comment by Styxxy** [comment]
@ahmedalejo Issues are sometimes a good place to ask questions about usage. This can indicate a lack of documentation or lack of good documentation (which is not this case).

**Comment by ahmedalejo** [comment]
@Styxxy cool to know

**Comment by benjaminhowarth1** [comment]
@onovotny please close
