### ISSUE TITLE
Use Refit for multiple Multiple Endpoints 

### ISSUE THREAD

**Issue by mindofai** [reactiveui/refit#600]
Hi,

I've been trying to use Refit to implement my rest service for two different endpoints (I'm using an IoC here).

![image](https://user-images.githubusercontent.com/18261468/51961168-d0e6ed00-2496-11e9-973c-d5c6ddd4d175.png)

But it seems like everytime I do this, I get a "GENERAL CONNECTION ERROR" error. Is it possible to set up multiple endpoints using Refit

**Comment by onovotny** [comment]
I'm not sure there's anything to do with Refit here. Refit is a wrapper around HttpClient, so supplying specific HttpClient instances or creating multiple instances with the factory method should work. I'd file an issue on the CoreFX repo if you think there's something with HttpClient,
