### ISSUE TITLE
Xml Content Support

### ISSUE THREAD

**Issue by ColKrumpler** [reactiveui/refit#601]
The project documentation indicates Refit currently supports XML Content:

```
`var gitHubApi = RestService.For<IXmlApi>("https://www.w3.org/XML",
    new RefitSettings {
        ContentSerializer = new XmlContentSerializer()
    });
````
However, the Nuget and MyGet packages as of 4.6.58 still do not support XML Content.  Is XML Content expected to be available soon?

**Comment by stevewgh** [comment]
4.6.68 contains XML support but it is only available on the MyGet feed at the moment.

It needs admin support to promote it. @onovotny are you able to do this?

**Comment by onovotny** [comment]
I'll get published in the next few days.

**Comment by onovotny** [comment]
Latest NuGet version has these changes.
