### ISSUE TITLE
Refit throwing exception on 404 response

### ISSUE THREAD

**Issue by fatagun** [reactiveui/refit#604]
We are using refit for all our client for a very large project.

I have researched on the questions and found out that refit throws exception on 404 responses. I have to do the following
```
            try
            {
                var something = _client.GetSomethingAsync();
            }
            catch (Refit.ApiException exc)
            {
                _logger?.LogError($"ErrCode : {exc.ReasonPhrase}");  
            }
            catch (Exception exc)
            {
                _logger?.LogError($"ErrCode : {exc}");
            }
```

Is it possible not to throw exception? How can I handle 400, or 500 status codes without throwing exceptions?

**Comment by bennor** [comment]
Change your method's return type from `Task<Whatever>` to `Task<ApiResponse<Whatever>>`. Then you can check the status code yourself.
