### ISSUE TITLE
PreserveAttribute Could not be found

### ISSUE THREAD

**Issue by Darlingtone** [reactiveui/refit#609]
After adding Refit (v4.6.58) to my Xamarin project I got the following error

`The type or namespace name 'RefitInternalGenerated' does not exist in the namespace 'AppNamespace' (are you missing an assembly reference?)`

and 

`The type or namespace name 'PreserveAttribute' could not be found (are you missing a using directive or an assembly reference?)`

the error were flagged in **RefitStubs.g.cs** when I opened the file VS suggests that I add using **global::Gatelog.RefitInternalGenerated;** instead of using **Gatelog.RefitInternalGenerated;** that was originally added 

Add  using **global::Gatelog.RefitInternalGenerated;** makes the error go way, but then the file is regenerated on compilation 

Am using **.Net Standard v2.0.3** any solution?

**Comment by Darlingtone** [comment]
Resolved!!

The problem was I renamed my project in VS, and VS changed the default namespace for the project, when the **RefitStubs.g.cs** is generated the default namespace was used and broken the reference to the class for which the Stub is been generated which is using the _(desired)_ namespace when the project was originally created.

It would've been nice if the code generator for the RefitStubs uses the namespace as contained in the class in which the stub is been generated rather than VB default namespace

**Comment by nvchernov** [comment]
I have case when my class has same name with namespace

```csharp
namespace TestService
{
    public class TestService
    {
         //....
    }

}
```
Do not do like me : )
