### ISSUE TITLE
Refit ignores the EnumMember attribute in IEnumerable parameters

### ISSUE THREAD

**Issue by Sergio0694** [reactiveui/refit#618]
This is probably related with #587, and possibly with #459 and #502.
The `EnumMember` attribute is not used when the enum in question is used as an `IEnumerable<T>` parameter to a Refit method.
Here's an example:

```csharp
public enum TestEnum
{
    [EnumMember(Value = "bla")]
    BLA
}

public interface IService
{
    [Get("/foo")]
    Task FooAsync([Query(CollectionFormat.Csv)] TestEnum values);
}
```
This results in:
```csharp
FooAsync(new[] { TestEnum.BLA, TestEnum.BLA });
>>> /foo?values=BLA%2CBLA
```
Instead of `/foo?values=bla%2Cbla`.

**Comment by benjaminhowarth1** [comment]
I'll pick this up.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
