### ISSUE TITLE
MethodNotFoundException with .NET Framework and custom HttpClient

### ISSUE THREAD

**Issue by Flohack74** [reactiveui/refit#620]
Hello,

this is similar to https://github.com/reactiveui/refit/issues/441 ...

we got the following code:
```
        private T CreateRefitClientFor<T>(string serviceUrl, int timeout = 10) {
            return RestService.For<T>(new HttpClient 
            {
                    BaseAddress = new Uri(serviceUrl),
                    Timeout = TimeSpan.FromSeconds(timeout)
            });
        }
```
and this error out of it:
```
[0] 13:35:29: System.MissingMethodException: Method not found: 'System.__Canon Refit.RestService.For(System.Net.Http.HttpClient)'.
   at Base.Attachments.FileHandling.FileServiceClient.CreateRefitClientFor[T](String serviceUrl, Int32 timeout)
```
This happens not on all machines it seems but it is fixed by adding an assembly binding redirect:
```
        <dependentAssembly>
            <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
        </dependentAssembly>
```
It seems that for some reason sometimes the old Http client is being used, and obviously misses a method. Can you elaborate why
a) in nuspec file there is this (lines removed to make it shorter):
```
<group targetFramework=".NETFramework4.6.1">
      </group>
      <group targetFramework=".NETStandard1.4">
        <dependency id="System.Net.Http" version="4.3.3" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0">
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.6.1" />
    </frameworkAssemblies>
```
b) if removing the framework assembly statement and instead copying the one from .NET standard 1.4 to framework 4.6.1 above would help fixing the issue? We want to avoid static assembly binding redirects by all chance since they are hard to maintain in a multi-exe/app solution with nearly 400 csproj files.

**Comment by onovotny** [comment]
Refit is multi-targeted and does not use the `System.Net.HttpClient` package when targeting the .NET Framework. 

It's likely some other package is pulling that in instead and is causing the binding redirect issue.
