### ISSUE TITLE
Issue sending string and stream in MultiPart request.

### ISSUE THREAD

**Issue by alec-lieberman-ef** [reactiveui/refit#622]
Hello,

We are using Refit and have an endpoint definition that looks like this:

`
[Multipart]
SaveDocumentAsync(string idi, Guid courseId, [AliasAs("type")] string type, [AliasAs("file")] StreamPart stream, [Header(Headers.TraceId)] string traceId)`

We have some component tests that are using this interface and testing some internal controller endpoints. In these tests, when we debug, the string type is always coming through as null. Is there a way we can fix this or is there something we are doing wrong?

Thank you!

**Comment by VikasPawar2112** [comment]
@alec-lieberman-ef have you solved this issue? If not then please share the related code snippet and API endpoint definition.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
