### ISSUE TITLE
xml output encoding dose not follow  XmlWriterSettings encoding  setting

### ISSUE THREAD

**Issue by lhyqy5** [reactiveui/refit#625]
`XmlWriterSettings'` encoding  setting in `XmlContentSerializer`/`XmlReaderWriterSettings`  don't take effect, serialized xml `encoding` attribute always `utf-16`
```
<?xml version="1.0" encoding="utf-16"?>
<root>
</root>
```

**Comment by onovotny** [comment]
Do you have an easy repro (or can you PR a failing test that shows this behavior?
