### ISSUE TITLE
Issues with multi-targeted projects (.NET 4.6, .NET Standard 1.4, and .NET Standard 2.0)

### ISSUE THREAD

**Issue by benjaminhowarth1** [reactiveui/refit#626]
Hi folks,

If I run this against a multi-targeted project, both .NET 4.6 and .NET Standard 2.0 builds fail, no types are generated. I think this is partially because the Refit runtimes half-support .NET Standard but actually make more reference to .NET Core, a different part of the runtime standard.

I'm working on a fork now.

Related: Nustache is only supported on .NET Framework 2.0. Recommend an upgrade to https://github.com/StubbleOrg/Stubble which appears to be actively maintained, Nustache as of 2015 seems to be dormant.

**Comment by onovotny** [comment]
Do you have a repro? Multi-targeted projects should be supported.

**Comment by benjaminhowarth1** [comment]
Indeed I do: https://github.com/benjaminhowarth1/Refit.Clients/tree/develop

**Comment by benjaminhowarth1** [comment]
Closing... I'm an idiot. Forgot to upgrade my dependencies...

**Comment by benjaminhowarth1** [comment]
Also found an interesting bug as to why this fails using InterfaceStubGenerator.App.
The line "using Refit;" is required in the CS file. Interestingly, Visual Studio resolves the reference in .NET Standard without the using directive, but Refit will subsequently fail without it.

**Comment by benjaminhowarth1** [comment]
Closing as I discovered the root cause of my issue - wrong namespace calling.
