### ISSUE TITLE
Customize url/querystring serialization

### ISSUE THREAD

**Issue by carl-berg** [reactiveui/refit#64]
Hi,

I have an issue where a web UI project runs different UI cultures for different users. This has a side effect of for example DateTime being serialized differently depending on the culture. What i would like is to customize how refit serializes objects into the url/querystring. Is there any possible extension points for that, or could there be? If so, I'd be happy to provide a PR with a suggestion.

**Comment by krishire** [comment]
Somebody please tell me how to append Querystring to an URL in Refit.

[Get("/Test?query={value}]
Task<Result> GetTest(string value); But the query is getting removed.

**Comment by bennor** [comment]
You should don't need to explicitly add query parameters to the URL template. Any parameters to the method that aren't part of the URL (or body of the request) are added as querystring parameters.

This should work:

```csharp
[Get("/Test")]
Task GetTest(string value);
```

**Comment by krishire** [comment]
Many thanks Bennor, the rest api is expecting the URL in this fashion
"..api/test?query={value}. But when I call the get method with a string
parameter name as "query", the URL is not getting framed as expected with
the querystring, it just goes out as ..api/test without any querystring.
Don't know where I'm going wrong.

Thanks,
Krish.

**Comment by krishire** [comment]
Many Thanks Again Bennor, it worked. Actually there was a space left out in
the url which I didn't notice.

Thanks a lot.
Krish.

**Comment by krishire** [comment]
Hi Bennor,
Do you know how to receive a Byte[] from a Rest Api Method.Basically I'm
trying to download a PDF file. But I'm not able to get it has Byte[].

[Get("/document")]
Task<Byte[]> GetDocument(string id);

The Task.Result gives {"Unexpected character encountered while parsing
value: %. Path '', line 0, position 0."}.

**Comment by bennor** [comment]
You can use `Task<Stream>` and convert the stream to a byte array.

(The reason you're getting the error you are is that it's treating the response as JSON.)

More details here: https://github.com/paulcbetts/refit/blob/master/README.md#body-content

**Comment by krishire** [comment]
Bennor,
I tried Task<Stream> instead of Task<Byte[]> still getting the same error,
do I need to put in any declarative attributes to bypass the Json
deserialisation.

**Comment by krishire** [comment]
Bennor thanks again, got it working, instead of Task<Byte[]> got it as
Task<HttpResponseMessage> and took the StreamContent from there to convert
to Byte[].
