### ISSUE TITLE
[BUG] RefitStubs.g.cs generated by dotnet build 2.2.203 SDK cannot process nested type

### ISSUE THREAD

**Issue by lsuarez5280** [reactiveui/refit#649]
**Describe the bug**

When building using `dotnet build` with the 2.2.203 Core SDK, a RefitStubs.g.cs file is created (same file not created when building with SDK patch 102/103). The file implements a nested interface type for one of the project's Refit clients that has a response type in the signature that is likewise a nested type. The implementation incorrectly specifies that type and it cannot be found by the compiler.

> obj\Release\netcoreapp2.2\RefitStubs.g.cs(59,14): error CS0246: The type or namespace name 'DummyDto' could not be found (are you missing a using directive or an assembly reference?)
> obj\Release\netcoreapp2.2\RefitStubs.g.cs(59,68): error CS0539: 'AutoGeneratedRefitRequestProcessorTestsIRefitTestClient.GetDummyDto(Guid)' in explicit interface declaration is not a member of interface
> obj\Release\netcoreapp2.2\RefitStubs.g.cs(45,77): error CS0535: 'AutoGeneratedRefitRequestProcessorTestsIRefitTestClient' does not implement interface member 'RefitRequestProcessorTests.IRefitTestClient.GetDummyDto(Guid)'

**Steps To Reproduce**
1. Create .NET Core 2.2 app with Refit reference.
2. Created nested response type and Refit client interface in project as below.
```
public class RefitRequestProcessorTests
{
    public class DummyDto
    {
        public Guid Id { get; set; }
    }

    public interface IRefitTestClient
    {
        [Get("/DummyDto/{id}")]
        Task<DummyDto> GetDummyDto(Guid id);
    }
}
```
3. `dotnet build` application using 2.2.203 SDK.

**Additional Context**
- Sample RefitStubs.g.cs file reproduced below.
```
// <auto-generated />
using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Kpa.Services.Extensions;
using Moq;
using Refit;
using Xunit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

#pragma warning disable
namespace RefitTestApplication.RefitInternalGenerated
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {

        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
    }
}
#pragma warning restore

namespace RefitTestApplication
{
    using RefitTestApplication.RefitInternalGenerated;

    /// <inheritdoc />
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [Preserve]
    [global::System.Reflection.Obfuscation(Exclude=true)]
    partial class AutoGeneratedRefitRequestProcessorTestsIRefitTestClient : RefitRequestProcessorTests.IRefitTestClient
    {
        /// <inheritdoc />
        public HttpClient Client { get; protected set; }
        readonly IRequestBuilder requestBuilder;

        /// <inheritdoc />
        public AutoGeneratedRefitRequestProcessorTestsIRefitTestClient(HttpClient client, IRequestBuilder requestBuilder)
        {
            Client = client;
            this.requestBuilder = requestBuilder;
        }

        /// <inheritdoc />
        Task<DummyDto> RefitRequestProcessorTests.IRefitTestClient.GetDummyDto(Guid id)
        {
            var arguments = new object[] { id };
            var func = requestBuilder.BuildRestResultFuncForMethod("GetDummyDto", new Type[] { typeof(Guid) });
            return (Task<DummyDto>)func(Client, arguments);
        }
    }
}
```
- Interestingly, this is not reproducible, nor is the same file generated, after clearing bin/obj folders and building using the Visual Studio IDE which I believe has its own mechanisms for invoking MSBuild to do this work.
- I'm not saying that anything about these particular class or interface definitions are best practice, but there's a chance that this indicates potential for problems in other scenarios.

**Comment by wilsonbn** [comment]
I have found moving the following using to the top of the RefitStubs.g.cs file with the rest of the using declarations allowed my project to build. 

> using RefitTestApplication.RefitInternalGenerated;

Change made to [GeneratedInterfaceStubTemplate.mustache](https://github.com/wilsonbn/refit/commit/f2786f5d59eac2422bc78198fed861bd6e2feeb1) in my fork is what I believe needs to be changed for the file to be generated with the using declared at the top with the rest.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
