### ISSUE TITLE
[BUG] Uploading large size Stream on Android

### ISSUE THREAD

**Issue by Immons** [reactiveui/refit#655]
**Describe the bug**

When uploading large size Stream (over 100mb) on Android we get OOM.

**Steps To Reproduce**

Create API with Multipart Post and use StreamContent (with FileStream for example).

**Expected behavior**

You should get successful response, instead application is being closed due to eating too much memory.

**Environment**

- OS:        Android
- Version    8.1
- Device:    Huawei P10 Lite

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
