### ISSUE TITLE
[BUG] Method not generated when used in preprocessor condition

### ISSUE THREAD

**Issue by NGumby** [reactiveui/refit#659]
**Describe the bug**

Method is not generated in RefitStubs.g.cs when it is in a preprocessor condition

**Steps To Reproduce**

Add OLDWEB in build Compilation conditional symbols.

```
#if OLDWEB
        [Get("/cs/account/setdevicetoken")]
        Task<UserDeviceResponse> SetDeviceToken(string deviceToken, string deviceInternalId);
#endif        
```
gives this error when compiling
```
error CS0535: 'AutoGeneratedICSWebApi' does not implement interface member 'ICSWebApi.SetDeviceToken(string, string)'
```

If I remove the #if, it works fine.  

**Expected behavior**

To compile without errors

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   

VS 21019
Xamarin
Refit 4.6.107

**Additional context**

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
