### ISSUE TITLE
IDisposable Interfaces 

### ISSUE THREAD

**Issue by scharada** [reactiveui/refit#660]
using (var client = RestService.For<IInterface>(Url))
{
// code here
}

this requires the Interface to be IDisposable which makes sense , but when you make It IDisposable, it asks for a Dispose() Method..  but it's an interface .... the code generation needs to generate the appropriate Dispose call when an interface inherits from IDisposable.

**Comment by bennor** [comment]
I'm not sure it should be disposed. That would result in disposing of (or abandoning) the `HttpClient` instance it created, which [isn't the way you're supposed to work with HttpClient](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core).

Other than the HttpClient, there's nothing that really justifies disposal. What's the value here?

**Comment by BackDoorManUC** [comment]
Due to a bug: https://github.com/reactiveui/refit/issues/449 we cannot use Refit as a singleton. There's HttpClient created for every request. Might be related.
