### ISSUE TITLE
Unexpected character encountered while parsing value:

### ISSUE THREAD

**Issue by Denaindra** [reactiveui/refit#666]
**Describe the bug**

When trying to do a Get request for retrieve an image I'm suddenly getting following error (Please check attached image). here below mentioned my request. Refit version - 4.6.58

```csharp
[Get("/wer/v1/dsdfgg/image")]
Task<object> GetStaffImageDetail([AliasAs("staffNumber")] string staffNumber, [Header("Authorization")] string token);
```

**Screenshots**

**Environment**

Xamarin forms IOS

**Additional context**
![Screenshot 2019-06-04 at 9 35 26 PM](https://user-images.githubusercontent.com/20808824/58895856-801c2500-8712-11e9-9440-dab8e126a9b0.png)

**Comment by bennor** [comment]
By default, Refit will assume your response as JSON, but your image response is binary. You can fix this by changing the return type of your method to `Task<Stream>` then doing something with the stream. There's a little more info in the [Body content](https://github.com/reactiveui/refit#body-content) section of the README.

However, if you'd prefer to get a `byte[]` for your image, you can set the return type to `Task<HttpContent>`, then call `ReadAsByteArrayAsync()` on the [`HttpContent`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent?view=netframework-4.8) object.
