### ISSUE TITLE
Be less aggressive with dependency updates in core library?

### ISSUE THREAD

**Issue by martincostello** [reactiveui/refit#670]
Refit currently depends on Newtonsoft.Json 12.0.1, but this is problematic in some usage scenarios where the overall dependency graph of an application may have constraints on the version of Newtonsoft.Json that can be used.

Here's a concrete example:

I have an Azure function which consumes Refit, and part of the Azure Functions SDK has a requirement to use Newtonsoft.Json 11.0.2.

This currently makes it impossible to update Refit and pick up any bug fixes or improvements in an Azure Functions app because of the dependency defined in the Azure Functions libraries.

Here's a dependabot PR that highlights this incompatibility: https://github.com/martincostello/azure-functions/pull/34

As users are able to upgrade Newtonsoft.Json themselves in their top-level application to the latest and greatest version (or not) based on their overall application requirements, it would be better if Refit's core library used the lowest-common-denominator version of Newtonsoft.Json (and any other dependencies) if no specific features in the public API surface of these dependencies are used in Refit's own code.

For example the lowest-common-denominator version of Newtonsoft.Json for .NET Standard support is 9.0.1.

In many cases applications using Refit would be ASP.NET Core apps, which would raise the Newtonsoft.Json version to 11.0.2 (see [Microsoft.AspNetCore.JsonPatch](https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/) NuGet package).

**Comment by bennor** [comment]
I ran into this problem myself with AF recently. Will take a look.

**Comment by bennor** [comment]
As mentioned in the discussion on #671, this is really a problem with AF, and it's been logged as an [issue with the functions runtime](https://github.com/Azure/azure-functions-host/issues/4049).

In light of that, and the large number of bug fixes to Json.NET between 9.0.1 and the version we're on, we've decided to keep it the way it is.
