### ISSUE TITLE
[BUG] Refit is not generating implementations if added as an indirect reference

### ISSUE THREAD

**Issue by Elfocrash** [reactiveui/refit#686]
**Refit is not generating implementations if added as an indirect reference**

Currently I have the following scenario. I want to have a project called `Api.Client` and another one called `Api.Client.Consumer`. The `Api.Client` one is a .NET Standard 2.0 project which will refer to Refit, do some configuration and offer an extension method to allow the user to provide their own Refit API interface. The `Api.Client.Consumer` would refer to the `Api.Client` project/package and only call `AddRefitClient<T>` in their Startup.cs.

The problem i have is that, even though Refit is a reference to the `Api.Client` project (which is referred to by the `Api.Client.Consumer`), it won't generate the interface implementation unless the `Api.Client.Consumer` directly refers to the Refit nuget package too, even though it's already referred to by the `Api.Client.Consumer`.

**Expected behavior**
I would expect even non-direct referenced for Refit to run the interface building.

**Screenshots**

Generates implementations
![image](https://user-images.githubusercontent.com/8199968/59313946-eb35a080-8caa-11e9-9429-a51051ec39cf.png)

Doesn't generate implementations
![image](https://user-images.githubusercontent.com/8199968/59313984-2041f300-8cab-11e9-95be-bbe0539467df.png)

**Environment**
- OS:       Windows 10 Pro
- Version   10.0.17134
- Device:   PC

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
