### ISSUE TITLE
How to use query string to get data

### ISSUE THREAD

**Issue by jdang67** [reactiveui/refit#691]
Hi, 

I checked the documentation but could not find an easy way to get data with the existing query string

For example,  I have  the following setup
``` c#
  [Get("/something?{queryString}")]
  Task<object>SearchData([Query] string queryString);
```

the query string at runtime is dynamic .. and it throws an exception 
_Unexpected character encountered while parsing value: <. Path '', line 0, position 0._

Anything wrong with the way I use the library? Any help would be appreciated.

jdang

**Comment by anicething** [comment]
I had met  the same problem too.

**Comment by benjaminhowarth1** [comment]
Are you trying to retrieve JSON or XML data?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
