### ISSUE TITLE
How use Static + Dynamic headers

### ISSUE THREAD

**Issue by IgorStrekha** [reactiveui/refit#693]
I would like to set both a dynamic AND a static header. For this one specific call I need to set a content-type of application/json (for others, I do not), but I also need to pass a dynamic bearer token.

Is this valid and will it pass both content-type AND authorization: bearer ?

```csharp
[Headers("Content-Type: application/json")]
[Post("api/myendpoint")]
Task<bool> GetUser([Body]int id, [Header("Authorization")] string bearerToken);
```

It does not work.

**Comment by bennor** [comment]
What is it not doing that you expect it to? If a header is missing, which one?

**Comment by bennor** [comment]
Here's an example program that shows it working using https://httpbin.org/ (which responds with info about the request):

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var httpBin = RestService.For<IHttpBinApi>("https://httpbin.org");
        var response = await httpBin.Post(42, "Bearer <whatevs>");
        Console.WriteLine(response);
    }
}

[Headers("Content-Type: application/json")]
public interface IHttpBinApi
{
    [Post("/post")]
    Task<string> Post([Body]int id, [Header("Authorization")] string bearerToken);
}
```

And the output:

```powershell
C:\Users\benno_000\source\repos\ConsoleApp1\ConsoleApp1> dotnet run
{
  "args": {},
  "data": "42",
  "files": {},
  "form": {},
  "headers": {
    "Authorization": "Bearer <whatevs>",
    "Content-Length": "2",
    "Content-Type": "application/json",
    "Host": "httpbin.org"
  },
  "json": 42,
  "origin": "118.209.248.97, 118.209.248.97",
  "url": "https://httpbin.org/post"
}
```

**Comment by benjaminhowarth1** [comment]
If I'm not mistaken, it's because the [Header] attribute in OP's code is on the method, not the containing class.

**Comment by bennor** [comment]
That is different, but I wouldn't expect it to be make a difference. Class or method should work for a static header.

I'll check tomorrow to make sure.

**Comment by IgorStrekha** [comment]
Document says us:

Redefining headers
Unlike Retrofit, where headers do not overwrite each other and are all added to the request regardless of how many times the same header is defined, Refit takes a similar approach to the approach ASP.NET MVC takes with action filters — redefining a header will replace it, in the following order of precedence:

Headers attribute on the interface (lowest priority)
Headers attribute on the method
Header attribute on a method parameter (highest priority)



Example:

[Post("/users/new")]
    [Headers("X-Emoji: :metal:")]
    Task CreateUser([Body] User user, [Header("X-Emoji")] string emoji);

Result:
// X-Emoji: :trollface:
await CreateUser(user, ":trollface:");

**Comment by bennor** [comment]
@IgorStrekha I can see how that might be a bit confusing but "redefining" means redefining the same header name. `Content-Type` and `Authorization` are different headers, so the auth header won't replace the content type header. (I've shown an example of this working as expected too.)

I'll add something to the docs to clarify what "redefining" means.

**Comment by bennor** [comment]
Have confirmed that it makes no difference whether the attribute is on the interface or the method. 

Running this:

```csharp
using System;
using System.Threading.Tasks;
using Refit;

class Program
{
    static async Task Main(string[] args)
    {
        var httpBin = RestService.For<IHttpBinApi>("https://httpbin.org");
        var response = await httpBin.Post(42, "Bearer <whatevs>");
        Console.WriteLine(response);
    }
}

public interface IHttpBinApi
{
    [Headers("Content-Type: application/json")]
    [Post("/post")]
    Task<string> Post([Body]int id, [Header("Authorization")] string bearerToken);
}
```

Gives this output:

```json
{
  "args": {},
  "data": "42",
  "files": {},
  "form": {},
  "headers": {
    "Authorization": "Bearer <whatevs>",
    "Content-Length": "2",
    "Content-Type": "application/json",
    "Host": "httpbin.org"
  },
  "json": 42,
  "origin": "103.17.59.10, 103.17.59.10",
  "url": "https://httpbin.org/post"
}
```
