### ISSUE TITLE
set StreamReader encoding

### ISSUE THREAD

**Issue by dEEf** [reactiveui/refit#695]
**Is your feature request related to a problem? Please describe.**

When reading JSON response set the encoding so special characters will be displayed correctly.

**Describe the solution you'd like**

**RefitSettings.cs**
`using (var reader = new StreamReader(stream))`
becomes
`using (var reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-1"))`
where encoding **Encoding.GetEncoding("iso-8859-1")** can be set in settings.

**Describe alternatives you've considered**

Deriving charset from request headers
e.g. `[Headers("Accept-Charset: Windows-1252")]`

**Comment by benjaminhowarth1** [comment]
This isn't in RefitSettings.cs - what is though, is the option to specify your own IContentSerializer.
The default JsonContentSerializer can be derived from, which is where StreamReader is used. You can override SerializeAsync and DeserializeAsync accordingly to support encodings you need.

**Comment by dEEf** [comment]
Great, thank you for the feedback
