### ISSUE TITLE
Question Handling Arrays in ApiAttributes

### ISSUE THREAD

**Issue by finsharp** [reactiveui/refit#696]
[Get("/group/{id}/users")]
Task<List<User>> GroupList([AliasAs("id")] int groupId, [AliasAs("sort")] string sortOrder);

Works fine, However

[Get("/group/{ids}/users")]
Task<List<User>> GroupList([AliasAs("ids")] int [] groupId, [AliasAs("sort")] string sortOrder);

The type of the array is used in the url instead of the items in the array. 

Is it possible to use ids as an array in a similar way as it works for query parameter arrays.  The array would have a separator such as '.' or ';'

**Comment by benjaminhowarth1** [comment]
Good question. I'll write a test case for this.

**Comment by benjaminhowarth1** [comment]
I've just come back to this, you should be able to add a [Query] attribute with your separator of choice in the latest 4.7.51 release that just hit Nuget

**Comment by finsharp** [comment]
This worked
`
[Get("/customers/{identifiers}")]
Task<object> GetItems([Query(";")]long[] identifiers, [Query] QueryParams parameters);
`
but this didn't work 
`
[Get("/customers/{identifiers}/items")]
Task<object> GetItems([Query(";")]long[] identifiers, [Query] QueryParams parameters);
`

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
