### ISSUE TITLE
Dynamic boundary for multipart requests

### ISSUE THREAD

**Issue by bjornemannens** [reactiveui/refit#697]
A dynamic boundary string is necessary in order to communicate with some API:s.

**Comment by Cheesebaron** [comment]
https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L441

I guess it wouldn't take much to allow overriding this.

**Comment by benjaminhowarth1** [comment]
PR with tests written and ready to merge for the next release.
