### ISSUE TITLE
 TinyIoC.TinyIoCResolutionException: Unable to resolve type: Mobility.Services.CallApiService.ApiService ---> System.ArgumentException: Multipart requests may not contain a Body parameter

### ISSUE THREAD

**Issue by swapnil591** [reactiveui/refit#706]
Build time error for calling multipart api with class object as [body]

**Comment by benjaminhowarth1** [comment]
Hi there, unfortunately multipart requests can only accept certain types as their body parameters ([Body] is automatically implied with a non-URL parameter), which are documented here: https://github.com/reactiveui/refit#multipart-uploads

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
