### ISSUE TITLE
Url Encoding

### ISSUE THREAD

**Issue by SergeyE85** [reactiveui/refit#714]
Hello.

I have some issue.
I want to perform the query something like this [Get("/...?$filter=Id eq '{id}'$top=100$orderby=Id desc")]

As I understand url encoding is performed by default in refit.
And I get something like ...?%24filter=Id%20eq%20%27<id value>%27%24top%3D100%24orderby%3DId%20desc
But I expect [Get("/...?$filter=Id+eq+%27{id}%27$top=100$orderby=Id+desc")]

I tried different settings. But it was unsuccessful.

Can you advise me something?

**Comment by benjaminhowarth1** [comment]
@SergeyE85 is this an OData APIURL, by any chance?

**Comment by SergeyE85** [comment]
@benjaminhowarth1 Yep I think. It is an url with queries parts.

**Comment by SergeyE85** [comment]
@benjaminhowarth1 Do you know anything about it ?

**Comment by benjaminhowarth1** [comment]
@SergeyE85 have you considered using https://www.nuget.org/packages/Microsoft.OData.Client/ instead of Refit for connecting to an OData API?

**Comment by benjaminhowarth1** [comment]
@SergeyE85 if you've decided to use the MS OData client library, then that helps solve your use case, & I'd like to close this if you're OK with that.

Refit should work just fine with OData, but the number of query options available on an OData querystring, would mean that writing your own wrapper around an OData API, using Refit, would be far more effort than using an official OData client.

If you're OK with it, I'm proposing closing this issue.
