### ISSUE TITLE
Manual adding refit dll error

### ISSUE THREAD

**Issue by InciDuzenli** [reactiveui/refit#716]
**Describe the bug**
I adding refit dll by manually in visual studio .net framework 4.6.1 web project. When I build it get an error. Error is "doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project". I dont want to install refit by manage nuget. My project does not use nuget packages. All references added manualy .
How can I add refit dll manualy?

**Steps To Reproduce**

**Environment**

- OS: Windows 10
- Version  .Net Framework 4.6.1, Refit 4.6.99
- Device:   Web Application

**Additional context**

**Comment by bennor** [comment]
To do this, which is totally unsupported, you would have to replicate the changes made to the csproj file when installing via NuGet. 

The easiest way to do this is going to be to add refit via NuGet to another project, and do a diff on the changes to the csproj after installing Refit. Then replicate the changes.
