### ISSUE TITLE
Custom query string

### ISSUE THREAD

**Issue by robsonj** [reactiveui/refit#718]
I am trying to call a REST API, which is described as follows...

Usage: GET /api/storage/{repoKey}/{folder-path}?list[&deep=0/1][&depth=n][&listFolders=0/1][&mdTimestamps=0/1][&includeRootPath=0/1]

I am trying to form the URL... ```<host>/api/storage/<repoKey>/<folder-path>?list&deep=1```

How can I add the ?list&deep=1 to my url using Refit. It seems to always get dropped when I specify it as part of the Get() path.

Thank you,
Jonathan

**Comment by ajshiff** [comment]
Hi @robsonj .

In your example url, it appears you have a query string key with no value. Did you mean it this way, or did you mean `<host>/api/storage/<repoKey>/<folder-path>?list%26deep=1`, where `%26` is the url encoding for the `&` character.

Refit currently strips out key value pairs in query strings that are missing either keys or values, regardless of whether they were hard coded or passed in. It would appear to me that this is what may be happening in your use case.

You can find the details of this portion of the query string building process on lines 662-680 of RequestBuilderImplementation.cs, as linked below:
https://github.com/reactiveui/refit/blob/master/Refit/RequestBuilderImplementation.cs#L662-L680

**Comment by benjaminhowarth1** [comment]
@robsonj can you provide a gist or sample that we can validate against your test case?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
