### ISSUE TITLE
Use refit with wcf

### ISSUE THREAD

**Issue by rubenmonteiro** [reactiveui/refit#728]
This is not a issue per si.
I would like to know if I can use refit on a wcf service. 
Thanks for answering.

**Comment by benjaminhowarth1** [comment]
As long as your WCF service supports RESTful communication (GET/POST/PUT/DELETE) and parameters in both the querystring and body, then yes, you should be able to use Refit just fine, however you might find "Add Service Reference" in Visual Studio a better wrapper around your API.

**Comment by benjaminhowarth1** [comment]
'

**Comment by rubenmonteiro** [comment]
Thanks, for the reply
