### ISSUE TITLE
[BUG] The HttpClient factory already has a registered client with the name 

### ISSUE THREAD

**Issue by rossbuggins** [reactiveui/refit#730]
**Describe the bug**
When moving from .Net Core 2.2 to 3.0 preview 8,  Adding a Refit Typed client to a HttpClientBuilder now fails with "The HttpClient factory already has a registered client with the name...."

**Steps To Reproduce**
```
 var httpClientBuilder = services.AddHttpClient<TClient, TImplementation>(name, (client) =>
            {             
                client.BaseAddress = new Uri(hostBase);
            })
                .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
            {
                UseDefaultCredentials = true,
            })
            .AddTypedClient(c => Refit.RestService.For<TApi>(c));
```

**Expected behavior**
To run ok as per .net core 2.2

**Environment**

- OS:       Windows 10 
- Version   .net core 3.0 preview 8. Refit 4.7.9
- Device:

**Comment by marioffmarques** [comment]
Any news on this ?

**Comment by jasonliaocn** [comment]
same issue on core 3.1 with the version 5.0.23, any updates?

**Comment by jasonliaocn** [comment]
> same issue on core 3.1 with the version 5.0.23, any updates?

seems this is .net core issue see [#13346](https://github.com/dotnet/aspnetcore/issues/13346)

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
