### ISSUE TITLE
ObjectDisposedException throw when access to request content in ApiException

### ISSUE THREAD

**Issue by jbardon** [reactiveui/refit#732]
**Is your feature request related to a problem? Please describe.**

On request error (not success status code) an ApiException is throw.
When catching it for analysing, it's not possible to access the request content (of a POST for example).

```csharp
try {
    // this doesn't return a 200 status code
    await RefitInterface.makePostCall(payload);
} catch (ApiException ex) {
   /* Imagine this try/catch in a middleware so it can't access the payload 
      passed to RefitInterface.makePostCall

       This line throws ObjectDisposedException
   */
   var requestPayload = await ex.RequestMessage.Content.ReadAsStringAsync();
}
```

**Describe the solution you'd like**
I identified the problem located in `RequestBuilderImplementation::BuildCancellableTaskFuncForMethod`, the finally block runs dispose on the request. I'm sorry but I don't know if this line is mandatory so I'm not able to suggest a solution to this problem.

**Comment by gdodd1977** [comment]
I'd also like to know the solution to this issue.

**Comment by Px7-941** [comment]
I have the same issue. Debugging is very difficult.

**Comment by Dreamescaper** [comment]
Can you use `ApiException.Content` instead?

**Comment by Px7-941** [comment]
> Can you use `ApiException.Content` instead?

No, `ApiException.Content` is the content of the response. We want to read the content of the request message.  So we can check the settings of the JSON serializer or make sure that the properties are written correctly.

**Comment by evaldas-raisutis** [comment]
Any solution to this? Just ran into it myself.

I've made a middleware for logging all exceptions and am handling an ApiException. However, when trying to await exception.RequestMessage.Content.ReadAsStringAsync() I get the exception mentioned by OP. same if I try to .Content.CopyToAsync(anotherStream)

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by Px7-941** [comment]
@jbardon  can you reopen the issue?

@clairernovotny The problem still exists in the latest version. (v6.0.15)
`catch (ApiException aex)
  {
      var requestJson = await aex.RequestMessage.Content.ReadAsStringAsync();
  }`

Throws ObjectDisposedException

`ex	{System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Http.PushStreamContent'.   at System.Net.Http.HttpContent.CheckDisposed () [0x00008] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cor…}`

`"Cannot access a disposed object.\nObject name: 'System.Net.Http.PushStreamContent'."`

**Comment by jbardon** [comment]
Thanks for testing on the latest version @Px7-941.

**Comment by themronion** [comment]
+1 here, still an issue

**Comment by domagojmedo** [comment]
+1, still an issue

**Comment by clairernovotny** [comment]
Request content can be arbitrarily large and streamed to the wire. It's not kept in memory so it cannot be accessed once the request is sent.

**Comment by Px7-941** [comment]
I am missing the possibility to check the sent payload. Maybe a httpclient handler for a log output would help. Best on a request basis.

**Comment by lostincomputer** [comment]
@Px7-941 Could you use tools such as Wireshark, Fiddler, and Charles Proxy?

**Comment by StefanWentink** [comment]
Still an issue +1
