### ISSUE TITLE
[BUG] After upgraded to 4.7.51, Refit fails Build on CLI, but succeed on VS2019

### ISSUE THREAD

**Issue by unique94** [reactiveui/refit#739]
**As decribed in headlines**

.nuget\packages\refit\4.7.51\buildTransitive\netstandard1.4\refit.targets(35,5): error MSB4062: The "Refit.Generator.Tasks.GenerateStubsTask" task could not be loaded from the assembly
.nuget\packages\refit\4.7.51\buildTransitive\netstandard1.4\..\..\build\MSBuildCore20\InterfaceStubGenerator.BuildTasks.dll. Assembly with same name is already loaded Confirm that the <
UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by GlennArens** [comment]
how did you fix this?

**Comment by HelloKitty** [comment]
I encounter this too.

**Comment by rsibanez89** [comment]
Same here

**Comment by alastairtree** [comment]
Had this myself. Had to restart the machine to fix it!
