### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by jabbera** [reactiveui/refit#741]
I understand this is a duplicate request, but the last request was 2 years ago. This is a very popular package, not having it strong named is very unpleasant. It makes it very difficult to use. Please reconsider strong naming or publish some guidance on how to strong name it. 

I'm trying to reference refit from a library that will then be used by other teams. I cannot simply package my own copy of refit, or ask all users of my library to sign it.

**Comment by onovotny** [comment]
This is done in master / CI. Version 5 will have a strong name. If you need it immediately, please use the Azure Artifacts feed to get it.
