### ISSUE TITLE
"Get" annotation with parameters only

### ISSUE THREAD

**Issue by Basti82b** [reactiveui/refit#742]
**Is your feature request related to a problem? Please describe.**

"URL path &type=address&input={query} must be of the form '/foo/bar/baz'"

**Describe the solution you'd like**

[Get(&type=address&input={query})]

**Additional context**

https://developers.google.com/places/web-service/autocomplete

**Comment by clairernovotny** [comment]
Solution is to start the path with `/` before the query.
