### ISSUE TITLE
[BUG] AddRefitClient non-generic version does not register service

### ISSUE THREAD

**Issue by holotrek** [reactiveui/refit#745]
**Describe the bug**

When registering the refit client with the `HttpClientFactoryExtensions` using the method overload that takes in a runtime type (i.e. `services.AddRefitClient(myInterfaceType, settings)`), the service is not registered as it is with the generic version. This is due to it missing the line `services.AddSingleton(provider => RequestBuilder.ForType(refitInterfaceType, settings));` similar to the way it does it in the first line of the generic method, located [here](https://github.com/reactiveui/refit/blob/3cf1ef9e3fd50df565e383ff204b61a665806973/Refit.HttpClientFactory/HttpClientFactoryExtensions.cs#L17).

**Steps To Reproduce**

1. Create standard Refit interface, i.e. `IMyApi`
2. Create a .net core web API
3. In `Startup.ConfigureServices`, get a `Type` for your interface type and call the broken AddRefitClient method:
```
var refitInterfaceType = typeof(IMyApi);
services.AddRefitClient(refitInterfaceType);
```
4. In a controller, inject the IMyApi and attempt to use it in an endpoint:
```
[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{
  private readonly IMyApi _api;
  public ValuesController(IMyApi api)
  {
    _api = api;
  }

  // GET api/values
  [HttpGet]
  public ActionResult<IEnumerable<string>> Get()
  {
    _api.GetThing();
    return new string[] { "value1", "value2" };
  }
}
```
5. Navigate to route and receive error like `InvalidOperationException: Unable to resolve service for type 'IMyApi' while attempting to activate 'test_api.Controllers.ValuesController'.`
6. Note: follow steps 1-4 and use the generic version to register the API and it will work:
`services.AddRefitClient<IMyApi>();`

**Expected behavior**

It is expected that adding the refit client with the runtime type will act the same as adding it with the generic type.

**Environment**
- OS: Windows 10
- Version: 4.7.9
- Device: Desktop

**Comment by lobster2012-user** [comment]
It looks like a bug.
https://github.com/reactiveui/refit/blob/master/Refit.HttpClientFactory/HttpClientFactoryExtensions.cs

You can do PR.

**Comment by 362486122** [comment]
I also got this problem.here is my solution.

1. 

```c#
public static IHttpClientBuilder AddTypedClient(this IHttpClientBuilder builder, Type type, Func<HttpClient, IServiceProvider, object> factory)
        {
            if (builder == null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            if (factory == null)
            {
                throw new ArgumentNullException(nameof(factory));
            }

            builder.Services.AddTransient(type, s =>
            {
                var httpClientFactory = s.GetRequiredService<IHttpClientFactory>();
                var httpClient = httpClientFactory.CreateClient(builder.Name);

                return factory(httpClient, s);
            });

            return builder;
        }
```

2. Add a new AddRefitClient method
```c# 
public static IHttpClientBuilder AddRefitClient(this IServiceCollection services, Type refitInterfaceType, RefitSettings settings = null)
        {
            return services.AddHttpClient(UniqueName.ForType(refitInterfaceType))
                           .AddTypedClient(refitInterfaceType, (client, serviceProvider) => RestService.For(refitInterfaceType, client, settings));
        }
```

**Comment by Davilink** [comment]
We had a similar problem, resFit tried to register all the typeclient under the same name, so the DI container was throwing exception. We created this workaround : 
```csharp
public static class IServiceCollectionExtension
    {
        public static IServiceCollection AddRestServiceClient(this IServiceCollection services, Type type, Action<IServiceProvider, HttpClient> clientFactory)
        {
            services.AddHttpClient(type.FullName, clientFactory)
                .Services.AddTransient(type, services =>
                {
                    var httpClientFactory = services.GetRequiredService<IHttpClientFactory>();
                    var httpClient = httpClientFactory.CreateClient(type.FullName);
                    return Refit.RestService.For(type, httpClient);
                });

            return services;
        }

        public static IServiceCollection AddRestServiceClient(this IServiceCollection services, Type type, Action<HttpClient> clientFactory)
        {
            return AddRestServiceClient(services, type, (serviceProvider, client) => clientFactory(client));
        }
    }
```

I think the problem seem to be around the `UniqueName.ForType`

**Comment by netssfy** [comment]
another workaround is call generice version by reflection
`var builder = typeof(HttpClientFactoryExtensions)
                        .GetMethod("AddRefitClient", 1, new Type[] { typeof(IServiceCollection), typeof(RefitSettings) })
                        .MakeGenericMethod({yourType})
                        .Invoke(null, new object[] { services, null }) as IHttpClientBuilder;`

**Comment by mingyangzhu** [comment]
+1 me too.

**Comment by CooperLiu** [comment]
is it released?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
