### ISSUE TITLE
Support BodySerializationType.Xml

### ISSUE THREAD

**Issue by alexeyzimarev** [reactiveui/refit#75]
Why only Json and Forms? Xml is still needed for many legacy interfaces.

**Comment by Arithmomaniac** [comment]
+1

**Comment by CSchick** [comment]
+1

**Comment by ashutoshraina** [comment]
+1

**Comment by couven92** [comment]
+1

**Comment by gsgou** [comment]
+1

**Comment by OlafHaalstra** [comment]
+1

**Comment by Arithmomaniac** [comment]
The +1s predate the 👍 reaction. They're not needed anymore to signal approval.

**Comment by bennor** [comment]
I'm not sure exactly when it was added, but XML is supported in request and response bodies now. 

Docs here: https://github.com/reactiveui/refit/blob/master/README.md#xml-content
