### ISSUE TITLE
Refit fails to build on .NET Core 3.0.100

### ISSUE THREAD

**Issue by ergometh** [reactiveui/refit#756]
Similarly to #619 , project with Refit dependency doesn't build on new version of .NET Core 3.0.100.
However on .NET Core 2.2.401 it builds without a problem.

`error MSB4062: The "Refit.Generator.Tasks.GenerateStubsTask" task could not be loaded from the assembly C:\windows\system32\config\systemprofile\.nuget\packages\refit\4.7.51\buildTransitive\netstandard1.4\..\..\build\MSBuildCore20\InterfaceStubGenerator.BuildTasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

**Comment by onovotny** [comment]
If you just updated references, you might need to restart VS?

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by ergometh** [comment]
Problem was on the CI machine, but when updated to the Refit 4.7.9 version problem is gone. Thank you for help.
