### ISSUE TITLE
[BUG] Summary of item

### ISSUE THREAD

**Issue by csteeg** [reactiveui/refit#759]
**Describe the bug**

Multipart post with a stream fails if I have a url-parameter first.
So
```
        [Multipart]
        [Post("/api/photo/{clientLinkId}")]
        Task<bool> UploadPhotoAsync(StreamPart file, Guid clientLinkId, CancellationToken cancellationToken = default);

```
works, but
```
        [Multipart]
        [Post("/api/photo/{clientLinkId}")]
        Task<bool> UploadPhotoAsync(Guid clientLinkId, StreamPart file, CancellationToken cancellationToken = default);

```
does not! It throws an KeyNotFoundException in the RequestBuilderImplementation
I think this is because of the update in https://github.com/reactiveui/refit/commit/e5dff69f71f11a8b200d8b51daa79103ba2dee06#diff-ef1e95d8d69943f1b3f91e27c7bd5986
In this commit, a queryParamShift is introduced. This variable is used shift the index for everyting between 
```
 if (!restMethod.IsMultipart)
{
...
}

```
But not for everything between 
```
if (restMethod.BodyParameterInfo != null && restMethod.BodyParameterInfo.Item3 == i)
{
...
}
```

I think all access to paramList[i] in that section should be replaced by paramList[i -queryParamShift]

**Steps To Reproduce**
Try to call a method like this on your api interface:
```
        [Multipart]
        [Post("/api/photo/{clientLinkId}")]
        Task<bool> UploadPhotoAsync(Guid clientLinkId, StreamPart file, CancellationToken cancellationToken = default);

```

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
