### ISSUE TITLE
[BUG] Nameof in HTTP Action Path Throws at Runtime

### ISSUE THREAD

**Issue by HelloKitty** [reactiveui/refit#766]
**Describe the bug**

Nameof used in the path of HTTP action attributes of Refit causes Refit to fail to generate and at runtime throws an exception that claims the interface doesn't appear to be a Refit interface.

**Steps To Reproduce**

See Example: https://github.com/gladmmo/GladMMO.Library/commit/fd11c2e5ece2e754574013a673a6036d6eb182ef

**Expected behavior**

Refit should support nameof concatenated paths for HTTP actions between it's a compile time constant string result and is valid C#.

**Environment**

- OS:       Windows10
- Device:   Desktop
- Version:   4.6.107
- Working Version: 4.6.107

**Comment by clairernovotny** [comment]
Should be implemented in #1029

**Comment by clairernovotny** [comment]
Please try v6.0-preview.84 and file bugs as you come across them.
