### ISSUE TITLE
The same dto class names with different namespaces

### ISSUE THREAD

**Issue by vlapenkov** [reactiveui/refit#768]
Hi.
We got error in Refitstubs.g.cs if i use two dto objects with different namespaces. How to solve this problem?
CS0104	'BillObjectDto" является неоднозначной ссылкой между "TNE.BillMoney.Contracts.Dto.Accruals.BillObjectDto" и "TNE.BillMoney.Contracts.Dto.Nsi.BillObjectDto"

Thank you in advance!

**Comment by Styxxy** [comment]
Duplicate with #769

**Comment by onovotny** [comment]
The quickest workaround for this that wouldn't require any Refit updates is to fully qualify the namespaces in your interfaces.

I'm not sure that Refit can fix this directly as it's syntactic analysis, not a full roslyn workspace. It doesn't know any more than it can "see" in those few interface snippets.

**Comment by KyleGalvin** [comment]
I believe this is resolved by this recent merge:
https://github.com/reactiveui/refit/pull/803

**Comment by clairernovotny** [comment]
Should be fixed either in #803 or  #1029
