### ISSUE TITLE
[BUG] RefitStubs.g.cs ExcludeFromCodeCoverage and Obfuscation(Exclude=true) attributes don't exist in .Net Standard1.4

### ISSUE THREAD

**Issue by panoukos41** [reactiveui/refit#774]
**Describe the bug**

The following types are not available in .net standard 1.4 but the generated file contains them so the app can't build.

System.Reflection.Obfuscation(Exclude=true)
System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage

I use .net standard 1.4 as a shared library and i create my RestService using refit there to consume it on all the platforms/projects.

**Steps To Reproduce**

1. Create new .Net Standard (1.4) Class Library.
2. Install latest version of Refit.
3. Create the IGithubApi interface as seen in the readme example.
4. Create a project to consume the service from the class library.
5. Try to build and get the errors seen in the picture.

**Screenshots**

![image](https://user-images.githubusercontent.com/20771798/68076546-98c26100-fdbe-11e9-940d-384833926070.png)

**Additional context**

I think a possible fix would be to use Enviroment Constant for .net standard 1.4 and remove these attributes but i know it's not ideal, another fix would be to find and use quivalent attributes if .net standard 1.4 has any. 

The library works great before version 4.6.16 but after it problems with the attributes show up. 
I checked all versions from 4.0.0 till 4.6.16 and then checked only 4.6.107 and up.

**Comment by onovotny** [comment]
The workaround is to define those yourself as internal attributes. I'm going to mark this as `wontfix` though since we're about to drop `netstandard1.4` suport anyway.

**Comment by panoukos41** [comment]
Thanks a lot for the quick response, i am still getting used to attributes.  
Great solution i will remember it  for the next time i have issues with something like that ^_^!!
