### ISSUE TITLE
Interface inheritance results in "doesn't look like a Refit interface" exception

### ISSUE THREAD

**Issue by Ethicmeta** [reactiveui/refit#775]
In an effort to keep our code clean, we're attempting to segregate our refit interface into a base interface that inherits the controller refit interfaces. 

`    public interface IWebApiRefit : IAccountController, IContactController
    {
    }
`

```
public interface IAccountController
    {
        [Post("/account/create")]
        [Headers("Authorization: Bearer")]
        Task<ApiResponse<string>> CreateAccount([Body] CreateAccountRequest accountRequest);
 }
```

```
public interface IContactController
    {
        [Post("/contact")]
        Task<ApiResponse<string>> Contact([Body] ContactRequest contactRequest);
 }
```

This code is built as a nuget package with a reference to Refit package v4.7.51.

If there's a way I can implement the interface with a segregated layout similar to above that would be great.

As a side note, I've verified the interface functions properly when all in the base interface with no inheritance.

**Comment by zleao** [comment]
I have the same approach and therefore, the same problem :)
Ended up doing some 'nasty' workaround, by defining a `foo` method im my `IWebApiRefit`. This way, when using the `RestService.For`, the service gets created and the interface inheritance works like a charm.
I'm currently using Refit package v5.1.67

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
