### ISSUE TITLE
Can't send array of complex objects as query params

### ISSUE THREAD

**Issue by OlesKorzhynskiy** [reactiveui/refit#777]
Trying to send request using Refit to controller:
[HttpGet("api/users/{userId}/roles")]
public async Task<IActionResult> Get(Guid userId, [FromQuery] FilterRow[] filters = null) {..}

Added interface with this method:
[Get("/api/users/{userId}/roles")]
Task<IEnumerable<ReadModel>> Get([AliasAs("userId")] Guid userId, [AliasAs("filters")] FilterRow[] filters);

FilterRow:
public class FilterRow
    {
        public string FieldName { get; set; }
        public string FilterValue { get; set; }
    }

Tried to add RefitUrlParameterFormatter. But to it's function Format comes separate values from this object. Solved this using IFormattable to this object, but even with this it didn't work correctly

**Comment by onovotny** [comment]
What would you expect the query string to look like for this?

**Comment by xljiulang** [comment]
Maybe only  [WebApiClient](https://github.com/dotnetcore/WebApiClient) can help you! 
```
[LoggingFilter]
public interface IUserApi
{
    [HttpGet("/api/users/{userId}/roles")]
    Task<string> Get([AliasAs("userId")] Guid userId, [AliasAs("filters")] FilterRow[] filters);
}
```

####  Set FullName KeyNamingStyle
```
services.AddHttpApi<IUserApi>(o =>
{
    o.KeyValueSerializeOptions.KeyNamingStyle = KeyNamingStyle.FullName;
    o.HttpHost = new Uri("http://localhost:6000/");
});
```

#### Request String
```
GET /api/users/00000000-0000-0000-0000-000000000000/roles?filters%5b0%5d.fieldName=n1&filters%5b0%5d.filterValue=v1&filters%5b1%5d.fieldName=n2&filters%5b1%5d.filterValue=v2 HTTP/1.1
Host: localhost:6000
User-Agent: WebApiClientCore/1.0.0.0
Accept: application/json; q=0.01, application/xml; q=0.01
```

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
