### ISSUE TITLE
[BUG] Unable to set in header Content-Type application/json for GET

### ISSUE THREAD

**Issue by bo3po** [reactiveui/refit#780]
**Describe the bug**
Unable to make refit set/send the header [Content-Type application/json] at all. I can set it and it will send just about anything else at it will work.

**Steps To Reproduce**
Open the "Meow" project and make it send a Content-Type application/json - that will not work.

**Expected behavior**
The "Meow" has a output showing what is send. It's not in the request headers.

**Environment**
VS for Mac

**Additional context**
I'm new to refit so i might be mistaken. Even with the custom way (dynamic) this still does not work.

**Comment by ppasieka** [comment]
Hi! @bo3po ,

Are you sending a body with your GET request? If not then specifying Content-Type is pointless.
From the other hand if you expect to get a response where the content-type is `application/json` then you probably want to use `Accept application/json` header

The majority of situations, GET request is sent without a body (at least I never have seen it)

**Comment by bo3po** [comment]
Hi

a body in a get request? no. ok. i'll explain this. it might be me not
knowing what i'm doing. i have this service from a thired party that i need
to talk to. i use postman for debugging and see what is going on. i use it
to see how i should shape the request. then i do not have "Content-Type:
application/json" on my get request i get something like this ({"d":true})
<- with the ( and ). when i send WITH the Content-Type: application/json i
get a nice {"d": true} response. that is parsable from json.newton. The
({"d":true})-response is not.

so if i send the "Content-Type: application/json" in my get request it's
all good. tested from postman. but again it might be me doing
something very wrong.

please correct me if i am wrong

**Comment by ppasieka** [comment]
Instead of this header
```
"Content-Type: application/json"
```

 try to set:

```
"Accept: application/json"
```

My understanding is that `Content-type` describes what media type your client sends. Wheres `Accept` tells the server what type of media the client expects to get in the response.
So for GET requests, when you are sending nothing (no body) `Content-Type` is not needed. I believe it is impossible to send body with a GET request using Refit so it makes sense to remove this header after all

**Comment by bo3po** [comment]
arh ok. thank you very much for the update. that makes total sense to me. i
guess that postman is playing trick on me that when i set the header in a
get ... that is actually send a "accept" rather than a content-type. this
is very useful info to me.

i'll get back with my findings. i was unable to find out what i did wrong
with the docs and all my searches did not indicate this. or i did not
understand the answers.

thx!

**Comment by bo3po** [comment]
hi

it did not do anything to the result. i see that the accept is been send
but my result is still a invalid json response that is enclosed in a (...)
which is not parseable from the application. i might have to do a wireshark
to fully understand what is going on.

**Comment by bennor** [comment]
Refit can't attach a `Content-Type` header to a request without a body because the underlying `HttpClient` won't allow it and if I'm not mistaken, it won't allow adding a body to a GET request.

Unless you can make it work without that header, you might not be able to use Refit (or a plain `HttpClient`, for that matter).

**Comment by ppasieka** [comment]
It kinda looks like your response is a JSONP, not a JSON. Check API documentation on how to make proper requests to get JSON object.

**Comment by handsome-b-wonderful** [comment]
> It kinda looks like your response is a JSONP, not a JSON. Check API documentation on how to make proper requests to get JSON objec

Just stumbled on this issue - Yes, it looks like you've made a GET request to an API that (likely) expects a query parameter for the callback  function, you're not providing it and the API is not validating so  you get essentially 
````
<null>({ <your data> })
````
returned. typically your GET would look something like:
````
http://server.example.com/Users/123?callback=myFunction
````
and you would receive
````
myFunction({"Name": "John Doe", "Id": 1234, ... });
````

This is the older work-around prior to CORS so you could consume responses from outside the current page's origin.

run Fiddler or something similar and look at the underlying Request and Response to figure out exactly what's going on.

**Comment by bo3po** [comment]
Ohhh really? Hmm. Thank you very much. Yes this is a api build on top of
something else. But it is consume Outside the domain...

I’ll try 😄

søn. 17. nov. 2019 kl. 15.08 skrev Mark Dochstader <notifications@github.com

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
