### ISSUE TITLE
[BUG] ApiException's Content property shouldnt assume the content is always a string

### ISSUE THREAD

**Issue by amoorthaemer** [reactiveui/refit#781]
Hi,
I'm using Refit to as a proxy layer between the client and an API. The API returns BSON and I'm using a BSON IContentSerializer implementation for Refit.

When I get a non 200-range status code from the API (e.g. 404), Refit throws an ApiException. Which is fine ... what isn't fine, is the fact that I loose content because the content is converted into a string on the ApiException instance and I'm not able anymore to deserialize the data.

I think this is a bug, because it limits the usage of Refit to text-oriented HTTP bodies.

Please provide a work-around or solve this...

Thank you

Bert Moorthaemer

**Comment by amoorthaemer** [comment]
Anybody?

**Comment by amoorthaemer** [comment]
Anybody?????

**Comment by Dreamescaper** [comment]
Probably depends on https://github.com/reactiveui/refit/issues/272.
You can probably use same workaround - create custom `DelegatingHttpHandler`, which throws your custom exception in case of error - with `byte[] Content` property.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
