### ISSUE TITLE
Refit.HttpClientFactory pack broken, not SemVer 5.0

### ISSUE THREAD

**Issue by dotnetchris** [reactiveui/refit#782]
`Refit.HttpClientFactory` 4.8.14 has a dependency to `Microsoft.Extensions.Http` 3.0.0

This is a breaking change and requires release of version 5.

 4.8.15 needs released as a bug fix version that correctly depends on 2.2.

Then either the dependency to MEH 3.0.0 needs either eliminated or if it's required this creates SemVer release 5.0.0

**Comment by onovotny** [comment]
How is Microsoft.Extensions.Http 3.0 a breaking change? It supports the same targets as the prior verison does.

**Comment by onovotny** [comment]
Just to set expectations, we're likely releasing a 5.0.x version in the next week or so. Master is already there, just waiting on a PR or two to land.

We're unlikely to release any more 4.8 builds.

**Comment by dotnetchris** [comment]
It's a breaking change in that it literally breaks apps building 

>  error NU1107: Version conflict detected for Microsoft.Extensions.Configuration

**Comment by dotnetchris** [comment]
Also simply put, proper adherence to SemVer, if you change any dependency by a major version that by definition requires a major version change to your project.

**Comment by onovotny** [comment]
Closing as v5.0.15 was just released.

**Comment by dotnetchris** [comment]
Really disappointing to see the 4.0 series to be ended with a broken release that won't be properly bug fixed.
