### ISSUE TITLE
[BUG] Multiple Input Files (May) Lead To Ambiguous Reference Errors

### ISSUE THREAD

**Issue by KyleGalvin** [reactiveui/refit#784]
**Describe the bug**
Merging 'using' statements from multiple input files into RefitStubs.g.cs can cause unexpected ambiguity. 

**Steps To Reproduce**
Ambiguous.cs:
```
namespace NS1
{
    public class Ambiguous
    {
    }
}

namespace NS2
{
    public class Ambiguous
    {
    }
}

```
RefitClientA.cs:
```
using NS2;
using Refit;

namespace RefitBugCase
{
    public interface RefitClientA
    {
        [Get("/")]
        Ambiguous Get();
    }
}
```

RefitClientB.cs:
```
using NS1;
using Refit;

namespace RefitBugCase
{
    public interface RefitClientB
    {
        [Get("/")]
        Ambiguous Get();
    }
}

```

**Expected behavior**
both refit clients compile

**Screenshots**
N/A

**Environment**
Refit <=5.0.15

**Additional context**
Two suggested proposals for a fix:
1) Breaking down RefitStubs.g.cs into a single file per input file.
_or_
2) replacing all types with fully qualified namespaces instead of 'using' headers on code generation.

**Comment by KyleGalvin** [comment]
Looks like this is the underlying issue in both
https://github.com/reactiveui/refit/issues/769
and 
https://github.com/reactiveui/refit/issues/768

**Comment by danlyons-softek** [comment]
> Two suggested proposals for a fix:
>
>    1. Breaking down RefitStubs.g.cs into a single file per input file.
>    or
>    1. replacing all types with fully qualified namespaces instead of 'using' headers on code generation.

I'll add another option:
3. generate `using` headers for each stub inside their respective namespaces rather than generating them all at the top

Were I writing the code myself, I'd prefer separate files per stub, but I'm more ¯\\\_(ツ)\_/¯ about generated code.

**Comment by onovotny** [comment]
I'm happy to take a PR that fixes this. The main issue is that we've had is that Refit does not do semantic analysis on the phone. It just does syntax analysis to figure things out.

If there's a way to improve the template/generated code based on this, then I'm all for it. If someone wants to implement Semantic Analysis, then I'm good with that too, but that's a much bigger job (and we'd need to see how that affects build time as it's slower).
