### ISSUE TITLE
Enum w/ Flags Attribute throws InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by janderson-dev** [reactiveui/refit#794]
**Describe the bug**
C# supports enums decorated with the [flags] attribute. This allows a Developer to assign a single enum multiple values separated by the '|' binary 'or' bitwise operator. 
An example might be:  MyEnum myEnum = MyEnum.Value1 | MyEnum.Value2 | MyEnum.Value3; When an enum set with multiple values is passed in as a parameter to the refit client. Refit throws an Aggregate Exception with inner exception of InvalidOperationException: Sequence contains no elements.

**Steps To Reproduce**
Here is an example enum.
[Flags]
public enum MyEnum
{
Value1 = 0,
Value2 = 1,
Value3 = 2,
Value4 = 4,
Value5 = 8
}

client.SomeMethod(MyEnum.Value1 | MyEnum.Value2 | MyEnum.Value3); // throws exception

**Expected behavior**
When refit validates whether an enum is valid it should take into account whether the enum is decorated with the flags attribute and handle accordingly. At the very least, I would expect it to skip trying to validate if decorated with the flags attribute so that the client still works as intended instead of throwing an exception. As a workaround, we can set the client to use int instead of the enum, but this isn't a very good approach because it allows non valid enum values to be passed in. It also isn't very obvious to a Developer what type of parameter should be passed in to the client if using int.

**Environment**
Windows

**Additional context**

**Comment by CreepyGnome** [comment]
I have tried to do this as well, however, it does work, it just does it wrong for URL's.

If you decorate the enum with StringEnumConverter as shown below it will serialize the flags as a comma-separated list to the query string alias name.  Unfortunately, it adds a space after each comma which will cause issues with many REST endpoints as they expect no space in the majority of the cases.

```
[Flags]
[JsonConverter(typeof(StringEnumConverter))]  
public enum MyEnum
{
    Value1 = 0,
    Value2 = 1,
    Value3 = 2,
    Value4 = 4,
    Value5 = 8
}
```

To overcome this you can hack into a HttpMessageHandler to clean the URL with something like below, and it will work but its hacky. A better approach would be to create your own FlagEnumConverter to ensure it doesn't serialize them with the spaces in the first place and then you can be selective about using it which makes it safer.

```
var cleansedUri = request.RequestUri.AbsoluteUri.Replace("%2C%20", "%2C");
request.RequestUri = new Uri(cleansedUri, UriKind.Absolute);
```
If refits wants to build in the support for Flags that would be awesome, however there are ways to workaround it for now.

**Comment by CreepyGnome** [comment]
Update, tried using [Query(CollectionFormat.Csv)] but doesn't seem to work for enum flags. I supporting  CollectionFormat for Flags would be the best solution here, or switch to collection of enums.

**Comment by WesleyJesus99** [comment]
Hi @benjaminhowarth1 can you tell me if there was a fix for this bug?
I tried to simulate error to contribute with code and I didn't get failures.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by bandmask** [comment]
@clairernovotny 
This is still a problem with Refit v6.0.15. Can this be reopened?
Same problem as the original post, will it need more information?

**Comment by j-bbr** [comment]
I also stumbled over this today and would like this issue to be reopened. The exception is thrown by the DefaultUrlParameterFormatter here (currently line 117)
`
enummember = cached.GetOrAdd(parameterValue.ToString()!, val => parameterType.GetMember(val).First().GetCustomAttribute<EnumMemberAttribute>());`

and is thrown every time a flags enum with more than one field set is passed as an argument since parameterValue.ToString returns a number now that parameterType.GetMember can't parse -> Empty Collection -> Linq Exception. At the very least this should throw an exception with a more informative message. Workaround is to create your UrlParameterFormatter and add it in RefitSettings

**Comment by Newer91** [comment]
I actually use Refit.HttpClientFactory V 6.3.2 and I have same issue like as the original post
@clairernovotny can we reopen this issue?

**Comment by developer9969** [comment]
@clairernovotny Hi there , this is still an issue . Can someone clarify if  Enum with flags are supported by Refit?
if not I need to find an alternative solution.

Many thanks

**Comment by xingzhenlu** [comment]
I have the same problem!
