### ISSUE TITLE
feature: Custom query parameter formatting

### ISSUE THREAD

**Issue by fcapallera** [reactiveui/refit#797]
I don't know if this is already a feature, but I haven't found it on the docs.
Basically I'm working with the Prestashop API and the way it uses the query parameters is quite different from other apis, for example.

A parameter you would query as:
`/api/customers?id=3`
It queries like:
`/api/customers?filter[id]=3`
Or you can filter strings like:
`api/customers?filter[customer_name]=%[{string}]%`

Is there a way I can define my own formatting when it comes to query parameters? As of now, I have to write a call with hard coded query parameters.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
