### ISSUE TITLE
How to upload byte array as octet-stream?

### ISSUE THREAD

**Issue by Hooch180** [reactiveui/refit#799]
Hi,
I have method like this:

```
[Put("/2/0/workspaces/{WorkspaceId}/models/{ModelId}/files/{fileId}")]
[Headers("Authorization: AnaplanAuthToken")]
Task<JObject> PutFileAsSingleChunk(string workspaceId, string modelId, string fileId, byte[] fileContent);
```

What do I need to change to send fileContent it as octet-stream?

**Comment by bennor** [comment]
All you should need to do is add `"Content-Type: application/octet-stream"` to your headers attribute.

If it's trying to send it as JSON, you might need to wrap the `byte[]` in a `Stream` or `HttpContent`.
