### ISSUE TITLE
[BUG] Refit fails to serialize array to URL (This is not for QUERY string)

### ISSUE THREAD

**Issue by CreepyGnome** [reactiveui/refit#806]
When you try to set an array as part of the endpoint path Refit just ToStrings the object.  The Query string it handles fine, however, if you have a list of ID's a 3rd party API requires you to pass the comma-separated list as part of the endpoint path before any query string Refit fails.  

If there is a way to work around this, without passing an already formatted string instead of an array of values I am all ears.  

Worse case the performing the collection to strings will work, just that is a horrible API interface to have to preformat/parse and manage an array of numbers just because Refit doesn't know what to do.  

So if a Url formatter will work I am all as I have never implemented one before. 

However, this really should be fixed/supported by Refit as it is a valid URL and I know at least one fairly large company that uses this on a few of their endpoints (Etsy).

API Interface for https://www.etsy.com/developers/documentation/reference/receipt#method_getshop_receipt2
```
[Get("/v2/receipts/{receipt_ids}")]
Task<EtsyResponse<EtsyReceipt>> GetShopReceipt2([AliasAs("receipt_ids")] long[] receiptIds);
```

Expected URL if called with `long[] { 100 }`: `{baseUrl}/v2/receipts/100`

Actual URL when called with  `long[] { 100 }`: `{baseUrl}/v2/receipts/System.Int64%5B%5D`

Expected URL if called with `long[] { 100, 200, 300, 400 }`: `{baseUrl}/v2/receipts/100%2C200%2C300%2C400`

Actual URL when called with  `long[] { 100, 200, 300, 400  }`: `{baseUrl}/v2/receipts/System.Int64%5B%5D`

**Environment**

- OS:   Windows 10.0.18362.476
- Version:   Refit 5.0.23
- Working Version: none (went back to 4.6.58 and none seem to work so I assume it never has)

**Comment by CreepyGnome** [comment]
Looking more into this and it seems like the AliasAs attribute need be more like the Query attribute with the options for delimiter, prefix, and/or format or a CollectionFormat enum value.  Then to have them work like a Query param just for AlaisAs parameters.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by kmcclellan** [comment]
I am running into this too. The code to format collections is in [`BuildQueryMap(...)`](https://github.com/reactiveui/refit/blob/ed78b9244bb2b15d0653b3ae013c98ae96735d30/Refit/RequestBuilderImplementation.cs#L395-L396) and doesn't run for parameters in the path. My current workaround (as an extension method):

```c#
public static class RefitExtensions
{
    public static RefitSettings WithPathCollections(this RefitSettings refit)
    {
        refit.UrlParameterFormatter = new UrlCollectionFormatter(refit.UrlParameterFormatter, refit);
        return refit;
    }

    private class UrlCollectionFormatter : IUrlParameterFormatter
    {
        private static readonly Dictionary<CollectionFormat, char> _delimiters = new()
        {
            { CollectionFormat.Ssv, ' ' },
            { CollectionFormat.Tsv, '\t' },
            { CollectionFormat.Csv, ',' },
            { CollectionFormat.Pipes, '|' },
        };

        private readonly IUrlParameterFormatter _innerFormatter;
        private readonly RefitSettings _settings;

        public UrlCollectionFormatter(IUrlParameterFormatter innerFormatter, RefitSettings settings)
        {
            _innerFormatter = innerFormatter;
            _settings = settings;
        }

        public string? Format(object? value, ICustomAttributeProvider attributeProvider, Type type)
        {
            if (value is IEnumerable items && _delimiters.TryGetValue(_settings.CollectionFormat, out var delim))
            {
                return string.Join(delim, FormatItems());

                IEnumerable<string?> FormatItems()
                {
                    foreach (var item in items)
                    {
                        yield return _innerFormatter.Format(item, attributeProvider, type);
                    }
                }
            }

            return _innerFormatter.Format(value, attributeProvider, type);
        }
    }
}

**Comment by DmitriyBobrovskiy** [comment]
> Closing due to age. Please try Refit v6 and reopen if still an issue.

I'm using version 6.2.16 and still have this issue, can we reopen this?

**Comment by DmitriyBobrovskiy** [comment]
@kmcclellan can you elaborate please how to use this?
I connected it in Refit configuration
<img width="391" alt="image" src="https://user-images.githubusercontent.com/33372992/215459619-9661a6b6-61b7-4344-a569-fdf3b28a2aa5.png">

but in an interface I have tried both with `QueryAttribute` and without and it didn't work
```csharp
[Get("/api/v1/log/audit/domain/{logIds}")]
Task<HttpResponseMessage> TestAsync(
    [AliasAs("logIds"), Query(CollectionFormat.Csv)] IEnumerable<Guid> logIds,
    CancellationToken cancellationToken
);
```

**Comment by kmcclellan** [comment]
> @kmcclellan can you elaborate please how to use this?

Hi, that workaround works with the global collection format on `RefitSettings`, not the one on `QueryAttribute`. Hope this helps!

```c#
var refitSettings = new RefitSettings().WithPathCollections();
refitSettings.CollectionFormat = CollectionFormat.Csv;
services.AddRefitClient<ILogServiceClient>(refitSettings);
```
