### ISSUE TITLE
feature: Add the possibility to set Properties in HttpRequestMessage

### ISSUE THREAD

**Issue by unleashed-jamest** [reactiveui/refit#809]
**Is your feature request related to a problem? Please describe.**

Currently there isn't a (nice) way to pass data to your pipeline of DelegatingHandler classes. 

**Describe the solution you'd like**

What I would like to see is the ability to place data into HttpRequestMessage.Properties dictionary on a per-request basis. It should function basically the exact same way the Headers and Header attributes do, except you pass in key value pairs and they get stored in the HttpRequestMessage.Properties. 

**Describe alternatives you've considered**

I currently am using the Headers and Header attributes to accomplish this goal, but it's a nasty hack. It works, but it's not a nice solution. It's not what HTTP headers are intended for. I currently have 3 very different logging concerns that I take care of using a series of DelegatingHandler classes and each pulls out the header(s) its looking for and logs the contents if certain criteria are met. For example I need to log a friendly error message in a user facing log so there is one handler for that and the exception message (if the result is non 200) is stored in a header that I pull out and throw an exception which bubbles up to the client. I also need to log a success message in a user facing log if the request succeeded, so there is a header for that. Plus some diagnostics information for instrumenting performance and tracing metrics on the whole pipeline etc.

**Describe suggestions on how to achieve the feature**

It looks like it's not too hard to do, and if you agree with the approach I'd be happy to submit a PR. 
How I would implement it is add two new attributes `PropertiesAttribute` and `PropertyAttribute` and in the constructor of `RestMethodInfo.cs` extract the values present on the MethodInfo and MethodParams pretty much exactly the same as Headers and Header attributes do it and store them on the `RestMethodInfo` class.  

Then inside `RequestBuilderImplementation` take the Properties we saved in `RestMethodInfo` and populate them into the `HttpRequestMessage.Properties`

The one problem I can see is that all the building of those request objects is currently cached.  So, you'd need to be able to opt-out of caching either manually (with an attribute) or automatically (if Property attribute is detected) or update the cache key to include Property parameters key AND value pairs.

**Comment by clydevassallo** [comment]
Was this ever considered?

This would enable us to pass complex objects to [DelegatingHandlers](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=netcore-3.1) through the [HttpRequestMessage](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage?view=netcore-3.1)'s [Properties](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.properties?view=netcore-3.1) Dictionary which would be quite handy. 

I don't think it's currently possible to do so when using Refit without this feature.

**Comment by unleashed-jamest** [comment]
We wound up mimicking the desired behavior as close as we could by passing data via headers (can't do a complex object, sadly) where the headers follow a naming convention. Then we have a delegating handler at the beginning of the pipeline that leverages the naming convention to strip those headers off the request and migrate them into the HttpRequestMessage.Properties

That way at least inside our delegating handlers we can pull the data from the Properties, so if this ever does get implemented we don't need to make changes there.

Maybe I should just try submit a PR for this and see if it gets a better response... would really like to see it added to Refit. It's very handy indeed.

**Comment by clydevassallo** [comment]
I was doing something similar to work around this limitation however I encountered a particular use-case which requires me to pass a complex object to my delegating handler and the Properties dictionary would be perfect for this. 

I can't think of any reason why a PR adding this feature would be rejected. [RestEase](https://github.com/canton7/RestEase) already has [this implemented](https://github.com/canton7/RestEase#adding-to-httprequestmessageproperties) so I imagine it would end up looking quite similar here.

**Comment by unleashed-jamest** [comment]
Wow. Can't believe I never came across RestEase in my travels. What a great programming model too with being able to add a common object to all requests.

**Comment by clydevassallo** [comment]
Yeah the interface is very similar to Refit but they offer slightly different feature sets. Unfortunately neither of them offers both access to HttpRequestMessage Properties AND registration through the HttpClientFactory, yet.

**Comment by clydevassallo** [comment]
Will you be opening a PR to add support for HttpRequest Parameters here or should I? :) 
Really rooting for this feature

**Comment by unleashed-jamest** [comment]
Strike while the iron is hot my friend. Go for it. I'm rooting for this too.

**Comment by damianun** [comment]
@clydevassallo @unleashed-jamest any update on pull-request guys?

**Comment by unleashed-jamest** [comment]
@damianun I've worked around it for now. I've got some work coming up which will involve using more Refit and if the need arises during that I might see if I can throw something together, other than that i'm otherwise occupied at the moment.

**Comment by nicostouch** [comment]
@clydevassallo @damianun I finally got a PR https://github.com/reactiveui/refit/pull/1001 for this submitted.
