### ISSUE TITLE
feature: simple way to post api 

### ISSUE THREAD

**Issue by bill2004158** [reactiveui/refit#810]
Retrofit 2 do like this:
> public interface TaskService {  
>    @FormUrlEncoded
>    @POST("tasks")
>    Call<TaskObj> createTask(@Field("title") String title, @Field("message") String message);
>}

while in Refit, we have to do like this:
> public interface TaskService {  
>     [Post("tasks")]
>    Task<TaskObj> createTask([Body(BodySerializationMethod.UrlEncoded)] RequestObj);
>}

which require extra object or dictionary object.
that seems a bit complex for such simple case.

so I think it is better, refit could support similar thing like Retrofit.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
