### ISSUE TITLE
Timeout Happens iOS specific

### ISSUE THREAD

**Issue by RPiyush** [reactiveui/refit#821]
I am consuming one API in my Xamarin Form app, it is working in UWP app, but when I tries to run iOS app, timeout is occurring. Any one faced this issue?

System.Net.WebException: The request timed out. ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600002c11170 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <33614DF2-9E0A-4270-BA25-605613DC2954>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <33614DF2-9E0A-4270-BA25-605613DC2954>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://demoserver.com/rest/v1/inspections/get_inspections, NSErrorFailingURLKey=https://demoserver.com/rest/v1/inspections/get_inspections, _kCFStreamErrorDomainKey=4}
   --- End of inner exception stack trace ---
  at ModernHttpClient.NativeMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x002a5] in /Users/paul/code/paulcbetts/modernhttpclient/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs:139

**Comment by Cheesebaron** [comment]
How about not using ModernHttpClient and using NSUrlSessionHandler? Just curious about why you are using code that hasn't been maintained for over 4 years?

**Comment by RPiyush** [comment]
@Cheesebaron we need to use same code for iOS, windows and Android.

**Comment by Cheesebaron** [comment]
Which has nothing to do with ModernHttpClient. I highly suggest you remove all references to ModernHttpClient, that project is dead and will only cause you issues.

**Comment by RPiyush** [comment]
@Cheesebaron Thanks, I removed ModernHttpClient and uses Native handler with dependency services. It is working for me..
