### ISSUE TITLE
[BUG] Refit- How to send multipart/form-data body request without uploading a file?

### ISSUE THREAD

**Issue by AdrianSTANCULESCU** [reactiveui/refit#822]
Hi guys,
I'm trying to port some code from retrofit2 to refit.
The retrofit version is like this:
@POST("user/me/") @Multipart Observable<UserResponse> getProfile(@Part MultipartBody.Part part, @Part MultipartBody.Part part2);

If I use multipart with strings in my c# code, the request is different that retrofit2 request.
Also by copy pasting retrofit2 request in postman generates an error.
Bellow can find some screenshots.
Thanks.
![Screenshot_20200109-114322_Gallery](https://user-images.githubusercontent.com/7832842/72081528-527e0680-3307-11ea-8c91-71d5ae277b26.jpg)
![20200109_114607](https://user-images.githubusercontent.com/7832842/72081550-5ca00500-3307-11ea-9b7c-9a064dc18d50.jpg)

**Comment by benjaminhowarth1** [comment]
Hi Adrian, can you paste your Refit C# code in please that's not working?

**Comment by AdrianSTANCULESCU** [comment]
Hi @benjaminhowarth1 
Here is the code that I have tried:
//declaration method in interface
[Multipart("644e1dd7-2a7f-18fb-b8ed-ed78c3f92c2b")]
[Headers(blabla)]
Task<string> Login(string devLoc, string contentHead, string usr, string pass, string quality)
...
//api call
  //login api call
            string guidS = "644e1dd7-2a7f-18fb-b8ed-ed78c3f92c2b";
            var contentTypeHeader = $"Content-Type: multipart/form-data; boundary={guidS}";
            string username = "username";
            string password = "password";
            string getImageQuality = "quality";
            var loginResponse = await myApi.Login(ouDeviceLocationHeader, contentTypeHeader, username, password, getImageQuality);

The problem is that after content-type no parameter is inside quotes, and after each parameter there is no content-length, so the request is dropped by the server.

Thanks.

**Comment by AdrianSTANCULESCU** [comment]
Hi benjamin,
Another issue might be "MyGreatBoundary" according to the documentation:
"A custom boundary can be specified with an optional string parameter to the Multipart attribute. If left empty, this defaults to ----MyGreatBoundary."
The optional string parameter can be only a hardcoded value, so cannot be changed at runtime.
In my manual webrequest I did something like that:
HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
string guid = Guid.NewGuid().ToString();
request.ContentType = $"multipart/form-data; boundary={guid}";
....
So instead of hardcoded boundary or Multipart attribute, I think can be done easy by generating guid on the fly.
Thanks,
Adrian.

**Comment by ranjanpr** [comment]
@AdrianSTANCULESCU I am also facing same issue. Are you able to do it?

**Comment by AdrianSTANCULESCU** [comment]
Hi @ranjanpr 
Currently I'm doing this part of code with classic webrequests. 
There is a nice fiddler plugin: http://www.chadsowald.com/software/fiddler-extension-request-to-code
where you can see the request directly converted to c# code. So for the moment solved my issues, even the code is not as clean as with refit.
Good luck!

**Comment by ranjanpr** [comment]
@AdrianSTANCULESCU  Thanks for the fiddler extension. I think it is not possible right now with current refit. I did the same HttpWebRequest for multipart form-data. 
Hope it gets supported in future versions. One idea could be like in multi-query we use  `[Query(CollectionFormat.Multi)]` similarily we can have `[StreamPart(CollectionFormat.Multi)]` or something similar. Not sure how much is it possible. If possible we can create a feature request for its support. Also custom boundary seems broken even for single streampart currently.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by angularsen** [comment]
This is still an issue in Refit 6.3.2.

We are trying to write a client for Mailjet and it requires passing all parameters as multi-part data, even if no file upload is involved. [API examples](https://documentation.mailgun.com/en/latest/api-sending.html#examples).

Example 
```cs
public interface IMailgunSendingApi
{
    [Multipart]
    [Post("/{domain}/messages")]
    Task<SendMessageResponse> SendHtmlAsync(string domain,
        string from,
        string to,
        string subject,
        string text,
        CancellationToken ct = default);
}

public record SendMessageResponse(string id, string message);
```

```cs
var mailgunSendingApi = services.GetRequiredService<IMailgunSendingApi>();

await mailgunSendingApi.SendHtmlAsync(domain: "mail.mar.io",
    from:  "itsame@mar.io",
    to: "lui@gi",
    subject: "My subject",
    text: "My HTML text.");
```

No request body is populated and it for some reason ends up using GET method, even if specifying `[Post]` attribute.

**Comment by josephchrisman** [comment]
Also seeing this issue. The API I am calling uses a GUID in the boundary and the `Multipart` attribute does not allow for generated values.
