### ISSUE TITLE
Refit does not respect the BaseAddress of a provided HttpClient when creating rest services

### ISSUE THREAD

**Issue by trinitrotoluene** [reactiveui/refit#823]
**Describe the bug**
Locations provided to endpoints on a refit interface should seamlessly be appended to the HttpClient provided as long as the result is a valid URL when combined with that client's BaseAddress.

Instead refit throws an ArgumentException when calling RestService.For<T>(httpClient) if the endpoint is not prefixed with "/"

This is a problem because if your remote API has a base URL that includes a path, for example http://example.org/api/, HttpClient strips the "/api" location from its BaseAddress if it does not include a trailing "/". This is in conformance with the URI standard and is therefore rather an issue on refit's end.

**Steps To Reproduce**
- Create a refit endpoint
```
[Get("foo/bar")]
async Task FooAsync();
```
- Configure an HttpClient's BaseAddress to be `http://example.org/` (in the URI standard a trailing / is the correct way to indicate directories, HttpClient will strip out any trailing location for example).
- Attempt to call RestService.For() on your interface
- ArgumentException is thrown

**Expected behavior**
Request should be addressed to https://example.org/foo/bar

**Comment by WesleyJesus99** [comment]
Hello, create a pull request to solve this problem.
could you analyze if you agree?

Any doubts, suggestions or constructive criticism will be welcome.

Thanks.

https://github.com/reactiveui/refit/pull/831

@benjaminhowarth1

**Comment by clairernovotny** [comment]
Trying to isolate the issue but all paths in Refit attributes must be absolute as they'll be added to the base url. `[Get("foo/bar")]` is invalid, it should be `[Get("/foo/bar")]`
