### ISSUE TITLE
[BUG] Post without a body don't specify content length header

### ISSUE THREAD

**Issue by hahn-kev** [reactiveui/refit#833]
**Describe the bug**
When sending a request with default settings using the following interface method it sends a request without a Content-Length header, even though it's a post. In Some cases that's ok, but it should really include the header to be compliant.
```C#
[Post("/notification/email")]
Task SendEmailNotification(string emailAddress, string subject, string message);
```

It looks like #112 reported this same issue, but only when you have custom headers. I don't have custom headers and I'm still having the same issue.

**Expected behavior**
I would expect if no body parameter is specified then the request should include a content length header with the value 

**Environment**
- ASP.NET Core 3.1 Kestrel release build

**Comment by clairernovotny** [comment]
Hi,

Content-Length is only required for HTTP/1.0, not 1.1, so we don't send it. If your server requires a Content-Length header, the easiest way is to set a content header and Refit will send empty content with it.
