### ISSUE TITLE
[BUG] Refit.HttpClientFactory 5.x Forces Libraries to .NET Core 3 based dependencies

### ISSUE THREAD

**Issue by CreepyGnome** [reactiveui/refit#835]
**Describe the bug**
After upgrading to Refit.HttpClientFactory 5.x everything broken as we are .NET Core 2.1 and .NET Standard 2.0. 

It seems to be due to its dependencies on
- Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.1.1)
- Microsoft.Extensions.Logging (>= 3.1.1)
- Microsoft.Extensions.Options (>= 3.1.1)

**Steps To Reproduce**

1. A project that targets netcoreapp2.1
2. Include a package reference Microsoft.AspNetCore.App Version 2.1.1
3. Include a package reference Refit.HttpClientFactory 5.0.23 
4. Try to compile

error NU1107: Version conflict detected for Microsoft.Extensions.Configuration. Install/reference Microsoft.Extensions.Configuration 3.0.0
error NU1107:  WebApp -> Refit.HttpClientFactory 5.0.23 -> Microsoft.Extensions.Http 3.0.0 -> Microsoft.Extensions.Logging 3.0.0 -> Microsoft.Extensions.Configuration.Binder 3.0.0 -> Microsoft.Extensions.Configuration (>= 3.0.0) 
error NU1107:  WebApp -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Configuration (>= 2.1.1 && < 2.2.0)

So AspNetCore 2.1.1 depends on Microsoft.Extensions.Configuration 2.1.1 but Refit Refit.HttpClientFactory 5.0.23 depdends on Microsoft.Extensions.Configuration 3.0.0 so it fails. 

**Expected behavior**
That upgrading Refit to a 5.x version that still claims to be .NET Standard 2.0 complaint would not depend on libraries that are outside the scope of .NET Standard 2.0 and can and do cause forced upgrades to 3.x libraries. Libraries that many companies cannot jump to because they rely on Microsoft LTS 2.1 version .NET Core.

**Comment by onovotny** [comment]
The newer versions of the packages are supported on .NET Core 2.1. Refit, as policy, always uses the latest versions of its dependencies, long as they support the minimum .NET Standard/.NET Core version that refit itself does.

.NET Core 2.1 is a runtime and can run the Microsoft.Extensions.Configuration 3.1.1 packages.

BTW, I would not recommend using Microsoft.AspNetCore.App 2.1.1 as it has multiple CVE's issued against it. Use at least 2.1.15.

That said, it seems like ASP.NET Core 2.1.x has a <= 2.2 requirement on Microsoft.Extensions.Configuration. They don't support a newer version in conjunction with that package. There's not much we intend to do about that; as a volunteer project, we do not follow the LTS policy of every package as we do not have the resources to do so. You are welcome to fork/build a private copy which targets older dependencies if you need it.

**Comment by CreepyGnome** [comment]
This also occurs on 4.8.14 which is when you added that blocking dependency.

I am aware of the Microsoft.AspNetCore.App 2.1.1 is at 2.1.15 but I don't control the environments we deploy to.  For kicks I tried it locally but that doesn't resolve this issue. 

> That said, it seems like ASP.NET Core 2.1.x has a <= 2.2 requirement on Microsoft.Extensions.Configuration. They don't support a newer version in conjunction with that package.

Exactly that is what I stated the issue is and that you can fix by using 2.1.1 of Microsoft.Extensions.Configuration libraries.

Your rules are not decided for enterprises, do you only support startups or something? 

We went in this circle before about you just marching blindly forward on bleeding edge packages without vetting them.

How can you be a REST library that doesn't work with the LTS version of ASP.NET Core?? Do you not have any tests that test within ASP.NET?

We have invested a lot of time in building around Refit and now after two bugs related to how you choose to release and just auto-upgrade your package dependencies to the latest are causing us lots of headaches.

Would you possibly consider provided an LTS version that you could support for enterprises?  This way it gets bug fixes and security fixes just no breaking changes/features.

**Comment by onovotny** [comment]
> Would you possibly consider provided an LTS version that you could support for enterprises? This way it gets bug fixes and security fixes just no breaking changes/features.

If there's a paid/support option, then perhaps. None of the maintainers is getting paid for their work in this project. The beauty of open source is that anyone is welcome to fork and/or rebuild a private copy.

The policy will continue, we will only maintain the latest versions of dependencies as we do not have the resources to support things for as long as Microsoft does.

**Comment by CreepyGnome** [comment]
So you are not an enterprise-grade library. 

Plus we have a chicken and egg situation as if you provided a paid LTS version I know we and others would pay for it depending on the cost.  However, you are "perhaps" on that meaning that unless you had people already paying to do it you are not going to provide it seems. 

We have already hacked are way around limitations and bugs and wanted to see how far we can upgrade to and at what cost it will be to the teams. So if I am lucky I can only get to 4.7.51 which I know is one version from a bug fix we would like to have that I know is in 5.0.15 but I think may also be also in 4.8.14.  However, it will not remove any of are workarounds.

I guess I will stop reporting bugs that require downgrading libraries to fix and trying to get the 2nd most popular .NET REST library to be enterprise-class.

**Comment by anaisbetts** [comment]
You're absolutely free to fork and maintain this library yourself against upstream, and we're thankful for your contribution. That being said, please take this enterprise-grade entitlement somewhere else.

**Comment by CreepyGnome** [comment]
Wow, great attitude there @anaisbetts.

How is it being entitled to just wanting a library you've used for years and love to just work for people who have to use supported LTS versions of Microsoft ASP.NET Core and would like to be able to get the bug fixes that it releases at the same time?

**Comment by onovotny** [comment]
I appreciate the difficulty of having to use older LTS versions of products. Open Source libraries are not free, there is always a cost, and the cost is in maintainers time. It is not reasonable to expect that unpaid library maintainers support things "just because it's LTS". That's Microsoft's LTS policy, not this project's.
