### ISSUE TITLE
Interface default (static) methods are not working with Refit in C# 8+

### ISSUE THREAD

**Issue by rodion-m** [reactiveui/refit#845]
**Describe the bug**
C# 8.0 allows to define default methods for interface (include static) and this feature gives us a very useful possibility like a creating a default factory for a Refit service.

**Example code**
```csharp
public interface IClient
{
	[Get("/events.json")]
	Task<Events> GetEvents(string query);

	public static ITimepadClient Create()
	{
		var settings = new RefitSettings
		{
			ContentSerializer = new JsonContentSerializer()
		};
		return RestService.For<ITimepadClient>("service_url", settings);
	}
}
```
Now we may easily create a configured service like this: `var client = IClient.Create()`.
But it's not working, because the interface is not compiling with error:
`  RefitStubs.g.cs(63, 32): [CS0539] 'AutoGeneratedIClient.Create()' in explicit interface declaration is not found among members of the interface that can be implemented`

**Environment**
.NET Core 3.1, C# 8.0
Refit 5.0.23

**Additional context**
Please fix it and add support for default static methods and also for local default methods.

**Comment by clairernovotny** [comment]
This should be working in the latest code:
https://github.com/reactiveui/refit/commit/03cdde45d07faa3f07a10ea15368595abf1d5f78
