### ISSUE TITLE
feature: [Body(BodySerializationMethod.Serialized)] string include parameter name

### ISSUE THREAD

**Issue by bugproof** [reactiveui/refit#846]
e.g. 

`Task<ApiResult<Product>> GetProductInfo([Body(BodySerializationMethod.Serialized)] string code);`

sends `"xxx"`, but I would like it to send `{"code": "xxx"}` without creating another class with Code property.

**Comment by AdrianSTANCULESCU** [comment]
I think can be done like this:
Task<ApiResult<Product>> GetProductInfo(RequestCode requestCode);

class RequestCode
{
    public string code;
}
// and call
RequestCode rc = new RequestCode();
rc.code = "xxx";
var response = await iapi.GetProductInfo(rc);

Is not as expected, but worked for me.
Cheers.

**Comment by bugproof** [comment]
I know, but I didn't want to create another class just for 1 property

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
