### ISSUE TITLE
[BUG] AuthorizationHeaderValueGetter not used when HttpClient is passed instead of Uri

### ISSUE THREAD

**Issue by jmichas** [reactiveui/refit#850]
**Describe the bug**
When using the RestService.For<> and passing in RefitSettings that includes the AuthorizationHeaderValueGetter set, the AuthorizationHeaderValueGetter does not fire when an HttpClient is passed to the For<>() method.

For example:
This does not work: (where client is an existing HttpClient)
````
var service = RestService.For<IMyApi>(Client, new RefitSettings{AuthorizationHeaderValueGetter = () = > Task.FromResult(_token)});
````
while this works:
````
var service = RestService.For<IMyApi>("http://mybaseaddress", new RefitSettings{AuthorizationHeaderValueGetter = () = > Task.FromResult(_token)});
````

**Steps To Reproduce**
The only significant step in my usage is I am attempting to use this in an integration test using WebApplicationFactory which provides its own HttpClient implementation. I do not know and cannot figure out what is different about the test server client from a normal HttpClient. But attempting to use an HttpClient using the localhost base url does not work to hit the TestServer controllers.

**Expected behavior**
I expect the auth header to be set via a call to AuthorizationHeaderValueGetter.

**Environment**

- OS:       
- Device:   
- Version:   
- Working Version: 

**Additional context**

**Comment by clairernovotny** [comment]
So far this is by design as the HttpClient doesn't allow its pipeline to be modified.

What is the scenario where you'd want to use an existing HttpClient instance for this instead of supplying the string url? 

The fix here may be documentation update noting this.
