### ISSUE TITLE
ValidationApiException HasContent is false when Content is not null

### ISSUE THREAD

**Issue by jmichas** [reactiveui/refit#852]
**Describe the bug**
Returning a ValidationProblem from aspnet core api throws a ValidationApiException.
The HasContent is false when the Content property is set to a ProblemDetail object with Errors present.

**Steps To Reproduce**
Create a simple controller action like this:
```
[Route("ValidationProblem")]
public async Task<IActionResult> ValidationProblem([Required] string id, [Required] string name)
{
    await Task.Delay(0);
    if (!ModelState.IsValid)
    {
        return ValidationProblem(ModelState);
    }

    return NoContent();
}
```
Call it from the refit library passing null for the arguments and inspect the ValidationApiException.

**Expected behavior**
I expect that HasContent would be true if the Content property is not null.
Is HasContent only true if Content.Details is not null?

How do I know to check for validation errors from serialized modelstate without doing an
`exception.Content!=null && exception.Content.Error!=null` every time I catch a ValidationApiException?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
