### ISSUE TITLE
[BUG] Response Content is null when a custom DelegateHandler is in the request pipeline

### ISSUE THREAD

**Issue by azho472** [reactiveui/refit#853]
**Describe the bug**
I have registered a typed client in Startup.cs, with additional HttpMessageHandlers. However, when a Bad Request is thrown by the API which I call, I am unable to get the content of the response body. 

**Steps To Reproduce**
1. Register a TypedClient in Startup.cs 
```
services.AddHttpClient("user", client => {
    client.BaseAddress = new Uri("localhost:4000/api");
 })
.AddTypedClient(client => Refit.RestService.For<IUserApi>(client))
.AddHttpMessageHandler<CustomerHandler>();
```

2. Add a custom DelegateHandler as described here: https://github.com/reactiveui/refit#authorization-dynamic-headers-redux
Edit 9 Apr 2020: I've tested without the custom HttpHandler with same result below. 
3. Call a Post API with a return type of Task i.e. `Task AddUser(...);`
4. Have the API return a 400 Bad Request, with a error response body. 
I.e. `{ "error": "errorMessage", "errorDescription": "errorDescription" }`
5. Catch ApiException and retrieve content like: `var error = ex.GetContentAs<T>();`. (solution from https://github.com/reactiveui/refit/issues/231) where T is the expected error object
6. `error` will be null

Note: I've tried to read the content stream in the DelegateHandler and have gotten the response body successfully
```
  var response = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
  var receiveStream = await response.Content.ReadAsStreamAsync();
  StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8);
  var t = readStream.ReadToEnd();
  return response;
```
**Expected behavior**
Response body for errors are readable when ApiException is thrown due to 400 Bad Request.
i.e. in step 6 above, error will be the error object 

**Environment**
.NET Core 2.2
Refit v5.0.23

**Comment by azho472** [comment]
Bump?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
