### ISSUE TITLE
Methods with a Delete attribute not working in Client Side Blazor

### ISSUE THREAD

**Issue by HankyPanky99** [reactiveui/refit#855]
Hello!

I have spent some time trying to figure out why all CRUD methods work except the Delete method. I am pretty new to the Refit solution but after looking at Nick Chapsas youtube tutorial "Creating an API SDK with Refit " (https://youtu.be/grBTYaTGLv8), i decided to look into this since it looked really powerful. My implementations follow that exact logic.

When running the Delete method in a Client Side Blazor project, the method returns a "System.ArgumentException: Invalid argument: source can not be null and must have a length" error. When I run the exact same function in a Server Side Blazor project or a .Net Core Console app, it works without any problem.

My solution consists of three projects:
SDK -> Refit Interface:
Blazor Client Side
Web Api

SDK:
My interface looks like this:
```
[Headers("ApiKey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")]
public interface IBIMServicesApi
    {
        [Delete("/api/v1/bimobjects/{bimobjectguid}")]
        Task<ApiResponse<string>> DeleteBIMObjectAsync(Guid bimobjectguid);
    }
```

Blazor Client Side:
The implementation in the standard razor compent page, looks like this.

Observe that the guid variable below has a value, this is controlled in google chrome debug. I have just removed the code retreiving it to make it shorter.

```
protected async override Task OnInitializedAsync()
    {
        IBIMServicesApi bimServicesApi;
        bimServicesApi = RestService.For<IBIMServicesApi>("https://localhost:44331");
        var deletedPost = await bimServicesApi.DeleteBIMObjectAsync(guid);
    }
```

WebApi:
Controller implementation:
The controller injects the bimService via DI.

```
[HttpDelete(ApiRoutes.BIMObject.Delete)]
public async Task<IActionResult> Delete([FromRoute] Guid bimobjectguid)
        {
               var deleted = await bimService.DeleteBIMObjectAsync(bimobjectguid);

                if (deleted)
                {
                    return NoContent();
                }
                else
                {
                    return NotFound();
                }
        }
```

Interface:
```
public interface IBIMService
{
        Task<bool> DeleteBIMObjectAsync(Guid bimobjectguid);
}
```

Class that implements Interface:
```
    public class BIMService : IBIMService
        public async Task<bool> DeleteBIMObjectAsync(Guid bimobjectguid)
        {
            var result = await GetBIMObjectAsync(bimobjectguid);

            if (result == null)
            {
                return false;
            }

            context.BIMObjects.Remove(result);
            var deleted = await context.SaveChangesAsync();

            return deleted > 0;
        }
}
```

**Environment**
Google Chrome Version 80.0.3987.132 (64 bit)
Windows 10 Version 1909

WebAPI: -> NetCore 3.1
```
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Dapper" Version="2.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="1.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0" />
  </ItemGroup>
```

Blazor Client Side -> .NetStandard 2.1
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.2.0-preview1.20073.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.2.0-preview1.20073.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Refit.HttpClientFactory" Version="5.0.23" />
  </ItemGroup>
```

Sdk Project -> .Net Standard 2.1
```
  <ItemGroup>
    <PackageReference Include="refit" Version="5.0.23" />
  </ItemGroup>
```

Error messages popping up in Google Chrome console after executing Delete method in Client Side Blazor app:
![2020-03-15_12-14-00](https://user-images.githubusercontent.com/29940591/76738270-9ad3fd80-676a-11ea-832d-b016f726fb82.png)

Please let me know if there is anything else needed. I hope it gives you something .
/Henrik

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. This definitely looks like a bug.

I've filed https://github.com/mono/mono/issues/19288 and will close it as external in this repo.

**Comment by HankyPanky99** [comment]
Great, i hope i got it right. Does this mean that i get notified automatically in the future when there are updates in thread?

Thanks 😀




Best Regards/Vänliga hälsningar

Henrik Bengtsson

23 mars 2020 kl. 12:50 skrev Steve Sanderson <notifications@github.com>:

﻿

Sorry for the inconvenience. This definitely looks like a bug.

I've filed mono/mono#19288<https://github.com/mono/mono/issues/19288>

**Comment by clairernovotny** [comment]
@HankyPanky99 Best to follow mono/mono#19288 to ensure you get updated.

**Comment by HankyPanky99** [comment]
Check,  thanks 💪🏻




Best Regards/Vänliga hälsningar

Henrik Bengtsson

23 mars 2020 kl. 16:18 skrev Claire Novotny <notifications@github.com>:

﻿

@HankyPanky99<https://github.com/HankyPanky99> Best to follow mono/mono#19288<https://github.com/mono/mono/issues/19288> to ensure you get updated.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
