### ISSUE TITLE
Microsoft.Extensions.Http: The 'additionalHandlers' must not contain a null entry.

### ISSUE THREAD

**Issue by kaluznyt** [reactiveui/refit#857]
Hi, 

These are relevant versions of framework libs in the azure function I'm using:

TargetFramework: netcoreapp3.1 
AzureFunctionsVersion: v3 

PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" 
PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" 
PackageReference Include="Newtonsoft.Json" Version="12.0.3" 
PackageReference Include="Refit" Version="5.0.23" 
PackageReference Include="Refit.HttpClientFactory" Version="5.0.23" 

Not really sure if I'm doing something wrong, or it is some kind of bug, but I register the Refit client as in most tutorials/online docs, therefore it looks like:

            builder.Services.AddRefitClient<IRefitApiClient>(_refitSettings)
                .ConfigureHttpClient(ConfigureClient)
                .AddHttpMessageHandler<CustomAccessTokenDelegatingHandler>();

Then I'm getting the following exception:

 Microsoft.Extensions.Http: The 'additionalHandlers' must not contain a null entry.
[3/20/2020 6:35:40 PM] An unhandled host error has occurred.
[3/20/2020 6:35:40 PM] Microsoft.Extensions.Http: The 'additionalHandlers' must not contain a null entry.

But I've found a workaround which basically works:

            services
                .AddHttpClient(typeof(T).FullName)
                .ConfigureHttpClient(ConfigureClient)
                .AddTypedClient(c => RestService.For<T>(c, refitSettings))
                .AddHttpMessageHandler<CustomAccessTokenDelegatingHandler>();

The question is, is it some bug or am I registering it in a wrong way in the first example ?

Thanks
Tomasz

**Comment by rmaziarka** [comment]
I had the same problem. It turned out that the first registration requires adding a handler to services.
`            builder.Services.AddSingleton<CustomAccessTokenDelegatingHandler>();`
Then it works without an error.
