### ISSUE TITLE
[Refactoring] Use separate files per each type

### ISSUE THREAD

**Issue by Dreamescaper** [reactiveui/refit#859]
Currently it's quite hard to navigate across repository (especially if you're attempting to take a quick look directly in GitHub, not in VS).
So I'm wondering if there's any specific reason in keeping multiple types per file (e.g. Attributes.cs contains 18 types)?

Can we split those files to have 1 type per file (and probably put them to subfolders, e.g. Attributes/Settings/etc)? Alternatively - with the exception of generic and non-generic types with same name (e.g. `ApiResponse` and `ApiResponse<T>`).

I'd be willing to submit PRs for that, unless there are objections.

**Comment by clairernovotny** [comment]
@anaisbetts any thoughts?

**Comment by anaisbetts** [comment]
No, this trashes git blame and one class per file is Inherently Bad
