### ISSUE TITLE
feature: Housekeeping - move documentation out of Readme.MD into wiki

### ISSUE THREAD

**Issue by benjaminhowarth1** [reactiveui/refit#871]
**Is your feature request related to a problem? Please describe.**
Reamde.md is getting extremely large and should ideally be broken up into consumable chunks & hosted on GH wiki

**Describe the solution you'd like**
I'm happy to start triaging the Readme.md over to the wiki section

**Describe alternatives you've considered**
N/A

**Describe suggestions on how to achieve the feature**
Take sections of the Readme.md and convert to separate pages with links from the wiki homepage

**Additional context**
N/A

**Comment by Styxxy** [comment]
It would be nice though if it can be published from the repo itself, so also the documentation can live closely to the code.

Generally I use a "docs" folder in my repos for that exact purpose.

**Comment by clairernovotny** [comment]
No. This is used for the static site generation on GitHub pages.
