### ISSUE TITLE
Question: Nothing in the documentation about Task<ApiResponse<T>> return type?

### ISSUE THREAD

**Issue by sidm1983** [reactiveui/refit#872]
Hi,

First of all, I would like to thank you all for creating refit. I absolutely love how simple it is to set up and use. Absolute genius!

So, I have a question. I was researching how to read response headers when using refit and I couldn't find anything on the main refit GitHub Pages site (https://reactiveui.github.io/refit/).

I then stumbled upon this old [issue](https://github.com/reactiveui/refit/issues/23), and found out that I could specify `Task<ApiResponse<T>>` as my return type and that would have all the header information along with my strongly-type content object representing the response body.

Why is this return type not mentioned in the main refit documentation? Is ApiResponse<T> obsolete or not working properly? Should I not be using it? If not, then is there a better way to read response headers? Otherwise, if it is still in use, then shouldn't it be added to the documentation?

Please let me know when you get a chance. Thank you. 🙏🙌❤️

**Comment by clairernovotny** [comment]
Thanks. We try to keep the docs up to date but there are clearly gaps. We always appreciate PR's to the docs if you would like to fix that!

**Comment by sidm1983** [comment]
No worries @clairenovotny. I’ll submit a PR to update the documentation soon. Thank you.

**Comment by sidm1983** [comment]
Hi @clairernovotny, before updating the documentation, I wanted to test out having one of my API interface methods return a `Task<ApiResponse<T>>`, however, I seem to be getting an ArgumentNullException being thrown at line 24 in the `ApiResponse.cs` file.

https://github.com/reactiveui/refit/blob/5216edc51385a4ffc994c3239d5f73c046d9807c/Refit/ApiResponse.cs#L24

I am fairly new to refit and I am unsure why the response object being passed in to the ApiResponse constructor is null. I have been debugging my own code and reading refit code for a while and can't seem to figure out what is going wrong. Have you seen or heard of this issue before?

The API call works fine if my return type is `Task<PostmanEchoPostResponse>`, but doesn't work as soon as I change it to `Task<ApiResponse<PostmanEchoPostResponse>>` (see code snippet below). Is there something else I need to do to get this working?

I am testing this on .net core 3.1 and currently using Refit v5.1.27 which I installed via nuget. Also, just an FYI, this .net core 3.1 app I am building is a Durable Azure Function project. Here is my test API interface for base address https://postman-echo.com:

```c#
public interface IPostmanEchoApi
{
    [Post("/post")]
    Task<ApiResponse<PostmanEchoPostResponse>> Post([Body] TagRequest request);
}

public class TagRequest
{
    public IEnumerable<string> Objects { get; set; }

    public TagRequest(IEnumerable<string> tags) => Objects = tags;
}

public class PostmanEchoPostResponse
{
    public TagRequest Json { get; set; }
}
```
And then I am calling it using the code below:
```c#
var postmanEchoService = RestService.For<IPostmanEchoApi>("https://postman-echo.com");
var response = await postmanEchoService.Post(new TagRequest(objects));
```
Any thoughts, ideas or pointers would be greatly appreciated. Thank you.

**Comment by sidm1983** [comment]
@clairernovotny I did some more debugging and troubleshooting of my code and it turns out that it is not an issue with refit. 🤦‍♂ Ah the wonders of stepping away from code, getting a good night's sleep and rubber ducking. 🛌🦆😂

Turns out it is a limitation in how Durable Orchestration works in Azure Functions. Basically, the ApiResponse<T> return type gets serialized to JSON in one of my azure functions and then gets deserialized back to an object by the orchestrator function. At that point, the JSON serializer was having trouble re-instantiating some properties within the ApiResponse object hierarchy as they are based on an abstract class or interface. I've solved it by returning my own custom POCO that will hold only the bits of the response I need. Just thought I'd share what I found here in case someone else using Durable Orchestrations finds their way here.

Apologies for spamming you with the above issue. Will update the documentation when I get some time in the next few days. Thank you.

**Comment by sidm1983** [comment]
Hi @clairernovotny, as promised, I have added documentation and examples for the `ApiResponse<T>` return type. Please review the linked PR when you get a chance. Also, please let me know if I need to make changes anywhere else other than the main readme file in order for the changes to be shown on the main documentation site once the PR has been merged. Have a great day! 😄
