### ISSUE TITLE
[BUG] Stubs No Longer Compiles If Namespaces Overlap

### ISSUE THREAD

**Issue by acgritt** [reactiveui/refit#876]
**Describe the bug**
Using statements with names that overlap are no longer properly respected when compiling the RefitStubs.g.cs. It generates the error "The type or namespace name 'Security' does not exist in the namespace 'Project.Common' (are you missing an assembly reference?)". This was working just fine with version 5.0.23.

**Steps To Reproduce**
1. Create a class that uses namespaces similar to the following:
```cs
using Common.Security;
using Project.Common;
```
A workaround currently is to do the following:
```cs
using Project.Common;
using SomeType = global::Common.Security;
```
**NOTE** `global::` is required to make the code compile correctly.

**Expected behavior**
It should compile without error and without having to add `global::` or `using SomeType = global::Common.Security.SomeType;`. Just referencing `using Common.Security;` should compile.

**Environment**
- OS: Windows 10
- Version: 5.1.27
- Working Version: 5.0.23

**Comment by clairernovotny** [comment]
What would a minimal repro be?

**Comment by acgritt** [comment]
@clairernovotny I can put one together today. As I haven't put one together for C# before is there a good tool for it or just create a github repo to share it and link to that?

**Comment by clairernovotny** [comment]
Easiest thing to do is to create a couple of interfaces in the right namespaces that'll show the error in the unit test project and submit a PR.

**Comment by Dreamescaper** [comment]
I think we should add `global::` for all usings, that were defined _outside_ of namespace in original file.
(usings defined _inside_ namespace declaration should be left as-is)

**Comment by clairernovotny** [comment]
@Dreamescaper Can you add a PR with this fix and the changes from #881 demonstrating the issue?

**Comment by Dreamescaper** [comment]
Yes, a bit later.

**Comment by martincostello** [comment]
I had a similar build failure to this caused by a nested internal interface in a test class as there were some usings at the top of the stub file, and then some more nested within that.

In that scenario I was able to fix the build break by just making the test interface non-nested.

**Comment by Dreamescaper** [comment]
@martincostello
Could you share some example to be sure that's same issue?

**Comment by martincostello** [comment]
I’ll see if I can come up with a repro tomorrow.
