### ISSUE TITLE
feature: Refit.HttpClientFactory AddRefitClient with service provider

### ISSUE THREAD

**Issue by sanjuroo** [reactiveui/refit#903]
**Is your feature request related to a problem? Please describe.**
When adding refit client to ServiceCollection using AddRefitClient, i would like to initialize some of the refit settings using ServiceProvider. I implemented custom IContentSerializer, but i would like to resolve its dependencies from container, but without building service provider in ConfigureServices.

**Describe the solution you'd like**
Solution by adding AddRefitClient overload taking Func<IServiceProvider, RefitSettings>, so i could do:
`services.AddRefitClient<T>((serviceProvider) => new RefitSettings
 { 
      ContentSerializer = serviceProvider.GetRequiredService<IContentSerializer>();
 })`

**Describe alternatives you've considered**
Maybe options pattern in order to use IConfigureOptions.

**Comment by nnnvvvcv** [comment]
@sanjuroo did you ever manage to do this? I'm looking at a similar issue.

**Comment by sanjuroo** [comment]
no, i had no time to investigate more options at that time, so i left it tightly coupled.

**Comment by nnnvvvcv** [comment]
Amazing! Thanks guys.
