### ISSUE TITLE
Could not load file or assembly when using refit

### ISSUE THREAD

**Issue by AnjaliSahu51** [reactiveui/refit#915]
<##[error]\.nuget\packages\refit\5.1.67\build\netstandard2.0\refit.targets(33,5): Error : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified>>

Working properly in local machine, the error comes when building the app in azure devops.
Tried adding nuget package for System.Runtime.CompilerServices.Unsafe expilicitly but not working.

**Comment by cotyhamilton** [comment]
@AnjaliSahu51 any resolution details? we're having the same issue, both in azure devops and building locally

**Comment by jdevincework** [comment]
@cotyhamilton My team just ran into this same issue when using Refit. Not a definitive fix, but here's what worked for us:  Delete entire .nuget folder to clear package cache, commented out code from refit.target file, re-downloaded packages and run it... it gave me a different error, then I un-comment same code from refit.target file and it worked.

**Comment by cotyhamilton** [comment]
@jdevincework when I was working with this I discovered some ways to get it to build, similar to yours, but it would never build from a clean state so our cicd efforts were blown. I think we ended up downgrading the version of this one

**Comment by anderly** [comment]
@cotyhamilton @jdevincework @AnjaliSahu51 ran into this on a project where it would build locally fine, but not on devops. Tried all sorts of binding redirect variations to no avail. Finally, thought to check the task group on DevOps and noticed it was using VS2017, where we were working with VS2019 locally. Updated the task in DevOps to use VS2019 and problem solved!

Hope that helps somone!
