### ISSUE TITLE
[BUG] "IMyInterface doesn't look like a Refit interface"after upgrade from 4.6.58 to 4.8.14 (or 5.1.67)

### ISSUE THREAD

**Issue by ilya-spv** [reactiveui/refit#916]
**Describe the bug**

I have a very simple interface with one method that worked just fine in version 4.6.58. After I did upgrade to 4.8.14 (tried with latest 5.1.67 as well) and clean rebuild with no cached packages I get this error:

> IOAuthClient doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

**Steps To Reproduce**

This is my interface:

```
using System.Threading.Tasks;
using Refit;

public interface IOAuthClient
{
    [Post("/oauth/token")]
    Task<TokenResponse> GetToken([Body] TokenRequest request);
}
```

and register it like this:

`RestService.For<IOAuthClient>(oauthHttpClient) // Error happens at this line`

**Expected behavior**

No errors in the newest version of the library.

**Screenshots**

**Environment**

- OS: Windows      
- Device: Desktop  
- Version: 10  
- Working Version: 10 

**Additional context**

I use .Net Framework 4.7.2 in my Project. I have another .net core project that uses a newer version of the library and there are no troubles there. Perhaps it's framework version related

**Comment by clairernovotny** [comment]
What `Post` attribute is it? Is it the one from Refit's namespace?

**Comment by ilya-spv** [comment]
Yes, it's a Refit `PostAttribute`

**Comment by Zinski** [comment]
So I don't know if this fits to this bug, but I get an exception in this very line.
The exception says:
`
Unable to cast object of type 'Zinski.SmartHome.WirelessSockets.Services.Broker.AutoGeneratedISocketsApi' to type 'Zinski.SmartHome.WirelessSockets.Services.Broker.ISocketsApi'.
`

My code looks like this:
```
SocketsApi = RestService.For<ISocketsApi>(config.BaseUrl);
```
Whereby `ISocketsApi` looks like this:
```
public interface ISocketsApi
    {
        [Refit.Get("/api/manage/sockets/{id}")]
        Task<WirelessSocket> GetSocket(Guid id);
    }
```

This is happening in an ASP .Net Core 3.1 project though the actual library is targetting framework is .netstandard 2.1.
Any idea if this is related or how to fix it?

**Comment by jamiehowarth0** [comment]
I'm seeing this in netstandard 2.0 projects as well, VS2019 16.7.3 (see https://github.com/BenjaminAbt/hcaptcha/issues/1). I'll investigate cause I need it sorted as a priority for other reasons.

**Comment by clairernovotny** [comment]
Please try v6 and reopen if needed.

**Comment by MychellSantos** [comment]
I caught the same problem, it was with different versions in dependent projects.

Example;
MyProject.One => Refit 5.4
MyProject.Two => Refit 6.0.3

**Comment by sonsy-soft** [comment]
I Have the same problem with version 6.0.15

may project is 4.7

**Comment by jslucas22** [comment]
I Have the same issue with the version 5.2.4 
project version 4.6.1

**Comment by pchrist84** [comment]
I have the same issue with the version 5.0.23 and 5.2.4. In my main project, Refit works fine. Main project loads by DI library that implements Refit in the same way and doesn't work. Maybe I should copy something more than * .dll? I noticed that Refit generates "AutoGenerated" classes. Is it only needed for debugging?

**Comment by jslucas22** [comment]
I couldn't solve this problem, so I ended up making the request in an API that had a problem in the refit using the standard HTTP namespaces that were in visual studio

**Comment by viktoreinars** [comment]
For me it was conflicting versions.

I had a main project using Refit 6.2.2. That project was using a NuGet package which used Refit 5.2.1. When I changed the main project to use the same version (5.2.1) everything worked.
