### ISSUE TITLE
Mocking service with Refit client

### ISSUE THREAD

**Issue by SWarnberg** [reactiveui/refit#920]
Hi

I'm writing a unit test for a service that has IHttpClientFactory as DI. IHttpClientFactory is mocked using Moq framework, using same logic as written in [https://thecodebuzz.com/unit-test-mock-httpclientfactory-moq-net-core/](https://thecodebuzz.com/unit-test-mock-httpclientfactory-moq-net-core/).
The service in test is then creating clients from the factory.
This works excellent when using **PostAsync** and **GetAsync** on the HttpClient directly. However, when using typed clients with Refit (with RestService.For<>), on second request I get:
> System.ObjectDisposedException: 'Cannot access a disposed object.
> Object name: 'System.Net.Http.StringContent'.'

Any clue on why this is happening and how to solve it?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
