### ISSUE TITLE
feature: Complex Header Class Support

### ISSUE THREAD

**Issue by autyan** [reactiveui/refit#936]
**Is your feature request related to a problem? Please describe.**
If we have mutiple custom headers for a series RESTful interfaces, will make our method declaration
has very long parameters list,like:
Task<BaseResponse<SomeObj>> DoSomeThingAsync([Query] QueryType query, [Body] RequestType request, [Header] string header1, [Header] string header2, [Header] string header3,
[Header] string header4);

So could refit suppurt Class Type Custom Headers?

**Describe the solution you'd like**
if we could make a class as headers, or dictionary as headers, that will be very helperful.
like:
Task<BaseResponse<SomeObj>> DoSomeThingAsync([Query] QueryType query, [Body] RequestType request, [Header] HeaderType header);

public class HeaderType
{
    [Alias("headerName1")]
    public string Header1 {get; set;}

    [Alias("headerName2")]
    public string Header2 {get; set;}

    [Alias("headerName3")]
    public string Header3 {get; set;}
}

Or
Task<BaseResponse<SomeObj>> DoSomeThingAsync([Query] QueryType query, [Body] RequestType request, [Header] Dictionary<string,string> header);

**Comment by jamiehowarth0** [comment]
Ooh, I like this idea.
