### ISSUE TITLE
[BUG] HttpStatusCode 404 returned an invalid response

### ISSUE THREAD

**Issue by BladeXR** [reactiveui/refit#939]
**Describe the bug**
Any http responses where status code sent is NotFound (404) produce a System IO Exception related to invalid server response, therefore throwing an unexpected exception.

**Steps To Reproduce**

**Expected behavior**
Response should be NotFound in HttpStatusCode as expected.

**Screenshots**
API endpoint returns:
![image](https://user-images.githubusercontent.com/28309700/84699864-86d99c80-af0f-11ea-8abf-df7e2255e704.png)

App receives data but system io exception is thrown:
![image](https://user-images.githubusercontent.com/28309700/84700065-cef8bf00-af0f-11ea-947c-d43234a33414.png)

**Environment**

- OS:       Windows 10
- Device:   Android Emulator (Pie)
- Version:   5.1.67
- Working Version: can't recall

**Additional context**

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
