### ISSUE TITLE
JsonSerializerSettings for camelcase issue.

### ISSUE THREAD

**Issue by softboy99** [reactiveui/refit#941]
Hi,

when i use the following settings for camelcase. Is it mean it will automatically mapping to Entity Class? eg. serverside json: "isAdministrator" will be automatically mapped to "IsAdministrator" in Entity Class?

            JsonSerializerSettings setting = new Newtonsoft.Json.JsonSerializerSettings();
            setting.ContractResolver = new CamelCasePropertyNamesContractResolver();

            JsonConvert.DefaultSettings = new Func<JsonSerializerSettings>(() => {
                return setting;
            });

**Comment by jamiehowarth0** [comment]
@softboy99 if you check the documentation here, you'll see that that does exactly what you want: https://github.com/reactiveui/refit#json-content
