### ISSUE TITLE
Question - how I should properly use SwitchOutRootNavigation?

### ISSUE THREAD

**Issue by kkazmierczak-vertex** [reactiveui/refit#944]
Hi!

I'm so sorry if it is not a proper place to ask for this. If so - I'd like to appologize.

I have a question regarding SwitchOutRootNavigation functionality I described here:

https://stackoverflow.com/questions/62562442/how-to-switch-out-root-navigation

Maybe is there someone who could helpme solve the issue? Many thanks in advance!

Thanks for a great framework!! I love it!
Best
Krzysztof

**Comment by clairernovotny** [comment]
Closing as unrelated to refit.
