### ISSUE TITLE
[BUG] AuthorizeAttribute does not add a header to the request

### ISSUE THREAD

**Issue by N00mBus2000** [reactiveui/refit#946]
**Describe the bug**
```
[AttributeUsage(AttributeTargets.Parameter)]
public class AuthorizeAttribute : HeaderAttribute
{
     public AuthorizeAttribute(string scheme = "Bearer")
       : base("Authorization: " + scheme) { }
}
```
```
Refit.RequestBuilderImplementation.SetHeader(HttpRequestMessage request, string name/*"Authorization: Bearer"*/, string value)
{
...
var added = request.Headers.TryAddWithoutValidation(name, value);
...
}
```

but:
```
var req = new HttpRequestMessage();
var trueResult = req.Headers.TryAddWithoutValidation("Authorization", "Bearer someValue");
var falseResult = req.Headers.TryAddWithoutValidation("Authorization: Bearer", "someValue");
```

**Steps To Reproduce**
```
    internal interface IAuthorizationService
    {
        [Get("/api/auth/refreshToken")]
        Task<Response<AuthToken>> RefreshTokenAsync([Authorize("Bearer")] string token);
    }
```

**Expected behavior**
Add header

**Environment**
- OS:       Window 10
- Device:   PC
- Version: 10.0.19041 Build 19041
- Working Version: .net core 3.1

**Comment by tien** [comment]
Yeah got the same issue

**Comment by BarsikV** [comment]
Please fix this, even better would be to set the authorization scheme for the whole interface, instead of each request.

**Comment by N00mBus2000** [comment]
> Please fix this, even better would be to set the authorization scheme for the whole interface, instead of each request.

You can use this code for the whole interface (e. g.):
`
    [Headers("Authorization: Bearer", "Content-Type: application/json", "Accept: application/json")]
    internal interface IDataProviderService
`

**Comment by BarsikV** [comment]
> You can use this code for the whole interface (e. g.):
> 
> ```
>     [Headers("Authorization: Bearer", "Content-Type: application/json", "Accept: application/json")]
>     internal interface IDataProviderService
> ```

Yeah, but won't it be overrided by the header on the parameter?
```
    [Headers("Authorization: Bearer")]
    public interface IDataProviderService
    {
        [Get("")]
        Task<DataDto> GetData([Header("Authorization")]string token);
    }
```
Am I doing it wrong?

**Comment by netotz** [comment]
Same issue 😕

**Comment by bgribaudo** [comment]
Same issue, I believe. `[Authorize("Bearer")] string token)` isn't working for us. 

.Net Core 3.1

**Comment by N00mBus2000** [comment]
#979
