### ISSUE TITLE
Refit is not working in Visual studio 2019 latest version in Xamrain.Andorid.

### ISSUE THREAD

**Issue by jitendrashandilya** [reactiveui/refit#947]
Refit is not working in Visual studio 2019 latest version(16.6.0) in Xamrain.Andorid. Almost all api working fine but few api is not working.
 I downgrade version 16.6.0 to 16.2.0 then its working fine.

**Comment by clairernovotny** [comment]
Is there a specific error code?

**Comment by jitendrashandilya** [comment]
Hi
There is no specific error. Just find out that problem is due to version code by hit and try.
Output of 2 api is not correct out of 10 api. Its a strange problem not able to find out.

Thanks
Jitendra

________________________________

**Comment by clairernovotny** [comment]
Closing due to age. Please try again with Refit v6 and re-open if needed.
