### ISSUE TITLE
How to write reusable C# code to visit one URL

### ISSUE THREAD

**Issue by johngit2020** [reactiveui/refit#948]
Hello:
I have found an issue when I want to write reusable C# RestSharp code for visiting one URL:
https://www.betonline.ag/sportsbook/soccer/todaygames
First, I used Insomnia Rest Client Version: 2020.2.2; HTTP GET failed with error code: 1020.
Second, I tried with Postman Version 7.27.1, after I set up the following headers:
Accept, Accept-Language, Connection, User-Agent, then the HTTP GET works, I see OK 200 with a lot of data returned.
I can use the code generation by Postman to see the C# code, like the following:
`var client = new RestClient("https://www.betonline.ag/sportsbook/soccer/todaygames");
client.Timeout = -1;
var request = new RestRequest(Method.GET);
request.AddHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/apng,*/*;q=0.8");
request.AddHeader("Accept-Language", "en-GB");
request.AddHeader("Connection", "keep-alive");
client.UserAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36";
request.AddHeader("Cookie", "__cfduid=d0b759ddd2fd299d2f2c9de03c4b0fc831593630928; ASP.NET_SessionId=011tzj55pax0mteqwvyoy52j; KW_Search=domain=&kw=&HTTP_Refer=; UDeepLink=soccer/todaygames; THE_COOKIE=!8mJlp93nsBg0bsxPZwurU0T9hxdEzIjav0h+jNr3wz7WGGb3QX9sfA4aRlYR60ZxaQpPjWM/TK5nmlc=; __cf_bm=8428a48b248f93f0bcf0ce207c632a8dd4ea9bf8-1593882478-1800-AVbbpKBDcqxwlVhAJa+kDYiw2jOTOlW02R28g5sAp4Ga675L8j7ZywqzLlcBxCHJhj9vyrmCAHBI36cVdVupi5s=; __cfruid=4df47a91b423cd4a3d3d1de756d5e9e4657798c9-1593882478");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
`
However, as I can see the cookies are specific for each different session.
If I want to write a C# reusable code to visit this URL, what I should do using Refit?
Thanks,

**Comment by clairernovotny** [comment]
Refit is not RestSharp.
