### ISSUE TITLE
How to set timeout of HttpClient?

### ISSUE THREAD

**Issue by bruceliu2015** [reactiveui/refit#949]
I set the default timeout of HttpClient to 20 seconds:
            services.AddRefitClient<IFinicityApi>(new RefitSettings()
                {
                    ...
                })
                .ConfigureHttpClient((provider, c) =>
                {
                    c.Timeout = TimeSpan.FromSeconds(20);
                });
However, there is a call which takes longer, such as 60 seconds. How can I overwrite the timeout in my specific call?
Thank you very much for your help.

**Comment by bennor** [comment]
If you're setting a lower timeout globally like and it's on the same API, you can't.

I'm not 100% sure, but I think each API you register with `AddRefitClient` gets its own `HttpClient`, so if you put that one call which needs a longer timeout in its own API interface, you should be able to set a different timeout.

```csharp

public interface IExistingApi 
{
    // All your existing endpoints except the slow one
}

public interface ISlowApi
{
   // Just the slow one(s)
}

services.AddRefitClient<ICurrentApi>(new RefitSettings()
{
    // ...
})
.ConfigureHttpClient((provider, c) =>
{
    c.Timeout = TimeSpan.FromSeconds(20);
});

services.AddRefitClient<ISlowApi>(new RefitSettings()
{
    // ...
})
.ConfigureHttpClient((provider, c) =>
{
    c.Timeout = TimeSpan.FromSeconds(60);
});
```

**Comment by bruceliu2015** [comment]
I have one interface with multiple methods. All methods have a timeout of 20, except one of them has a timeout of 120. So I set the default timeout to 20 in ConfigureHttpClient. How can I overwrite it using 120 in the special method which needs 120? Thank you so much for your reply.

**Comment by bennor** [comment]
You can't in the same API, but you should be able to split your API interface in two, and configure one with a timeout of 20 and the other with 120 (like I've tried to show in my sample above).

**Comment by bennor** [comment]
If you're still not sure what I mean, maybe share your API interface, tell me which is the slow call, and I'll show you what I mean using your actual example.

**Comment by clairernovotny** [comment]
Closing due to age.
