### ISSUE TITLE
Put request

### ISSUE THREAD

**Issue by avanloo01** [reactiveui/refit#955]
I don't know how I would use a PUT request in c# (Xamarin forms). The usage in the readme file isn't that clear to me. Can anyone help?

Thanks.

**Comment by avanloo01** [comment]
I used this tutorial: [https://xamgirl.com/consuming-a-restful-web-service-in-xamarin-forms-using-refit-part-1/#comment-124](https://xamgirl.com/consuming-a-restful-web-service-in-xamarin-forms-using-refit-part-1/#comment-124 )

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
