### ISSUE TITLE
[BUG] Refit 5.1.67 is not working with Visual studio 2019 Version 16.2.0

### ISSUE THREAD

**Issue by KripsI** [reactiveui/refit#960]
**Describe the bug**
I am using refit 5.1.67 and my .net 3.1 project does not complie and throw error 

... \.nuget\packages\refit\5.1.67\buildTransitive\netstandard2.0\refit.targets(33,5): error : could not load file or assembly ‘System.Runtime.ComplierServices.Unsafe, Version=4.0.4.1, Culture =neutral, PublicKeyToken=b03f5f711d50a3a’ or one of its dependancies. The system cannot find the file specified

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**

**Comment by clairernovotny** [comment]
Closing as won't fix. v6.0 will require VS 2019 16.8 or higher as well.
