### ISSUE TITLE
Make PooledMemoryStream seekable

### ISSUE THREAD

**Issue by delight-by** [reactiveui/refit#962]
Are there any specific reasons why PooledMemoryStream made not seekable?

SystemTextJsonContentSerializer wraps it in StreamContent which relies on stream being seekable to allow multiple content reads (see [StreamContent.PrepareContent](https://github.com/dotnet/runtime/blob/17b096dfbce8a91e854f98beb5ac182ca69b10a2/src/libraries/System.Net.Http/src/System/Net/Http/StreamContent.cs#L131)). Which in turn is required to retry requests, for example when using libraries like [IdentityModel](https://github.com/IdentityModel) that retry requests with refreshed access token on 401 responses (see [UserAccessTokenHandler. SendAsync](https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/b4d4dab02a931ac25c1c97651660468034fc3e20/src/AccessTokenManagement/UserAccessTokenHandler.cs#L36)).

**Comment by clairernovotny** [comment]
Closing as we're now using the `System.Net.Http.Json` for deserializing.
