### ISSUE TITLE
[BUG] Mutilpart attribute with Dictonary paras not work as excepted

### ISSUE THREAD

**Issue by jasonliaocn** [reactiveui/refit#963]
I have a post method as below:

        [Multipart]
        [Post("/api/device/reboot")]
        Task<SzJiaLingResponse> Reboot(string deviceKey, string secret);

        [Multipart]
        [Post("/api/device/Config")]
        Task<SzJiaLingResponse> Config(Dictionary<string, string> request);

but in the generated file it is looks like below:
        Task<SzJiaLingResponse> ISzJiaLingGateApi.Reboot(string deviceKey, string secret)
        {
            var arguments = new object[] { deviceKey, secret };
            var func = requestBuilder.BuildRestResultFuncForMethod("Reboot", new Type[] { typeof(string), typeof(string) });
            return (Task<SzJiaLingResponse>)func(Client, arguments);
        }

        Task<SzJiaLingResponse> ISzJiaLingGateApi.Config(Dictionary<string, string> request)
        {
            var arguments = new object[] { request };
            var func = requestBuilder.BuildRestResultFuncForMethod("Config", new Type[] { typeof(Dictionary<string, string>) });
            return (Task<SzJiaLingResponse>)func(Client, arguments);
        }

the confifg method has many paras and I cannot list all in the parameters, and some are optional, so how to make the arguments in the ISzJiaLingGateApi.Config generated same format as the arguments generated in the ISzJiaLingGateApi.Reboot method?

Refit version 5.1.67

thanks.

**Comment by nicostouch** [comment]
@jasonliaocn the docs state that Multipart only works with certain types object and Dictionary<string, string> isn't one of the supported types. Supporting it is more like a feature request I think...

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
