### ISSUE TITLE
InterfaceStubGenerator not working on build

### ISSUE THREAD

**Issue by pierskarsenbarg** [reactiveui/refit#97]
I'm getting the following error on my build:

`C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1069, 5): error MSB3073: The command ""..\packages\refit.2.1.0\tools\InterfaceStubGenerator.exe" "C:\TeamCity\buildAgent\work\5c154ea65fba2a12\src\Website\RefitStubs.cs" "App_Start\IoC.cs;App_Start\LessTransform.cs;App_Start\RouteConfig.cs;App_Start\BundleConfig.cs;Classes\BundleHelper.cs;Classes\FormHelper.cs;Controllers\CallbackController.cs;Controllers\T101AsyncController.cs;Models\ConfirmationViewModel.cs;Orchestrators\ISecurePaymentOrchestrator.cs;Controllers\SecureController.cs;Orchestrators\SecurePaymentOrchestrator.cs;Controllers\T101Controller.cs;Global.asax.cs;Models\PaymentViewModel.cs;Properties\AssemblyInfo.cs"" exited with code 3.`

I don't have any refit stub classes in that project (they're all in a different one that is referenced in this one) so I'm not sure why the generator is trying to check all these.

Or am I wrong in what this .exe is trying to achieve?

Should specify that I'm using teamcity for build.

**Comment by leojh** [comment]
I'm actually getting this error when building from the solution

**Comment by paulcbetts** [comment]
@leojh Can you paste in the error you're seeing here?

**Comment by leojh** [comment]
@paulcbetts, I'm seeing the exact same error posted above. My client's solution file may just be truly messed up. It's a hotchpotch of different types of projects in different languages, etc. So it's probably that.

**Comment by bennor** [comment]
Could be an unrelated error? That's just a generic error you'll get any time `InterfaceStubGenerator.exe` fails. Can you try running the command at the command line (you'll need to clean up the quoting to make it work) and give us a dump of the exact error.

**Comment by luisrudge** [comment]
I'm having this problem too on appveyor with an Azure Cloud Project.

![image](https://cloud.githubusercontent.com/assets/941075/7206809/710e91c2-e50b-11e4-93ac-a81b5ff1a9a6.png)

Notice the *Undefined*/projects. I'm guessing SolutionDir isn't available too? Can we fix this?

**Comment by Genri1996** [comment]
Having similar issue with building in visual studio locally 
The command ""C:\Users\Oleh_Kosiakov\Documents\Source\Repos\TRVD\Src\packages\refit.2.4.1\build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\..\..\tools\InterfaceStubGenerator.exe" "obj\Debug\\RefitStubs.g.cs" "C:\Users\Oleh_Kosiakov\Documents\Source\Repos\TRVD\Src\Epam.GuestGuide.Core" "obj\Debug\\RefitParams.rsp"" exited with code 1.	Epam.GuestGuide.Core	C:\Users\Oleh_Kosiakov\Documents\Source\Repos\TRVD\Src\packages\refit.2.4.1\build\portable-net45+netcore45+wp8+wpa81+monoandroid+xamarin.ios10\refit.targets	33

**Comment by onovotny** [comment]
This is a very old version. Please try the latest and open a new issue if there's still a problem. Thanks.
