### ISSUE TITLE
C# 9 Source Generators

### ISSUE THREAD

**Issue by clairernovotny** [reactiveui/refit#972]
We should look to see if we can move the source generation to use the Source Generator feature of C# 9, and what would that look like from a compatibility standpoint.

**Comment by bennor** [comment]
Had missed the announcement of Source Generators, but it sounds interesting and totally appropriate.

From the post announcing it, it looks like the only dependency is .NET Standard 2.0. isn't that what we already rely on?

> A Source Generator is a .NET Standard 2.0 assembly that is loaded by the compiler along with any analyzers. It is usable in environments where .NET Standard components can be loaded and run.

Can you think of any other potential compatibility issues?

**Comment by clairernovotny** [comment]
I believe it'll require use of C# 9. So while C# 9 can target any .NET flavor, it may not be the default or used, etc. So so we maintain both code paths, etc? What config is there to use the generator on a project targeting .NET 4.6.2, etc?

**Comment by clairernovotny** [comment]
Done!
