### ISSUE TITLE
Xamarin.Forms (android device) not sending body params (large) from device but works from VS

### ISSUE THREAD

**Issue by cguevara1970** [reactiveui/refit#974]
Hello, 

I have just started using xamarin.forms with refit to connect to an asp.net webapi.  The method I am calling receives to large strings in the body (actually base64 images).  If I try using VS debug and the emulator, the client sends the appropiate call to the service with the proper body.  If I try from a device attached to the VS machine for debugging, in the debugger I do see the fields being filled and sent as part of the call (at least while making the call).

However, in this scenario and in the one where the device is not attached (happens on both), the server does not receive the body params (I get a null exception on the server because the params are not received).

Any help will be greatly appreciated.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
