### ISSUE TITLE
[BUG] Using parameter name "arguments" causes compile error

### ISSUE THREAD

**Issue by lylerolleman** [reactiveui/refit#977]
**Describe the bug**
In a Refit interface, if I use a parameter name "arguments" this causes the generated RefitStubs.g.cs to be invalid, as it initializes a variable "arguments"

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Create a Refit interface with a method that has a parameter named "arguments"
ex. `Task<HttpResponseMessage> Search(SearchArguments arguments)`

**Expected behavior**
I should not get a error based on an arbitrary naming system

**Environment**

- OS:       Windows 10 (probably universal seeing as it's codegen)
- Device:   N/A
- Version:   Refit 5.2.1 (haven't checked earlier versions)
- Working Version: Unknown

**Comment by napalm684** [comment]
This is one of my favorite libraries. I would like to give back if the project owners feel this would be a good issue to get hands on with the package implementation vs just using it.

**Comment by clairernovotny** [comment]
This is fixed v6.0.

**Comment by clairernovotny** [comment]
*Will be fixed

**Comment by clairernovotny** [comment]
Fixed in the version after `6.0-preview.121` but will be in the 6.0 stable release on Monday.
