### ISSUE TITLE
[BUG] pass constants to Get and Post attributes

### ISSUE THREAD

**Issue by jalil1408** [reactiveui/refit#978]
trying to pass constants to Get and Post attributes:

    public static class Routes 
    {
        public const string PREFIX = "/api/v1";
        public const string USER = PREFIX + "/users/{user}";
    }

    public interface IGitHubApi
    {
        [Get("/api/v1/users/{user}")]    =====> ok
        //[Get(Routes.USER)]             =====> System.InvalidOperationException: 'IGitHubApi doesn't look like a Refit interface. 
        Task<User> Get(string user); 
    }

**Comment by jamiehowarth0** [comment]
We're aware of this, it fits under the semantic analysis that we've been thinking about for some time, and is already covered under #263.
