### ISSUE TITLE
[BUG] .NET Standard 2.0 project using Refit 5.2.1 can't be built with VS 2017

### ISSUE THREAD

**Issue by iBobb** [reactiveui/refit#983]
**Describe the bug**
I have a .NET Standard 2.0 project with one interface defined and only Refit 5.2.1 installed as a nuget package. That project I build fine with VS 2019 but when I tried to build it using our agent running VS 2017 I realised there's something wrong. I started up VS 2017 locally and I saw - indeed I can't build the project using VS 2017 15.9.22 which is quite new.

The exception is:

Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
I don't see where this is referenced or how to go around that, in .NET standard projects there are no binding redirects either... And this works fine built with VS 2019!

**Steps To Reproduce**

1. Create a .NET Standard 2.0 project
2. Add one interface method to a class and install Refit 5.2.1.
3. Try to build.

**Environment**
- OS:      Windows 10
- Device:   HP Z Book 
- Version:   Refit 5.2.1

Any clues?

**Comment by iBobb** [comment]
One way I worked around this - simply downgraded Refit to 5.0.23 which is the latest version that builds fine.

**Comment by jamiehowarth0** [comment]
If I'm not mistaken, .NETStandard2 is only supported by 4.7.2 and above - this could be why you're experiencing issues?

**Comment by clairernovotny** [comment]
Closing as by-design/won't fix. VS 2017 is old at this point. If you need that support, you can use an older Refit version, otherwise please use a newer MSBuild--or `dotnet build`.
