### ISSUE TITLE
[BUG] System.ArgumentException  must be of the form '/foo/bar/baz

### ISSUE THREAD

**Issue by Hedyia** [reactiveui/refit#988]
**Describe the bug**

I got this exception With "POST" and "PUT" decoration attributes.
**System.ArgumentException: 'URL path ​/api​/Message​/UserSendMessage must be of the form '/foo/bar/baz''**
My base url is 
**var apiResponse = RestService.For<IChatApi>("http://algosys-001-site21.ctempurl.com");**
I prefixed with "/" but I got the same issue

**[Post("​/api​/Message​/UserSendMessage")]
        Task SendMessage([Body] StudentMessage message, [Header("Authorization")] string token);**

**Comment by wcoder** [comment]
Based on your example used non-printable unicode characters in your path string:

![Screen Shot 2020-12-02 at 3 15 21 PM](https://user-images.githubusercontent.com/766193/100871455-5f708f00-34b1-11eb-8a36-174a187dc85c.png)

Try this:
```cs
[Post("/api/Message/UserSendMessage")]
```
