### ISSUE TITLE
[Question/Feature request] Support for synchronous methods

### ISSUE THREAD

**Issue by hankovich** [reactiveui/refit#992]
HttpClient in .NET 5 received [synchronous Send methods](https://github.com/dotnet/runtime/pull/34948).
I'm interested if future versions of refit will use these methods to allow sync methods inside refit interfaces.
Do you have such plans?

Current behavior:

```
public interface IApi
{
    [Get("/ping")]
    ApiResponse<Response> Ping(CancellationToken cancellationToken = default);
}
```
`api.Ping()` throws InvalidCastException with the following message:

```Unable to cast object of type 'TaskToObservable`1[AwesomeProject.Response]' to type 'Refit.ApiResponse`1[AwesomeProject.Response]'.```

**Comment by clairernovotny** [comment]
Not likely, sync HTTP is pretty much a giant hack. Network I/O is async by definition. What is the issue with `Task<ApiResponse<Response>``?

**Comment by hankovich** [comment]
There are cases when you just can't use async methods. For example, when you are implementing an existing sync interface.

**Comment by rodion-m** [comment]
This is became a necessity to call refit methods from C++/CLI code (it doesn't support async/await).

**Comment by jrummell** [comment]
I have to support ASP.NET MVC 4 projects, and there are places such as AuthorizeAttribute implementations that have no async support. I'm having to write different API client libraries that are async based on Refit (for all the new, shiny projects) and synchronous based on RestSharp (for all of the old stuff I have to maintain). I would love to use Refit everywhere.

**Comment by clairernovotny** [comment]
I'm closing this as won't fix. Refit may not be able to handle the edge cases where sync is required.
